; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

WEBSERVICE_COM_MEDIA="Seirbhís gréasáin Meán"
WEBSERVICE_COM_MEDIA_MISSING_REQUIRED_PARAMETERS="Paraiméadar riachtanach in easnamh: %s"
WEBSERVICE_COM_MEDIA_FILE_NOT_FOUND="Comhad gan aimsiú: %s"
WEBSERVICE_COM_MEDIA_FILE_EXISTS="Comhad ann agus gan ró-scríobh iarrtha: %s"
WEBSERVICE_COM_MEDIA_BAD_FILE_TYPE="Cosán neamhbhailí nó cineál comhaid nach gceadaítear: %s"
WEBSERVICE_COM_MEDIA_UNSUPPORTED_PARAMETER_COMBINATION="Meascán paraiméadar fiosrúcháin gan choinne nó nach dtacaítear leis"
