; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

; The placeholder for this key is the configured log path for the site.
COM_PRIVACY="Príobháideacht"
COM_PRIVACY_ACTION_DELETE_DATA="Scrios Sonraí"
COM_PRIVACY_ACTION_EMAIL_EXPORT_DATA="Sonraí Easpórtála Ríomhphoist"
COM_PRIVACY_ACTION_EXPORT_DATA="Sonraí Easpórtála"
COM_PRIVACY_ACTION_LOG_ADMIN_COMPLETED_REQUEST="Úsáideoir <a href='{accountlink}'>{username}</a> chríochnaigh <a href='{itemlink}'>iarratas #{id}</a> do {subjectemail}"
COM_PRIVACY_ACTION_LOG_ADMIN_CREATED_REQUEST="Úsáideoir <a href='{accountlink}'>{username}</a> chruthaigh <a href='{itemlink}'>iarratas #{id}</a> do {subjectemail}"
COM_PRIVACY_ACTION_LOG_ADMIN_INVALIDATED_REQUEST="Úsáideoir <a href='{accountlink}'>{username}</a> neamhbhailigh <a href='{itemlink}'>iarratas #{id}</a> do {subjectemail}"
COM_PRIVACY_ACTION_LOG_CONFIRMED_REQUEST="{subjectemail} dheimhnigh <a href='{itemlink}'>iarratas #{id}</a>"
COM_PRIVACY_ACTION_LOG_CREATED_REQUEST="{subjectemail} chuir isteach <a href='{itemlink}'>iarratas #{id}</a>"
COM_PRIVACY_ACTION_LOG_EXPORT="Úsáideoir <a href='{accountlink}'>{username}</a> easpórtáil na sonraí do <a href='{itemlink}'>iarratas #{id}</a>"
COM_PRIVACY_ACTION_LOG_EXPORT_EMAILED="Úsáideoir <a href='{accountlink}'>{username}</a> sheol ríomhphost leis na sonraí easpórtáilte do <a href='{itemlink}'>iarratas #{id}</a> chuig an bhfaighteoir"
COM_PRIVACY_ACTION_LOG_REMOVE="Úsáideoir <a href='{accountlink}'>{username}</a> bhain na sonraí do <a href='{itemlink}'>iarratas #{id}</a>"
COM_PRIVACY_ACTION_LOG_REMOVE_BLOCKED="Úsáideoir <a href='{accountlink}'>{username}</a> rinne iarracht na sonraí do <a href='{itemlink}'>iarratas #{id}</a> a bhaint ach cuireadh bac ar an ngníomh seo"
COM_PRIVACY_ACTION_VIEW="Féach ar Iarratas"
COM_PRIVACY_BADGE_URGENT_REQUEST="Práinneach"
COM_PRIVACY_CONFIGURATION="Príobháideacht: Roghanna"
COM_PRIVACY_CONSENTS_EMPTYSTATE_CONTENT="Taispeánann an scáileán seo gach Príobháideacht: Toiliú a tugadh. Is féidir leat toiliú a neamhbhailiú anseo freisin."
COM_PRIVACY_CONSENTS_EMPTYSTATE_TITLE="Níor tugadh aon Toiliú fós."
COM_PRIVACY_CONSENTS_FILTER_STATE="Staid na dToiliú"
COM_PRIVACY_CONSENTS_FILTER_SUBJECT="Ábhar"
COM_PRIVACY_CONSENTS_INVALIDATED_ALL="Tá gach toiliú den ábhar seo neamhbhailithe."
COM_PRIVACY_CONSENTS_STATE_INVALIDATED="Toiliú Neamhbhailithe"
COM_PRIVACY_CONSENTS_STATE_OBSOLETE="Toiliú As Dáta"
COM_PRIVACY_CONSENTS_STATE_VALID="Toiliú Bailí"
COM_PRIVACY_CONSENTS_SUBJECT_DEFAULT="Gach Ábhar"
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE="Neamhbhailigh Toiliú"
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE_ALL="Neamhbhailigh gach Toiliú"
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE_ALL_CONFIRM_MSG="An bhfuil tú cinnte gur mhaith leat gach toiliú den ábhar roghnaithe a neamhbhailiú? Cuirfidh sé seo iallach ar úsáideoirí a dtoiliú a thabhairt arís."
COM_PRIVACY_CONSENTS_TOOLBAR_INVALIDATE_CONFIRM_MSG="An bhfuil tú cinnte gur mhaith leat na toiliú roghnaithe a neamhbhailiú? Cuirfidh sé seo iallach ar úsáideoirí a dtoiliú a thabhairt arís."
COM_PRIVACY_CORE_CAPABILITY_COMMUNICATION_WITH_JOOMLA_ORG="Nuair a bhíonn nasc líonra ar fáil, déanfaidh suiteáil Joomla iarracht cumarsáid a dhéanamh le freastalaithe joomla.org do chumais éagsúla, lena n-áirítear:<ul><li>Seiceáil le haghaidh nuashonruithe don fheidhmchlár Joomla</li><li>Scáileáin chabhrach do shíneadh croí Joomla</li><li>An tseirbhís Suiteáil ón nGréasán (roghnach)</li><li>An freastalaí bailithe staitisticí (roghnach)</li></ul>Mar a bhíonn le gach iarratas HTTP, seolfar seoladh IP do fhreastalaí mar chuid den iarratas. Le haghaidh faisnéise ar conas a phróiseálann Joomla sonraí ar a fhreastalaithe, féach ar ár <a href=\"https://www.joomla.org/privacy-policy.html\" target=\"_blank\" rel=\"noopener noreferrer\">bpolasaí príobháideachais</a>."
COM_PRIVACY_CORE_CAPABILITY_LOGGING_IP_ADDRESS="Taifeadann córas logála Joomla seoladh IP an chuairteora a fhágann go scríobhtar teachtaireacht chuig a chomhaid logála. Úsáidtear na comhaid logála seo chun gníomhaíocht éagsúla ar shuíomh Joomla a thaifeadadh, lena n-áirítear faisnéis a bhaineann le nuashonruithe croí, iarrachtaí logála isteach neamhbhailí, earráidí neamhbhainistithe, agus faisnéis forbartha mar úsáid APIanna atá as dáta. Is féidir formáid na gcomhad logála seo a shaincheapadh ag aon síneadh a chumraíonn logálaí, mar sin moltar duit na comhaid logála do do shuíomh gréasáin a íoslódáil agus a athbhreithniú a d'fhéadfadh a bheith le fáil ag `%s`."
COM_PRIVACY_CORE_CAPABILITY_SESSION_IP_ADDRESS_AND_COOKIE="Tosaíonn gach iarratas chuig suíomh gréasáin Joomla seisiún a stórálann an seoladh IP sna sonraí seisiúin agus a chruthaíonn fianán seisiúin i mbrabhsálaí an úsáideora. Úsáidtear an seoladh IP mar bheart slándála chun cabhrú le cosaint i gcoinne ionsaithe greamaithe seisiúin féideartha agus scriostar an fhaisnéis seo nuair a bhíonn an seisiún imithe in éag agus a shonraí glanta. Tá ainm an fhianáin seisiúin bunaithe ar hash a ghintear go randamach agus mar sin níl aitheantóir seasta aige. Scriostar an fianán seisiúin nuair a bhíonn an seisiún imithe in éag nó nuair a bhíonn an t-úsáideoir tar éis a mbrabhsálaí a fhágáil."
COM_PRIVACY_DASHBOARD_BADGE_ACTIVE_REQUESTS_0="<span class=\"badge bg-info\">0</span> Iarrataí Gníomhacha"
COM_PRIVACY_DASHBOARD_BADGE_ACTIVE_REQUESTS_1="<span class=\"badge bg-warning\">1</span> Iarratas Gníomhach"
COM_PRIVACY_DASHBOARD_BADGE_ACTIVE_REQUESTS_MORE="<span class=\"badge bg-warning\">%d</span> Iarrataí Gníomhacha"
COM_PRIVACY_DASHBOARD_BADGE_TOTAL_REQUESTS_0="<span class=\"badge bg-info\">0</span> Iomlán na nIarratas"
COM_PRIVACY_DASHBOARD_BADGE_TOTAL_REQUESTS_1="<span class=\"badge bg-info\">1</span> Iomlán Iarrata"
COM_PRIVACY_DASHBOARD_BADGE_TOTAL_REQUESTS_MORE="<span class=\"badge bg-info\">%d</span> Iomlán na nIarratas"
COM_PRIVACY_DASHBOARD_HEADING_CHECK="Seiceáil"
COM_PRIVACY_DASHBOARD_HEADING_REQUEST_COUNT="# d'Iarrataí"
COM_PRIVACY_DASHBOARD_HEADING_REQUEST_STATUS="Stádas"
COM_PRIVACY_DASHBOARD_HEADING_REQUEST_TYPE="Cineál Iarrata"
COM_PRIVACY_DASHBOARD_HEADING_STATUS="Stádas"
COM_PRIVACY_DASHBOARD_HEADING_STATUS_CHECK="Seiceáil Stádais"
COM_PRIVACY_DASHBOARD_HEADING_TOTAL_REQUEST_COUNT="Iomlán na nIarratas"
COM_PRIVACY_DASHBOARD_NO_REQUESTS="Níl aon iarrataí ann."
COM_PRIVACY_DASHBOARD_TITLE="Painéal Príobháideachais"
COM_PRIVACY_DASHBOARD_VIEW_REQUESTS="Féach ar Iarrataí"
COM_PRIVACY_DATA_REMOVED="Sonraí bainte"
COM_PRIVACY_EDIT_PRIVACY_CONSENT_PLUGIN="Cuir in Eagar Breiseán Toiliú Príobháideachais"
COM_PRIVACY_EDIT_PRIVACY_POLICY="Cuir in Eagar Polasaí Príobháideachais"
COM_PRIVACY_EMAIL_ADMIN_REQUEST_BODY_EXPORT_REQUEST="Tá riarachán do {URL} tar éis iarratas a chruthú chun faisnéis phearsanta a easpórtáil a bhaineann leis an seoladh ríomhphoist seo. Mar bheart slándála, ní mór duit a dhearbhú gur iarratas bailí é seo ar do chuid faisnéise pearsanta ón suíomh Gréasáin seo.\n\nMá bhí sé seo ina bhotún, déan neamhaird ar an ríomhphost seo agus ní tharlóidh aon rud.\n\nChun an t-iarratas seo a dhearbhú, is féidir leat ceann de na tascanna seo a leanas a chomhlánú:\n\n1. Tabhair cuairt ar an URL seo a leanas: {TOKENURL}\n\n2. Cóipeáil do thicéad ón ríomhphost seo, tabhair cuairt ar an URL tagartha, agus greamaigh do thicéad isteach sa fhoirm.\nURL: {FORMURL}\nTicéad: {TOKEN}\n\nTabhair faoi deara nach bhfuil an ticéad seo bailí ach ar feadh 24 uair an chloig ón am a seoladh an ríomhphost seo."
COM_PRIVACY_EMAIL_ADMIN_REQUEST_BODY_REMOVE_REQUEST="Tá riarachán do {URL} tar éis iarratas a chruthú chun gach faisnéis phearsanta a bhaineann leis an seoladh ríomhphoist seo a bhaint. Mar bheart slándála, ní mór duit a dhearbhú gur iarratas bailí é seo chun do chuid faisnéise pearsanta a bhaint ón suíomh Gréasáin seo.\n\nMá bhí sé seo ina bhotún, déan neamhaird ar an ríomhphost seo agus ní tharlóidh aon rud.\n\nChun an t-iarratas seo a dhearbhú, is féidir leat ceann de na tascanna seo a leanas a chomhlánú:\n\n1. Tabhair cuairt ar an URL seo a leanas: {TOKENURL}\n\n2. Cóipeáil do thicéad ón ríomhphost seo, tabhair cuairt ar an URL tagartha, agus greamaigh do thicéad isteach sa fhoirm.\nURL: {FORMURL}\nTicéad: {TOKEN}\n\nTabhair faoi deara nach bhfuil an ticéad seo bailí ach ar feadh 24 uair an chloig ón am a seoladh an ríomhphost seo."
COM_PRIVACY_EMAIL_ADMIN_REQUEST_SUBJECT_EXPORT_REQUEST="Iarratas Faisnéise Cruthaithe ag {SITENAME}"
COM_PRIVACY_EMAIL_ADMIN_REQUEST_SUBJECT_REMOVE_REQUEST="Iarratas ar Fhaisnéis a Scriosadh Cruthaithe ag {SITENAME}"
COM_PRIVACY_EMAIL_DATA_EXPORT_COMPLETED_BODY="Tá riarachán do {URL} tar éis an t-easpórtáil sonraí a d'iarr tú a chríochnú agus is féidir cóip den fhaisnéis a fháil sa chomhad atá ceangailte leis an teachtaireacht seo."
COM_PRIVACY_EMAIL_DATA_EXPORT_COMPLETED_SUBJECT="Easpórtáil Sonraí do {SITENAME}"
COM_PRIVACY_ERROR_ACTIVE_REQUEST_FOR_EMAIL="Tá iarratas faisnéise gníomhach cheana féin don seoladh ríomhphoist seo, ba cheart an t-iarratas gníomhach a chríochnú sula dtosaítear ceann nua."
COM_PRIVACY_ERROR_CANNOT_CREATE_REQUEST_FOR_SELF="Ní féidir leat iarratas faisnéise a chruthú duit féin."
COM_PRIVACY_ERROR_CANNOT_CREATE_REQUEST_WHEN_SENDMAIL_DISABLED="Ní féidir iarratais faisnéise a chruthú nuair a bhíonn seoladh ríomhphoist díchumasaithe."
COM_PRIVACY_ERROR_CANNOT_EXPORT_UNCONFIRMED_REQUEST="Ní féidir na sonraí d'iarratas neamhdaingnithe a easpórtáil."
COM_PRIVACY_ERROR_CANNOT_REMOVE_DATA="Ní féidir na sonraí don iarratas seo a bhaint."
COM_PRIVACY_ERROR_CANNOT_REMOVE_UNCONFIRMED_REQUEST="Ní féidir na sonraí d'iarratas neamhdaingnithe a bhaint."
COM_PRIVACY_ERROR_COMPLETE_TRANSITION_NOT_PERMITTED="Ní féidir an taifead seo a nuashonrú go stádas \"Críochnaithe\"."
COM_PRIVACY_ERROR_EXPORT_EMAIL_FAILED="Theip ar an easpórtáil leis an earráid seo a leanas: %s"
COM_PRIVACY_ERROR_INVALID_TRANSITION_NOT_PERMITTED="Ní féidir an taifead seo a nuashonrú go stádas \"Neamhbhailí\"."
COM_PRIVACY_ERROR_REMOVE_DATA_FAILED="Theip ar an mbainistiú leis an earráid seo a leanas: %s"
COM_PRIVACY_ERROR_REQUEST_ID_REQUIRED_FOR_EXPORT="Tá ID iarratais ag teastáil chun sonraí a easpórtáil."
COM_PRIVACY_ERROR_REQUEST_ID_REQUIRED_FOR_REMOVE="Tá ID iarratais ag teastáil chun sonraí a bhaint."
COM_PRIVACY_ERROR_REQUEST_TYPE_NOT_EXPORT="Ní féidir ach iarratais easpórtála a easpórtáil."
COM_PRIVACY_ERROR_REQUEST_TYPE_NOT_REMOVE="Ní féidir ach iarratais bainte a bheith a gcuid sonraí bainte."
COM_PRIVACY_ERROR_UNKNOWN_REQUEST_TYPE="Cineál iarratais faisnéise anaithnid."
COM_PRIVACY_EXPORT_EMAILED="Tá an t-easpórtáil sonraí curtha ar ríomhphost."
COM_PRIVACY_EXTENSION_CAPABILITY_PERSONAL_INFO="Chun iarratais faisnéise a phróiseáil, caithfear faisnéis faoin úsáideoir a bhailiú agus a logáil chun críocha log iniúchta a choinneáil. Tá an córas iarratais bunaithe ar sheoladh ríomhphoist duine aonair a úsáidfear chun an t-iarratas a nascadh le húsáideoir láithreáin atá ann cheana más féidir."
COM_PRIVACY_FIELD_REQUESTED_AT_LABEL="Dáta Iarrtha"
COM_PRIVACY_FIELD_REQUEST_TYPE_LABEL="Cineál Iarratais"
COM_PRIVACY_FIELD_STATUS_LABEL="Stádas Iarratais"
COM_PRIVACY_FILTER_SEARCH_LABEL="Cuardaigh Iarratais"
COM_PRIVACY_HEADING_ACTIONS="Gníomhartha"
COM_PRIVACY_HEADING_ACTION_LOG="Loga Gníomhaíochta"
COM_PRIVACY_HEADING_CONSENTS_BODY="Comhlacht"
COM_PRIVACY_HEADING_CONSENTS_CREATED="Toilithe"
COM_PRIVACY_HEADING_CONSENTS_SUBJECT="Ábhar"
COM_PRIVACY_HEADING_CORE_CAPABILITIES="Cumais Lárnacha Joomla"
COM_PRIVACY_HEADING_CREATED_ASC="Toilithe ag ardú"
COM_PRIVACY_HEADING_CREATED_DESC="Toilithe ag ísliú"
COM_PRIVACY_HEADING_EMAIL_ASC="Ríomhphost ag ardú"
COM_PRIVACY_HEADING_EMAIL_DESC="Ríomhphost ag ísliú"
COM_PRIVACY_HEADING_NAME="Ainm"
COM_PRIVACY_HEADING_REQUESTED_AT="Iarrtha"
COM_PRIVACY_HEADING_REQUESTED_AT_ASC="Iarrtha ag ardú"
COM_PRIVACY_HEADING_REQUESTED_AT_DESC="Iarrtha ag ísliú"
COM_PRIVACY_HEADING_REQUEST_INFORMATION="Faisnéis Iarratais"
COM_PRIVACY_HEADING_REQUEST_TYPE="Cineál Iarratais"
COM_PRIVACY_HEADING_REQUEST_TYPE_ASC="Cineál Iarratais ag ardú"
COM_PRIVACY_HEADING_REQUEST_TYPE_DESC="Cineál Iarratais ag ísliú"
COM_PRIVACY_HEADING_REQUEST_TYPE_TYPE_EXPORT="Easpórtáil"
COM_PRIVACY_HEADING_REQUEST_TYPE_TYPE_REMOVE="Bain"
COM_PRIVACY_HEADING_STATUS_ASC="Stádas ag ardú"
COM_PRIVACY_HEADING_STATUS_DESC="Stádas ag ísliú"
COM_PRIVACY_HEADING_SUBJECT_ASC="Ábhar ag ardú"
COM_PRIVACY_HEADING_SUBJECT_DESC="Ábhar ag ísliú"
COM_PRIVACY_HEADING_USERID="ID Úsáideora"
COM_PRIVACY_HEADING_USERID_ASC="ID Úsáideora ag ardú"
COM_PRIVACY_HEADING_USERID_DESC="ID Úsáideora ag ísliú"
COM_PRIVACY_HEADING_USERNAME_ASC="Ainm Úsáideora ag ardú"
COM_PRIVACY_HEADING_USERNAME_DESC="Ainm Úsáideora ag ísliú"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_EXPORT_DESC="Ríomhphost chun an t-úsáideoir a chur ar an eolas go bhfuil iarratas chun na sonraí a easpórtáil ón suíomh gréasáin seo cruthaithe ag an riarthóir"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_EXPORT_TITLE="Príobháideacht: Iarr Easpórtáil Sonraí (Riarthóir)"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_REMOVE_DESC="Ríomhphost chun an t-úsáideoir a chur ar an eolas go bhfuil iarratas chun na sonraí a bhaint ón suíomh gréasáin seo cruthaithe ag an riarthóir"
COM_PRIVACY_MAIL_NOTIFICATION_ADMIN_REMOVE_TITLE="Príobháideacht: Iarr Bain Sonraí (Riarthóir)"
COM_PRIVACY_MAIL_NOTIFICATION_EXPORT_DESC="Ríomhphost chun a fhíorú gur chóir sonraí úsáideora a easpórtáil ón suíomh gréasáin"
COM_PRIVACY_MAIL_NOTIFICATION_EXPORT_TITLE="Príobháideacht: Iarr Easpórtáil Sonraí"
COM_PRIVACY_MAIL_NOTIFICATION_REMOVE_DESC="Ríomhphost chun a fhíorú gur chóir sonraí úsáideora a bhaint ón suíomh gréasáin"
COM_PRIVACY_MAIL_NOTIFICATION_REMOVE_TITLE="Príobháideacht: Iarr Bain Sonraí"
COM_PRIVACY_MAIL_USERDATAEXPORT_DESC="Ríomhphost le heaspórtáil sonraí úsáideora"
COM_PRIVACY_MAIL_USERDATAEXPORT_TITLE="Príobháideacht: Easpórtáil Sonraí Úsáideora"
COM_PRIVACY_MSG_CAPABILITIES_ABOUT_THIS_INFORMATION="Maidir leis an bhFaisnéis Seo"
COM_PRIVACY_MSG_CAPABILITIES_INTRODUCTION="Bailítear an fhaisnéis ar an scáileán seo ó fhorlíontáin a thuairiscíonn a gcumas a bhaineann le príobháideacht don chóras seo. Tá sé beartaithe chun cabhrú le húinéirí láithreán a bheith ar an eolas faoi chumas na bhforlíontán suiteáilte agus faisnéis a sholáthar chun cabhrú le húinéirí polasaithe láithreán áitiúla a chruthú mar bheartas príobháideachta. Ós rud é go dteastaíonn tacaíocht ó fhorlíontáin don chóras tuairiscithe seo, agus nach dtaispeánann sé ach faisnéis ó fhorlíontáin chumasaithe, níor cheart é seo a mheas mar liosta iomlán agus moltar duit dul i gcomhairle le doiciméadú gach forlíontáin le haghaidh tuilleadh faisnéise."
COM_PRIVACY_MSG_CAPABILITIES_NO_CAPABILITIES="Níl aon chumais forlíontáin tuairiscithe ann."
COM_PRIVACY_MSG_CONFIRM_EMAIL_SENT_TO_USER="Seoladh ríomhphost dearbhaithe don iarratas seo chuig an úsáideoir."
COM_PRIVACY_MSG_EXTENSION_NO_CAPABILITIES="Ní thuairiscíonn an forlíonadh seo aon chumais."
COM_PRIVACY_NOTIFY_DESC="Taispeáin fógra nuair a bhíonn iarratais níos sine ná an líon sonraithe laethanta."
COM_PRIVACY_NOTIFY_LABEL="Laethanta Chun Iarratas a Mheas Mar Thábhachtach"
COM_PRIVACY_N_CONSENTS_INVALIDATED="Cuireadh %d toiliú ar neamhní."
COM_PRIVACY_N_CONSENTS_INVALIDATED_1="Cuireadh an toiliú ar neamhní."
COM_PRIVACY_OPTION_LABEL="Roghanna"
COM_PRIVACY_POSTINSTALL_BODY="<p>Le tabhairt isteach GDPR do shaoránaigh an AE agus rialacháin chosúla in áiteanna eile ar domhan, b'fhéidir go mbeidh gá agat toiliú a iarraidh sula stórálann tú aon <strong>Faisnéis Phearsanta</strong> úsáideora.</p><p>Cuireann Joomla 3.9 cumais nua ar fáil chun cabhrú leat polasaithe príobháideachta láithreáin a chruthú agus toiliú úsáideora a bhailiú. Ina theannta sin, tá sreabhadh oibre ar fáil chun cabhrú leat iarratais faisnéise úsáideora a bhainistiú, mar shampla iarratais chun a gcuid sonraí pearsanta a bhaint as do shuíomh.</p><p>Le haghaidh tuilleadh faisnéise faoin ngné nua seo, léigh an <a href='https://docs.joomla.org/Special:MyLanguage/J3.x:Privacy' target='_blank' rel='noopener noreferrer'>doiciméadú Príobháideachta</a>.</p>"
COM_PRIVACY_POSTINSTALL_TITLE="Bainistíocht Méadaithe ar Phríobháideacht Úsáideoirí"
COM_PRIVACY_REQUESTS_EMPTYSTATE_BUTTON_ADD="Cuir isteach d'iarratas chéad uair"
COM_PRIVACY_REQUESTS_EMPTYSTATE_CONTENT="Taispeánann an scáileán seo gach Iarratas Faisnéise Príobháideachta a fuarthas agus a stádas. Is féidir leat iarratas nua a chruthú anseo freisin."
COM_PRIVACY_REQUESTS_EMPTYSTATE_TITLE="Níl aon Iarratais Faisnéise curtha isteach go fóill."
COM_PRIVACY_REQUEST_COMPLETED="Tá an t-iarratas críochnaithe."
COM_PRIVACY_REQUEST_FORM_EDIT="Cuir Iarratas in Eagar"
COM_PRIVACY_REQUEST_FORM_NEW="Iarratas Nua"
COM_PRIVACY_REQUEST_INVALIDATED="Cuireadh an t-iarratas ar neamhní."
COM_PRIVACY_SEARCH_IN_EMAIL="Cuardaigh i seoladh ríomhphoist an iarrthóra. Cuir ID: roimh chun cuardach a dhéanamh ar ID iarratais."
COM_PRIVACY_SEARCH_IN_USERNAME="Cuardaigh i ainm úsáideora. Cuir Name: roimh chun cuardach a dhéanamh ar ainm. Cuir ID: roimh chun cuardach a dhéanamh ar ID toiliú. Cuir UID: roimh chun cuardach a dhéanamh ar ID Úsáideora."
COM_PRIVACY_SELECT_REQUEST_TYPE="- Roghnaigh Cineál Iarratais -"
COM_PRIVACY_SHOW_URGENT_REQUESTS="Taispeáin Iarratais Thábhachtacha"
COM_PRIVACY_STATUS_CHECK_NOT_AVAILABLE="Níl Ar Fáil"
COM_PRIVACY_STATUS_CHECK_OUTSTANDING_URGENT_REQUESTS="Iarratais Thábhachtacha Gan Réiteach"
COM_PRIVACY_STATUS_CHECK_OUTSTANDING_URGENT_REQUESTS_DESCRIPTION="Iarratais atá níos sine ná %d lá, mar atá socraithe i gcumraíocht an chomhpháirt."
COM_PRIVACY_STATUS_CHECK_PRIVACY_POLICY_PUBLISHED="Beartas Príobháideachta Foilsithe"
COM_PRIVACY_STATUS_CHECK_REQUEST_FORM_MENU_ITEM_PUBLISHED="Mír Roghchláir Foirm Iarratais Foilsithe"
COM_PRIVACY_STATUS_CHECK_SENDMAIL_DISABLED="Seoladh Ríomhphoist Díchumasaithe"
COM_PRIVACY_STATUS_CHECK_SENDMAIL_DISABLED_DESCRIPTION="Caithfear Seoladh Ríomhphoist a bheith cumasaithe, is riachtanas é chun an córas iarratais a úsáid"
COM_PRIVACY_STATUS_CHECK_SENDMAIL_ENABLED="Seoladh Ríomhphoist Cumasaithe"
COM_PRIVACY_STATUS_COMPLETED="Críochnaithe"
COM_PRIVACY_STATUS_CONFIRMED="Deimhnithe"
COM_PRIVACY_STATUS_INVALID="Neamhbhailí"
COM_PRIVACY_STATUS_PENDING="Ar feitheamh"
COM_PRIVACY_TABLE_CAPTION="Iarratais Príobháideachais"
COM_PRIVACY_TABLE_CONSENTS_CAPTION="Toilithe Príobháideachais"
COM_PRIVACY_TOOLBAR_COMPLETE="Críochnaigh"
COM_PRIVACY_TOOLBAR_INVALIDATE="Neamhbhailigh"
COM_PRIVACY_USER_FIELD_EMAIL_DESC="Seoladh ríomhphoist an duine a bhfuil an t-eolas á iarraidh aige."
COM_PRIVACY_VIEW_CAPABILITIES="Príobháideachas: Cumas Síneadh"
COM_PRIVACY_VIEW_CONSENTS="Príobháideachas: Toilithe"
COM_PRIVACY_VIEW_DASHBOARD="Príobháideachas: Painéal"
COM_PRIVACY_VIEW_REQUESTS="Príobháideachas: Iarratais Eolais"
COM_PRIVACY_VIEW_REQUEST_ADD_REQUEST="Príobháideachas: Iarratas Nua ar Eolas"
COM_PRIVACY_VIEW_REQUEST_SHOW_REQUEST="Príobháideachas: Athbhreithniú ar Iarratas Eolais"
COM_PRIVACY_WARNING_CANNOT_CREATE_REQUEST_WHEN_SENDMAIL_DISABLED="Ní féidir iarratais eolais a chruthú nuair atá seoladh ríomhphoist díchumasaithe."
COM_PRIVACY_XML_DESCRIPTION="Comhpháirt chun gníomhartha a bhaineann le príobháideachas a bhainistiú."
