; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_ACTIONLOGS="Log Gníomhartha Úsáideora"
COM_ACTIONLOGS_VIEW_DEFAULT_DESC="Taispeánann sé liosta de ghníomhartha úsáideora."
COM_ACTIONLOGS_VIEW_DEFAULT_TITLE="Log Gníomh Úsáideora"
COM_ACTIONLOGS_XML_DESCRIPTION="Taispeánann sé log de ghníomhartha a rinne úsáideoirí ar do shuíomh gréasáin."
