; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_LANGUAGES="Teangacha"
COM_LANGUAGES_INSTALLED_VIEW_DEFAULT_DESC="Taispeánann pacáistí teanga atá suiteáilte ar do shuíomh Gréasáin Joomla!"
COM_LANGUAGES_INSTALLED_VIEW_DEFAULT_TITLE="Teangacha Suiteáilte"
COM_LANGUAGES_LANGUAGES_VIEW_DEFAULT_DESC="Cruthaigh nó bainistigh teangacha ábhair do do shuíomh Gréasáin Joomla!"
COM_LANGUAGES_LANGUAGES_VIEW_DEFAULT_TITLE="Teangacha Ábhair"
COM_LANGUAGES_OVERRIDE_VIEW_DEFAULT_DESC="Anseo sannann tú téacs saincheaptha do eochair teanga ar mhaith leat a úsáid in ionad téacs réamhshocraithe an phacáiste teanga."
COM_LANGUAGES_OVERRIDE_VIEW_DEFAULT_TITLE="Forghníomhaithe Teanga"
COM_LANGUAGES_XML_DESCRIPTION="Comhpháirt le haghaidh bainistíocht teanga."
