; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CACHE="Taisce"
COM_CACHE_CLEAR_CACHE="Cothabháil: Glan an Taisce"
COM_CACHE_CONFIGURATION="Taisce: Roghanna"
COM_CACHE_EMPTYSTATE_CONTENT="Má chuireann tú taisce ar chumas i gCumraíocht Dhomhanda Joomla, taispeánfar aon mhíreanna taiscthe anseo."
COM_CACHE_EMPTYSTATE_TITLE="Níl aon ábhar taiscthe agat."
COM_CACHE_ERROR_CACHE_CONNECTION_FAILED="Níorbh fhéidir ceangal leis an stór taisce chun na sonraí taisce a fháil."
COM_CACHE_ERROR_CACHE_DRIVER_UNSUPPORTED="Níorbh fhéidir na sonraí taisce a léamh, níl an láimhseálaí taisce cumraithe tacaíochta ag an timpeallacht seo."
COM_CACHE_EXPIRED_ITEMS_DELETE_ERROR="Earráid ag glanadh grúpa(í) taisce: %s."
COM_CACHE_EXPIRED_ITEMS_HAVE_BEEN_DELETED="Tá an grúpa(í) taisce roghnaithe glanta."
COM_CACHE_EXPIRED_ITEMS_HAVE_BEEN_PURGED="Tá míreanna taiscthe atá imithe in éag glanta."
COM_CACHE_EXPIRED_ITEMS_PURGING_ERROR="Earráid ag glanadh míreanna taiscthe atá imithe in éag."
COM_CACHE_FILTER_SEARCH_DESC="Cuardaigh i ngrúpa taisce."
COM_CACHE_FILTER_SEARCH_LABEL="Cuardaigh Taisce"
COM_CACHE_GROUP="Grúpa Taisce"
COM_CACHE_HEADING_COUNT_ASC="Líon na gComhad ag méadú"
COM_CACHE_HEADING_COUNT_DESC="Líon na gComhad ag laghdú"
COM_CACHE_HEADING_GROUP_ASC="Grúpa Taisce ag méadú"
COM_CACHE_HEADING_GROUP_DESC="Grúpa Taisce ag laghdú"
COM_CACHE_HEADING_SIZE_ASC="Méid ag méadú"
COM_CACHE_HEADING_SIZE_DESC="Méid ag laghdú"
COM_CACHE_MSG_ALL_CACHE_GROUPS_CLEARED="Tá gach grúpa taisce glanta."
COM_CACHE_MSG_SOME_CACHE_GROUPS_CLEARED="Níl ach roinnt grúpa(í) taisce glanta."
COM_CACHE_NUMBER_OF_FILES="Líon na gComhad"
COM_CACHE_PURGE_EXPIRED="Glan Taisce atá Imthéite in Éag"
COM_CACHE_PURGE_EXPIRED_ITEMS="Glan míreanna atá imithe in éag"
COM_CACHE_PURGE_INSTRUCTIONS="Roghnaigh an cnaipe Glan Taisce atá Imthéite in Éag sa bharra uirlisí chun gach comhad taisce atá imithe in éag a scriosadh. Nóta: Ní scriosfar comhaid taisce atá fós reatha."
COM_CACHE_QUICKICON_SRONLY="Taisce: Méid an taisce ná %s."
COM_CACHE_QUICKICON_SRONLY_NOCACHE="Níl an taisce cumasaithe."
COM_CACHE_RESOURCE_INTENSIVE_WARNING="D’fhéadfadh sé seo a bheith dian ar acmhainní ar shuíomhanna le líon mór míreanna!"
COM_CACHE_SELECT_CLIENT="- Roghnaigh Suíomh -"
COM_CACHE_SIZE="Méid"
COM_CACHE_TABLE_CAPTION="Comhaid Taiscthe"
COM_CACHE_XML_DESCRIPTION="Comhpháirt le haghaidh bainistíocht taisce."

JLIB_RULES_SETTING_NOTES_COM_CACHE="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Dhomhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus cuirtear i bhfeidhm ar gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Dhomhanda."
