; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_BANNERS="Meirgí"
COM_BANNERS_BANNERS="Meirgí"
COM_BANNERS_CATEGORIES="Catagóirí"
COM_BANNERS_CLIENTS="Cliaint"
COM_BANNERS_CONTENT_TYPE_BANNER="Meirge"
COM_BANNERS_CONTENT_TYPE_CATEGORY="Catagóir Meirge"
COM_BANNERS_CONTENT_TYPE_CLIENT="Cliant Meirge"
COM_BANNERS_TAGS_CATEGORY="Catagóir Meirge"
COM_BANNERS_TRACKS="Rianta"
COM_BANNERS_XML_DESCRIPTION="Bainistíonn an comhpháirt seo meirgí agus cliaint meirgí."
