; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_ASSOCIATIONS="Comhlachais Ilteangacha"
COM_ASSOCIATIONS_ADD_NEW_ASSOCIATION="Cuir comhlachas nua leis"
COM_ASSOCIATIONS_ASSOCIATED_ITEM="Sprioc"
COM_ASSOCIATIONS_CHANGE_TARGET="Athraigh Sprioc"
COM_ASSOCIATIONS_COMPONENT_NOT_SUPPORTED="Ní thacaíonn an síneadh %s le comhlachais ilteangacha."
COM_ASSOCIATIONS_CONFIGURATION="Comhlachais Ilteangacha: Roghanna"
COM_ASSOCIATIONS_COPY_REFERENCE="Cóipeáil Tagairt go Sprioc"
COM_ASSOCIATIONS_DELETE_ORPHANS="Scrios Dílseáin"
COM_ASSOCIATIONS_DELETE_ORPHANS_FAILED="Theip ar scriosadh dílseáin."
COM_ASSOCIATIONS_DELETE_ORPHANS_NONE="Ní raibh aon dílseáin le scriosadh."
COM_ASSOCIATIONS_DELETE_ORPHANS_SUCCESS="Tá gach dílseán scriosta."
COM_ASSOCIATIONS_EDIT_ASSOCIATION="Eagar comhlachais"
COM_ASSOCIATIONS_EDIT_HIDE_REFERENCE="Folaigh Tagairt"
COM_ASSOCIATIONS_EDIT_SHOW_REFERENCE="Taispeáin Tagairt"
COM_ASSOCIATIONS_ERROR_NO_ASSOC="Ní féidir leat Comhlachais Ilteangacha a chruthú mura bhfuil an suíomh socraithe mar ilteangach agus/nó mura bhfuil Comhlachais cumasaithe sa <a href=\"%s\">breiseán Scagaire Teanga</a>."
COM_ASSOCIATIONS_ERROR_NO_TYPE="Níl an cineál mír roghnaithe ann don chomhpháirt seo."
COM_ASSOCIATIONS_FILTER_SEARCH_DESC="Cuardaigh mír de réir a teidil"
COM_ASSOCIATIONS_FILTER_SEARCH_LABEL="Cuardaigh mír"
COM_ASSOCIATIONS_FILTER_SELECT_ITEM="Roghnaigh Cineál Míre"
COM_ASSOCIATIONS_FILTER_SELECT_ITEM_TYPE="- Roghnaigh Cineál Míre -"
COM_ASSOCIATIONS_FILTER_SELECT_LANGUAGE="Roghnaigh Teanga"
COM_ASSOCIATIONS_HEADING_ASSOCIATION="Comhlachais"
COM_ASSOCIATIONS_HEADING_MENUTYPE="Biachlár"
COM_ASSOCIATIONS_HEADING_MENUTYPE_ASC="Biachlár ag ardú"
COM_ASSOCIATIONS_HEADING_MENUTYPE_DESC="Biachlár ag ísliú"
COM_ASSOCIATIONS_HEADING_NO_ASSOCIATION="Gan Comhlachas"
COM_ASSOCIATIONS_ITEMS="Míreanna"
COM_ASSOCIATIONS_NO_ASSOCIATION="Níl aon chomhlachas don teanga seo"
COM_ASSOCIATIONS_NOTICE_NO_SELECTORS="Roghnaigh Cineál Míre agus teanga tagartha le do thoil chun na comhlachais a fheiceáil."
COM_ASSOCIATIONS_PURGE="Scrios Gach Comhlachas"
COM_ASSOCIATIONS_PURGE_CONFIRM_PROMPT="An bhfuil tú cinnte gur mhaith leat gach comhlachas a scriosadh? Má dheimhnítear é, scriosfar iad go buan!"
COM_ASSOCIATIONS_PURGE_FAILED="Theip ar scriosadh gach comhlachas."
COM_ASSOCIATIONS_PURGE_NONE="Ní raibh aon chomhlachas le scriosadh."
COM_ASSOCIATIONS_PURGE_SUCCESS="Tá gach comhlachas scriosta."
COM_ASSOCIATIONS_REFERENCE_ITEM="Tagairt"
COM_ASSOCIATIONS_SAVE_REFERENCE="Sábháil Tagairt"
COM_ASSOCIATIONS_SAVE_TARGET="Sábháil Sprioc"
COM_ASSOCIATIONS_SELECT_MENU="- Roghnaigh Biachlár -"
COM_ASSOCIATIONS_SELECT_TARGET="Roghnaigh Sprioc"
COM_ASSOCIATIONS_SELECT_TARGET_LANGUAGE="- Roghnaigh Teanga Sprioc -"
COM_ASSOCIATIONS_SELECT_TARGET_LANGUAGE_LABEL="Roghnaigh Teanga Sprioc"
COM_ASSOCIATIONS_TABLE_CAPTION="Comhlachais"
COM_ASSOCIATIONS_TITLE="Comhlachais"
COM_ASSOCIATIONS_TITLE_EDIT="Comhlachais Ilteangacha: Eagar Comhlachais (%1$s &rarr; %2$s)"
COM_ASSOCIATIONS_TITLE_LIST="Comhlachais Ilteangacha (%1$s &rarr; %2$s)"
COM_ASSOCIATIONS_TITLE_LIST_SELECT="Comhlachais Ilteangacha: Roghnaigh Cineál Míre agus Teanga"
COM_ASSOCIATIONS_XML_DESCRIPTION="Comhpháirt bainistíochta ábhair ilteangach feabhsaithe"
COM_ASSOCIATIONS_YOU_ARE_NOT_ALLOWED_TO_CHECKIN_THIS_ITEM="Ní féidir leat an mhír seo a sheiceáil isteach"
