; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_NEWSFEEDS="Beatha Nuachta"
COM_NEWSFEEDS_BATCH_OPTIONS="Próiseáil bhaisc na beatha nuachta roghnaithe"
COM_NEWSFEEDS_BATCH_TIP="Má roghnaítear catagóir le haghaidh bogadh/cóipeáil, cuirfear aon ghníomhartha roghnaithe i bhfeidhm ar na beatha nuachta cóipeáilte nó bogtha. Seachas sin, cuirtear gach gníomh i bhfeidhm ar na beatha nuachta roghnaithe."
COM_NEWSFEEDS_CACHE_TIME_HEADING="Am Taisce"
COM_NEWSFEEDS_CACHE_TIME_HEADING_ASC="Am Taisce ag ardú"
COM_NEWSFEEDS_CACHE_TIME_HEADING_DESC="Am Taisce ag ísliú"
COM_NEWSFEEDS_CATEGORIES_DESC="Baineann na socruithe seo le Roghanna Catagóirí Beatha Nuachta mura n-athraítear iad le haghaidh mír roghchláir ar leith."
COM_NEWSFEEDS_CONFIG_INTEGRATION_SETTINGS_DESC="Socraíonn na socruithe seo conas a chomhtháthaíonn an Comhpháirt Beatha Nuachta le síntí eile."
COM_NEWSFEEDS_CONFIGURATION="Beatha Nuachta: Roghanna"
COM_NEWSFEEDS_EDIT_NEWSFEED="Cuir Beatha Nuachta in Eagar"
COM_NEWSFEEDS_EMPTYSTATE_BUTTON_ADD="Cuir do chéad bheatha nuachta leis"
COM_NEWSFEEDS_EMPTYSTATE_CONTENT="Is bealach é beatha nuachta a chur le do shuíomhanna chun ábhar ó shuíomhanna gréasáin eile a chomhtháthú."
COM_NEWSFEEDS_EMPTYSTATE_TITLE="Níl aon Bheatha Nuachta cruthaithe go fóill."
COM_NEWSFEEDS_ERROR_ALL_LANGUAGE_ASSOCIATED="Ní féidir mír beatha nuachta atá socraithe do Gach teanga a chomhcheangal. Níor socraíodh comhcheangail."
COM_NEWSFEEDS_ERROR_UNIQUE_ALIAS="Tá an t-ailias céanna ag beatha nuachta eile ón gcatagóir seo."
COM_NEWSFEEDS_ERROR_UNIQUE_ALIAS_TRASHED="Tá an t-ailias céanna ag beatha nuachta sa chiseán bruscair sa chatagóir seo."
COM_NEWSFEEDS_FIELD_CACHETIME_LABEL="Am Taisce"
COM_NEWSFEEDS_FIELD_CHARACTER_COUNT_DESC="Taispeánfaidh 0 an téacs ar fad."
COM_NEWSFEEDS_FIELD_CHARACTER_COUNT_LABEL="Líon na gCarachtar"
COM_NEWSFEEDS_FIELD_CHARACTERS_COUNT_DESC="Taispeánfaidh 0 an téacs ar fad."
COM_NEWSFEEDS_FIELD_CHARACTERS_COUNT_LABEL="Líon na gCarachtar"
COM_NEWSFEEDS_FIELD_CONFIG_CATEGORY_SETTINGS_DESC="Baineann na socruithe seo le Roghanna Catagóirí Beatha Nuachta mura n-athraítear iad le haghaidh mír roghchláir ar leith."
COM_NEWSFEEDS_FIELD_CONFIG_LIST_SETTINGS_DESC="Baineann na socruithe seo le Roghanna Leagan Amach Liosta mura n-athraítear iad le haghaidh mír roghchláir ar leith."
COM_NEWSFEEDS_FIELD_CONFIG_NEWSFEED_SETTINGS_DESC="Baineann na socruithe seo le beatha nuachta aonair mura n-athraítear iad le haghaidh mír roghchláir ar leith nó beatha nuachta."
COM_NEWSFEEDS_FIELD_CONFIG_NEWSFEED_SETTINGS_LABEL="Beatha Nuachta"
COM_NEWSFEEDS_FIELD_FEED_DISPLAY_ORDER_LABEL="Ord Taispeána na Beatha"
COM_NEWSFEEDS_FIELD_FIRST_LABEL="An Chéad Íomhá"
COM_NEWSFEEDS_FIELD_IMAGE_ALT_EMPTY_DESC="Íomhá Maisiúil - níl aon tuairisc ag teastáil"
COM_NEWSFEEDS_FIELD_IMAGE_ALT_EMPTY_LABEL="Gan Tuairisc"
COM_NEWSFEEDS_FIELD_IMAGE_ALT_LABEL="Tuairisc Íomhá (Téacs Alt)"
COM_NEWSFEEDS_FIELD_IMAGE_CAPTION_LABEL="Fotheideal"
COM_NEWSFEEDS_FIELD_LINK_LABEL="Nasc"
COM_NEWSFEEDS_FIELD_NUM_ARTICLES_COLUMN_LABEL="# Altanna"
COM_NEWSFEEDS_FIELD_NUM_ARTICLES_LABEL="Líon na nAlt"
COM_NEWSFEEDS_FIELD_RTL_LABEL="Treoir Teanga"
COM_NEWSFEEDS_FIELD_SECOND_LABEL="An Dara Íomhá"
COM_NEWSFEEDS_FIELD_SELECT_FEED_LABEL="Beatha"
COM_NEWSFEEDS_FIELD_SHOW_CAT_ITEMS_LABEL="# Beatha sa Chatagóir"
COM_NEWSFEEDS_FIELD_SHOW_CAT_TAGS_LABEL="Clibeanna"
COM_NEWSFEEDS_FIELD_SHOW_FEED_DESCRIPTION_LABEL="Cur Síos na Beatha"
COM_NEWSFEEDS_FIELD_SHOW_FEED_IMAGE_LABEL="Íomhá na Beatha"
COM_NEWSFEEDS_FIELD_SHOW_ITEM_DESCRIPTION_LABEL="Ábhar na Beatha"
COM_NEWSFEEDS_FIELD_SHOW_LINKS_LABEL="Naisc na Beatha"
COM_NEWSFEEDS_FIELD_SHOW_TAGS_LABEL="Clibeanna"
COM_NEWSFEEDS_FIELD_VALUE_LTR="Ó Chlé go Deas"
COM_NEWSFEEDS_FIELD_VALUE_RTL="Ó Dheas go Clé"
COM_NEWSFEEDS_FIELD_VALUE_SITE="Teanga an tSuímh"
COM_NEWSFEEDS_FIELD_VERSION_LABEL="Leagan"
COM_NEWSFEEDS_FIELDSET_MORE_OPTIONS_LABEL="Roghanna Taispeána Beatha"
COM_NEWSFEEDS_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus ailias na beatha nuachta. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID beatha nuachta."
COM_NEWSFEEDS_FILTER_SEARCH_LABEL="Cuardaigh Beatha Nuachta"
COM_NEWSFEEDS_FLOAT_FIRST_LABEL="Snámh an Chéad Íomhá"
COM_NEWSFEEDS_FLOAT_LABEL="Snámh Íomhá"
COM_NEWSFEEDS_FLOAT_SECOND_LABEL="Snámh an Dara Íomhá"
COM_NEWSFEEDS_FORM_TITLE_EDIT="Cuir Beatha Nuachta in Eagar"
COM_NEWSFEEDS_FORM_TITLE_NEW="Beatha Nuachta Nua"
COM_NEWSFEEDS_HEADING_ASSOCIATION="Comhlachas"
COM_NEWSFEEDS_LEFT="Clé"
COM_NEWSFEEDS_MANAGER_NEWSFEED_EDIT="Beatha Nuachta: Cuir in Eagar"
COM_NEWSFEEDS_MANAGER_NEWSFEED_NEW="Beatha Nuachta: Nua"
COM_NEWSFEEDS_MANAGER_NEWSFEEDS="Beatha Nuachta"
COM_NEWSFEEDS_N_ITEMS_ARCHIVED="%d beatha nuachta cartlainne."
COM_NEWSFEEDS_N_ITEMS_ARCHIVED_1="Beatha nuachta cartlainne."
COM_NEWSFEEDS_N_ITEMS_CHECKED_IN_1="Beatha nuachta seiceáilte isteach."
COM_NEWSFEEDS_N_ITEMS_CHECKED_IN_MORE="%d beatha nuachta seiceáilte isteach."
COM_NEWSFEEDS_N_ITEMS_DELETED="%d beatha nuachta scriosta."
COM_NEWSFEEDS_N_ITEMS_DELETED_1="Beatha nuachta scriosta."
COM_NEWSFEEDS_N_ITEMS_PUBLISHED="%d beatha nuachta foilsithe."
COM_NEWSFEEDS_N_ITEMS_PUBLISHED_1="Beatha nuachta foilsithe."
COM_NEWSFEEDS_N_ITEMS_TRASHED="%d beatha nuachta bruscair."
COM_NEWSFEEDS_N_ITEMS_TRASHED_1="Beatha nuachta bruscair."
COM_NEWSFEEDS_N_ITEMS_UNPUBLISHED="%d beatha nuachta neamhfhoilsithe."
COM_NEWSFEEDS_N_ITEMS_UNPUBLISHED_1="Beatha nuachta neamhfhoilsithe."
COM_NEWSFEEDS_N_QUICKICON="Beatha Nuachta"
COM_NEWSFEEDS_N_QUICKICON_1="Beatha Nuachta"
COM_NEWSFEEDS_N_QUICKICON_SRONLY="Beatha Nuachta: %d beatha nuachta foilsithe."
COM_NEWSFEEDS_N_QUICKICON_SRONLY_1="Beatha Nuachta: Tá beatha nuachta amháin foilsithe."
COM_NEWSFEEDS_NEW_NEWSFEED="Beatha Nuachta Nua"
COM_NEWSFEEDS_NEWSFEEDS="Beatha Nuachta"
COM_NEWSFEEDS_NO_ITEM_SELECTED="Níor roghnaíodh beatha nuachta ar bith."
COM_NEWSFEEDS_NONE="Dada"
COM_NEWSFEEDS_NUM_ARTICLES_HEADING="# Airteagail"
COM_NEWSFEEDS_NUM_ARTICLES_HEADING_ASC="# Airteagail ag ardú"
COM_NEWSFEEDS_NUM_ARTICLES_HEADING_DESC="# Airteagail ag ísliú"
COM_NEWSFEEDS_RIGHT="Deas"
COM_NEWSFEEDS_SAVE_SUCCESS="Beatha nuachta sábháilte."
COM_NEWSFEEDS_SELECT_A_FEED="Roghnaigh Beatha Nuachta"
COM_NEWSFEEDS_TABLE_CAPTION="Beatha Nuachta"
COM_NEWSFEEDS_TIP_ASSOCIATION="Beatha nuachta comhlachaithe"
COM_NEWSFEEDS_WARNING_PROVIDE_VALID_NAME="Tabhair ainm bailí le do thoil."
COM_NEWSFEEDS_XML_DESCRIPTION="Bainistíonn an comhpháirt seo beatha nuachta RSS agus Atom."
JGLOBAL_NEWITEMSLAST_DESC="Socraítear beatha nuachta nua de réir réamhshocraithe sa suíomh deireanach. Is féidir an t-ordú a athrú tar éis an beatha nuachta seo a bheith sábháilte."

JLIB_RULES_SETTING_NOTES_COM_NEWSFEEDS="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Diúltaithe</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus a bhaineann le gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas na comhpháirte seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
