; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MESSAGES="Teachtaireachtaí"
COM_MESSAGES_ADD="Teachtaireacht Phríobháideach Nua"
COM_MESSAGES_MANAGER="Teachtaireachtaí Príobháideacha"
COM_MESSAGES_MESSAGES_VIEW_DEFAULT_DESC="Taispeánann sé liosta de na teachtaireachtaí go léir."
COM_MESSAGES_MESSAGES_VIEW_DEFAULT_TITLE="Liosta na dTeachtaireachtaí go Léir"
COM_MESSAGES_READ="Teachtaireachtaí Príobháideacha a Léamh"
COM_MESSAGES_XML_DESCRIPTION="Comhpháirt le haghaidh tacaíochta teachtaireachtaí príobháideacha sa Chúlra."
