; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FINDER="Cuardach Cliste"
COM_FINDER_ALLOW_EMPTY_QUERY_DESC="Ní amháin má roghnaítear scagaire, ceadaigh teaghrán cuardaigh folamh chun cuardach a thionscnamh laistigh de shrianta an scagaire."
COM_FINDER_ALLOW_EMPTY_QUERY_LABEL="Ceadaigh Cuardach Folamh"
COM_FINDER_AN_ERROR_HAS_OCCURRED="Tharla Earráid"
COM_FINDER_CONFIG_ALLOW_EMPTY_QUERY_LABEL="Ceadaigh Cuardach Folamh"
COM_FINDER_CONFIG_BATCH_SIZE_LABEL="Méid Baisc Innéacsóra"
COM_FINDER_CONFIG_DESCRIPTION_LENGTH_LABEL="Fad Cur Síos"
COM_FINDER_CONFIG_ENABLE_LOGGING_LABEL="Cumasaigh Logáil"
COM_FINDER_CONFIG_EXPAND_ADVANCED_LABEL="Leathnaigh Cuardach Casta"
COM_FINDER_CONFIG_FIELD_OPENSEARCH_DESCRIPTION_LABEL="Cur Síos OpenSearch"
COM_FINDER_CONFIG_FIELD_OPENSEARCH_NAME_LABEL="Ainm OpenSearch"
COM_FINDER_CONFIG_FILTER_COMMONWORDS_LABEL="Scagaire Focail Choitianta"
COM_FINDER_CONFIG_FILTER_NUMERICS_LABEL="Scagaire Téarmaí Uimhriúla"
COM_FINDER_CONFIG_GATHER_SEARCH_STATISTICS_LABEL="Bailigh Staitisticí Cuardaigh"
COM_FINDER_CONFIG_HIGHLIGHT_CONTENT_SEARCH_TERMS_DESC="Ar chúiseanna feidhmíochta, ní chuirfidh sé níos mó ná 10 dtéarmaí éagsúla i mbuaicphointe sna torthaí cuardaigh."
COM_FINDER_CONFIG_HILIGHT_CONTENT_SEARCH_TERMS_LABEL="Cuir Téarmaí Cuardaigh i mBuaicphointe"
COM_FINDER_CONFIG_IMAGE_CLASS_LABEL="Rang Íomhá"
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_DEFAULT_LANGUAGE="Teanga Réamhshocraithe an tSuímh"
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_DESC="Socraigh an teanga le húsáid do shuímh neamh-ilteangacha nó ábhar marcáilte mar \"Uile\"."
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_LABEL="Teanga Réamhshocraithe"
COM_FINDER_CONFIG_LANGUAGE_DEFAULT_NONE="Dada"
COM_FINDER_CONFIG_LINKED_IMAGE_LABEL="Íomhá Nascáilte"
COM_FINDER_CONFIG_META_MULTIPLIER_LABEL="Iolraitheoir Meáchain Meiteashonraí"
COM_FINDER_CONFIG_MISC_MULTIPLIER_LABEL="Iolraitheoir Meáchain Téacs Ilghnéitheach"
COM_FINDER_CONFIG_OPENSEARCH_LABEL="Cumasaigh OpenSearch"
COM_FINDER_CONFIG_PATH_MULTIPLIER_LABEL="Iolraitheoir Meáchain Téacs Conair"
COM_FINDER_CONFIG_SHOW_ADVANCED_LABEL="Cuardach Casta"
COM_FINDER_CONFIG_SHOW_ADVANCED_TIPS_LABEL="Leideanna Casta"
COM_FINDER_CONFIG_SHOW_AUTOSUGGEST_LABEL="Moltaí Cuardaigh"
COM_FINDER_CONFIG_SHOW_DATE_FILTERS_LABEL="Scagairí Dáta"
COM_FINDER_CONFIG_SHOW_DATE_LABEL="Dáta Torthaí"
COM_FINDER_CONFIG_SHOW_DESCRIPTION_LABEL="Cur Síos Torthaí"
COM_FINDER_CONFIG_SHOW_EXPLAINED_QUERY_LABEL="Míniú ar an gCeist"
COM_FINDER_CONFIG_SHOW_IMAGE_LABEL="Íomhá Torthaí"
COM_FINDER_CONFIG_SHOW_SORT_ORDER_LABEL="Taispeáin Réimsí Sórtála"
COM_FINDER_CONFIG_SHOW_SUGGESTED_QUERY_LABEL="An raibh i gceist agat"
COM_FINDER_CONFIG_SHOW_TAXONOMY_LABEL="Tacsanomaíocht Torthaí"
COM_FINDER_CONFIG_SHOW_URL_LABEL="URL Torthaí"
COM_FINDER_CONFIG_SORT_DIRECTION_LABEL="Treoir Sórtála"
COM_FINDER_CONFIG_SORT_OPTION_ASCENDING="Ag Dul i Méid"
COM_FINDER_CONFIG_SORT_OPTION_DESCENDING="Ag Dul i Lú"
COM_FINDER_CONFIG_SORT_OPTION_LIST_PRICE="Praghas liosta"
COM_FINDER_CONFIG_SORT_OPTION_RELEVANCE="Ábharthacht"
COM_FINDER_CONFIG_SORT_OPTION_SALES_PRICE="Praghas díolacháin"
COM_FINDER_CONFIG_SORT_OPTION_START_DATE="Dáta"
COM_FINDER_CONFIG_SORT_OPTION_TITLE="Teideal"
COM_FINDER_CONFIG_SORT_ORDER_FIELDS_LABEL="Réimsí Sórtála Breise"
COM_FINDER_CONFIG_SORT_ORDER_LABEL="Réimse Sórtála"
COM_FINDER_CONFIG_TEXT_MULTIPLIER_DESCRIPTION="Úsáidtear an t-iolraitheoir chun rialú a dhéanamh ar cé mhéad tionchar atá ag téacs a mheaitseálann ar scór ábharthachta iomlán toradh cuardaigh. Meastar iolraitheoir i gcaidreamh leis na hiolraitheoirí eile. Tagann an téacs coirp ón achoimre agus/nó corp an ábhair."
COM_FINDER_CONFIG_TEXT_MULTIPLIER_LABEL="Iolraitheoir Meáchain Téacs Coirp"
COM_FINDER_CONFIG_TITLE_MULTIPLIER_DESCRIPTION="Úsáidtear an t-iolraitheoir chun smacht a choinneáil ar an tionchar atá ag téacs a mheaitseálann ar scór iomlán ábharthachta toradh cuardaigh. Meastar iolraitheoir i gcaidreamh leis na hiolraitheoirí eile. Tagann an téacs teidil ón teideal ábhair."
COM_FINDER_CONFIG_TITLE_MULTIPLIER_LABEL="Iolraitheoir Meáchan Téacs Teidil"
COM_FINDER_CONFIG_TUPLECOUNT_LABEL="Cuardaigh Frásaí"
COM_FINDER_CONFIG_TUPLECOUNT_PHRASE_DISABLED="Díchumasaithe (Feidhmíocht fheabhsaithe)"
COM_FINDER_CONFIG_TUPLECOUNT_PHRASE_ENABLED="Cumasaíodh (Torthaí cuardaigh feabhsaithe)"
COM_FINDER_CONFIG_WORD_MATCH_DESC="Socraigh conas a mheaitseáiltear téarmaí cuardaigh san innéacs. De réir réamhshocraithe, meaitseáiltear focal go díreach, ach nuair a thacaíonn teanga le focail chomhdhúile, ceadaíonn sé seo an téarma cuardaigh a mheaitseáil leis an tús nó in áit randamach laistigh de na focail san innéacs."
COM_FINDER_CONFIG_WORD_MATCH_LABEL="Meaitseáil Focal"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_BEGIN="Meaitseáil focail a thosaíonn leis an téarma cuardaigh"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_EXACT="Meaitseáil go díreach"
COM_FINDER_CONFIG_WORD_MATCH_OPTION_FUZZY="Meaitseáil focail ina bhfuil an téarma cuardaigh áit ar bith"
COM_FINDER_CONFIGURATION="Cuardach Cliste: Roghanna"
COM_FINDER_CONTENT_PLUGIN="Breiseán Ábhar Cuardaigh Cliste"
COM_FINDER_CREATE_FILTER="Cruthaigh scagaire."
COM_FINDER_EDIT_FILTER="Cuir Scagaire in Eagar"
COM_FINDER_EDIT_PLUGIN_SETTINGS="Cuir Socruithe Breiseáin in Eagar"
COM_FINDER_EMPTYSTATE_BUTTON_ADD="Tosaigh an t-innéacsóir"
COM_FINDER_EMPTYSTATE_CONTENT="Níl aon ábhar innéacsaithe nó tá do léarscáileanna go léir scriosta agat. Tabhair cuairt ar leathanach Innéacs Cuardaigh Cliste chun d'ábhar a athinnéacsú."
COM_FINDER_EMPTYSTATE_SEARCHES_CONTENT="Níl aon fhrásaí a úsáideadh le haghaidh cuardach láithreáin le feiceáil fós."
COM_FINDER_FIELD_CREATED_BY_ALIAS_LABEL="Cruthaithe ag Ailias"
COM_FINDER_FIELD_CREATED_BY_LABEL="Cruthaithe Ag"
COM_FINDER_FIELD_FINDER_PLUGIN_LABEL="Breiseán Aimsitheora"
COM_FINDER_FIELDSET_INDEX_OPTIONS_DESCRIPTION="Bíonn tionchar ag na roghanna seo ar an gcaoi a ndéantar an t-ábhar a innéacsú. Tar éis socruithe a athrú anseo, ní mór an t-innéacs a atógáil."
COM_FINDER_FIELDSET_INDEX_OPTIONS_LABEL="Innéacs"
COM_FINDER_FIELDSET_SEARCH_OPTIONS_LABEL="Cuardach Cliste"
COM_FINDER_FILTER_BRANCH_LABEL="Cuardaigh de réir %s"
COM_FINDER_FILTER_EDIT_TOOLBAR_TITLE="Cuardach Cliste: Cuir Scagaire in Eagar"
COM_FINDER_FILTER_END_DATE_LABEL="Dáta Deiridh"
COM_FINDER_FILTER_ERROR_UNIQUE_ALIAS="Tá an t-ailias céanna ag Scagaire eile."
COM_FINDER_FILTER_FIELDSET_PARAMS="Amlíne Scagaire"
COM_FINDER_FILTER_FORM_TITLE_EDIT="Cuir Scagaire in Eagar"
COM_FINDER_FILTER_FORM_TITLE_NEW="Scagaire Nua"
COM_FINDER_FILTER_HIDE_ALL="Laghdaigh Gach"
COM_FINDER_FILTER_MAP_COUNT="Líon Léarscáile"
COM_FINDER_FILTER_NEW_TOOLBAR_TITLE="Cuardach Cliste: Scagaire Nua"
COM_FINDER_FILTER_SELECT_ALL_LABEL="Cuardaigh Gach"
COM_FINDER_FILTER_SELECT_CONTENT_MAP="- Roghnaigh Léarscáil Ábhar -"
COM_FINDER_FILTER_SHOW_ALL="Leathnaigh Gach"
COM_FINDER_FILTER_START_DATE_DESCRIPTION="Formáid BBBB-MM-LA"
COM_FINDER_FILTER_START_DATE_LABEL="Dáta Tosaigh"
COM_FINDER_FILTER_TIMESTAMP="Cruthaithe Ar"
COM_FINDER_FILTER_WHEN_AFTER="Tar éis"
COM_FINDER_FILTER_WHEN_BEFORE="Roimh"
COM_FINDER_FILTER_WHEN_END_DATE_LABEL="Cathain (Dáta Deiridh)"
COM_FINDER_FILTER_WHEN_EXACTLY="Go díreach"
COM_FINDER_FILTER_WHEN_START_DATE_LABEL="Cathain (Dáta Tosaigh)"
COM_FINDER_FILTERS="Scagairí"
COM_FINDER_FILTERS_EMPTYSTATE_BUTTON_ADD="Cuir scagaire leis"
COM_FINDER_FILTERS_EMPTYSTATE_CONTENT="Níl aon scagairí cruthaithe agat fós."
COM_FINDER_FILTERS_N_ITEMS_CHECKED_IN="%d scagairí seiceáilte isteach."
COM_FINDER_FILTERS_N_ITEMS_CHECKED_IN_1="Scagaire seiceáilte isteach."
COM_FINDER_FILTERS_N_ITEMS_DELETED="%d scagairí scriosta."
COM_FINDER_FILTERS_N_ITEMS_DELETED_1="Scagaire scriosta."
COM_FINDER_FILTERS_N_ITEMS_PUBLISHED="%d scagairí foilsithe."
COM_FINDER_FILTERS_N_ITEMS_PUBLISHED_1="Scagaire foilsithe."
COM_FINDER_FILTERS_N_ITEMS_UNPUBLISHED="%d scagairí neamhfhoilsithe."
COM_FINDER_FILTERS_N_ITEMS_UNPUBLISHED_1="Scagaire neamhfhoilsithe."
COM_FINDER_FILTERS_TABLE_CAPTION="Scagairí"
COM_FINDER_FILTERS_TOOLBAR_TITLE="Cuardach Cliste: Scagairí Cuardaigh"
COM_FINDER_FINDER_PLUGINS="Breiseáin Aimsithe Cuardaigh Cliste"
COM_FINDER_HEADING_CHILDREN="Léarscáileanna"
COM_FINDER_HEADING_CREATED_BY="Cruthaithe ag"
COM_FINDER_HEADING_CREATED_BY_ASC="Cruthaithe ag ag ardú"
COM_FINDER_HEADING_CREATED_BY_DESC="Cruthaithe ag ag ísliú"
COM_FINDER_HEADING_CREATED_ON="Cruthaithe ar"
COM_FINDER_HEADING_CREATED_ON_ASC="Cruthaithe ar ag ardú"
COM_FINDER_HEADING_CREATED_ON_DESC="Cruthaithe ar ag ísliú"
COM_FINDER_HEADING_INDEXER="Innéacsóir Cuardaigh Cliste"
COM_FINDER_HEADING_MAP_COUNT="Líon Léarscáileanna"
COM_FINDER_HEADING_MAP_COUNT_ASC="Líon Léarscáileanna ag ardú"
COM_FINDER_HEADING_MAP_COUNT_DESC="Líon Léarscáileanna ag ísliú"
COM_FINDER_HEADING_NODES="Míreanna"
COM_FINDER_HEADING_PHRASE="Frása Cuardaigh"
COM_FINDER_HEADING_RESULTS="Torthaí"
COM_FINDER_HEADING_SEARCH_TERM_ASC="Frása Cuardaigh ag ardú"
COM_FINDER_HEADING_SEARCH_TERM_DESC="Frása Cuardaigh ag ísliú"
COM_FINDER_INDEX="Innéacs"
COM_FINDER_INDEX_CONFIRM_DELETE_PROMPT="An bhfuil tú cinnte gur mhaith leat an mhír/na míreanna roghnaithe a scriosadh?"
COM_FINDER_INDEX_CONFIRM_PURGE_PROMPT="An bhfuil tú cinnte gur mhaith leat GACH mír a scriosadh ón innéacs? Is féidir leis seo a bheith fada ar shuíomhanna móra."
COM_FINDER_INDEX_DATE_INFO="<strong>Tús Foilsithe:</strong> %s<br><strong>Deireadh Foilsithe:</strong> %s<br><strong>Tús Ábhair:</strong> %s<br><strong>Deireadh Ábhair:</strong> %s"
COM_FINDER_INDEX_DATE_INFO_TITLE="Eolas Dáta Nasc"
COM_FINDER_INDEX_FILTER_BY_STATE="Aon Stádas Foilsithe"
COM_FINDER_INDEX_HEADING_DETAILS="Sonraí"
COM_FINDER_INDEX_HEADING_INDEX_DATE="Nuashonraithe Deireanach"
COM_FINDER_INDEX_HEADING_INDEX_DATE_ASC="Nuashonraithe Deireanach ag ardú"
COM_FINDER_INDEX_HEADING_INDEX_DATE_DESC="Nuashonraithe Deireanach ag ísliú"
COM_FINDER_INDEX_HEADING_INDEX_TYPE="Cineál"
COM_FINDER_INDEX_HEADING_INDEX_TYPE_ASC="Cineál ag ardú"
COM_FINDER_INDEX_HEADING_INDEX_TYPE_DESC="Cineál ag ísliú"
COM_FINDER_INDEX_HEADING_LINK_URL="URL Amh"
COM_FINDER_INDEX_HEADING_LINK_URL_ASC="URL Amh ag ardú"
COM_FINDER_INDEX_HEADING_LINK_URL_DESC="URL Amh ag ísliú"
COM_FINDER_INDEX_NO_CONTENT="Níl aon ábhar a oireann do do chritéir chuardaigh."
COM_FINDER_INDEX_NO_DATA="Níl aon ábhar innéacsaithe."
COM_FINDER_INDEX_OPTIMISE_FINISHED="Críochnaíodh an barrfheabhsú."
COM_FINDER_INDEX_PLUGIN_CONTENT_NOT_ENABLED="Tá an Breiseán Ábhar Cuardaigh Cliste díchumasaithe. Ní dhéanfar athruithe ar ábhar a nuashonrú san innéacs Cuardaigh Cliste go dtí go gcumasaítear an Breiseán."
COM_FINDER_INDEX_PLUGIN_CONTENT_NOT_ENABLED_LINK="Tá an %s díchumasaithe. Ní dhéanfar athruithe ar ábhar a nuashonrú san innéacs Cuardaigh Cliste mura gcumasaíonn tú an breiseán seo."
COM_FINDER_INDEX_PLUGIN_FINDER_NOT_ENABLED_LINK="Tá na %s díchumasaithe. Ní dhéanfar athruithe ar ábhar a nuashonrú san innéacs Cuardaigh Cliste mura gcumasaíonn tú na breiseáin seo."
COM_FINDER_INDEX_PURGE_FAILED="Theip ar scriosadh na míreanna roghnaithe."
COM_FINDER_INDEX_PURGE_SUCCESS="Scriosadh gach mír."
COM_FINDER_INDEX_SEARCH_DESC="Cuardaigh i dteideal, URL agus dáta nuashonraithe deireanach."
COM_FINDER_INDEX_SEARCH_LABEL="Cuardaigh Ábhar Innéacsaithe"
COM_FINDER_INDEX_TABLE_CAPTION="Ábhar Innéacsaithe"
COM_FINDER_INDEX_TIP="Tosaigh an t-innéacsóir trí bhrú ar an gcnaipe thíos, nó sa bharra uirlisí."
COM_FINDER_INDEX_TOOLBAR_INDEX_DEBUGGING="Dífhabhtú Innéacs"
COM_FINDER_INDEX_TOOLBAR_MAINTENANCE="Cothabháil"
COM_FINDER_INDEX_TOOLBAR_OPTIMISE="Bheith Optamach"
COM_FINDER_INDEX_TOOLBAR_PURGE="Glan Innéacs"
COM_FINDER_INDEX_TOOLBAR_TITLE="Cuardach Cliste: Ábhar Innéacsaithe"
COM_FINDER_INDEX_TYPE_FILTER="Aon Chineál Ábhair"
COM_FINDER_INDEXER_ERROR_PLUGIN_FAILURE="Tá earráid tar éis tarlú i mbreiseán \"finder\"."
COM_FINDER_INDEXER_FIELDSET_ATTRIBUTES="Réad Toradh"
COM_FINDER_INDEXER_FIELDSET_ELEMENTS="Eilimintí Breise"
COM_FINDER_INDEXER_FIELDSET_INSTRUCTIONS="Treoracha"
COM_FINDER_INDEXER_FIELDSET_TAXONOMIES="Tacsanomaíochtaí"
COM_FINDER_INDEXER_HEADER_COMPLETE="Innéacsú Críochnaithe"
COM_FINDER_INDEXER_HEADER_ERROR="Tharla Earráid"
COM_FINDER_INDEXER_HEADER_INIT="Tosú Innéacsóra"
COM_FINDER_INDEXER_HEADER_OPTIMIZE="Innéacs a Bheith Optamach"
COM_FINDER_INDEXER_HEADER_RUNNING="Innéacsóir ag Rith"
COM_FINDER_INDEXER_INVALID_DRIVER="Ní thacaíonn an t-innéacsóir le próiseáil ar an tiománaí bunachar sonraí %s."
COM_FINDER_INDEXER_INVALID_PARSER="Cineál parsálaí neamhbhailí %s"
COM_FINDER_INDEXER_INVALID_STEMMER="Cineál gasálaí neamhbhailí %s"
COM_FINDER_INDEXER_MESSAGE_COMPLETE="Tá an próiseas innéacsaithe críochnaithe. Tá sé sábháilte anois an fhuinneog seo a dhúnadh."
COM_FINDER_INDEXER_MESSAGE_INIT="Tá an t-innéacsóir ag tosú. Ná dún an fhuinneog seo."
COM_FINDER_INDEXER_MESSAGE_OPTIMIZE="Tá táblaí an innéacs á n-optamú don fheidhmíocht is fearr is féidir. Ná dún an fhuinneog seo."
COM_FINDER_INDEXER_MESSAGE_RUNNING="Tá d'ábhar á innéacsú. Ná dún an fhuinneog seo."
COM_FINDER_INDEXER_MSG_DEBUGGING_INDEXING="Dífhabhtú breiseáin innéacsaithe Cuardach Cliste"
COM_FINDER_INDEXER_MSG_DEBUGGING_INDEXING_TEXT="Roghnaigh breiseán Cuardach Cliste agus soláthair ID le hinneacsú. Taispeánfar toradh an bhreiseáin sin don ID sin sa limistéar thíos."
COM_FINDER_INDEXER_OUTPUT_AREA_TITLE="Aschur"
COM_FINDER_INDEXER_TOOLBAR_TITLE="Innéacsóir: Mód Dífhabhtaithe"
COM_FINDER_ITEM_FIELDSET_ITEM_TITLE="Tréithe mír"
COM_FINDER_ITEM_FIELDSET_TAXONOMIES_TITLE="Tacsanomaíochtaí"
COM_FINDER_ITEM_FIELDSET_TERMS_TITLE="Téarmaí"
COM_FINDER_ITEM_TAXONOMIES_TABLE_CAPTION="Tábla tacsanomaíochtaí"
COM_FINDER_ITEM_TERMS_TABLE_CAPTION="Tábla téarmaí"
COM_FINDER_ITEM_X_ONLY="%s Amháin"
COM_FINDER_ITEMS="Ábhar"
COM_FINDER_LOGGING_DISABLED="Tá bailiú staitisticí díchumasaithe. Cumasaigh é sa %s."
COM_FINDER_LOGGING_DISABLED_NO_AUTH="Tá bailiú staitisticí díchumasaithe. Níl cead agat é seo a athrú. Déan teagmháil le riarthóir láithreán gréasáin más mícheart é seo."
COM_FINDER_MANAGER_SEARCHES="Cuardach Cliste: Anailís ar Théarmaí Cuardaigh"
COM_FINDER_MAPS="Léarscáileanna"
COM_FINDER_MAPS_CONFIRM_DELETE_PROMPT="An bhfuil tú cinnte gur mhaith leat an léarscáil/na léarscáileanna roghnaithe a scriosadh?"
COM_FINDER_MAPS_COUNT_PUBLISHED_ITEMS="Ábhar Innéacsaithe Foilsithe"
COM_FINDER_MAPS_COUNT_UNPUBLISHED_ITEMS="Ábhar Innéacsaithe Neamhfhoilsithe"
COM_FINDER_MAPS_HEADING_BRANCH="Grúpa Léarscáile"
COM_FINDER_MAPS_HEADING_CONTENT_MAP="Léarscáil Ábhair"
COM_FINDER_MAPS_HEADING_TYPE="Cineál Ábhair"
COM_FINDER_MAPS_MULTILANG="Nóta: Tá breiseán córas scagaire teanga cumasaithe, mar sin ní úsáidfear an brainse seo."
COM_FINDER_MAPS_N_ITEMS_DELETED="%d léarscáileanna scriosta."
COM_FINDER_MAPS_N_ITEMS_DELETED_1="Léarscáil scriosta."
COM_FINDER_MAPS_N_ITEMS_FAILED_PUBLISHING="Theip ar fhoilsiú %d léarscáileanna ábhair mar tá ar a laghad ceann dá dtuismitheoirí neamhfhoilsithe nó tá ceann dá leanaí seiceáilte amach."
COM_FINDER_MAPS_N_ITEMS_FAILED_PUBLISHING_1="Theip ar fhoilsiú %d léarscáil ábhair mar go bhfuil ar a laghad ceann dá thuismitheoirí neamhfhoilsithe nó ceann dá leanaí seiceáilte amach."
COM_FINDER_MAPS_N_ITEMS_PUBLISHED="%d léarscáil foilsithe."
COM_FINDER_MAPS_N_ITEMS_PUBLISHED_1="Léarscáil foilsithe."
COM_FINDER_MAPS_N_ITEMS_UNPUBLISHED="%d léarscáil neamhfhoilsithe."
COM_FINDER_MAPS_N_ITEMS_UNPUBLISHED_1="Léarscáil neamhfhoilsithe."
COM_FINDER_MAPS_NO_CONTENT="Níl aon torthaí le taispeáint. Níl aon ábhar innéacsaithe nó ní chomhlíonann aon ábhar do chritéir scagaire."
COM_FINDER_MAPS_SELECT_BRANCH="- Roghnaigh Grúpa Léarscáile -"
COM_FINDER_MAPS_SELECT_TYPE="- Roghnaigh Cineál Ábhair -"
COM_FINDER_MAPS_TABLE_CAPTION="Léarscáileanna Ábhair"
COM_FINDER_MAPS_TOOLBAR_TITLE="Cuardach Cliste: Léarscáileanna Ábhair"
COM_FINDER_MESSAGE_RETURNED="An teachtaireacht seo a leanas a tugadh ar ais ag an bhfreastalaí:"
COM_FINDER_N_ITEMS_CHECKED_IN_1="Mír seiceáilte isteach."
COM_FINDER_N_ITEMS_CHECKED_IN_MORE="%d mír seiceáilte isteach."
COM_FINDER_N_ITEMS_DELETED="%d mír scriosta."
COM_FINDER_N_ITEMS_DELETED_1="Mír scriosta."
COM_FINDER_N_ITEMS_PUBLISHED="%d mír foilsithe."
COM_FINDER_N_ITEMS_PUBLISHED_1="Mír foilsithe."
COM_FINDER_N_ITEMS_TRASHED="%d mír bruscair."
COM_FINDER_N_ITEMS_TRASHED_1="Mír bruscair."
COM_FINDER_N_ITEMS_UNPUBLISHED="%d mír neamhfhoilsithe."
COM_FINDER_N_ITEMS_UNPUBLISHED_1="Mír neamhfhoilsithe."
COM_FINDER_NO_ERROR_RETURNED="Níor tugadh aon earráid ar ais. Déan cinnte go bhfuil tuairisciú earráide cumasaithe."
COM_FINDER_NO_FILTERS="Níl aon scagairí cruthaithe go fóill."
COM_FINDER_NO_RESULTS="Níl aon torthaí a mheaitseálann do chritéir chuardaigh."
COM_FINDER_NO_RESULTS_OR_FILTERS="Níl aon torthaí a mheaitseálann do chritéir chuardaigh nó níl aon scagairí cruthaithe go fóill."
COM_FINDER_PREFILL_SEARCH_LABEL="Téarma Cuardaigh Réamhlíonta"
COM_FINDER_QUERY_FILTER_TODAY="Inniu"
COM_FINDER_QUERY_OPERATOR_AND="Agus"
COM_FINDER_QUERY_OPERATOR_NOT="Ní"
COM_FINDER_QUERY_OPERATOR_OR="Nó"
COM_FINDER_SEARCH_FILTER_SEARCH_DESC="Cuardaigh i dteideal an scagaire."
COM_FINDER_SEARCH_FILTER_SEARCH_LABEL="Scagairí Cuardaigh"
COM_FINDER_SEARCH_IN_PHRASE_DESC="Cuardaigh an frása logáilte de chuardach."
COM_FINDER_SEARCH_IN_PHRASE_LABEL="Scag de réir frása cuardaigh"
COM_FINDER_SEARCH_LABEL="Cuardaigh %s:"
COM_FINDER_SEARCH_SEARCH_QUERY_DESC="Cuardaigh i dteideal an léarscáil ábhair."
COM_FINDER_SEARCH_SEARCH_QUERY_LABEL="Cuardaigh Léarscáileanna Ábhair"
COM_FINDER_SEARCHES_TABLE_CAPTION="Staitisticí Cuardaigh"
COM_FINDER_SELECT_FILTER_LABEL="Scagaire"
COM_FINDER_SELECT_SEARCH_FILTER="Roghnaigh scagaire"
COM_FINDER_STATISTICS="Staitisticí"
COM_FINDER_STATISTICS_LINK_TYPE_COUNT="Líon"
COM_FINDER_STATISTICS_LINK_TYPE_HEADING="Cineál Nasc"
COM_FINDER_STATISTICS_LINK_TYPE_TOTAL="Iomlán"
COM_FINDER_STATISTICS_STATS_DESCRIPTION="Áirítear an t-ábhar innéacsaithe ar an suíomh seo %s téarmaí trasna %s nasc le %s tréithe i %s brainsí."
COM_FINDER_STATISTICS_TITLE="Staitisticí Cuardaigh Cliste"
COM_FINDER_XML_DESCRIPTION="Cuardach Cliste."
