; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONFIG="Cumraíocht"
COM_CONFIG_COMPONENT_VIEW_DEFAULT_DESC="Taispeáin na roghanna cumraíochta don chomhpháirt roghnaithe."
COM_CONFIG_COMPONENT_VIEW_DEFAULT_TITLE="Roghanna Cumraíochta Comhpháirte"
COM_CONFIG_CONFIG_VIEW_DEFAULT_DESC="Taispeánann roghanna cumraíochta domhanda an tsuímh."
COM_CONFIG_CONFIG_VIEW_DEFAULT_TITLE="Roghanna Cumraíochta an tSuímh"
COM_CONFIG_TEMPLATES_VIEW_DEFAULT_DESC="Taispeánann roghanna paraiméadair teimpléid má cheadaíonn an teimpléad é seo."
COM_CONFIG_TEMPLATES_VIEW_DEFAULT_TITLE="Taispeáin Roghanna Teimpléid"
COM_CONFIG_XML_DESCRIPTION="Bainisteoir Cumraíochta"
