; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MESSAGES="Teachtaireacht"
COM_MESSAGES_ADD="Teachtaireacht Phríobháideach Nua"
COM_MESSAGES_CONFIGURATION="Teachtaireachtaí: Roghanna"
COM_MESSAGES_CONFIG_FORM="Mo Shocruithe"
COM_MESSAGES_CONFIG_SAVED="Cumraíocht sábháilte."
COM_MESSAGES_EMPTYSTATE_BUTTON_ADD="Seol teachtaireacht"
COM_MESSAGES_EMPTYSTATE_CONTENT="Seol teachtaireachtaí chuig riarthóirí eile ar do shuíomh agus léigh a bhfreagraí."
COM_MESSAGES_EMPTYSTATE_TITLE="Níl aon teachtaireachtaí agat i do bhosca isteach."
COM_MESSAGES_ERR_INVALID_USER="Úsáideoir neamhbhailí"
COM_MESSAGES_ERR_SEND_FAILED="Tá a mbosca poist faoi ghlas ag an úsáideoir. Theip ar an teachtaireacht."
COM_MESSAGES_ERROR_COULD_NOT_SEND_INVALID_RECIPIENT="Ní féidir an teachtaireacht ríomhphoist a sheoladh mar gheall ar sheoladh faighteora neamhbhailí."
COM_MESSAGES_ERROR_COULD_NOT_SEND_INVALID_REPLYTO="Ní féidir an teachtaireacht ríomhphoist a sheoladh mar gheall ar sheoladh freagra-to neamhbhailí."
COM_MESSAGES_ERROR_INVALID_FROM_USER="Seoltóir neamhbhailí"
COM_MESSAGES_ERROR_INVALID_MESSAGE="Ábhar teachtaireachta neamhbhailí"
COM_MESSAGES_ERROR_INVALID_SUBJECT="Ábhar neamhbhailí"
COM_MESSAGES_ERROR_INVALID_TO_USER="Faighteoir neamhbhailí"
COM_MESSAGES_ERROR_MAIL_FAILED="Níorbh fhéidir an ríomhphost a sheoladh."
COM_MESSAGES_ERROR_MISSING_ROOT_ASSET_GROUPS="Grúpaí sócmhainní fréimhe in easnamh chun fógra a sheoladh."
COM_MESSAGES_ERROR_NO_GROUPS_SET_AS_SUPER_USER="Níl aon ghrúpaí socraithe le ceadanna sár-úsáideora."
COM_MESSAGES_ERROR_NO_USERS_SET_AS_SUPER_USER="Níl aon úsáideoirí socraithe le ceadanna sár-úsáideora."
COM_MESSAGES_ERROR_RECIPIENT_NOT_AUTHORISED="Níl cead ag an bhfaighteoir teachtaireachtaí a fháil."
COM_MESSAGES_FIELD_AUTO_PURGE_LABEL="Teachtaireachtaí a scriosadh go huathoibríoch (laethanta)"
COM_MESSAGES_FIELD_DATE_TIME_LABEL="Postáilte"
COM_MESSAGES_FIELD_LOCK_LABEL="Glas Bosca Isteach"
COM_MESSAGES_FIELD_MAIL_ON_NEW_LABEL="Ríomhphost Teachtaireachtaí Nua"
COM_MESSAGES_FIELD_MESSAGE_LABEL="Teachtaireacht"
COM_MESSAGES_FIELD_SUBJECT_LABEL="Ábhar"
COM_MESSAGES_FIELD_USER_ID_FROM_LABEL="Ó"
COM_MESSAGES_FIELD_USER_ID_TO_LABEL="Faighteoir"
COM_MESSAGES_FILTER_SEARCH_LABEL="Cuardaigh Teachtaireachtaí"
COM_MESSAGES_FILTER_STATES_LABEL="Staid"
COM_MESSAGES_FORM_NEW="Teachtaireacht Nua"
COM_MESSAGES_HEADING_FROM="Ó"
COM_MESSAGES_HEADING_FROM_ASC="Ó ag ardú"
COM_MESSAGES_HEADING_FROM_DESC="Ó ag ísliú"
COM_MESSAGES_HEADING_READ="Léite"
COM_MESSAGES_HEADING_READ_ASC="Léite ag ardú"
COM_MESSAGES_HEADING_READ_DESC="Léite ag ísliú"
COM_MESSAGES_HEADING_SUBJECT="Ábhar"
COM_MESSAGES_HEADING_SUBJECT_ASC="Ábhar ag ardú"
COM_MESSAGES_HEADING_SUBJECT_DESC="Ábhar ag ísliú"
COM_MESSAGES_INVALID_REPLY_ID="Faighteoir neamhbhailí"
COM_MESSAGES_MANAGER_MESSAGES="Teachtaireachtaí Príobháideacha"
COM_MESSAGES_MAIL_NEW_MESSAGE_DESC="Ríomhphost ina bhfuil teachtaireacht cruthaithe sa chomhpháirt teachtaireachtaí."
COM_MESSAGES_MAIL_NEW_MESSAGE_TITLE="Teachtaireachtaí: Teachtaireacht nua"
COM_MESSAGES_MARK_AS_READ="Marcáil mar Léite"
COM_MESSAGES_MARK_AS_UNREAD="Marcáil mar Neamhléite"
COM_MESSAGES_N_ITEMS_DELETED="%d teachtaireachtaí scriosta."
COM_MESSAGES_N_ITEMS_DELETED_1="Teachtaireacht scriosta."
COM_MESSAGES_N_ITEMS_PUBLISHED="%d teachtaireachtaí marcáilte mar léite."
COM_MESSAGES_N_ITEMS_PUBLISHED_1="Teachtaireacht marcáilte mar léite."
COM_MESSAGES_N_ITEMS_TRASHED="%d teachtaireachtaí truflais."
COM_MESSAGES_N_ITEMS_TRASHED_1="Teachtaireacht truflais."
COM_MESSAGES_N_ITEMS_UNPUBLISHED="%d teachtaireachtaí marcáilte mar neamhléite."
COM_MESSAGES_N_ITEMS_UNPUBLISHED_1="Teachtaireacht marcáilte mar neamhléite."
COM_MESSAGES_NEW_MESSAGE="[{SITENAME}] - {SUBJECT}"
COM_MESSAGES_NEW_MESSAGE_BODY="{MESSAGE}"
COM_MESSAGES_NO_ITEM_SELECTED="Níl aon teachtaireachtaí roghnaithe."
COM_MESSAGES_OPTION_READ="Léite"
COM_MESSAGES_OPTION_UNREAD="Neamhléite"
COM_MESSAGES_RE="Re:"
COM_MESSAGES_READ="Teachtaireachtaí"
COM_MESSAGES_SAVE_SUCCESS="Teachtaireacht seolta."
COM_MESSAGES_SEARCH_IN_SUBJECT="Cuardaigh i dteideal agus i dtuairisc na teachtaireachta."
COM_MESSAGES_TABLE_CAPTION="Teachtaireachtaí"
COM_MESSAGES_TOOLBAR_MARK_AS_READ="Marcáil mar Léite"
COM_MESSAGES_TOOLBAR_MARK_AS_UNREAD="Marcáil mar Neamhléite"
COM_MESSAGES_TOOLBAR_MY_SETTINGS="Mo Shocruithe"
COM_MESSAGES_TOOLBAR_REPLY="Freagair"
COM_MESSAGES_TOOLBAR_SEND="Seol"
COM_MESSAGES_VIEW_PRIVATE_MESSAGE="Teachtaireachtaí Príobháideacha: Amharc"
COM_MESSAGES_WRITE_PRIVATE_MESSAGE="Teachtaireachtaí Príobháideacha: Scríobh"
COM_MESSAGES_XML_DESCRIPTION="Comhpháirt le haghaidh tacaíochta teachtaireachtaí príobháideacha sa Chúlra."

JLIB_RULES_SETTING_NOTES_COM_MESSAGES="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann sé i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus a bhaineann le gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé ar chumas an ghnímh don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
