; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_REDIRECT="Aistriúcháin"
COM_REDIRECT_ADVANCED_OPTIONS="Casta"
COM_REDIRECT_BATCH_OPTIONS="Próiseas mórchóir chun URLanna nua a chur leis"
COM_REDIRECT_BATCH_TIP="Cuir isteach URL imithe in éag (éigeantach) le URL nua (roghnach) scartha le %1$s (m.sh. sean-url%1$surl-nua). Gach líne iontráil amháin!"
COM_REDIRECT_BATCH_UPDATE_WITH_NEW_URL="Nuashonraigh Baisc URL(anna) Roghnaithe"
COM_REDIRECT_BULK_SEPARATOR_DESC="An deighilteoir a úsáidtear le haghaidh iompórtáil mórchóir, de réir réamhshocraithe is é '|' é ach is féidir é a bheith ',' le haghaidh cóipeáil / greamaigh ó chomhad CSV mar shampla."
COM_REDIRECT_BULK_SEPARATOR_LABEL="Deighilteoir Iompórtála Mórchóir"
COM_REDIRECT_BUTTON_UPDATE_LINKS="Nuashonraigh Naisc"
COM_REDIRECT_CLEAR_FAIL="Theip ar scriosadh naisc díchumasaithe."
COM_REDIRECT_CLEAR_SUCCESS="Scriosadh gach nasc díchumasaithe."
COM_REDIRECT_COLLECT_MODAL_URLS_DISABLED="%1$s Tá an rogha 'Bailigh URLanna' sa %2$s díchumasaithe. Ní bhailíonn an comhpháirt seo URLanna leathanach earráide."
COM_REDIRECT_COLLECT_URLS_ENABLED="%1$s Tá an rogha 'Bailigh URLanna' cumasaithe."
COM_REDIRECT_CONFIGURATION="Aistriúchán: Roghanna"
COM_REDIRECT_CONFIRM_PURGE="An bhfuil tú cinnte gur mhaith leat gach nasc díchumasaithe a scriosadh?"
COM_REDIRECT_DEFAULT_IMPORT_STATE_DESC="Nuair a bhíonn aistriúcháin á n-iompórtáil i mbaisc, cumasaigh nó díchumasaigh de réir réamhshocraithe."
COM_REDIRECT_DEFAULT_IMPORT_STATE_LABEL="Staid Iompórtála"
COM_REDIRECT_DISABLE_LINK="Díchumasaigh Nasc"
COM_REDIRECT_EDIT_LINK="Cuir Nasc in Eagar #%d"
COM_REDIRECT_EDIT_PLUGIN_SETTINGS="Cuir Socruithe Breiseán in Eagar"
COM_REDIRECT_EMPTYSTATE_BUTTON_ADD="Cuir nasc nua leis"
COM_REDIRECT_EMPTYSTATE_CONTENT="Aistrigh URLanna do leathanaigh ghréasáin nach bhfuil ann a thuilleadh ar do shuíomh gréasáin go leathanaigh ghréasáin atá ag obair."
COM_REDIRECT_EMPTYSTATE_TITLE="Aistriúcháin: Naisc"
COM_REDIRECT_ENABLE_LINK="Cumasaigh Nasc"
COM_REDIRECT_ERROR_DESTINATION_URL_REQUIRED="Caithfidh URL ceann scríbe a bheith ag an aistriúchán"
COM_REDIRECT_ERROR_DUPLICATE_OLD_URL="Caithfidh an URL foinse a bheith uathúil."
COM_REDIRECT_ERROR_DUPLICATE_URLS="Ní féidir leis na URLanna foinse agus ceann scríbe a bheith mar an gcéanna."
COM_REDIRECT_ERROR_SOURCE_URL_REQUIRED="Caithfidh URL foinse a bheith ag an aistriúchán."
COM_REDIRECT_FIELD_COMMENT_LABEL="Tráchtaireacht"
COM_REDIRECT_FIELD_CREATED_DATE_LABEL="Dáta Cruthaithe"
COM_REDIRECT_FIELD_NEW_URL_DESC="Cuir isteach an URL le haistriú chuige."
COM_REDIRECT_FIELD_NEW_URL_LABEL="URL Nua"
COM_REDIRECT_FIELD_OLD_URL_DESC="Cuir isteach an URL atá le haistriú."
COM_REDIRECT_FIELD_OLD_URL_LABEL="URL Imithe in Éag"
COM_REDIRECT_FIELD_REDIRECT_STATUS_CODE_DESC="Roghnaigh an cód stádais HTTP 1.1 le comhcheangal leis an aistriúchán. Ní fhreagraíonn ach cóid stádais ó 300-399 le haistriú."
COM_REDIRECT_FIELD_REDIRECT_STATUS_CODE_LABEL="Cód Stádais Aistriúcháin"
COM_REDIRECT_FIELD_REFERRER_LABEL="Tagairt Nasc"
COM_REDIRECT_FIELD_UPDATED_DATE_LABEL="Dáta Nuashonraithe Deireanach"
COM_REDIRECT_FILTER_SEARCH_DESC="Cuardaigh i URL imithe in éag, URL nua, leathanach tagartha agus trácht. Réamhtheachtaigh le ID: chun ID nasc a chuardach."
COM_REDIRECT_FILTER_SEARCH_LABEL="Cuardaigh Naisc"
COM_REDIRECT_FILTER_SELECT_OPTION_HTTP_HEADER="- Roghnaigh Cód Stádais HTTP -"
COM_REDIRECT_FORM_EDIT="Cuir Aistriúchán in Eagar"
COM_REDIRECT_FORM_NEW="Aistriúchán Nua"
COM_REDIRECT_HEADING_CREATED_DATE="Dáta Cruthaithe"
COM_REDIRECT_HEADING_CREATED_DATE_ASC="Dáta Cruthaithe ag ardú"
COM_REDIRECT_HEADING_CREATED_DATE_DESC="Dáta Cruthaithe ag ísliú"
COM_REDIRECT_HEADING_HITS="Buaileann 404"
COM_REDIRECT_HEADING_HITS_ASC="Buaileann 404 ag ardú"
COM_REDIRECT_HEADING_HITS_DESC="Buaileann 404 ag ísliú"
COM_REDIRECT_HEADING_NEW_URL="URL Nua"
COM_REDIRECT_HEADING_NEW_URL_ASC="URL Nua ag ardú"
COM_REDIRECT_HEADING_NEW_URL_DESC="URL Nua ag ísliú"
COM_REDIRECT_HEADING_OLD_URL="URL Imithe in Éag"
COM_REDIRECT_HEADING_OLD_URL_ASC="URL imithe in éag ag dul suas"
COM_REDIRECT_HEADING_OLD_URL_DESC="URL imithe in éag ag dul síos"
COM_REDIRECT_HEADING_REFERRER="Leathanach Tagartha"
COM_REDIRECT_HEADING_REFERRER_ASC="Leathanach Tagartha ag dul suas"
COM_REDIRECT_HEADING_REFERRER_DESC="Leathanach Tagartha ag dul síos"
COM_REDIRECT_HEADING_STATUS_CODE="Cód Stádais"
COM_REDIRECT_HEADING_STATUS_CODE_ASC="Cód Stádais ag dul suas"
COM_REDIRECT_HEADING_STATUS_CODE_DESC="Cód Stádais ag dul síos"
COM_REDIRECT_MANAGER_LINK_EDIT="Athsheoltaí: Cuir in Eagar"
COM_REDIRECT_MANAGER_LINK_NEW="Athsheoltaí: Nua"
COM_REDIRECT_MANAGER_LINKS="Athsheoltaí: Naisc"
COM_REDIRECT_MODE_DESC="Ligeann an Mód Ardleibhéil úsáid a bhaint as cóid stádais HTTP 1.1 seachas an '301 Bogtha go Buan' réamhshocraithe."
COM_REDIRECT_MODE_LABEL="Gníomhachtaigh Mód Ardleibhéil"
COM_REDIRECT_N_ITEMS_ARCHIVED="%d nasc cartlannaithe."
COM_REDIRECT_N_ITEMS_ARCHIVED_1="Nasc cartlannaithe."
COM_REDIRECT_N_ITEMS_DELETED="%d nasc scriosta."
COM_REDIRECT_N_ITEMS_DELETED_1="Nasc scriosta."
COM_REDIRECT_N_ITEMS_PUBLISHED="%d nasc cumasaithe."
COM_REDIRECT_N_ITEMS_PUBLISHED_1="Nasc cumasaithe."
COM_REDIRECT_N_ITEMS_TRASHED="%d nasc bruscair."
COM_REDIRECT_N_ITEMS_TRASHED_1="Nasc bruscair."
COM_REDIRECT_N_ITEMS_UNPUBLISHED="%d nasc díchumasaithe."
COM_REDIRECT_N_ITEMS_UNPUBLISHED_1="Nasc díchumasaithe."
COM_REDIRECT_N_LINKS_ADDED="%d nasc curtha leis."
COM_REDIRECT_N_LINKS_ADDED_1="Nasc curtha leis."
COM_REDIRECT_N_LINKS_UPDATED="%d nasc nuashonraithe."
COM_REDIRECT_N_LINKS_UPDATED_1="Nasc nuashonraithe."
COM_REDIRECT_NEW_LINK="Nasc Nua"
COM_REDIRECT_NO_ITEM_ADDED="Gan aon nasc curtha leis."
COM_REDIRECT_NO_ITEM_SELECTED="Gan aon nasc roghnaithe."
COM_REDIRECT_NO_SEPARATOR_FOUND="Níor aimsíodh an deighilteoir %s i do iompórtáil."
COM_REDIRECT_PLUGIN_ENABLED="Tá an Breiseán Athsheolta cumasaithe."
COM_REDIRECT_PLUGIN_MODAL_DISABLED="Tá an %s díchumasaithe. Ní mór é a chumasú chun go n-oibreoidh an comhpháirt seo."
COM_REDIRECT_REDIRECTED_ON="Athsheolta ar: %s."
COM_REDIRECT_SAVE_SUCCESS="Nasc sábháilte."
COM_REDIRECT_SEARCH_LINKS="Cuardaigh i réimsí naisc."
COM_REDIRECT_SYSTEM_PLUGIN="Breiseán Córas Athsheolta"
COM_REDIRECT_TOOLBAR_PURGE="Glan Díchumasaithe"
COM_REDIRECT_XML_DESCRIPTION="Cuireann an comhpháirt seo athsheoladh nasc i bhfeidhm."
COM_REDIRECTS_TABLE_CAPTION="Naisc Athsheolta"

JLIB_RULES_SETTING_NOTES_COM_REDIRECT="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú leibhéal níos airde i bhfeidhm.<br><em><strong>Diúltaithe</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus a bhaineann le gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas an chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
