; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_JOOMLAUPDATE="Nuashonrú Joomla!"
COM_JOOMLAUPDATE_DEFAULT_VIEW_DEFAULT_DESC="Seiceáil le haghaidh nuashonruithe Joomla! agus nuashonraigh do shuíomh gréasáin leis an eisiúint is déanaí atá ar fáil."
COM_JOOMLAUPDATE_DEFAULT_VIEW_DEFAULT_TITLE="Féach ar Nuashonruithe Joomla!"
COM_JOOMLAUPDATE_JOOMLAUPDATE_VIEW_DISPLAY_BADGE="Taispeáin Suaitheantas"
COM_JOOMLAUPDATE_XML_DESCRIPTION="Nuashonrú aon-cliceáil go dtí an eisiúint Joomla is déanaí."
