; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_SCHEDULER="Tascanna Sceidealta"
COM_SCHEDULER_ERROR_FORBIDDEN_JUMP_TO_ADD_VIEW="Ní mór duit cineál Tasc a roghnú ar dtús."
COM_SCHEDULER_ERROR_INVALID_TASK_TYPE="Cineál Tasc Neamhbhailí"
COM_SCHEDULER_MANAGER_TASK="Bainisteoir Tascanna"
COM_SCHEDULER_MANAGER_TASK_EDIT="Cuir Tasc in Eagar"
COM_SCHEDULER_MANAGER_TASK_NEW="Tasc Nua"
COM_SCHEDULER_MANAGER_TASKS="Bainisteoir Tascanna"
COM_SCHEDULER_MSG_MANAGE_NO_TASK_PLUGINS="Níl aon chineálacha tascanna a oireann do d'fhiosrúchán."
COM_SCHEDULER_TASKS_VIEW_DEFAULT_DESC="Sceideal agus Bainistigh Rutiní Tascanna."
COM_SCHEDULER_TASKS_VIEW_DEFAULT_TITLE="Tascanna Sceidealta"
COM_SCHEDULER_XML_DESCRIPTION="Comhpháirt chun tascanna sceidealta agus cronjobs a bhainistiú (má thacaíonn an freastalaí leis)."
