; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_SCHEDULER="Tascanna Sceidealta"
COM_SCHEDULER_CLEAR_FAIL="Theip ar scriosadh logaí stair feidhmithe."
COM_SCHEDULER_CONFIGURATION="Cumraíocht Tascanna Sceidealta"
COM_SCHEDULER_CONFIG_FIELDSET_LAZY_SCHEDULER_DESC="Cumraigh conas a spreagann cuairteanna ar an suíomh Tascanna Sceidealta."
COM_SCHEDULER_CONFIG_FIELDSET_LAZY_SCHEDULER_LABEL="Sceidealóir Leisciúil"
COM_SCHEDULER_CONFIG_GENERATE_WEBCRON_KEY_DESC="Teastaíonn eochair chosanta ón webcron sula mbeidh sé feidhmiúil. Cruthóidh sábháil na cumraíochta seo an eochair go huathoibríoch."
COM_SCHEDULER_CONFIG_GLOBAL_WEBCRON_KEY_LABEL="Eochair Dhomhanda"
COM_SCHEDULER_CONFIG_GLOBAL_WEBCRON_LINK_DESC="De réir réamhshocraithe, ní rithfidh iarratas ar an nasc bonn seo ach tascanna atá le feidhmiú. Chun tasc ar leith a fheidhmiú, bain úsáid as ID an tasc mar pharaiméadar fiosrúcháin a ghabhann leis an URL: <code>BASE_URL&id=&lt;taskId&gt;</code>"
COM_SCHEDULER_CONFIG_GLOBAL_WEBCRON_LINK_LABEL="Nasc Webcron (Bonn)"
COM_SCHEDULER_CONFIG_HASH_PROTECTION_DESC="Má tá sé cumasaithe, ní spreagfar tascanna ach nuair a bhíonn an hash sceidealóra mar pharaiméadar ag URLanna."
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_ENABLED_DESC="Má tá sé díchumasaithe, ní spreagfaidh cuairteoirí ar an suíomh tascanna sceidealta.<br>Molta é an Sceidealóir Leisciúil a DHÍCHUMASÚ, má tá tú ag spreagadh le cron dúchais."
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_ENABLED_LABEL="Sceidealóir Leisciúil"
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_INTERVAL_DESC="Eatramh idir iarratais spreagtha sceidealóra ón gcliant."
COM_SCHEDULER_CONFIG_LAZY_SCHEDULER_INTERVAL_LABEL="Eatramh Iarratais (soicindí)"
COM_SCHEDULER_CONFIG_RESET_WEBCRON_KEY_LABEL="Athshocraigh Eochair Rochtana"
COM_SCHEDULER_CONFIG_TASKS_FIELDSET_LABEL="Cumraigh Tascanna"
COM_SCHEDULER_CONFIG_TASK_TIMEOUT_LABEL="Am Teorann Tasc (soicindí)"
COM_SCHEDULER_CONFIG_WEBCRON_DESC="Spreag agus bainistigh feidhmiú tascanna le seirbhís sheachtrach."
COM_SCHEDULER_CONFIG_WEBCRON_ENABLED_LABEL="Cron Gréasáin"
COM_SCHEDULER_CONFIG_WEBCRON_LABEL="Cron Gréasáin"
COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_DESC="Cóipeáil an nasc chuig do ghearrthaisce."
COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_FAIL="Níorbh fhéidir an nasc a chóipeáil."
COM_SCHEDULER_CONFIG_WEBCRON_LINK_COPY_SUCCESS="Nasc cóipeáilte."
COM_SCHEDULER_DESCRIPTION_TASK_PRIORITY="Is féidir le tascanna le tosaíocht níos airde tascanna le tosaíocht níos ísle a bhlocáil go féideartha."
COM_SCHEDULER_DURATION_ASC="Fad ag ardú"
COM_SCHEDULER_DURATION_DESC="Fad ag ísliú"
COM_SCHEDULER_EDIT_TASK="Cuir Tasc in Eagar"
COM_SCHEDULER_EMPTYSTATE_BUTTON_ADD="Cuir do Chéad Tasc leis"
COM_SCHEDULER_EMPTYSTATE_CONTENT="Is gníomhartha ar do shuíomh gréasáin iad tascanna atá sceidealta le tarlú ag amanna socraithe."
COM_SCHEDULER_EMPTYSTATE_TITLE="Níor cruthaíodh Tascanna fós."
COM_SCHEDULER_ERROR_FORBIDDEN_JUMP_TO_ADD_VIEW="Ní mór duit cineál Tasc a roghnú ar dtús."
COM_SCHEDULER_ERROR_INVALID_TASK_TYPE="Cineál Tasc Neamhbhailí"
COM_SCHEDULER_EXECUTION_CRON_EXPRESSION="Léiriú Cron (Ardleibhéal)"
COM_SCHEDULER_EXECUTION_HISTORY="Stair Feidhmithe"
COM_SCHEDULER_EXECUTION_INTERVAL_DAYS="Eatramh, Laethanta"
COM_SCHEDULER_EXECUTION_INTERVAL_HOURS="Eatramh, Uaireanta"
COM_SCHEDULER_EXECUTION_INTERVAL_MINUTES="Eatramh, Nóiméid"
COM_SCHEDULER_EXECUTION_INTERVAL_MONTHS="Eatramh, Míonna"
COM_SCHEDULER_EXITCODE="Cód Scoir"
COM_SCHEDULER_EXIT_CODE_ASC="Cód Scoir ag ardú"
COM_SCHEDULER_EXIT_CODE_DESC="Cód Scoir ag ísliú"
COM_SCHEDULER_EXIT_CODE_EXECUTED="Feidhmithe"
COM_SCHEDULER_EXIT_CODE_FAILED="Theip"
COM_SCHEDULER_EXIT_CODE_WILLRESUME="Tasc Le Leanúint"
COM_SCHEDULER_FIELDSET_BASIC="Réimsí Bunúsacha"
COM_SCHEDULER_FIELDSET_CRON_OPTIONS="Comhoiriúnacht Cron"
COM_SCHEDULER_FIELDSET_EXEC_HIST="Stair Feidhmithe"
COM_SCHEDULER_FIELDSET_LOGGING="Logáil"
COM_SCHEDULER_FIELDSET_NOTIFICATIONS="Fógraí"
COM_SCHEDULER_FIELDSET_PRIORITY="Tosaíocht"
COM_SCHEDULER_FIELDSET_TASK_PARAMS="Paraiméadair Tasc"
COM_SCHEDULER_FIELD_HINT_LOG_FILE_AUTO="réamhshocraithe go 'task_<taskId>.log.php'"
COM_SCHEDULER_FIELD_LABEL_EXEC_RULE="Riail Feidhmithe"
COM_SCHEDULER_FIELD_LABEL_INDIVIDUAL_LOG="Logaí Tasc Aonair"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_DAYS="Eatramh i Laethanta"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_HOURS="Eatramh in Uaireanta"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_MINUTES="Eatramh i Nóiméid"
COM_SCHEDULER_FIELD_LABEL_INTERVAL_MONTHS="Eatramh i Míonna"
COM_SCHEDULER_FIELD_LABEL_LOG_FILE="Ainm an Chomhaid Logála"
COM_SCHEDULER_FIELD_LABEL_SHOW_ORPHANED="Taispeáin Dílleachtaí"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_DAYS_M="Laethanta na Míosa"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_DAYS_W="Laethanta na Seachtaine"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_HOURS="Uaireanta"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_MINUTES="Nóiméid"
COM_SCHEDULER_FIELD_OPTION_INTERVAL_MATCH_MONTHS="Míonna"
COM_SCHEDULER_FIELD_TASK_TYPE="Cineál ID"
COM_SCHEDULER_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus i nóta an tasc. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID tasc."
COM_SCHEDULER_FILTER_SEARCH_HISTORY_DESC="Cuardaigh i dteideal an tasc. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID staire."
COM_SCHEDULER_FILTER_SEARCH_LABEL="Cuardaigh Tascanna"
COM_SCHEDULER_FILTER_SELECT_OPTION_EXITCODE="- Cód Scoir -"
COM_SCHEDULER_FORM_TITLE_EDIT="Cuir Tasc in Eagar"
COM_SCHEDULER_FORM_TITLE_NEW="Tasc Nua"
COM_SCHEDULER_HEADING_TASK_TYPE="- Cineál Tasc -"
COM_SCHEDULER_LABEL_DURATION="Fad"
COM_SCHEDULER_LABEL_EXEC_DAY="Lá Feidhmithe"
COM_SCHEDULER_LABEL_EXEC_INTERVAL="Eatramh Feidhmithe"
COM_SCHEDULER_LABEL_EXEC_TIME="Am Feidhmithe (UTC)"
COM_SCHEDULER_LABEL_EXIT_CODE="Cód Scoir Deireanach"
COM_SCHEDULER_LABEL_LAST_EXEC="Feidhmithe Deireanach"
COM_SCHEDULER_LABEL_NEXT_EXEC="Feidhmiú Eile"
COM_SCHEDULER_LABEL_NOTES="Nóta"
COM_SCHEDULER_LABEL_TASK_PRIORITY="Tosaíocht"
COM_SCHEDULER_LABEL_TASK_PRIORITY_HIGH="Ard"
COM_SCHEDULER_LABEL_TASK_PRIORITY_LOW="Íseal"
COM_SCHEDULER_LABEL_TASK_PRIORITY_NORMAL="Gnáth"
COM_SCHEDULER_LABEL_TIMES_EXEC="Uaireanta Feidhmithe"
COM_SCHEDULER_LABEL_TIMES_FAIL="Uaireanta Theip"
COM_SCHEDULER_LAST_RUN_ASC="Rith Deireanach ag ardú"
COM_SCHEDULER_LAST_RUN_DATE="Dáta Rith Deireanach"
COM_SCHEDULER_LAST_RUN_DESC="Rith Deireanach ag titim"
COM_SCHEDULER_LOGS_CLEAR="Scriosadh gach loga staire feidhmithe."
COM_SCHEDULER_LOGS_N_ITEMS_DELETED="%d loga scriosta."
COM_SCHEDULER_LOGS_N_ITEMS_DELETED_1="Loga scriosta."
COM_SCHEDULER_MANAGER_TASKS="Tascanna Sceidealta"
COM_SCHEDULER_MANAGER_TASK_EDIT="Cuir Tasc in Eagar"
COM_SCHEDULER_MANAGER_TASK_NEW="Tasc Nua"
COM_SCHEDULER_MANAGER_TOOLTIP_NOT_AUTHORIZED="Ní údaraithe"
COM_SCHEDULER_MANAGER_TOOLTIP_TASK_FAILING="Theip ar an tasc. Cód scoir: %1$d"
COM_SCHEDULER_MANAGER_TOOLTIP_TASK_TRASHED="Cuireadh an tasc sa bhruscar"
COM_SCHEDULER_MSG_DUETASKS="Tá ar a laghad tasc amháin dlite a ba chóir a bheith rite cheana féin. Déan cinnte go bhfuil ar a laghad sceidealóir cron amháin cumasaithe agus ag rith."
COM_SCHEDULER_MSG_MANAGE_NO_TASK_PLUGINS="Níl aon chineálacha tascanna a mheaitseálann do cheist."
COM_SCHEDULER_NEW_TASK="Tasc Nua"
COM_SCHEDULER_NEXT_RUN_ASC="Rith Eile ag ardú"
COM_SCHEDULER_NEXT_RUN_DATE="Dáta Rith Eile"
COM_SCHEDULER_NEXT_RUN_DESC="Rith Eile ag titim"
COM_SCHEDULER_NEXT_RUN_MANUAL="Lámhleabhar"
COM_SCHEDULER_N_ITEMS_CHECKED_IN_1="Tasc seiceáilte isteach."
COM_SCHEDULER_N_ITEMS_CHECKED_IN_MORE="%d tascanna seiceáilte isteach."
COM_SCHEDULER_N_ITEMS_DELETED="%d tascanna scriosta."
COM_SCHEDULER_N_ITEMS_DELETED_1="Tasc scriosta."
COM_SCHEDULER_N_ITEMS_FAILED_UNLOCKING="Theip ar dhíghlasáil %d tascanna."
COM_SCHEDULER_N_ITEMS_FAILED_UNLOCKING_1="Theip ar dhíghlasáil tasc amháin."
COM_SCHEDULER_N_ITEMS_PUBLISHED="%d tascanna cumasaithe."
COM_SCHEDULER_N_ITEMS_PUBLISHED_1="Tasc cumasaithe."
COM_SCHEDULER_N_ITEMS_TRASHED="%d tascanna curtha sa bhruscar."
COM_SCHEDULER_N_ITEMS_TRASHED_1="Tasc curtha sa bhruscar."
COM_SCHEDULER_N_ITEMS_UNPUBLISHED="%d tascanna díchumasaithe."
COM_SCHEDULER_N_ITEMS_UNPUBLISHED_1="Tasc díchumasaithe."
COM_SCHEDULER_N_ITEMS_UNLOCKED="%d tascanna díghlasáilte."
COM_SCHEDULER_N_ITEMS_UNLOCKED_1="Tasc díghlasáilte."
COM_SCHEDULER_OPTION_EXECUTION_MANUAL_LABEL="Feidhmiú Lámhleabhar"
COM_SCHEDULER_OPTION_ORPHANED_HIDE="Folaigh Díchéile"
COM_SCHEDULER_OPTION_ORPHANED_ONLY="Díchéile Amháin"
COM_SCHEDULER_OPTION_ORPHANED_SHOW="Taispeáin Díchéile"
COM_SCHEDULER_PERMISSION_TESTRUN="Tástáil tasc"
COM_SCHEDULER_ROUTINE_LOG_PREFIX="Tasc> "
COM_SCHEDULER_RUNNING_SINCE="Ag rith ó %s"
COM_SCHEDULER_SCHEDULER="Sceidealóir"
COM_SCHEDULER_SCHEDULER_TASK_COMPLETE="Críochnaíodh tasc#%1$02d go rathúil i %2$.2f (glan %3$.2f) soicind."
COM_SCHEDULER_SCHEDULER_TASK_LOCKED="tasc#%1$02d faoi ghlas."
COM_SCHEDULER_SCHEDULER_TASK_ROUTINE_NA="Níl aon ghnáthamh comhfhreagrach ag tasc#%1$02d. B'fhéidir go raibh an breiseán díchumasaithe nó bainte. Ag scipeáil feidhmiú."
COM_SCHEDULER_SCHEDULER_TASK_START="Ag rith tasc#%1$02d '%2$s'."
COM_SCHEDULER_SCHEDULER_TASK_UNKNOWN_EXIT="D'éirigh tasc#%1$02d le cód %4$d i %2$.2f (glan %3$.2f) soicind."
COM_SCHEDULER_SCHEDULER_TASK_UNLOCKED="Díghlasáladh tasc#%1$02d."
COM_SCHEDULER_SCHEDULER_TASK_WILL_RESUME="Tá tuilleadh oibre le déanamh ag tasc#%1$02d."
COM_SCHEDULER_SELECT_INTERVAL_MINUTES="- Roghnaigh eatramh i Nóiméid -"
COM_SCHEDULER_SELECT_TASK_TYPE="Roghnaigh tasc, %s"
COM_SCHEDULER_SELECT_TYPE="- Cineál Tasc -"
COM_SCHEDULER_TABLE_CAPTION="Tascanna"
COM_SCHEDULER_TASK="Tasc"
COM_SCHEDULER_TASKS_VIEW_DEFAULT_DESC="Sceideal agus Bainistigh Gnáthaimh Tascanna."
COM_SCHEDULER_TASKS_VIEW_DEFAULT_TITLE="Tascanna Sceidealta"
COM_SCHEDULER_TASK_EXECUTED="Curtha i gcrích: %s"
COM_SCHEDULER_TASK_FAILED="Theip: %s"
COM_SCHEDULER_TASK_PARAMS_FIELDSET_LABEL="Paraiméadair Tasc"
COM_SCHEDULER_TASK_PRIORITY="Tosaíocht Tasc"
COM_SCHEDULER_TASK_PRIORITY_ASC="Tosaíocht Tasc ag ardú"
COM_SCHEDULER_TASK_PRIORITY_DESC="Tosaíocht Tasc ag titim"
COM_SCHEDULER_TASK_RESUME="Athbhunófar: %s"
COM_SCHEDULER_TASK_ROUTINE_EXCEPTION="Threw gnáthamh eisceacht: %1$s"
COM_SCHEDULER_TASK_TIMES_ASC="Amanna ag ardú"
COM_SCHEDULER_TASK_TIMES_DESC="Amanna ag titim"
COM_SCHEDULER_TASK_TYPE="Cineál Tasc"
COM_SCHEDULER_TASK_TYPE_ASC="Cineál Tasc ag ardú"
COM_SCHEDULER_TASK_TYPE_DESC="Cineál Tasc ag titim"
COM_SCHEDULER_TEST_RUN="Rith Tástáil"
COM_SCHEDULER_TEST_RUN_DURATION="Fad: %s soicind"
COM_SCHEDULER_TEST_RUN_OUTPUT="Aschur:<br>%s"
COM_SCHEDULER_TEST_RUN_STATUS_COMPLETED="Stádas: Críochnaithe"
COM_SCHEDULER_TEST_RUN_STATUS_STARTED="Stádas: Tosaíodh"
COM_SCHEDULER_TEST_RUN_STATUS_TERMINATED="Stádas: Críochnaithe"
COM_SCHEDULER_TEST_RUN_TASK="Tasc: \"%s\""
COM_SCHEDULER_TEST_RUN_TITLE="Tástáil tasc (ID: %d)"
COM_SCHEDULER_TEST_TASK="Tástáil Tasc"
COM_SCHEDULER_TOOLBAR_PURGE="Glan Stair"
COM_SCHEDULER_TOOLBAR_PURGE_CONFIRM="An bhfuil tú cinnte gur mhaith leat an Stair Feidhmithe go léir a scriosadh?"
COM_SCHEDULER_TOOLBAR_UNLOCK="Díghlasáil"
COM_SCHEDULER_TYPE_CHOOSE="Roghnaigh cineál Tasc"
COM_SCHEDULER_WARNING_EXISTING_TASK_TYPE_NOT_FOUND="Níorbh fhéidir an gnáthamh tasc don tasc seo a aimsiú!<br>Is dócha gur baineadh nó gur díchumasadh an breiseán soláthraí."
COM_SCHEDULER_XML_DESCRIPTION="Comhpháirt le haghaidh tascanna sceidealta agus cronjobs a bhainistiú (má thacaíonn an freastalaí leis)."
JLIB_HTML_PUBLISH_ITEM="Cumasaigh tasc"
JLIB_HTML_UNPUBLISH_ITEM="Díchumasaigh tasc"
