; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENTHISTORY_BUTTON_COMPARE="Comparáid"
COM_CONTENTHISTORY_BUTTON_COMPARE_DESC="Roghnaigh dhá leagan agus roghnaigh chun iad a chur i gcomparáid."
COM_CONTENTHISTORY_BUTTON_DELETE="Scrios"
COM_CONTENTHISTORY_BUTTON_DELETE_DESC="Roghnaigh leagan amháin nó níos mó agus roghnaigh chun iad a scriosadh go buan."
COM_CONTENTHISTORY_BUTTON_KEEP="Coinnigh Ar/As"
COM_CONTENTHISTORY_BUTTON_KEEP_DESC="Roghnaigh leagan amháin nó níos mó agus roghnaigh chun an coinnigh go deo a chasadh air nó as."
COM_CONTENTHISTORY_BUTTON_LOAD="Athchóirigh"
COM_CONTENTHISTORY_BUTTON_LOAD_DESC="Luchtaíonn an cnaipe seo an leagan roghnaithe isteach sa fhoirm eagarthóireachta."
COM_CONTENTHISTORY_BUTTON_PREVIEW="Réamhamharc"
COM_CONTENTHISTORY_BUTTON_PREVIEW_DESC="Ligeann an cnaipe seo duit réamhamharc den leagan roghnaithe a fheiceáil."
COM_CONTENTHISTORY_BUTTON_SELECT_ONE_VERSION="Roghnaigh leagan amháin le do thoil."
COM_CONTENTHISTORY_BUTTON_SELECT_TWO_VERSIONS="Roghnaigh dhá leagan le do thoil."
COM_CONTENTHISTORY_CHARACTER_COUNT="Líon na gCarachtar"
COM_CONTENTHISTORY_COMPARE_CAPTION="Comparáid Dhá Leagan"
COM_CONTENTHISTORY_COMPARE_DIFF="Athruithe"
COM_CONTENTHISTORY_COMPARE_NEW="Nua"
COM_CONTENTHISTORY_COMPARE_OLD="Sean"
COM_CONTENTHISTORY_COMPARE_TITLE="Amharc Comparáide"
COM_CONTENTHISTORY_ERROR_FAILED_LOADING_CONTENT_TYPE="Theip ar luchtú an chineál ábhair."
COM_CONTENTHISTORY_ERROR_INVALID_ID="ID neamhbhailí roghnaithe."
COM_CONTENTHISTORY_ERROR_KEEP_NOT_PERMITTED="Níl cead agat stádas an coinnigh go deo a athrú."
COM_CONTENTHISTORY_ERROR_VERSION_NOT_FOUND="Ní bhfuarthas an leagan."
COM_CONTENTHISTORY_KEEP_VERSION="Coinnigh go Deo"
COM_CONTENTHISTORY_MODAL_TITLE="Stair Leagan Míre"
COM_CONTENTHISTORY_N_ITEMS_DELETED="Scriosadh %d leagan stairiúil."
COM_CONTENTHISTORY_N_ITEMS_DELETED_1="Scriosadh leagan stairiúil."
COM_CONTENTHISTORY_N_ITEMS_KEEP_TOGGLE="Athraíodh an luach coinnigh go deo do %d leagan stairiúil."
COM_CONTENTHISTORY_N_ITEMS_KEEP_TOGGLE_1="Athraíodh an luach coinnigh go deo do leagan stairiúil."
COM_CONTENTHISTORY_NO_ITEM_SELECTED="Níor roghnaíodh leagan stairiúil."
COM_CONTENTHISTORY_PREVIEW_CAPTION="Sonraí Leagain"
COM_CONTENTHISTORY_PREVIEW_FIELD="Réimse"
COM_CONTENTHISTORY_PREVIEW_SUBTITLE="Nóta leagain: %s"
COM_CONTENTHISTORY_PREVIEW_SUBTITLE_DATE="Réamhamharc ar leagan ó %s"
COM_CONTENTHISTORY_PREVIEW_VALUE="Luach"
COM_CONTENTHISTORY_VERSION_CAPTION="Gach Leagan"
COM_CONTENTHISTORY_VERSION_NOTE="Nóta Leagain"
