; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_LANGUAGES="Teangacha"
COM_LANGUAGES_CONFIGURATION="Teangacha: Roghanna"
COM_LANGUAGES_CONTENT_TABLE_CAPTION="Teangacha Ábhair"
COM_LANGUAGES_ERR_NO_LANGUAGE_SELECTED="Níl aon teanga roghnaithe."
COM_LANGUAGES_ERR_PUBLISH="Roghnaigh teanga le foilsiú."
COM_LANGUAGES_ERROR_LANG_TAG="<br>Ba chóir go mbeadh 2 nó 3 litir bheaga sa Chlib Teanga a fhreagraíonn don teanga ISO, fleiscín agus 2 litir mhóra a fhreagraíonn don chód tíre ISO. <br>Ba chóir gurb é seo an réimír cruinn a úsáidtear don teanga atá suiteáilte nó le suiteáil. Sampla: en-GB, srp-ME."
COM_LANGUAGES_ERROR_LANGUAGE_METAFILE_MISSING="Níorbh fhéidir comhad XML meiteashonraí teanga %s a lódáil ó %s."
COM_LANGUAGES_ERROR_SEF="<br>Ba chóir go mbeadh ach carachtair alfa-uimhriúla agus fleiscíní (-) sa \"Cód Teanga URL\".<br>Chun carachtair UTF-8 a úsáid, ba chóir \"Ailiasanna Unicode\" a shocrú go \"Tá\" sa Chumraíocht Domhanda."
COM_LANGUAGES_FIELD_IMAGE_LABEL="Íomhá"
COM_LANGUAGES_FIELD_LANG_CODE_DESC="Beidh an Cód Teanga seo san áireamh i URL an tsuímh. Tabhair faoi deara <em>caithfidh an Cód Teanga a bheith uathúil i measc na dteangacha go léir</em>."
COM_LANGUAGES_FIELD_LANG_CODE_LABEL="Cód Teanga URL"
COM_LANGUAGES_FIELD_LANG_TAG_DESC="Cuir isteach an chlib teanga – sampla: en-GB don Bhéarla (en-GB). Ba chóir gurb é seo an réimír cruinn a úsáidtear don teanga atá suiteáilte nó le suiteáil."
COM_LANGUAGES_FIELD_LANG_TAG_LABEL="Clib Teanga"
COM_LANGUAGES_FIELD_SITE_NAME_LABEL="Ainm Suímh Saincheaptha"
COM_LANGUAGES_FIELD_TITLE_NATIVE_LABEL="Teideal sa Teanga Dhúchais"
COM_LANGUAGES_FIELDSET_SITE_NAME_LABEL="Ainm an tSuímh"
COM_LANGUAGES_HEADING_AUTHOR="Údar"
COM_LANGUAGES_HEADING_AUTHOR_ASC="Údar ag ardú"
COM_LANGUAGES_HEADING_AUTHOR_DESC="Údar ag ísliú"
COM_LANGUAGES_HEADING_AUTHOR_EMAIL="Ríomhphost an Údair"
COM_LANGUAGES_HEADING_AUTHOR_EMAIL_ASC="Ríomhphost an Údair ag ardú"
COM_LANGUAGES_HEADING_AUTHOR_EMAIL_DESC="Ríomhphost an Údair ag ísliú"
COM_LANGUAGES_HEADING_DATE="Dáta"
COM_LANGUAGES_HEADING_DATE_ASC="Dáta ag ardú"
COM_LANGUAGES_HEADING_DATE_DESC="Dáta ag ísliú"
COM_LANGUAGES_HEADING_DEFAULT="Réamhshocrú"
COM_LANGUAGES_HEADING_DEFAULT_ASC="Réamhshocrú ag ardú"
COM_LANGUAGES_HEADING_DEFAULT_DESC="Réamhshocrú ag ísliú"
COM_LANGUAGES_HEADING_HOMEPAGE="Baile"
COM_LANGUAGES_HEADING_HOMEPAGE_ASC="Baile ag ardú"
COM_LANGUAGES_HEADING_HOMEPAGE_DESC="Baile ag ísliú"
COM_LANGUAGES_HEADING_LANG_CODE="Cód Teanga URL"
COM_LANGUAGES_HEADING_LANG_CODE_ASC="Cód Teanga URL ag ardú"
COM_LANGUAGES_HEADING_LANG_CODE_DESC="Cód Teanga URL ag ísliú"
COM_LANGUAGES_HEADING_LANG_IMAGE="Íomhá"
COM_LANGUAGES_HEADING_LANG_IMAGE_ASC="Íomhá ag ardú"
COM_LANGUAGES_HEADING_LANG_IMAGE_DESC="Íomhá ag ísliú"
COM_LANGUAGES_HEADING_LANG_TAG="Clib Teanga"
COM_LANGUAGES_HEADING_LANG_TAG_ASC="Clib Teanga ag ardú"
COM_LANGUAGES_HEADING_LANG_TAG_DESC="Clib Teanga ag ísliú"
COM_LANGUAGES_HEADING_TITLE_ASC="Teideal ag ardú"
COM_LANGUAGES_HEADING_TITLE_DESC="Teideal ag ísliú"
COM_LANGUAGES_HEADING_TITLE_NATIVE="Teideal Dúchais"
COM_LANGUAGES_HEADING_TITLE_NATIVE_ASC="Teideal Dúchais ag ardú"
COM_LANGUAGES_HEADING_TITLE_NATIVE_DESC="Teideal Dúchais ag ísliú"
COM_LANGUAGES_HEADING_VERSION="Leagan"
COM_LANGUAGES_HEADING_VERSION_ASC="Leagan ag ardú"
COM_LANGUAGES_HEADING_VERSION_DESC="Leagan ag ísliú"
COM_LANGUAGES_HOMEPAGE="Baile"
COM_LANGUAGES_INSTALL="Teangacha a Shuiteáil"
COM_LANGUAGES_INSTALLED_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus i gclib teanga."
COM_LANGUAGES_INSTALLED_FILTER_SEARCH_LABEL="Cuardaigh Teangacha Suiteáilte"
COM_LANGUAGES_INSTALLED_TABLE_CAPTION="Teangacha Suiteáilte"
COM_LANGUAGES_LANGUAGE_FORM_EDIT="Eagar Teanga"
COM_LANGUAGES_LANGUAGE_FORM_NEW="Teanga Nua"
COM_LANGUAGES_LANGUAGE_NEW_LANGUAGE_TITLE="Sonraí Nua Teanga Ábhair"
COM_LANGUAGES_MSG_DEFAULT_LANGUAGE_SAVED="Teanga Réamhshocraithe Sábháilte. Ní chuireann sé seo isteach ar úsáideoirí a roghnaigh teanga shonrach ina bpróifíl nó ar an leathanach logála isteach."
COM_LANGUAGES_MSG_DEFAULT_MULTILANG_SAVED="Teanga Réamhshocraithe Sábháilte. Ní chuireann sé seo isteach ar úsáideoirí a roghnaigh teanga shonrach ina bpróifíl nó ar an leathanach logála isteach.<br><strong>Rabhadh!</strong> Caithfidh Teanga Réamhshocraithe an tSuímh a bheith ina teanga Ábhair foilsithe freisin."
COM_LANGUAGES_MSG_SWITCH_ADMIN_LANGUAGE_SUCCESS="Tá Teanga an Riarthóra athraithe go &quot;<strong>%s</strong>&quot;."
COM_LANGUAGES_MULTILANGSTATUS_CONTACTS_ERROR="Tá roinnt de na teagmhálacha nasctha leis an úsáideoir <strong>%s</strong> mícheart."
COM_LANGUAGES_MULTILANGSTATUS_CONTACTS_ERROR_TIP="Rabhadh! Níor cheart go mbeadh ach teagmháil amháin ag úsáideoir/údar a bhfuil teanga 'Uile' sannta dó NÓ teagmháil amháin do gach Teanga Ábhair foilsithe."
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_HOME_UNPUBLISHED="Tá an Teanga Ábhair <strong>%s</strong> agus a leathanach Baile neamhfhoilsithe. <strong>Ní thaispeánfar an teanga ar an suíomh.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_MISSING="Tá an Teanga Ábhair <strong>%s</strong> scriosta cé go bhfuil Teanga an tSuímh comhfhreagrach cumasaithe agus leathanach Baile sannta don teanga seo. <strong>Ní thaispeánfar an teanga ar an suíomh.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_PUBLISHED="Teangacha Ábhair Foilsithe"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_SEF_MISSING="Tá an \"Cód Teanga URL\" in easnamh don Teanga Ábhair <strong>%s</strong>. <strong>B'fhéidir nach n-oibreoidh an ghné ilteangach i gceart nó nach mbeidh teacht ar an suíomh!</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_LANGUAGE_TRASHED="Tá an Teanga Ábhair <strong>%s</strong> sa bhruscar. <strong>Ní thaispeánfar an teanga ar an suíomh.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_CONTENT_TABLE_CAPTION="Stádas Teanga Ábhair"
; The following string is deprecated and will be removed with 7.0
COM_LANGUAGES_MULTILANGSTATUS_DEFAULT_HOME_MODULE_PUBLISHED="Níor cheart go mbeadh an modúl roghchláir a thaispeánann an mhír roghchláir Baile socraithe go teanga &quot;Uile&quot; foilsithe."
COM_LANGUAGES_MULTILANGSTATUS_ERROR_CONTENT_LANGUAGE="Tá leathanach Baile Réamhshocraithe sannta don Teanga Ábhair <strong>%s</strong> cé nach bhfuil Teanga an tSuímh don Teanga Ábhair seo suiteáilte nó cumasaithe AGUS/NÓ nach bhfuil an Teanga Ábhair foilsithe. <strong>Ní thaispeánfar an teanga ar an suíomh.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_ERROR_DEFAULT_CONTENT_LANGUAGE="Tá an Teanga Ábhair don Teanga Réamhshocraithe an tSuímh <strong>%s</strong> neamhfhoilsithe nó nach bhfuil ann. <strong>B'fhéidir nach n-oibreoidh an ghné ilteangach i gceart nó nach mbeidh teacht ar an suíomh!</strong>"
COM_LANGUAGES_MULTILANGSTATUS_ERROR_LANGUAGE_TAG="Níl clib Teanga Ábhair <strong>%s</strong> ag teacht le clib Teanga an tSuímh. Seiceáil go bhfuil Teanga an tSuímh suiteáilte agus cumasaithe AGUS go bhfuil an chlib teanga cheart in úsáid don Teanga Ábhair. Sampla: do Bhéarla (en-GB) ba cheart go mbeadh an dá chlib 'en-GB'. <strong>Ní thaispeánfar an teanga ar an suíomh.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_HOMES_PUBLISHED="Leathanaigh Baile Réamhshocraithe Foilsithe"
COM_LANGUAGES_MULTILANGSTATUS_HOMES_PUBLISHED_ALL="1 sannaithe don teanga 'Uile'."
COM_LANGUAGES_MULTILANGSTATUS_HOMES_PUBLISHED_INCLUDING_ALL="Leathanaigh Baile Réamhshocraithe Foilsithe (lena n-áirítear 1 sannaithe don teanga &quot;Uile&quot;)."
COM_LANGUAGES_MULTILANGSTATUS_HOME_UNPUBLISHED="Níl an Leathanach Baile Réamhshocraithe a sannadh don <strong>%s</strong> Teanga Ábhair foilsithe. <strong>Ní thaispeánfar an teanga ar an suíomh.</strong>"
COM_LANGUAGES_MULTILANGSTATUS_LANGSWITCHER_PUBLISHED="Modúil Athraithe Teanga Foilsithe."
COM_LANGUAGES_MULTILANGSTATUS_LANGSWITCHER_UNPUBLISHED="Caithfear ar a laghad modúl amháin Athraithe Teanga socraithe don teanga &quot;Uile&quot; a fhoilsiú. Seachas sin, beidh sé dodhéanta teangacha a athrú ar an suíomh. Déan neamhaird ar an teachtaireacht seo mura n-úsáideann tú modúl athraithe teanga ach naisc dhíreacha."
COM_LANGUAGES_MULTILANGSTATUS_LANGUAGEFILTER="Breiseán Scagaire Teanga"
COM_LANGUAGES_MULTILANGSTATUS_LANGUAGEFILTER_DISABLED="Níl an breiseán Scagaire Teanga cumasaithe cé go bhfuil modúil Athraithe Teanga amháin nó níos mó AGUS/NO leathanach baile réamhshocraithe teanga ábhair ar leith foilsithe."
COM_LANGUAGES_MULTILANGSTATUS_NONE="Níl an suíomh seo socraithe mar shuíomh ilteangach."
COM_LANGUAGES_MULTILANGSTATUS_SITE_LANG_PUBLISHED="Teangacha Suímh Cumasaithe"
COM_LANGUAGES_MULTILANGSTATUS_TABLE_CAPTION="Stádas Ilteangach"
COM_LANGUAGES_MULTILANGSTATUS_USELESS_HOMES="Níl an suíomh seo socraithe mar shuíomh ilteangach.<br><strong>Nóta</strong>: tá leathanach baile réamhshocraithe ar a laghad sannaithe do Theanga Ábhair. Ní bhrisfidh sé seo suíomh aon-teangach ach tá sé gan úsáid."
COM_LANGUAGES_NO_ITEM_SELECTED="Níor roghnaíodh aon teangacha."
COM_LANGUAGES_N_ITEMS_DELETED="%d Teangacha Ábhair scriosta."
COM_LANGUAGES_N_ITEMS_DELETED_1="Teanga Ábhair scriosta."
COM_LANGUAGES_N_ITEMS_PUBLISHED="%d Teangacha Ábhair foilsithe."
COM_LANGUAGES_N_ITEMS_PUBLISHED_1="Teanga Ábhair foilsithe."
COM_LANGUAGES_N_ITEMS_TRASHED="%d Teangacha Ábhair bruscair."
COM_LANGUAGES_N_ITEMS_TRASHED_1="Teanga Ábhair bruscair."
COM_LANGUAGES_N_ITEMS_UNPUBLISHED="%d Teangacha Ábhair neamhfhoilsithe. <br><strong>Rabhadh!</strong> Agus an fheidhmiúlacht ilteangach á úsáid (ie nuair a bhíonn an breiseán Córas - Scagaire Teanga cumasaithe) caithfidh teanga ábhair foilsithe a bheith sannaithe don Teanga Réamhshocraithe Suímh."
COM_LANGUAGES_N_ITEMS_UNPUBLISHED_1="Teanga Ábhair neamhfhoilsithe. <br><strong>Rabhadh!</strong> Agus an fheidhmiúlacht ilteangach á úsáid (ie nuair a bhíonn an breiseán Córas - Scagaire Teanga cumasaithe) caithfidh teanga ábhair foilsithe a bheith sannaithe don Teanga Réamhshocraithe Suímh."
COM_LANGUAGES_N_QUICKICON="Teangacha"
COM_LANGUAGES_N_QUICKICON_1="Teanga"
COM_LANGUAGES_N_QUICKICON_SRONLY="Teangacha: tá %d teangacha cumasaithe."
COM_LANGUAGES_N_QUICKICON_SRONLY_1="Teangacha: Tá teanga amháin cumasaithe."
COM_LANGUAGES_OVERRIDE_ERROR_RESERVED_WORDS="Is focail chúlchiste iad TÁ, NÍL, NULL, BRÉAGACH, AR, AS, AON, FÍOR agus ní féidir iad a úsáid mar chonstantaí teanga."
COM_LANGUAGES_OVERRIDE_FIELD_BOTH_LABEL="Do an Dá Suíomh"
COM_LANGUAGES_OVERRIDE_FIELD_CLIENT_LABEL="Suíomh"
COM_LANGUAGES_OVERRIDE_FIELD_FILE_LABEL="Comhad"
COM_LANGUAGES_OVERRIDE_FIELD_KEY_LABEL="Constaic Teanga"
COM_LANGUAGES_OVERRIDE_FIELD_LANGUAGE_LABEL="Teanga"
COM_LANGUAGES_OVERRIDE_FIELD_OVERRIDE_LABEL="Téacs"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHSTRING_LABEL="Téacs Cuardaigh"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHTYPE_CONSTANT="Constaic"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHTYPE_LABEL="Cuardaigh Do"
COM_LANGUAGES_OVERRIDE_FIELD_SEARCHTYPE_TEXT="Luach"
COM_LANGUAGES_OVERRIDE_FIRST_SELECT_MESSAGE="Chun forluí nua a chruthú, roghnaigh teanga agus cliant ar dtús le do thoil."
COM_LANGUAGES_OVERRIDE_SELECT_LANGUAGE="- Roghnaigh Teanga & Cliant -"
COM_LANGUAGES_OVERRIDE_SELECT_LANGUAGECLIENT="Roghnaigh Teanga & Cliant"
COM_LANGUAGES_OVERRIDES_TABLE_CAPTION="Forluíthe Teanga"
COM_LANGUAGES_SAVE_SUCCESS="Teanga Ábhair sábháilte."
COM_LANGUAGES_SEARCH_IN_TITLE="Cuardaigh sa teideal."
COM_LANGUAGES_SWITCH_ADMIN="Aistrigh Teanga"
COM_LANGUAGES_VIEW_INSTALLED_ADMIN_TITLE="Teangacha: Suiteáilte (Riarthóir)"
COM_LANGUAGES_VIEW_INSTALLED_SITE_TITLE="Teangacha: Suiteáilte (Suíomh)"
COM_LANGUAGES_VIEW_LANGUAGE_EDIT_EDIT_TITLE="Teangacha: Cuir Teanga Ábhair in Eagar"
COM_LANGUAGES_VIEW_LANGUAGE_EDIT_NEW_TITLE="Teangacha: Teanga Ábhair Nua"
COM_LANGUAGES_VIEW_LANGUAGES_TITLE="Teangacha: Ábhar"
COM_LANGUAGES_VIEW_OVERRIDE_CLIENT_ADMINISTRATOR="Riarthóir"
COM_LANGUAGES_VIEW_OVERRIDE_CLIENT_SITE="Suíomh"
COM_LANGUAGES_VIEW_OVERRIDE_EDIT_EDIT_OVERRIDE_LEGEND="Cuir an Forluí seo in Eagar"
COM_LANGUAGES_VIEW_OVERRIDE_EDIT_NEW_OVERRIDE_LEGEND="Cruthaigh Forluí Nua"
COM_LANGUAGES_VIEW_OVERRIDE_EDIT_TITLE="Teangacha: Cuir Forluí in Eagar"
COM_LANGUAGES_VIEW_OVERRIDE_FORM_EDIT="Cuir Forluí in Eagar"
COM_LANGUAGES_VIEW_OVERRIDE_FORM_NEW="Forluí Nua"
COM_LANGUAGES_VIEW_OVERRIDE_LANGUAGE="%1$s [%2$s]"
COM_LANGUAGES_VIEW_OVERRIDE_MORE_RESULTS="Tuilleadh Torthaí"
COM_LANGUAGES_VIEW_OVERRIDE_NO_RESULTS="Níor aimsíodh aon téacsanna a mheaitseálann."
COM_LANGUAGES_VIEW_OVERRIDE_REFRESHING="Fan le do thoil agus an taisce á athchruthú."
COM_LANGUAGES_VIEW_OVERRIDE_REQUEST_ERROR="Earráid agus iarratas Ajax á dhéanamh."
COM_LANGUAGES_VIEW_OVERRIDE_RESULTS_LEGEND="Torthaí Cuardaigh"
COM_LANGUAGES_VIEW_OVERRIDE_SAVE_SUCCESS="Sábháladh Forluí Teanga."
COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_BUTTON="Cuardaigh"
COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_LEGEND="Cuardaigh téacs ar mhaith leat a athrú."
COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_TIP="Tá sreang teanga comhdhéanta de dhá chuid: tairiseach teanga ar leith agus a luach.<br>Mar shampla, sa sreang: COM_CONTENT_READ_MORE=&quot;Léigh níos mó: &quot;<br>'<u>COM_CONTENT_READ_MORE</u>' is é an tairiseach agus '<u>Léigh níos mó: </u>' is é an luach.<br>Caithfidh tú an tairiseach teanga ar leith a úsáid chun forluí ar an luach a chruthú.<br>Mar sin, is féidir leat cuardach a dhéanamh ar an tairiseach nó ar an luach ar mhaith leat a athrú leis an réimse cuardaigh thíos.<br>Trí an toradh inmhianaithe a roghnú cuirfear an tairiseach ceart isteach go huathoibríoch sa bhfoirm."
COM_LANGUAGES_VIEW_OVERRIDES_FILTER_SEARCH_DESC="Cuardaigh tairiseach nó téacs."
COM_LANGUAGES_VIEW_OVERRIDES_KEY="Tairiseach"
COM_LANGUAGES_VIEW_OVERRIDES_KEY_ASC="Tairiseach ag ardú"
COM_LANGUAGES_VIEW_OVERRIDES_KEY_DESC="Tairiseach ag ísliú"
COM_LANGUAGES_VIEW_OVERRIDES_LANGUAGES_BOX_ITEM="%1$s - %2$s"
COM_LANGUAGES_VIEW_OVERRIDES_N_ITEMS_DELETED="Scriosadh %d forluí teanga."
COM_LANGUAGES_VIEW_OVERRIDES_N_ITEMS_DELETED_1="Scriosadh forluí teanga."
COM_LANGUAGES_VIEW_OVERRIDES_NO_ITEM_SELECTED="Níl aon fhorluí roghnaithe agat."
COM_LANGUAGES_VIEW_OVERRIDES_PURGE="Glan Taisce"
COM_LANGUAGES_VIEW_OVERRIDES_PURGE_SUCCESS="Glanadh tábla taisce forluí."
COM_LANGUAGES_VIEW_OVERRIDES_TEXT="Téacs"
COM_LANGUAGES_VIEW_OVERRIDES_TEXT_ASC="Téacs ag ardú"
COM_LANGUAGES_VIEW_OVERRIDES_TEXT_DESC="Téacs ag ísliú"
COM_LANGUAGES_VIEW_OVERRIDES_TITLE="Teangacha: Forluíthe"
COM_LANGUAGES_XML_DESCRIPTION="Comhpháirt do bhainistíocht teanga"
JLIB_RULES_SETTING_NOTES_COM_LANGUAGES="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreacht</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann sé i gcónaí - is cuma cad atá socraithe ag an leibhéal Domhanda nó níos airde agus cuirtear i bhfeidhm ar gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé ar chumas an ghnímh don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda." ; Alternate language strings for the rules form field
