; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MEDIA="Meáin"
COM_MEDIA_ACTIONS_TOOLBAR_LABEL="Mír: %s"
COM_MEDIA_ACTION_DELETE="Scrios"
COM_MEDIA_ACTION_DOWNLOAD="Íoslódáil"
COM_MEDIA_ACTION_EDIT="Eagar"
COM_MEDIA_ACTION_PREVIEW="Réamhamharc"
COM_MEDIA_ACTION_RENAME="Athainmnigh"
COM_MEDIA_ACTION_SHARE="Faigh Nasc"
COM_MEDIA_BREADCRUMB_LABEL="Blúire aráin"
COM_MEDIA_BROWSER_TABLE_CAPTION="Ábhar an Eolaire %s"
COM_MEDIA_CHANGE_ORDERING="Athraigh Ordú"
COM_MEDIA_CONFIGURATION="Meáin: Roghanna"
COM_MEDIA_CONFIRM_DELETE_MODAL="Scrios"
COM_MEDIA_CONFIRM_DELETE_MODAL_HEADING="Deimhnigh Scriosadh"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE_FILE_ALREADY_EXISTS="Ní féidir comhad a chóipeáil mar go bhfuil comhad ceann scríbe ann cheana"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE="Ní féidir comhad a chóipeáil"
COM_MEDIA_COPY_FOLDER_ALREADY_EXISTS="Ní féidir fillteán a chóipeáil mar go bhfuil fillteán ceann scríbe ann cheana"
COM_MEDIA_COPY_FOLDER_DESTINATION_CAN_NOT_DELETE="Ní féidir fillteán a chóipeáil mar go bhfuil fillteán ceann scríbe ina chomhad agus ní féidir é a scriosadh"
COM_MEDIA_COPY_FOLDER_NOT_POSSIBLE="Ní féidir fillteán a chóipeáil"
COM_MEDIA_CREATE_NEW_FOLDER="Cruthaigh Fillteán Nua"
COM_MEDIA_CREATE_NEW_FOLDER_ERROR="Earráid ag cruthú fillteáin."
COM_MEDIA_CREATE_NEW_FOLDER_EXISTING_FOLDER_ERROR="Tá ainm fillteáin nó comhaid ann cheana."
COM_MEDIA_CREATE_NEW_FOLDER_RELATIVE_PATH_ERROR="Níl cead ag cosáin choibhneasta."
COM_MEDIA_CREATE_NEW_FOLDER_SUCCESS="Cruthaíodh fillteán."
COM_MEDIA_CREATE_NEW_FOLDER_UNEXPECTED_CHARACTER="Ainm fillteáin neamhbhailí. Roghnaigh ainm fillteáin le a-z, A-Z, 0-9, ., - agus _ le do thoil."
COM_MEDIA_DECREASE_GRID="Laghdú ar mhéid na greille"
COM_MEDIA_DELETE_ERROR="Earráid ag scriosadh na míre."
COM_MEDIA_DELETE_NOT_POSSIBLE="Ní féidir scriosadh!"
COM_MEDIA_DELETE_SUCCESS="Scriosadh mír."
COM_MEDIA_DROP_FILE="Scaoil comhad(aí) le hUaslódáil"
COM_MEDIA_EDIT="Eagar Meáin"
COM_MEDIA_ERROR="Tharla earráid."
COM_MEDIA_ERROR_ACCOUNT_NOT_FOUND="Ní bhfuarthas an cuntas"
COM_MEDIA_ERROR_ACCOUNT_NOT_SET="Níor socraíodh an cuntas."
COM_MEDIA_ERROR_MAKESAFE="Níorbh fhéidir an t-ainm comhaid a dhéanamh sábháilte. Má tá carachtair neamh-ASCII ann, cinntigh go bhfuil na Síntí PHP INTL agus ICONV suiteáilte agat."
COM_MEDIA_ERROR_MEDIA_PROVIDER_NOT_FOUND="Ní bhfuarthas Soláthraí Meán."
COM_MEDIA_ERROR_MISSING_DIR="Níl ceann amháin nó níos mó de na heolairí sainithe sa bhreiseán Córas Comhad - Áitiúil ann."
COM_MEDIA_ERROR_NOT_AUTHENTICATED="Níl tú fíordheimhnithe. Logáil isteach le do thoil."
COM_MEDIA_ERROR_NOT_AUTHORIZED="Níl tú údaraithe"
COM_MEDIA_ERROR_NOT_FOUND="Ní bhfuarthas Comhad nó Fillteán"
COM_MEDIA_ERROR_NO_ADAPTER_FOUND="Ní bhfuarthas aon oiriúnóir."
COM_MEDIA_ERROR_NO_CONTENT_AVAILABLE="Níl aon ábhar ar fáil!"
COM_MEDIA_ERROR_NO_PROVIDERS="Ní bhfuarthas aon sholáthraithe córas comhad. Cumasaigh ar a laghad ceann amháin <a href=\"%s\">breiseán córas comhad</a> le do thoil."
COM_MEDIA_ERROR_WARNFILETOOLARGE="Tá an comhad seo ró-mhór le híoslódáil. Is féidir leat na teorainneacha do do shuíomh a athrú sa chomhpháirt Meáin %s."
COM_MEDIA_FIELDSET_OPTIONS_LABEL="Meáin"
COM_MEDIA_FIELD_CHECK_MIME_DESC="Úsáid MIME Magic nó Fileinfo chun iarracht a dhéanamh comhaid a fhíorú. Bain triail as seo a dhíchumasú má fhaigheann tú earráidí cineál mime neamhbhailí."
COM_MEDIA_FIELD_CHECK_MIME_LABEL="Seiceáil Cineálacha MIME"
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_DESC="Síneadh comhaid neamhairdte le haghaidh seiceáil cineál MIME agus uaslódálacha srianta."
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_LABEL="Síneadh Neamhairdte"
COM_MEDIA_FIELD_LEGAL_AUDIO_EXTENSIONS_DESC="Síneadh fuaime (cineálacha comhaid) atá ceadaithe agat a uaslódáil (scartha le camóg). Úsáidtear iad seo chun ceannteidil fuaime bailí a sheiceáil."
COM_MEDIA_FIELD_LEGAL_AUDIO_EXTENSIONS_LABEL="Síneadh Fuaime Dlíthiúil (Cineálacha Comhaid)"
COM_MEDIA_FIELD_LEGAL_DOCUMENT_EXTENSIONS_DESC="Síneadh doiciméad (cineálacha comhaid) atá ceadaithe agat a uaslódáil (scartha le camóg). Úsáidtear iad seo chun ceannteidil doiciméad bailí a sheiceáil."
COM_MEDIA_FIELD_LEGAL_DOCUMENT_EXTENSIONS_LABEL="Síneadh Doiciméad Dlíthiúil (Cineálacha Comhaid)"
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_DESC="Síneadh íomhá (cineálacha comhaid) atá ceadaithe agat a uaslódáil (scartha le camóg). Úsáidtear iad seo chun ceannteidil íomhá bailí a sheiceáil."
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_LABEL="Síneadh Íomhá Dlíthiúil (Cineálacha Comhaid)"
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_DESC="Liosta MIME cineálacha dlíthiúla le huaslódáil, scartha le camóg."
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_LABEL="Cineálacha MIME Dlíthiúla"
COM_MEDIA_FIELD_LEGAL_VIDEO_EXTENSIONS_DESC="Síneadh físeán (cineálacha comhaid) atá ceadaithe agat a uaslódáil (scartha le camóg). Úsáidtear iad seo chun ceannteidil físeán bailí a sheiceáil."
COM_MEDIA_FIELD_LEGAL_VIDEO_EXTENSIONS_LABEL="Síneadh Físeán Dlíthiúil (Cineálacha Comhaid)"
COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Úsáid nialas le haghaidh gan teorainn. Nóta: tá teorainn uasta ag do fhreastalaí."
COM_MEDIA_FIELD_MAXIMUM_SIZE_LABEL="Méid Uasta (i MB)"
COM_MEDIA_FIELD_PATH_FILE_FOLDER_DESC="Cuir isteach an cosán chuig an bhfillteán comhaid i gcoibhneas le fréamh do spás gréasáin. Rabhadh! D’fhéadfadh athrú go cosán eile seachas an réamhshocrú 'íomhánna' do naisc a bhriseadh. Nóta: Ná tosaigh an cosán le slais!"
COM_MEDIA_FIELD_PATH_FILE_FOLDER_LABEL="Cosán chuig Fillteán Comhaid"
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_DESC="Cuir isteach an cosán chuig an bhfillteán íomhánna i gcoibhneas le fréamh do spás gréasáin. Caithfidh an cosán seo <strong> a bheith mar an gcéanna le cosán chuig comhaid (réamhshocrú) nó chuig fo-fhillteán den chosán chuig fillteán comhaid.</strong> Nóta: Ná tosaigh an cosán le slais!"
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_LABEL="Cosán chuig Fillteán Íomhánna"
COM_MEDIA_FIELD_RESTRICT_UPLOADS_DESC="Srian a chur ar uaslódálacha do úsáideoirí níos ísle ná bainisteoir chuig íomhánna mura bhfuil Fileinfo nó MIME Magic suiteáilte."
COM_MEDIA_FIELD_RESTRICT_UPLOADS_EXTENSIONS_DESC="Srian a chur ar uaslódálacha do úsáideoirí níos ísle ná bainisteoir chuig comhaid sa liosta."
COM_MEDIA_FIELD_RESTRICT_UPLOADS_EXTENSIONS_LABEL="Síneadh Ceadaithe"
COM_MEDIA_FIELD_RESTRICT_UPLOADS_LABEL="Srian a Chur ar Uaslódálacha"
COM_MEDIA_FILE="Comhad"
COM_MEDIA_FILE_EXISTS_AND_OVERRIDE="%s ann cheana. An bhfuil tú ag iarraidh é a athsholáthar?"
COM_MEDIA_FOLDER="Fillteán"
COM_MEDIA_FOLDERS="Fillteáin Meán"
COM_MEDIA_FOLDER_NAME="Ainm Fillteáin"
COM_MEDIA_INCREASE_GRID="Méadaigh méid na greille"
COM_MEDIA_MANAGE_ITEM="Bainistigh mír: %s"
COM_MEDIA_MEDIA_DATE_CREATED="Dáta Cruthaithe"
COM_MEDIA_MEDIA_DATE_MODIFIED="Dáta Modhnaithe"
COM_MEDIA_MEDIA_DIMENSION="Toisí"
COM_MEDIA_MEDIA_EXTENSION="Síneadh"
COM_MEDIA_MEDIA_MIME_TYPE="Cineál MIME"
COM_MEDIA_MEDIA_NAME="Ainm"
COM_MEDIA_MEDIA_SIZE="Méid"
COM_MEDIA_MEDIA_TYPE="Cineál"
COM_MEDIA_MOVE_FILE_ALREADY_EXISTS="Ní féidir comhad a bhogadh mar go bhfuil comhad ceann scríbe ann cheana"
COM_MEDIA_MOVE_FILE_EXTENSION_INVALID="Ní féidir comhad a bhogadh mar go bhfuil an síneadh neamhbhailí"
COM_MEDIA_MOVE_FILE_NOT_POSSIBLE="Ní féidir comhad a bhogadh"
COM_MEDIA_MOVE_FOLDER_ALREADY_EXISTS="Ní féidir fillteán a bhogadh mar go bhfuil fillteán ceann scríbe ann cheana"
COM_MEDIA_MOVE_FOLDER_EXISTING_DESTINATION_FAILED="Theip ar bhogadh fillteán chuig ceann scríbe atá ann cheana"
COM_MEDIA_MOVE_FOLDER_NOT_POSSIBLE="Ní féidir fillteán a bhogadh mar go bhfuil an fillteán ceann scríbe ina chomhad agus ní féidir é a scriosadh"
COM_MEDIA_NAME="Ainm"
COM_MEDIA_ORDER_ASC="Ordú ag Méadú"
COM_MEDIA_ORDER_BY="Ordú De réir"
COM_MEDIA_ORDER_DESC="Ordú ag Laghdu"
COM_MEDIA_ORDER_DIRECTION="Treoir Ordaithe"
COM_MEDIA_PLEASE_SELECT_ITEM="Roghnaigh mír le do thoil."
COM_MEDIA_RENAME="Athainmnigh"
COM_MEDIA_RENAME_ERROR="Earráid ag athainmniú mír."
COM_MEDIA_RENAME_SUCCESS="Mír athainmnithe."
COM_MEDIA_RESET="Athshocraigh"
COM_MEDIA_SEARCH="Cuardaigh"
COM_MEDIA_SELECT_ALL="Cas ar roghnú gach rud"
COM_MEDIA_SERVER_ERROR="Earráid inmheánach freastalaí"
COM_MEDIA_SHARE="Roinn an comhad"
COM_MEDIA_SHARE_COPY="Cóipeáil chuig an gearrthaisce"
COM_MEDIA_SHARE_COPY_FAILED_ERROR="Earráid ag cóipeáil chuig an gearrthaisce"
COM_MEDIA_SHARE_DESC="Is féidir le duine ar bith leis an nasc an comhad a fheiceáil."
COM_MEDIA_TOGGLE_INFO="Cas ar eolas mír"
COM_MEDIA_TOGGLE_LIST_VIEW="Cas idir radhairc greille agus tábla"
COM_MEDIA_TOGGLE_SELECT_ITEM="Cas ar roghnú mír"
COM_MEDIA_TOOLBAR_LABEL="Bainisteoir Meán"
COM_MEDIA_UPLOAD_SUCCESS="Mír uaslódáilte."
