; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_POSTINSTALL="Teachtaireachtaí Iar-shuiteála"
COM_POSTINSTALL_BTN_ARCHIVE="Cartlann"
COM_POSTINSTALL_BTN_HIDE="Folaigh an teachtaireacht seo"
COM_POSTINSTALL_BTN_REPUBLISH="Léigh Arís"
COM_POSTINSTALL_CONFIGURATION="Teachtaireachtaí Iar-shuiteála: Roghanna"
COM_POSTINSTALL_EMPTYSTATE_BUTTON_ADD="Athshocraigh Teachtaireachtaí"
COM_POSTINSTALL_EMPTYSTATE_CONTENT="Tá na teachtaireachtaí go léir léite agat."
COM_POSTINSTALL_EMPTYSTATE_TITLE="Teachtaireachtaí Iar-shuiteála agus Uasghrádaithe"
COM_POSTINSTALL_HIDE_ALL_MESSAGES="Folaigh na Teachtaireachtaí go léir"
COM_POSTINSTALL_LBL_SINCEVERSION="Ón leagan %s"
COM_POSTINSTALL_MESSAGES_FOR="Ag taispeáint teachtaireachtaí do"
COM_POSTINSTALL_MESSAGES_TITLE="Teachtaireachtaí Iar-shuiteála do %s"
COM_POSTINSTALL_XML_DESCRIPTION="Taispeánann sé teachtaireachtaí iar-shuiteála agus iar-uasghrádaithe do Joomla agus a síntí."
