; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_WORKFLOW_BASIC_STAGE="Céim Bhunúsach"
COM_WORKFLOW_BASIC_WORKFLOW="Sreabhadh Oibre Bunúsach"
COM_WORKFLOW_CHOOSE_CONTEXT_LABEL="Comhthéacs"
COM_WORKFLOW_COUNT_STAGES="Céimeanna"
COM_WORKFLOW_COUNT_TRANSITIONS="Aistrithe"
COM_WORKFLOW_CREATED_LABEL="Dáta Cruthaithe"
COM_WORKFLOW_DEFAULT="Réamhshocrú"
COM_WORKFLOW_DESCRIPTION="Cur Síos"
COM_WORKFLOW_DISABLE_DEFAULT="Ní féidir an stádas réamhshocraithe a athrú."
COM_WORKFLOW_ERROR_EXTENSION_NOT_SET="Síneadh gan socrú."
COM_WORKFLOW_ERROR_WORKFLOW_ID_NOT_SET="Aitheantas Sreabhadh Oibre gan socrú."
COM_WORKFLOW_FIELD_IS_DEFAULT_LABEL="Réamhshocrú"
COM_WORKFLOW_FIELD_NAME_LABEL="Ainm"
COM_WORKFLOW_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus i gcur síos."
COM_WORKFLOW_FILTER_SEARCH_LABEL="Cuardaigh"
COM_WORKFLOW_FORM_EDIT="Cuir Sreabhadh Oibre in Eagar"
COM_WORKFLOW_FORM_NEW="Sreabhadh Oibre Nua"
COM_WORKFLOW_FROM_STAGE="Céim Reatha"
COM_WORKFLOW_FROM_STAGE_FILTER_ASC="Céim Reatha ag ardú"
COM_WORKFLOW_FROM_STAGE_FILTER_DESC="Céim Reatha ag ísliú"
COM_WORKFLOW_ID="Aitheantas"
COM_WORKFLOW_INHERIT_WORKFLOW="Oidhreacht (%s)"
COM_WORKFLOW_INHERIT_WORKFLOW_NEW="Oidhreacht"
COM_WORKFLOW_ITEM_MUST_PUBLISHED="Ní mór an mhír a fhoilsiú chun an chéim réamhshocraithe a shocrú."
COM_WORKFLOW_ITEM_UNSET_DEFAULT="Céim réamhshocraithe díshuite."
COM_WORKFLOW_MODIFIED_LABEL="Dáta Modhnaithe"
COM_WORKFLOW_MSG_DELETE_IS_DEFAULT="Ní féidir leat an mhír réamhshocraithe a scriosadh."
COM_WORKFLOW_MSG_DELETE_STAGE_IS_ASSIGNED="Tá an chéim seo sannaithe do mhír den chomhpháirt seo agus caithfidh sí fanacht i staid fhoilsithe."
COM_WORKFLOW_MSG_DELETE_WORKFLOW_IS_ASSIGNED="Tá an sreabhadh oibre seo in úsáid ag an gcomhpháirt."
COM_WORKFLOW_MSG_DISABLE_DEFAULT="Caithfidh an mhír réamhshocraithe fanacht foilsithe."
COM_WORKFLOW_MSG_WORKFLOWS_DELETE_ERROR="Bhí fadhb ann agus an mhír á scriosadh: %s"
COM_WORKFLOW_NAME="Ainm"
COM_WORKFLOW_NO_ITEM_SELECTED="Níor roghnaíodh aon sreabhadh oibre."
COM_WORKFLOW_N_ITEMS_CHECKED_IN="%d sreabhadh oibre seiceáilte isteach."
COM_WORKFLOW_N_ITEMS_CHECKED_IN_1="Sreabhadh oibre seiceáilte isteach."
COM_WORKFLOW_N_ITEMS_DELETED="%d sreabhadh oibre scriosta."
COM_WORKFLOW_N_ITEMS_DELETED_1="Sreabhadh oibre scriosta."
COM_WORKFLOW_N_ITEMS_PUBLISHED="%d sreabhadh oibre cumasaithe."
COM_WORKFLOW_N_ITEMS_PUBLISHED_1="Sreabhadh oibre cumasaithe."
COM_WORKFLOW_N_ITEMS_TRASHED="%d sreabhadh oibre bruscair."
COM_WORKFLOW_N_ITEMS_TRASHED_1="Sreabhadh oibre bruscair."
COM_WORKFLOW_N_ITEMS_UNPUBLISHED="%d sreabhadh oibre díchumasaithe."
COM_WORKFLOW_N_ITEMS_UNPUBLISHED_1="Sreabhadh oibre díchumasaithe."
COM_WORKFLOW_PUBLISHED_LABEL="Stádas"
COM_WORKFLOW_RULES_TAB="Ceadanna"
COM_WORKFLOW_SELECT_FROM_STAGE="- Roghnaigh Céim Reatha -"
COM_WORKFLOW_SELECT_TO_STAGE="- Roghnaigh Céim Sprioc -"
COM_WORKFLOW_SET_DEFAULT="Sreabhadh oibre socraithe mar réamhshocrú."
COM_WORKFLOW_STAGES="Céimeanna"
COM_WORKFLOW_STAGES_LIST="Céimeanna: %s"
COM_WORKFLOW_STAGES_N_ITEMS_CHECKED_IN="%d céimeanna seiceáilte isteach."
COM_WORKFLOW_STAGES_N_ITEMS_CHECKED_IN_1="Céim seiceáilte isteach."
COM_WORKFLOW_STAGES_N_ITEMS_DELETED="%d céimeanna scriosta."
COM_WORKFLOW_STAGES_N_ITEMS_DELETED_1="Céim scriosta."
COM_WORKFLOW_STAGES_N_ITEMS_PUBLISHED="%d céimeanna cumasaithe."
COM_WORKFLOW_STAGES_N_ITEMS_PUBLISHED_1="Céim cumasaithe."
COM_WORKFLOW_STAGES_N_ITEMS_TRASHED="%d céimeanna bruscair."
COM_WORKFLOW_STAGES_N_ITEMS_TRASHED_1="Céim bruscair."
COM_WORKFLOW_STAGES_N_ITEMS_UNPUBLISHED="%d céimeanna díchumasaithe."
COM_WORKFLOW_STAGES_N_ITEMS_UNPUBLISHED_1="Céim díchumasaithe."
COM_WORKFLOW_STAGES_TABLE_CAPTION="Céimeanna Sreabhadh Oibre"
COM_WORKFLOW_STAGE_ADD="Cuir Céim leis"
COM_WORKFLOW_STAGE_EDIT="Cuir Céim in Eagar"
COM_WORKFLOW_STAGE_FORM_EDIT="Cuir Céim in Eagar"
COM_WORKFLOW_STAGE_FORM_NEW="Cuir Céim leis"
COM_WORKFLOW_STAGE_NOTE="Nóta"
COM_WORKFLOW_STAGE_SET_DEFAULT="Staid socraithe mar réamhshocrú."
COM_WORKFLOW_TITLE_TRANSLATION="Ainm (%s)"
COM_WORKFLOW_TOOLBAR_DEFAULT="Réamhshocrú"
COM_WORKFLOW_TOO_MANY_STAGES="Ní féidir ach staid amháin a shocrú mar réamhshocrú."
COM_WORKFLOW_TOO_MANY_WORKFLOWS="Ní féidir ach sreabhadh oibre amháin a shocrú mar réamhshocrú."
COM_WORKFLOW_TO_STAGE="Staid Sprioc"
COM_WORKFLOW_TO_STAGE_FILTER_ASC="Staid Sprioc ag ardú"
COM_WORKFLOW_TO_STAGE_FILTER_DESC="Staid Sprioc ag ísliú"
COM_WORKFLOW_TRANSITION="Aistriú"
COM_WORKFLOW_TRANSITIONS="Aistrithe"
COM_WORKFLOW_TRANSITIONS_LIST="Aistrithe: %s"
COM_WORKFLOW_TRANSITIONS_N_ITEMS_CHECKED_IN="%d aistrithe seiceáilte isteach."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_CHECKED_IN_1="Aistriú seiceáilte isteach."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_DELETED="%d aistrithe scriosta."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_DELETED_1="Aistriú scriosta."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_PUBLISHED="%d aistrithe cumasaithe."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_PUBLISHED_1="Aistriú cumasaithe."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_TRASHED="%d aistrithe bruscair."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_TRASHED_1="Aistriú bruscair."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_UNPUBLISHED="%d aistrithe díchumasaithe."
COM_WORKFLOW_TRANSITIONS_N_ITEMS_UNPUBLISHED_1="Aistriú díchumasaithe."
COM_WORKFLOW_TRANSITIONS_TABLE_CAPTION="Aistrithe Sreabhadh Oibre"
COM_WORKFLOW_TRANSITION_ACTIONS_LABEL="Gníomhartha Aistrithe"
COM_WORKFLOW_TRANSITION_ADD="Cuir Aistriú Leis"
COM_WORKFLOW_TRANSITION_EDIT="Cuir Aistriú in Eagar"
COM_WORKFLOW_TRANSITION_FORM_EDIT="Cuir Aistriú in Eagar"
COM_WORKFLOW_TRANSITION_FORM_NEW="Aistriú Nua"
COM_WORKFLOW_TRANSITION_NOTE="Nóta"
COM_WORKFLOW_UNPUBLISH_DEFAULT_ERROR="Ní féidir an sreabhadh oibre réamhshocraithe a dhíchumasú."
COM_WORKFLOW_USE_DEFAULT_WORKFLOW="Úsáid réamhshocrú (%s)"
COM_WORKFLOW_WORKFLOWS_ADD="Cuir Sreabhadh Oibre Leis"
COM_WORKFLOW_WORKFLOWS_EDIT="Cuir Sreabhadh Oibre in Eagar"
COM_WORKFLOW_WORKFLOWS_LIST="Sreabha Oibre"
COM_WORKFLOW_WORKFLOWS_TABLE_CAPTION="Sreabha Oibre"
COM_WORKFLOW_WORKFLOW_NOTE="Nóta"
JLIB_HTML_PUBLISH_ITEM="Cumasú"
JLIB_HTML_UNPUBLISH_ITEM="Díchumasú"
