; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MENUS="Biachláir"
COM_MENUS_ITEM_VIEW_EDIT_DESC="Taispeánann foirm chun mír nua biachláir a chruthú"
COM_MENUS_ITEM_VIEW_EDIT_TITLE="Mír Nua Biachláir"
COM_MENUS_ITEMS_CHOOSE_MENU_DESC="Roghnaigh Cineál Biachláir don leathanach sprice.<br><br>Ná mearbhall é leis an <strong>Biachlár</strong> faoina mbeidh an mhír biachláir seo sannaithe."
COM_MENUS_ITEMS_CHOOSE_MENU_LABEL="Roghnaigh Cineál Biachláir"
COM_MENUS_ITEMS_VIEW_DEFAULT_DESC="Taispeánann liosta de mhíreanna biachláir"
COM_MENUS_ITEMS_VIEW_DEFAULT_TITLE="Míreanna Biachláir"
COM_MENUS_MENU_VIEW_EDIT_DESC="Taispeánann foirm chun biachlár nua a chruthú"
COM_MENUS_MENU_VIEW_EDIT_TITLE="Biachlár Nua"
COM_MENUS_MENUS_PRESET_ALTERNATE="Réamhshocrú - Príomh-Biachlár Malartach"
COM_MENUS_MENUS_PRESET_COMPONENTS="Réamhshocrú - Painéal Comhpháirteanna"
COM_MENUS_MENUS_PRESET_DEFAULT="Réamhshocrú - Príomh-Biachlár Joomla"
COM_MENUS_MENUS_PRESET_HELP="Réamhshocrú - Painéal Cabhrach"
COM_MENUS_MENUS_PRESET_MENUS="Réamhshocrú - Painéal Biachláir"
COM_MENUS_MENUS_PRESET_SYSTEM="Réamhshocrú - Painéal Córas"
COM_MENUS_MENUS_VIEW_DEFAULT_DESC="Taispeánann liosta de Chineálacha Biachláir"
COM_MENUS_MENUS_VIEW_DEFAULT_TITLE="Biachláir"
COM_MENUS_XML_DESCRIPTION="Comhpháirt chun biachláir a chruthú."
