; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_TAGS="Clibeanna"
COM_TAGS_ALL="Uile"
COM_TAGS_ALL_TAGS_DESCRIPTION_LABEL="Cur Síos ar an gCeannteideal"
COM_TAGS_ALL_TAGS_MEDIA_LABEL="Comhad Íomhá Ceannteidil"
COM_TAGS_ANY="Aon"
COM_TAGS_BASIC_FIELDSET_LABEL="Roghanna"
COM_TAGS_BATCH_OPTIONS="Próiseáil bhaisc na gclibeanna roghnaithe"
COM_TAGS_COMPACT_COLUMNS_LABEL="Líon na gColún"
COM_TAGS_CONFIG_ALL_TAGS_FIELD_LAYOUT_LABEL="Leagan Amach Réamhshocraithe Liosta na gClibeanna Uile"
COM_TAGS_CONFIG_ALL_TAGS_SETTINGS_DESC="Baineann na socruithe seo le Liosta de na Clibeanna Uile mura n-athraítear iad do mhír roghchláir ar leith."
COM_TAGS_CONFIG_ALL_TAGS_SETTINGS_LABEL="Liosta na gClibeanna Uile"
COM_TAGS_CONFIG_DATA_ENTRY_SETTINGS_DESC="Rialaíonn na socruithe seo an bealach a chuirtear clibeanna isteach."
COM_TAGS_CONFIG_DATA_ENTRY_SETTINGS_LABEL="Iontráil Sonraí"
COM_TAGS_CONFIG_INTEGRATION_SETTINGS_DESC="Socraíonn na socruithe seo conas a chomhtháthaíonn an Comhpháirt Clibeanna le síntí eile."
COM_TAGS_CONFIG_NUMBER_OF_ITEMS="Líon na Míreanna Clibeáilte"
COM_TAGS_CONFIG_SELECTION_SETTINGS_DESC="Rialaíonn na socruithe seo cé na míreanna a roghnaítear i leagan amach liosta na Míreanna Clibeáilte."
COM_TAGS_CONFIG_SELECTION_SETTINGS_LABEL="Roghnú Míre"
COM_TAGS_CONFIG_SHARED_SETTINGS_DESC="Baineann na socruithe seo le gach leagan amach clibeanna mura n-athraítear iad do mhír roghchláir ar leith."
COM_TAGS_CONFIG_SHARED_SETTINGS_LABEL="Leagan Amach Roinnte"
COM_TAGS_CONFIG_TAG_MIN_LENGTH_LABEL="Fad Íosta Cuardaigh"
COM_TAGS_CONFIG_TAG_SETTINGS_DESC="Baineann na socruithe seo le Liosta na Míreanna Clibeáilte nó Liosta Dlúth de na Míreanna Clibeáilte mura n-athraítear iad do mhír roghchláir ar leith."
COM_TAGS_CONFIG_TAG_SETTINGS_LABEL="Míreanna Clibeáilte"
COM_TAGS_CONFIG_TAGGED_ITEMS_FIELD_LAYOUT_LABEL="Leagan Amach Réamhshocraithe na Míreanna Clibeáilte"
COM_TAGS_CONFIGURATION="Clibeanna: Roghanna"
COM_TAGS_COUNT_ARCHIVED_ITEMS="Míreanna cartlainne"
COM_TAGS_COUNT_PUBLISHED_ITEMS="Míreanna foilsithe"
COM_TAGS_COUNT_TAGGED_ITEMS="Míreanna Clibeáilte"
COM_TAGS_COUNT_TAGGED_ITEMS_ASC="Míreanna Clibeáilte ag ardú"
COM_TAGS_COUNT_TAGGED_ITEMS_DESC="Míreanna Clibeáilte ag ísliú"
COM_TAGS_COUNT_TRASHED_ITEMS="Míreanna bruscair"
COM_TAGS_COUNT_UNPUBLISHED_ITEMS="Míreanna neamhfhoilsithe"
COM_TAGS_EMPTYSTATE_BUTTON_ADD="Cuir do chéad chlib leis"
COM_TAGS_EMPTYSTATE_CONTENT="Soláthraíonn clibeanna i Joomla! bealach solúbtha chun ábhar a eagrú. Is féidir an chlib chéanna a chur i bhfeidhm ar go leor míreanna ábhair éagsúla ar fud cineálacha ábhair."
COM_TAGS_EMPTYSTATE_TITLE="Níor cruthaíodh aon Chlibeanna go fóill."
COM_TAGS_ERROR_UNIQUE_ALIAS="Tá an t-ailias céanna ag Clib eile (cuimhnigh gur féidir gur mír bhruscair í)."
COM_TAGS_ERROR_UNIQUE_ALIAS_TRASHED="Tá an t-ailias céanna ag Clib bhruscair leis an gclib thuismitheora céanna."
COM_TAGS_EXCLUDE="Eisiamh"
COM_TAGS_FIELD_CONTENT_TYPE_LABEL="Cineálacha ábhair"
COM_TAGS_FIELD_FULL_LABEL="Íomhá Iomlán"
COM_TAGS_FIELD_IMAGE_ALT_LABEL="Téacs Malartach"
COM_TAGS_FIELD_IMAGE_CAPTION_LABEL="Fotheideal"
COM_TAGS_FIELD_IMAGE_LABEL="Íomhá"
COM_TAGS_FIELD_INTRO_LABEL="Íomhá Réamhrá"
COM_TAGS_FIELD_LANGUAGE_FILTER_LABEL="Scagaire Teanga"
COM_TAGS_FIELD_NOTE_LABEL="Nóta"
COM_TAGS_FIELD_NUMBER_ITEMS_LIST_LABEL="# Míreanna le Liostáil"
COM_TAGS_FIELD_PARENT_LABEL="Tuismitheoir"
COM_TAGS_FIELD_PARENT_TAG_LABEL="Clib Thuismitheora"
COM_TAGS_FIELD_TAG_BODY_LABEL="Cur Síos."
COM_TAGS_FIELD_TAG_LABEL="Clib"
COM_TAGS_FIELD_TAG_LINK_CLASS="Rang CSS don nasc clibe"
COM_TAGS_FIELD_TYPE_LABEL="Roghnaigh Cineál Ábhair"
COM_TAGS_FIELD_VERSION_LABEL="Leagan"
COM_TAGS_FIELDSET_DETAILS="Sonraí Clibe"
COM_TAGS_FIELDSET_OPTIONS="Roghanna"
COM_TAGS_FIELDSET_PUBLISHING="Foilsitheoireacht"
COM_TAGS_FIELDSET_TAGGED_ITEMS="Míreanna Clibeáilte"
COM_TAGS_FIELDSET_URLS_AND_IMAGES="Naisc agus Íomhánna"
COM_TAGS_FILTER_SEARCH_DESC="Cuardaigh i dteideal, ailias agus nóta an chlib. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID clibe."
COM_TAGS_FILTER_SEARCH_LABEL="Cuardaigh Clibeanna"
COM_TAGS_FLOAT_LABEL="Snámh"
COM_TAGS_FORM_TITLE_EDIT="Eagar Clibe"
COM_TAGS_FORM_TITLE_NEW="Clib Nua"
COM_TAGS_HAS_SUBCATEGORY_ITEMS="%d míreanna sannta do fho-chlibeanna an chlib seo."
COM_TAGS_HAS_SUBCATEGORY_ITEMS_1="Tá mír sannta do cheann de fho-chlibeanna an chlib seo."
COM_TAGS_HEADING_TAGTYPE="Cineál Clibe"
COM_TAGS_INCLUDE="Cuir san áireamh"
COM_TAGS_INCLUDE_CHILDREN_LABEL="Fochlibeanna"
COM_TAGS_ITEM_OPTIONS="Roghanna Míre"
COM_TAGS_ITEMS_SEARCH_FILTER="Cuardaigh"
COM_TAGS_LEFT="Clé"
COM_TAGS_LIST_ALL_SELECTION_OPTIONS="Roghanna Roghnúcháin"
COM_TAGS_LIST_MAX_CHARACTERS_LABEL="Uasmhéid Carachtair"
COM_TAGS_LIST_MAX_LABEL="Uasmhéid Míreanna"
COM_TAGS_LIST_SELECTION_OPTIONS="Roghanna Roghnúcháin Míre"
COM_TAGS_MANAGER_TAG_EDIT="Clibeanna: Eagar"
COM_TAGS_MANAGER_TAG_NEW="Clibeanna: Nua"
COM_TAGS_MANAGER_TAGS="Clibeanna"
COM_TAGS_MATCH_COUNT="Líon na gclibeanna a mheaitseálann"
COM_TAGS_N_ITEMS_ARCHIVED="%d clibeanna cartlainne."
COM_TAGS_N_ITEMS_ARCHIVED_1="Clib cartlainne."
COM_TAGS_N_ITEMS_CHECKED_IN_1="Clib seiceáilte isteach."
COM_TAGS_N_ITEMS_CHECKED_IN_MORE="%d clibeanna seiceáilte isteach."
COM_TAGS_N_ITEMS_DELETED="%d clibeanna scriosta."
COM_TAGS_N_ITEMS_DELETED_1="Clib scriosta."
COM_TAGS_N_ITEMS_FAILED_PUBLISHING="Theip ar fhoilsiú %d clibeanna mar tá ar a laghad ceann dá dtuismitheoirí neamhfhoilsithe nó tá ceann dá leanaí seiceáilte amach."
COM_TAGS_N_ITEMS_FAILED_PUBLISHING_1="Theip ar fhoilsiú an chlib mar tá ar a laghad ceann dá tuismitheoirí neamhfhoilsithe nó tá ceann dá leanaí seiceáilte amach."
COM_TAGS_N_ITEMS_PUBLISHED="%d clibeanna foilsithe."
COM_TAGS_N_ITEMS_PUBLISHED_1="Clib foilsithe."
COM_TAGS_N_ITEMS_TRASHED="%d clibeanna bruscair."
COM_TAGS_N_ITEMS_TRASHED_1="Clib bruscair."
COM_TAGS_N_ITEMS_UNPUBLISHED="%d clibeanna neamhfhoilsithe."
COM_TAGS_N_ITEMS_UNPUBLISHED_1="Clib neamhfhoilsithe."
COM_TAGS_N_QUICKICON="Clibeanna"
COM_TAGS_N_QUICKICON_0="Clibeanna"
COM_TAGS_N_QUICKICON_1="Clib"
COM_TAGS_N_QUICKICON_SRONLY="Clibeanna: %d clibeanna foilsithe."
COM_TAGS_N_QUICKICON_SRONLY_0="Clibeanna: Níl aon chlib foilsithe."
COM_TAGS_N_QUICKICON_SRONLY_1="Clibeanna: Tá clib amháin foilsithe."
COM_TAGS_NONE="Dada"
COM_TAGS_NUMBER_TAG_ITEMS_LABEL="Taispeáin Líon na Míreanna"
COM_TAGS_OPTIONS="Roghanna Clibe"
COM_TAGS_PAGINATION_OPTIONS="Roghanna Leathanaigh"
COM_TAGS_PARAMS_IMAGE_FULLTEXT="Íomhá Iomlán"
COM_TAGS_PARAMS_IMAGE_INTRO="Íomhá Réamhrá"
COM_TAGS_REBUILD_FAILURE="Theip ar athfhoirgniú sonraí crann Clibeanna."
COM_TAGS_REBUILD_SUCCESS="Sonraí crann Clibeanna athfhoirgthe."
COM_TAGS_RIGHT="Deas"
COM_TAGS_SAVE_SUCCESS="Clib sábháilte."
COM_TAGS_SEARCH_TYPE_LABEL="Cineál Meaitseála"
COM_TAGS_SELECT_TAGTYPE="- Roghnaigh Cineál Clibe -"
COM_TAGS_SHOW_ALL_TAGS_IMAGE_LABEL="Taispeáin Íomhá Ceannlíne"
COM_TAGS_SHOW_ITEM_BODY_LABEL="Comhlacht Míre"
COM_TAGS_SHOW_ITEM_DESCRIPTION_LABEL="Cur Síos ar Chlibeanna"
COM_TAGS_SHOW_ITEM_IMAGE_LABEL="Íomhánna Míre"
COM_TAGS_SHOW_TAG_BODY_LABEL="Taispeáin Cur Síos ar Chlib"
COM_TAGS_SHOW_TAG_DESCRIPTION_LABEL="Cur Síos ar Chlib"
COM_TAGS_SHOW_TAG_IMAGE_LABEL="Íomhá Clibe"
COM_TAGS_SHOW_TAG_LIST_DESCRIPTION_LABEL="Cur Síos"
COM_TAGS_SHOW_TAG_TITLE_LABEL="Ainm Clibe"
COM_TAGS_SUBSLIDER_DRILL_TAG_LIST_LABEL="Roghanna do gach mír sa liosta."
COM_TAGS_TABLE_CAPTION="Clibeanna"
COM_TAGS_TAG_FIELD_MODE_AJAX="AJAX"
COM_TAGS_TAG_FIELD_MODE_DESC="Lorgaíonn mód Ajax clibeanna agus tú ag clóscríobh agus ligeann sé duit cruthú clibe ar an toirt. Taispeánann clibeanna neadaithe radharc neadaithe duit le gach clib atá ar fáil."
COM_TAGS_TAG_FIELD_MODE_LABEL="Mód Iontrála Clibe"
COM_TAGS_TAG_FIELD_MODE_NESTED="Neadaithe"
COM_TAGS_TAG_LIST_DESCRIPTION_DESC="Cur síos roghnach le taispeáint ag barr an liosta. Mar shampla, is féidir é seo a úsáid nuair atá leagan amach agat a chuimsíonn níos mó ná clib amháin."
COM_TAGS_TAG_LIST_DESCRIPTION_LABEL="Cur Síos ar an Leagan Amach"
COM_TAGS_TAG_LIST_FIELD_ITEM_DESCRIPTION_LABEL="Corp an Míre"
COM_TAGS_TAG_LIST_MEDIA_ALT_EMPTY_DESC="Íomhá Maisiúil - níl cur síos ag teastáil"
COM_TAGS_TAG_LIST_MEDIA_ALT_EMPTY_LABEL="Gan Cur Síos"
COM_TAGS_TAG_LIST_MEDIA_ALT_LABEL="Cur Síos ar Íomhá (Alt Téacs)"
COM_TAGS_TAG_LIST_MEDIA_LABEL="Íomhá"
COM_TAGS_TAG_LIST_SHOW_DATE_LABEL="Dáta"
COM_TAGS_TAG_LIST_SHOW_HEADINGS_LABEL="Ceanntásca Tábla"
COM_TAGS_TAG_LIST_SHOW_ITEM_DESCRIPTION_LABEL="Cur Síos ar an Mír"
COM_TAGS_TAG_LIST_SHOW_ITEM_IMAGE_LABEL="Íomhá na Míre"
COM_TAGS_TAGGED_ITEMS_ACCESS="Rochtain"
COM_TAGS_TAGGED_ITEMS_AUTHOR="Údar"
COM_TAGS_TAGGED_ITEMS_DATE="Dáta"
COM_TAGS_TAGGED_ITEMS_ID="ID"
COM_TAGS_TAGGED_ITEMS_LANGUAGE="Teanga"
COM_TAGS_TAGGED_ITEMS_TITLE="Teideal"
COM_TAGS_XML_DESCRIPTION="Bainistíonn an comhpháirt seo clibeanna."
JGLOBAL_NO_ITEM_SELECTED="Gan clibeanna roghnaithe"
