; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MODULES="Modúil"
COM_MODULES_ACTION_EDITFRONTEND="Eagarthóireacht Tosaigh"
COM_MODULES_GENERAL="Ginearálta"
COM_MODULES_MODULES_VIEW_DEFAULT_DESC="Taispeánann sé liosta de mhodúil le bainistiú"
COM_MODULES_MODULES_VIEW_DEFAULT_TITLE="Bainisteoir Modúil"
COM_MODULES_REDIRECT_EDIT_DESC="Roghnaigh más ceart eagarthóireacht modúil a oscailt ar an suíomh nó ar an gcomhéadan riaracháin."
COM_MODULES_REDIRECT_EDIT_LABEL="Eagar Modúil"
COM_MODULES_XML_DESCRIPTION="Comhpháirt le haghaidh bainistíocht modúil sa Chúlra Riaracháin."
