; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CATEGORIES="Catagóirí"
COM_CATEGORIES_CATEGORIES_VIEW_DEFAULT_DESC="Taispeánann Liosta de Gach catagóir sa chomhpháirt roghnaithe."
COM_CATEGORIES_CATEGORIES_VIEW_DEFAULT_TITLE="Liosta Gach Catagóir"
COM_CATEGORIES_CATEGORY_VIEW_EDIT_DESC="Cruthaigh Catagóir nua sa chomhpháirt roghnaithe."
COM_CATEGORIES_CATEGORY_VIEW_EDIT_TITLE="Cruthaigh Catagóir Nua"
COM_CATEGORIES_CHOOSE_COMPONENT_LABEL="Roghnaigh Comhpháirt"
COM_CATEGORIES_XML_DESCRIPTION="Bainistíonn an comhpháirt seo catagóirí."
