; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_NEWSFEEDS="Beatha Nuachta"
COM_NEWSFEEDS_CATEGORIES="Catagóirí"
COM_NEWSFEEDS_CATEGORIES_VIEW_DEFAULT_DESC="Taispeánann sé liosta de na catagóirí go léir i gcrann catagóir beatha nuachta roghnaithe."
COM_NEWSFEEDS_CATEGORIES_VIEW_DEFAULT_OPTION="Réamhshocrú"
COM_NEWSFEEDS_CATEGORIES_VIEW_DEFAULT_TITLE="Liostaigh Gach Catagóir i gCrann Catagóir Beatha Nuachta"
COM_NEWSFEEDS_CATEGORY_VIEW_DEFAULT_DESC="Taispeáin gach beatha nuachta laistigh de chatagóir."
COM_NEWSFEEDS_CATEGORY_VIEW_DEFAULT_OPTION="Réamhshocrú"
COM_NEWSFEEDS_CATEGORY_VIEW_DEFAULT_TITLE="Liostaigh Beatha Nuachta i gCatagóir"
COM_NEWSFEEDS_CONTENT_TYPE_CATEGORY="Catagóir Beatha Nuachta"
COM_NEWSFEEDS_CONTENT_TYPE_NEWSFEED="Beatha nuachta"
COM_NEWSFEEDS_FEEDS="Beatha"
COM_NEWSFEEDS_NEWSFEED_VIEW_DEFAULT_DESC="Taispeáin beatha nuachta aonair."
COM_NEWSFEEDS_NEWSFEED_VIEW_DEFAULT_OPTION="Réamhshocrú"
COM_NEWSFEEDS_NEWSFEED_VIEW_DEFAULT_TITLE="Beatha Nuachta Aonair"
COM_NEWSFEEDS_TAGS_CATEGORY="Catagóir Beatha Nuachta"
COM_NEWSFEEDS_TAGS_NEWSFEED="Beatha Nuachta"
COM_NEWSFEEDS_XML_DESCRIPTION="Bainistíonn an comhpháirt seo beatha nuachta RSS agus Atom."
