; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MODULES="Modúil"
COM_MODULES_ACTION_EDITFRONTEND="Eagarthóireacht Tosaigh"
COM_MODULES_ADD_CUSTOM_POSITION="Cuir suíomh saincheaptha leis"
COM_MODULES_ADMIN_LANG_FILTER_DESC="Ceadaíonn sé scagadh ar mhodúil riarthóra de réir teanga an riarthóra."
COM_MODULES_ADMIN_LANG_FILTER_FIELDSET_LABEL="Modúil Riarthóra"
COM_MODULES_ADMIN_LANG_FILTER_LABEL="Scagadh Teanga"
COM_MODULES_ADVANCED_FIELDSET_LABEL="Casta"
COM_MODULES_ASSIGNED_VARIES_EXCEPT="Gach ceann seachas na roghnaithe"
COM_MODULES_ASSIGNED_VARIES_ONLY="Roghnaithe"
COM_MODULES_BASIC_FIELDSET_LABEL="Roghanna"
COM_MODULES_BATCH_OPTIONS="Próiseáil bhaisc na modúil roghnaithe"
COM_MODULES_BATCH_POSITION_LABEL="Socraigh Suíomh"
COM_MODULES_BATCH_POSITION_NOCHANGE="Coinnigh an Suíomh Bunaidh"
COM_MODULES_BATCH_POSITION_NOPOSITION="Gan Suíomh Modúil"
COM_MODULES_BATCH_TIP="Má roghnaíonn tú modúl a chóipeáil, cuirfear aon ghníomhartha eile a roghnaítear i bhfeidhm ar an modúl cóipeáilte. Seachas sin, cuirtear gach gníomh i bhfeidhm ar an modúl roghnaithe. Agus tú ag cóipeáil agus gan suíomh a athrú, tá sé riachtanach fós 'Coinnigh an Suíomh Bunaidh' a roghnú sa roghchlár anuas."
COM_MODULES_CHANGE_POSITION_BUTTON="Roghnaigh"
COM_MODULES_CHANGE_POSITION_TITLE="Athraigh"
COM_MODULES_COLLAPSE="Crapadh"
COM_MODULES_CONFIGURATION="Modúl: Roghanna"
COM_MODULES_CUSTOM_OUTPUT="Aschur Saincheaptha"
COM_MODULES_CUSTOM_POSITION="Suímh Ghníomhacha"
COM_MODULES_DESELECT="Díroghnaigh"
COM_MODULES_EMPTYSTATE_BUTTON_ADD="Cuir modúl leis"
COM_MODULES_EMPTYSTATE_CONTENT="Is forlíontáin éadroma agus solúbtha iad modúil a úsáidtear chun leathanach a rindreáil. Úsáid iad chun bloic bheaga feidhmiúlachta a chur le do leathanach."
COM_MODULES_EMPTYSTATE_TITLE_ADMINISTRATOR="Níor cruthaíodh Modúil Riarthóra fós."
COM_MODULES_EMPTYSTATE_TITLE_SITE="Níor cruthaíodh Modúil Suímh fós."
COM_MODULES_ERR_XML="Níl sonraí XML an mhodúil ar fáil"
COM_MODULES_ERROR_CANNOT_FIND_MODULE="Ní féidir modúl a aimsiú"
COM_MODULES_ERROR_INVALID_EXTENSION="Modúl neamhbhailí"
COM_MODULES_ERROR_NO_MODULES_SELECTED="Níl modúl roghnaithe."
COM_MODULES_EXPAND="Leathnaigh"
COM_MODULES_EXTENSION_PUBLISHED_DISABLED="Modúl díchumasaithe agus foilsithe."
COM_MODULES_EXTENSION_PUBLISHED_ENABLED="Modúl cumasaithe agus foilsithe."
COM_MODULES_EXTENSION_UNPUBLISHED_DISABLED="Modúl díchumasaithe agus neamhfhoilsithe."
COM_MODULES_EXTENSION_UNPUBLISHED_ENABLED="Modúl cumasaithe agus neamhfhoilsithe."
COM_MODULES_FIELD_AUTOMATIC_TITLE_LABEL="Teideal Uathoibríoch"
COM_MODULES_FIELD_BOOTSTRAP_SIZE_LABEL="Méid Bootstrap"
COM_MODULES_FIELD_CACHE_TIME_LABEL="Am Taisce"
COM_MODULES_FIELD_CACHING_LABEL="Taisceáil"
COM_MODULES_FIELD_CLIENT_ID_LABEL="Suíomh an Mhodúil"
COM_MODULES_FIELD_CONTENT_LABEL="Téacs"
COM_MODULES_FIELD_CONTENT_TOO_LARGE="Sáraíonn an t-ábhar na teorainneacha ceadaithe"
COM_MODULES_FIELD_HEADER_CLASS_LABEL="Rang Ceanntásc"
COM_MODULES_FIELD_HEADER_TAG_LABEL="Clib Ceanntásc"
COM_MODULES_FIELD_MODULE_LABEL="Cineál Modúil"
COM_MODULES_FIELD_MODULE_STYLE_LABEL="Stíl Modúil"
COM_MODULES_FIELD_MODULE_TAG_LABEL="Clib Modúil"
COM_MODULES_FIELD_MODULECLASS_SFX_LABEL="Rang Modúil"
COM_MODULES_FIELD_NOTE_LABEL="Nóta"
COM_MODULES_FIELD_POSITION_LABEL="Suíomh"
COM_MODULES_FIELD_PUBLISH_DOWN_LABEL="Críochnaigh Foilsiú"
COM_MODULES_FIELD_PUBLISH_UP_LABEL="Tosaigh Foilsiú"
COM_MODULES_FIELD_SHOWTITLE_LABEL="Teideal"
COM_MODULES_FIELD_VALUE_NOCACHING="Gan taisceáil"
COM_MODULES_FIELDSET_RULES="Ceadanna"
COM_MODULES_FILTER_SEARCH_DESC="Scag de réir ainm an tsuímh."
COM_MODULES_FORM_TITLE_EDIT="Eagar Modúil"
COM_MODULES_FORM_TITLE_NEW="Modúl Nua"
COM_MODULES_GENERAL_FIELDSET_DESC="Cumraigh socruithe comhéadan eagarthóireachta modúil."
COM_MODULES_GLOBAL="Modúl a Shannadh do Míreanna Roghchláir"
COM_MODULES_GLOBAL_ASSIGN="Sannadh do Míreanna Roghchláir"
COM_MODULES_GLOBAL_TREE_EXPAND="Fo-chrainn Roghchláir a Leathnú"
COM_MODULES_HEADING_MODULE="Cineál"
COM_MODULES_HEADING_MODULE_ASC="Cineál ag ardú"
COM_MODULES_HEADING_MODULE_DESC="Cineál ag ísliú"
COM_MODULES_HEADING_PAGES="Leathanaigh"
COM_MODULES_HEADING_PAGES_ASC="Leathanaigh ag ardú"
COM_MODULES_HEADING_PAGES_DESC="Leathanaigh ag ísliú"
COM_MODULES_HEADING_POSITION="Seasamh"
COM_MODULES_HEADING_POSITION_ASC="Seasamh ag ardú"
COM_MODULES_HEADING_POSITION_DESC="Seasamh ag ísliú"
COM_MODULES_HEADING_TEMPLATES="Teimpléid"
COM_MODULES_HTML_PUBLISH_DISABLED="Foilsigh modúl::Síneadh díchumasaithe"
COM_MODULES_HTML_PUBLISH_ENABLED="Foilsigh modúl::Síneadh cumasaithe"
COM_MODULES_HTML_UNPUBLISH_DISABLED="Dífoilsigh modúl::Síneadh díchumasaithe"
COM_MODULES_HTML_UNPUBLISH_ENABLED="Dífoilsigh modúl::Síneadh cumasaithe"
COM_MODULES_MANAGER_MODULE="Modúil: %s"
COM_MODULES_MANAGER_MODULES_ADMIN="Modúil (Riarthóir)"
COM_MODULES_MANAGER_MODULES_SITE="Modúil (Suíomh)"
COM_MODULES_MENU_ASSIGNMENT="Sannadh Roghchláir"
COM_MODULES_MENU_ITEM_ALIAS="Ailias"
COM_MODULES_MENU_ITEM_HEADING="Ceannteideal"
COM_MODULES_MENU_ITEM_SEPARATOR="Deighilteoir"
COM_MODULES_MENU_ITEM_URL="URL"
COM_MODULES_MODULE="Modúl"
COM_MODULES_MODULE_ASSIGN="Sannadh Modúil"
COM_MODULES_MODULE_DESCRIPTION="Cur Síos ar an Modúl"
COM_MODULES_MODULE_TEMPLATE_POSITION="%1$s (%2$s)"
COM_MODULES_MODULES="Modúil"
COM_MODULES_MODULES_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus i nóta an mhodúil. Réamhtheachtaigh le ID: chun ID modúil a chuardach."
COM_MODULES_MODULES_FILTER_SEARCH_LABEL="Cuardaigh Modúil"
COM_MODULES_MSG_MANAGE_EXTENSION_DISABLED="Tá an modúl '%s' díchumasaithe. Úsáid Córas &rarr; Bainistigh &rarr; Síntí chun é a chumasú."
COM_MODULES_MSG_MANAGE_NO_MODULES="Níl aon mhodúil ag teacht le do cheist"
COM_MODULES_N_ITEMS_ARCHIVED="%d modúil cartlainne."
COM_MODULES_N_ITEMS_ARCHIVED_1="Modúl cartlainne."
COM_MODULES_N_ITEMS_CHECKED_IN_1="Modúl seiceáilte isteach."
COM_MODULES_N_ITEMS_CHECKED_IN_MORE="%d modúil seiceáilte isteach."
COM_MODULES_N_ITEMS_DELETED="%d modúil scriosta."
COM_MODULES_N_ITEMS_DELETED_1="Modúl scriosta."
COM_MODULES_N_ITEMS_PUBLISHED="%d modúil foilsithe."
COM_MODULES_N_ITEMS_PUBLISHED_1="Modúl foilsithe."
COM_MODULES_N_ITEMS_TRASHED="%d modúil bruscair."
COM_MODULES_N_ITEMS_TRASHED_1="Modúl bruscair."
COM_MODULES_N_ITEMS_UNPUBLISHED="%d modúil dífhoilsithe."
COM_MODULES_N_ITEMS_UNPUBLISHED_1="Modúl dífhoilsithe."
COM_MODULES_N_MODULES_DUPLICATED="%d modúil dúbláilte."
COM_MODULES_N_MODULES_DUPLICATED_1="Modúl dúbláilte."
COM_MODULES_N_QUICKICON="Modúil"
COM_MODULES_N_QUICKICON_0="Modúil"
COM_MODULES_N_QUICKICON_1="Modúl"
COM_MODULES_N_QUICKICON_SRONLY="Modúil: Tá %d modúil ar fáil."
COM_MODULES_N_QUICKICON_SRONLY_0="Modúil: Níl aon mhodúl ar fáil."
COM_MODULES_N_QUICKICON_SRONLY_1="Modúil: Tá modúl amháin ar fáil."
COM_MODULES_NO_ITEM_SELECTED="Níl aon mhodúil roghnaithe."
COM_MODULES_NODESCRIPTION="Níl aon tuairisc ar fáil."
COM_MODULES_NONE=":: Dada ::"
COM_MODULES_OPTION_MENU_ALL="Ar gach leathanach"
COM_MODULES_OPTION_MENU_EXCLUDE="Ar gach leathanach seachas na cinn roghnaithe"
COM_MODULES_OPTION_MENU_INCLUDE="Ach amháin ar na leathanaigh roghnaithe"
COM_MODULES_OPTION_MENU_NONE="Gan leathanaigh"
COM_MODULES_OPTION_ORDER_POSITION="%d. %s"
COM_MODULES_OPTION_POSITION_TEMPLATE_DEFINED="Teimpléad"
COM_MODULES_OPTION_POSITION_USER_DEFINED="Úsáideoir"
COM_MODULES_OPTION_SELECT_CLIENT="- Roghnaigh Cineál -"
COM_MODULES_OPTION_SELECT_MENU_ITEM="- Roghnaigh Mír Roghchláir -"
COM_MODULES_OPTION_SELECT_MODULE="- Roghnaigh Cineál -"
COM_MODULES_OPTION_SELECT_POSITION="- Roghnaigh Suíomh -"
COM_MODULES_OPTION_SELECT_TYPE="- Roghnaigh cineál -"
COM_MODULES_POSITION_ANALYTICS="Anailísíocht"
COM_MODULES_POSITION_BANNER="Meirge"
COM_MODULES_POSITION_BOTTOM="Bun"
COM_MODULES_POSITION_BREADCRUMB="Blúire Bealaigh"
COM_MODULES_POSITION_BREADCRUMBS="Blúirí Bealaigh"
COM_MODULES_POSITION_DEBUG="Dífhabhtú"
COM_MODULES_POSITION_FOOTER="Buntásc"
COM_MODULES_POSITION_HEADER="Ceanntásc"
COM_MODULES_POSITION_LEFT2="Clé 2"
COM_MODULES_POSITION_LEFT="Clé"
COM_MODULES_POSITION_MAINNAV="Príomh-Nascleanúint"
COM_MODULES_POSITION_NAV="Nascleanúint"
COM_MODULES_POSITION_OFFLINE="As Líne"
COM_MODULES_POSITION_POSITION-0="Suíomh 0"
COM_MODULES_POSITION_POSITION-10="Suíomh 10"
COM_MODULES_POSITION_POSITION-11="Suíomh 11"
COM_MODULES_POSITION_POSITION-12="Suíomh 12"
COM_MODULES_POSITION_POSITION-13="Suíomh 13"
COM_MODULES_POSITION_POSITION-14="Suíomh 14"
COM_MODULES_POSITION_POSITION-15="Suíomh 15"
COM_MODULES_POSITION_POSITION-1="Suíomh 1"
COM_MODULES_POSITION_POSITION-2="Suíomh 2"
COM_MODULES_POSITION_POSITION-3="Suíomh 3"
COM_MODULES_POSITION_POSITION-4="Suíomh 4"
COM_MODULES_POSITION_POSITION-5="Suíomh 5"
COM_MODULES_POSITION_POSITION-6="Suíomh 6"
COM_MODULES_POSITION_POSITION-7="Suíomh 7"
COM_MODULES_POSITION_POSITION-8="Suíomh 8"
COM_MODULES_POSITION_POSITION-9="Suíomh 9"
COM_MODULES_POSITION_RIGHT2="Deas 2"
COM_MODULES_POSITION_RIGHT="Deas"
COM_MODULES_POSITION_SUB1="Fo 1"
COM_MODULES_POSITION_SUB2="Fo 2"
COM_MODULES_POSITION_SUB3="Fo 3"
COM_MODULES_POSITION_SUB4="Fo 4"
COM_MODULES_POSITION_SUB5="Fo 5"
COM_MODULES_POSITION_SUB6="Fo 6"
COM_MODULES_POSITION_SUB="Fo"
COM_MODULES_POSITION_SUBNAV="Fo-Nascleanúint"
COM_MODULES_POSITION_SYNDICATE="Siondacáit"
COM_MODULES_POSITION_TOP2="Barr 2"
COM_MODULES_POSITION_TOP3="Barr 3"
COM_MODULES_POSITION_TOP4="Barr 4"
COM_MODULES_POSITION_TOP="Barr"
COM_MODULES_POSITION_USER1="Úsáideoir 1"
COM_MODULES_POSITION_USER2="Úsáideoir 2"
COM_MODULES_POSITION_USER3="Úsáideoir 3"
COM_MODULES_POSITION_USER4="Úsáideoir 4"
COM_MODULES_POSITION_USER5="Úsáideoir 5"
COM_MODULES_POSITION_USER6="Úsáideoir 6"
COM_MODULES_POSITION_USER7="Úsáideoir 7"
COM_MODULES_POSITION_USER8="Úsáideoir 8"
COM_MODULES_SAVE_SUCCESS="Modúl sábháilte."
COM_MODULES_SEARCH_MENUITEM="Cuardaigh Mír Roghchláir"
COM_MODULES_SELECT_MODULE="Roghnaigh modúl, %s"
COM_MODULES_SUBITEMS="Fo-mhíreanna"
COM_MODULES_TABLE_CAPTION="Modúil"
COM_MODULES_TYPE_CHOOSE="Roghnaigh Cineál Modúil"
COM_MODULES_TYPE_OR_SELECT_POSITION="Clóscríobh nó roghnaigh Suíomh"
COM_MODULES_XML_DESCRIPTION="Comhpháirt le haghaidh bainistíocht modúl sa Chúlra Riaracháin."

JLIB_RULES_SETTING_NOTES_COM_MODULES="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus a bhaineann le gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé ar chumas an ghnímh don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda." ; Alternate language strings for the rules form field
