; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

CATEGORIES_FIELDSET_OPTIONS="Roghanna"
COM_CATEGORIES="Catagóirí"
COM_CATEGORIES_BATCH_CANNOT_CREATE="Níl cead agat catagóirí nua a chruthú sa chatagóir seo."
COM_CATEGORIES_BATCH_CANNOT_EDIT="Níl cead agat ceann amháin nó níos mó de na catagóirí seo a chur in eagar."
COM_CATEGORIES_BATCH_OPTIONS="Próiseáil bhaisc na catagóirí roghnaithe."
COM_CATEGORIES_BATCH_TIP="Má roghnaítear catagóir le haghaidh bogadh/cóipeáil, cuirfear aon ghníomhartha roghnaithe i bhfeidhm ar na catagóirí cóipeáilte nó bogtha. Seachas sin, cuirtear gach gníomh i bhfeidhm ar na catagóirí roghnaithe."
COM_CATEGORIES_CATEGORIES_BASE_TITLE="Catagóirí"
COM_CATEGORIES_CATEGORIES_TITLE="%s: Catagóirí"
COM_CATEGORIES_CATEGORY_ADD_TITLE="%s: Catagóir Nua"
COM_CATEGORIES_CATEGORY_BASE_ADD_TITLE="Catagóir Nua"
COM_CATEGORIES_CATEGORY_BASE_EDIT_TITLE="Cuir Catagóir in Eagar"
COM_CATEGORIES_CATEGORY_EDIT_TITLE="%s: Cuir Catagóir in Eagar"
COM_CATEGORIES_COUNT_ARCHIVED_ITEMS="Míreanna Cartlainne"
COM_CATEGORIES_COUNT_PUBLISHED_ITEMS="Míreanna Foilsithe"
COM_CATEGORIES_COUNT_TRASHED_ITEMS="Míreanna Bruscair"
COM_CATEGORIES_COUNT_UNPUBLISHED_ITEMS="Míreanna Neamhfhoilsithe"
COM_CATEGORIES_DELETE_NOT_ALLOWED="Níl cead scriosadh don chatagóir %s."
COM_CATEGORIES_EDIT_CATEGORY="Cuir Catagóir in Eagar"
COM_CATEGORIES_EMPTYSTATE_BUTTON_ADD="Cuir catagóir leis"
COM_CATEGORIES_EMPTYSTATE_CONTENT="Níl aon chatagóirí ann faoi láthair don síneadh seo."
COM_CATEGORIES_ERROR_ALL_LANGUAGE_ASSOCIATED="Ní féidir mír chatagóir atá socraithe do Gach teanga a chomhcheangal. Níor socraíodh na comhlachais."
COM_CATEGORIES_FIELD_BASIC_LABEL="Roghanna"
COM_CATEGORIES_FIELD_IMAGE_ALT_EMPTY_DESC="Íomhá Maisiúil - níl aon tuairisc ag teastáil"
COM_CATEGORIES_FIELD_IMAGE_ALT_EMPTY_LABEL="Gan Tuairisc"
COM_CATEGORIES_FIELD_IMAGE_ALT_LABEL="Tuairisc Íomhá (Alt Téacs)"
COM_CATEGORIES_FIELD_IMAGE_LABEL="Íomhá"
COM_CATEGORIES_FIELD_NOTE_LABEL="Nóta"
COM_CATEGORIES_FIELD_PARENT_LABEL="Tuismitheoir"
COM_CATEGORIES_FIELDSET_DETAILS="Sonraí Catagóire"
COM_CATEGORIES_FIELDSET_PUBLISHING="Foilsitheoireacht"
COM_CATEGORIES_FIELDSET_RULES="Ceadanna"
COM_CATEGORIES_FILTER_SEARCH_DESC="Cuardaigh i dteideal, ailias agus nóta. Cuir ID: roimh chun ID catagóire a chuardach."
COM_CATEGORIES_FILTER_SEARCH_LABEL="Cuardaigh Catagóirí"
COM_CATEGORIES_FORM_TITLE_EDIT="Cuir Catagóir in Eagar"
COM_CATEGORIES_FORM_TITLE_NEW="Catagóir Nua"
COM_CATEGORIES_HAS_SUBCATEGORY_ITEMS="Tá %d mír sannta do fhochatagóirí na catagóire seo."
COM_CATEGORIES_HAS_SUBCATEGORY_ITEMS_1="Tá mír amháin sannta do cheann de fhochatagóirí na catagóire seo."
COM_CATEGORIES_HEADING_ARCHIVED="Cartlainne"
COM_CATEGORIES_HEADING_PUBLISHED="Foilsithe"
COM_CATEGORIES_HEADING_TRASHED="Bruscair"
COM_CATEGORIES_HEADING_UNPUBLISHED="Neamhfhoilsithe"
COM_CATEGORIES_HEADING_ASSOCIATION="Comhlachas"
COM_CATEGORIES_ITEMS_SEARCH_FILTER="Cuardaigh"
COM_CATEGORIES_N_ITEMS_ARCHIVED="Cartlannaíodh %d catagóir."
COM_CATEGORIES_N_ITEMS_ARCHIVED_1="Cartlannaíodh Catagóir."
COM_CATEGORIES_N_ITEMS_ASSIGNED="Tá %d mír sannta don chatagóir seo."
COM_CATEGORIES_N_ITEMS_ASSIGNED_1="Tá mír amháin sannta don chatagóir seo."
COM_CATEGORIES_N_ITEMS_CHECKED_IN_1="Seiceáil isteach catagóir."
COM_CATEGORIES_N_ITEMS_CHECKED_IN_MORE="Seiceáil isteach %d catagóir."
COM_CATEGORIES_N_ITEMS_DELETED="Scriosadh %d catagóir."
COM_CATEGORIES_N_ITEMS_DELETED_1="Scriosadh Catagóir."
COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING="Theip ar fhoilsiú %d catagóir mar tá a dtuismitheoir amháin ar a laghad neamhfhoilsithe nó tá ceann dá leanaí seiceáilte amach."
COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING_1="Theip ar fhoilsiú %d catagóir mar tá ar a laghad ceann dá thuismitheoirí neamhfhoilsithe nó tá ceann dá leanaí seiceáilte amach."
COM_CATEGORIES_N_ITEMS_PUBLISHED="%d catagóirí foilsithe."
COM_CATEGORIES_N_ITEMS_PUBLISHED_1="Catagóir foilsithe."
COM_CATEGORIES_N_ITEMS_TRASHED="%d catagóirí bruscair."
COM_CATEGORIES_N_ITEMS_TRASHED_1="Catagóir bruscair."
COM_CATEGORIES_N_ITEMS_UNPUBLISHED="%d catagóirí neamhfhoilsithe."
COM_CATEGORIES_N_ITEMS_UNPUBLISHED_1="Catagóir neamhfhoilsithe."
COM_CATEGORIES_N_QUICKICON="Catagóirí Airteagal"
COM_CATEGORIES_N_QUICKICON_0="Catagóirí Airteagal"
COM_CATEGORIES_N_QUICKICON_1="Catagóir Airteagal"
COM_CATEGORIES_N_QUICKICON_SRONLY="Catagóirí: %d catagóirí airteagal foilsithe."
COM_CATEGORIES_N_QUICKICON_SRONLY_0="Catagóirí: Níl aon chatagóir airteagal foilsithe."
COM_CATEGORIES_N_QUICKICON_SRONLY_1="Catagóirí: Tá catagóir airteagal amháin foilsithe."
COM_CATEGORIES_NEW_CATEGORY="Catagóir Nua"
COM_CATEGORIES_NO_ITEM_SELECTED="Roghnaigh rud éigin ón liosta ar dtús le do thoil."
COM_CATEGORIES_PATH_LABEL="Conair Catagóire"
COM_CATEGORIES_REBUILD_FAILURE="Theip ar athfhoirgniú sonraí crann na gCatagóirí."
COM_CATEGORIES_REBUILD_SUCCESS="Sonraí crann na gCatagóirí athfhoirgnithe."
COM_CATEGORIES_SAVE_SUCCESS="Catagóir sábháilte."
COM_CATEGORIES_SELECT_A_CATEGORY="Roghnaigh Catagóir"
COM_CATEGORIES_TABLE_CAPTION="Catagóirí"
COM_CATEGORIES_TIP_ASSOCIATION="Catagóirí comhcheangailte"
COM_CATEGORIES_XML_DESCRIPTION="Bainistíonn an comhpháirt seo catagóirí."
JGLOBAL_NO_ITEM_SELECTED="Níl aon chatagóirí roghnaithe."
JLIB_HTML_ACCESS_SUMMARY_DESC="Taispeántar thíos forbhreathnú ar na socruithe ceadanna don chatagóir seo. Roghnaigh na cluaisíní thuas chun na socruithe seo a shaincheapadh de réir gnímh."
JLIB_RULES_SETTING_NOTES_ITEM="Baineann athruithe leis an gcatagóir seo agus le gach catagóir leanaí.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú leibhéal níos airde i bhfeidhm.<br><em><strong>Diúltaithe</strong></em> i gcónaí buaite - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus a bhaineann le gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé ar chumas an ghnímh don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
