; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FIELDS="Réimsí"
COM_FIELDS_CHOOSE_COMPONENT_LABEL="Roghnaigh Comhpháirt"
COM_FIELDS_FIELDS_VIEW_DEFAULT_DESC="Taispeánann sé liosta de na réimsí go léir."
COM_FIELDS_FIELDS_VIEW_DEFAULT_TITLE="Liostaigh Gach Réimse"
COM_FIELDS_GROUPS_VIEW_DEFAULT_DESC="Taispeánann sé liosta de na grúpaí réimse go léir."
COM_FIELDS_GROUPS_VIEW_DEFAULT_TITLE="Liostaigh Gach Grúpa Réimse"
COM_FIELDS_XML_DESCRIPTION="Comhpháirt chun réimsí saincheaptha a bhainistiú."
