; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_PLUGINS="Breiseáin"
COM_PLUGINS_CONFIGURATION="Breiseán: Roghanna"
COM_PLUGINS_ELEMENT_HEADING="Eilimint"
COM_PLUGINS_ERROR_FILE_NOT_FOUND="Níorbh fhéidir an comhad %s a fháil."
COM_PLUGINS_FIELD_ELEMENT_LABEL="Comhad Breiseáin"
COM_PLUGINS_FIELD_FOLDER_LABEL="Cineál Breiseáin"
COM_PLUGINS_FIELD_NAME_LABEL="Ainm Breiseáin"
COM_PLUGINS_FILTER_SEARCH_LABEL="Cuardaigh Breiseáin"
COM_PLUGINS_FOLDER_HEADING="Cineál"
COM_PLUGINS_FORM_EDIT="Foirm Eagarthóireachta"
COM_PLUGINS_HEADING_ELEMENT_ASC="Eilimint ag ardú"
COM_PLUGINS_HEADING_ELEMENT_DESC="Eilimint ag ísliú"
COM_PLUGINS_HEADING_FOLDER_ASC="Cineál ag ardú"
COM_PLUGINS_HEADING_FOLDER_DESC="Cineál ag ísliú"
COM_PLUGINS_MANAGER_PLUGIN="Breiseáin: %s"
COM_PLUGINS_MANAGER_PLUGINS="Breiseáin"
COM_PLUGINS_N_ITEMS_CHECKED_IN_1="Breiseán seiceáilte isteach."
COM_PLUGINS_N_ITEMS_CHECKED_IN_MORE="%d breiseán seiceáilte isteach."
COM_PLUGINS_N_ITEMS_PUBLISHED="%d breiseán cumasaithe."
COM_PLUGINS_N_ITEMS_PUBLISHED_1="Breiseán cumasaithe."
COM_PLUGINS_N_ITEMS_UNPUBLISHED="%d breiseán díchumasaithe."
COM_PLUGINS_N_ITEMS_UNPUBLISHED_1="Breiseán díchumasaithe."
COM_PLUGINS_N_QUICKICON="Breiseáin"
COM_PLUGINS_N_QUICKICON_1="Breiseán"
COM_PLUGINS_N_QUICKICON_SRONLY="Breiseáin: Tá %d breiseán cumasaithe."
COM_PLUGINS_N_QUICKICON_SRONLY_1="Breiseáin: Tá breiseán amháin cumasaithe."
COM_PLUGINS_NAME_HEADING="Ainm Breiseáin"
COM_PLUGINS_NO_ITEM_SELECTED="Níl aon bhreiseán roghnaithe."
COM_PLUGINS_OPTION_ELEMENT="- Roghnaigh Eilimint -"
COM_PLUGINS_OPTION_FOLDER="- Roghnaigh Cineál -"
COM_PLUGINS_PLUGIN="Breiseán"
COM_PLUGINS_SAVE_SUCCESS="Breiseán sábháilte."
COM_PLUGINS_SEARCH_IN_TITLE="Cuardaigh in ainm an bhreiseáin. Cuir ID: roimh chun ID breiseáin a chuardach."
COM_PLUGINS_TABLE_CAPTION="Breiseáin"
COM_PLUGINS_XML_DESCRIPTION="Bainistíonn an comhpháirt seo breiseáin Joomla."
COM_PLUGINS_XML_ERR="Níl sonraí XML na mbreiseán ar fáil."
JLIB_HTML_PUBLISH_ITEM="Cumasaigh breiseán"
JLIB_HTML_UNPUBLISH_ITEM="Díchumasaigh breiseán"

JLIB_RULES_SETTING_NOTES_COM_PLUGINS="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Diúltaithe</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus cuirtear i bhfeidhm ar gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas na comhpháirte seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
