; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FIELDS="Réimsí"
COM_FIELDS_BATCH_GROUP_LABEL="Chun do rogha a aistriú nó a chóipeáil, roghnaigh grúpa le do thoil."
COM_FIELDS_BATCH_GROUP_OPTION_NONE="- Gan Grúpa -"
COM_FIELDS_CHOOSE_CONTEXT_LABEL="Comhthéacs"
COM_FIELDS_ERROR_UNIQUE_NAME="Tá réimse eile leis an ainm céanna (cuimhnigh go bhféadfadh sé a bheith ina mhír bhruscar nó go bhféadfadh sé a bheith ann cheana mar réimse saincheaptha i síneadh eile)."
COM_FIELDS_FIELD_CLASS_DESC="Na tréithe aicme den réimse sa bhfoirm eagarthóireachta. Má tá aicmí iolracha ag teastáil, liostáil iad le spásanna."
COM_FIELDS_FIELD_CLASS_LABEL="Aicme Réimse"
COM_FIELDS_FIELD_DEFAULT_VALUE_LABEL="Luach Réamhshocraithe"
COM_FIELDS_FIELD_DISPLAY_AFTER_DISPLAY="Tar éis Ábhar a Thaispeáint"
COM_FIELDS_FIELD_DISPLAY_AFTER_TITLE="Tar éis Teideal"
COM_FIELDS_FIELD_DISPLAY_BEFORE_DISPLAY="Roimh Ábhar a Thaispeáint"
COM_FIELDS_FIELD_DISPLAY_LABEL="Taispeáint Uathoibríoch"
COM_FIELDS_FIELD_DISPLAY_NO_DISPLAY="Ná taispeáin go huathoibríoch"
COM_FIELDS_FIELD_EDITABLE_IN_ADMIN="Riarthóir"
COM_FIELDS_FIELD_EDITABLE_IN_BOTH="An Dá Rud"
COM_FIELDS_FIELD_EDITABLE_IN_LABEL="In-eagarthóireachta I"
COM_FIELDS_FIELD_EDITABLE_IN_SITE="Suíomh"
COM_FIELDS_FIELD_FORM_EDIT="Cuir Réimse in Eagar"
; The following string is deprecated and will be removed with 6.0
COM_FIELDS_FIELD_FORM_LAYOUT_LABEL="Leagan Amach"
COM_FIELDS_FIELD_FORM_NEW="Réimse Nua"
COM_FIELDS_FIELD_FORMOPTIONS_HEADING="Roghanna Foirm"
COM_FIELDS_FIELD_GROUP_LABEL="Grúpa Réimse"
COM_FIELDS_FIELD_IMAGE_ALT_DESC="Téacs malartach a úsáidtear do chuairteoirí gan rochtain ar íomhánna."
COM_FIELDS_FIELD_IMAGE_ALT_LABEL="Téacs Alt"
COM_FIELDS_FIELD_IMAGE_DESC="Lipéad íomhá."
COM_FIELDS_FIELD_IMAGE_LABEL="Íomhá"
COM_FIELDS_FIELD_INVALID_DEFAULT_VALUE="Tá an luach réamhshocraithe neamhbhailí."
COM_FIELDS_FIELD_LABEL_FORM_CLASS_LABEL="Aicme Lipéad (Foirm)"
COM_FIELDS_FIELD_LABEL_LABEL="Lipéad"
COM_FIELDS_FIELD_LABEL_RENDER_CLASS_LABEL="Aicme Lipéad (Aschur)"
COM_FIELDS_FIELD_LAYOUT_LABEL="Leagan Amach"
COM_FIELDS_FIELD_N_ITEMS_ARCHIVED="%d réimsí cartlainne"
COM_FIELDS_FIELD_N_ITEMS_ARCHIVED_1="Réimse cartlainne"
COM_FIELDS_FIELD_N_ITEMS_CHECKED_IN="%d réimsí seiceáilte isteach"
COM_FIELDS_FIELD_N_ITEMS_CHECKED_IN_1="Réimse seiceáilte isteach"
COM_FIELDS_FIELD_N_ITEMS_DELETED="%d réimsí scriosta"
COM_FIELDS_FIELD_N_ITEMS_DELETED_1="Réimse scriosta"
COM_FIELDS_FIELD_N_ITEMS_PUBLISHED="%d réimsí foilsithe"
COM_FIELDS_FIELD_N_ITEMS_PUBLISHED_1="Réimse foilsithe"
COM_FIELDS_FIELD_N_ITEMS_TRASHED="%d réimsí bruscair"
COM_FIELDS_FIELD_N_ITEMS_TRASHED_1="Réimse bruscair"
COM_FIELDS_FIELD_N_ITEMS_UNPUBLISHED="%d réimsí neamhfhoilsithe"
COM_FIELDS_FIELD_N_ITEMS_UNPUBLISHED_1="Réimse neamhfhoilsithe"
COM_FIELDS_FIELD_NOTE_LABEL="Nóta"
COM_FIELDS_FIELD_ONLY_USE_IN_SUBFORM_BADGE="Fo-fhoirm Amháin"
COM_FIELDS_FIELD_ONLY_USE_IN_SUBFORM_LABEL="Úsáid Amháin i bhFo-fhoirm"
COM_FIELDS_FIELD_PLACEHOLDER_DESC="Téacs ionaid a bheidh le feiceáil laistigh den réimse mar leid don úsáideoir maidir leis an ionchur riachtanach."
COM_FIELDS_FIELD_PLACEHOLDER_LABEL="Ionad"
COM_FIELDS_FIELD_PREFIX_LABEL="Réimír"
COM_FIELDS_FIELD_RENDER_CLASS_DESC="Aicme an choimeádáin réimse san aschur."
COM_FIELDS_FIELD_RENDER_CLASS_LABEL="Aicme Taispeána"
COM_FIELDS_FIELD_RENDEROPTIONS_HEADING="Roghanna Taispeána"
COM_FIELDS_FIELD_REQUIRED_LABEL="Riachtanach"
COM_FIELDS_FIELD_SAVE_SUCCESS="Réimse sábháilte"
COM_FIELDS_FIELD_SEARCHINDEX_BOTH="Déan cuardach agus cuir leis mar thacsanomaíocht"
COM_FIELDS_FIELD_SEARCHINDEX_DESC="Rabhadh: Nuair a roghnaítear 'Déan cuardach', déantar ábhar ón réimse a innéacsú le ceadanna féachana an mhíre ábhair. D’fhéadfadh sé seo eolas gan choinne a nochtadh."
COM_FIELDS_FIELD_SEARCHINDEX_DONT="Ná déan inchuardaithe"
COM_FIELDS_FIELD_SEARCHINDEX_LABEL="Innéacs Cuardaigh"
COM_FIELDS_FIELD_SEARCHINDEX_SEARCHABLE="Déan inchuardaithe"
COM_FIELDS_FIELD_SEARCHINDEX_TAXONOMY="Cuir leis mar thacsanomaíocht"
COM_FIELDS_FIELD_SHOWLABEL_DESC="Taispeáin nó Folaigh an lipéad nuair a thaispeántar an réimse."
COM_FIELDS_FIELD_SHOWLABEL_LABEL="Lipéad"
COM_FIELDS_FIELD_SHOWON_DESC="Taispeáin nó folaigh an réimse go coinníollach ag brath ar luach réimsí eile."
COM_FIELDS_FIELD_SHOWON_LABEL="Tréith Taispeáin"
COM_FIELDS_FIELD_SMARTSEARCHOPTIONS_HEADING="Cuardach Cliste"
COM_FIELDS_FIELD_SUFFIX_LABEL="Iarmhír"
COM_FIELDS_FIELD_TYPE_LABEL="Cineál"
COM_FIELDS_FIELD_USE_GLOBAL="Úsáid socruithe ón mBreiseán"
COM_FIELDS_FIELD_VALUE_RENDER_CLASS_DESC="An rang luach réimse sa toradh."
COM_FIELDS_FIELD_VALUE_RENDER_CLASS_LABEL="Rang Luach"
COM_FIELDS_FIELDS_FILTER_ONLY_USE_IN_SUBFORM_LABEL="Úsáid Amháin i bhFoirm Fhoirm"
COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="Cuardaigh i ainm réimse, teideal nó nóta. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID réimse. Réamhtheachtaigh le ÚDAR: chun cuardach a dhéanamh ar údar réimse."
COM_FIELDS_FIELDS_FILTER_SEARCH_LABEL="Cuardaigh Réimsí"
COM_FIELDS_FIELDS_TABLE_CAPTION="Réimsí"
COM_FIELDS_GROUP_FORM_EDIT="Cuir Grúpa Réimse in Eagar"
COM_FIELDS_GROUP_FORM_NEW="Grúpa Réimse Nua"
COM_FIELDS_GROUP_N_ITEMS_ARCHIVED="Cartlannaíodh %d grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_ARCHIVED_1="Cartlannaíodh grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_CHECKED_IN="Seiceáil isteach %d grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_CHECKED_IN_1="Seiceáil isteach grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_DELETED="Scriosadh %d grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_DELETED_1="Scriosadh grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_PUBLISHED="Foilsíodh %d grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_PUBLISHED_1="Foilsíodh grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_TRASHED="Cuireadh %d grúpa réimse sa bhruscar"
COM_FIELDS_GROUP_N_ITEMS_TRASHED_1="Cuireadh grúpa réimse sa bhruscar"
COM_FIELDS_GROUP_N_ITEMS_UNPUBLISHED="Dífoilsíodh %d grúpa réimse"
COM_FIELDS_GROUP_N_ITEMS_UNPUBLISHED_1="Dífoilsíodh grúpa réimse"
COM_FIELDS_GROUP_SAVE_SUCCESS="Sábháladh Grúpa Réimse"
COM_FIELDS_GROUPS_FILTER_SEARCH_DESC="Cuardaigh i dteideal grúpa réimse. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID grúpa réimse."
COM_FIELDS_GROUPS_FILTER_SEARCH_LABEL="Cuardaigh Grúpaí Réimse"
COM_FIELDS_GROUPS_TABLE_CAPTION="Grúpaí Réimse"
COM_FIELDS_MUSTCONTAIN_A_TITLE_FIELD="Ní mór teideal a bheith ag an réimse."
COM_FIELDS_MUSTCONTAIN_A_TITLE_GROUP="Ní mór teideal a bheith ag Grúpa Réimse."
COM_FIELDS_NO_FIELDS_TO_CREATE_SUBFORM_FIELD_WARNING="Ní mór duit réimsí caighdeánacha a chruthú sula gcruthóidh tú réimse Foirm Fhoirm."
COM_FIELDS_ONLY_USE_IN_SUBFORM="- Úsáid i bhFoirm Fhoirm -"
COM_FIELDS_ONLY_USE_IN_SUBFORM_ANY="Aon Fhoirm"
COM_FIELDS_ONLY_USE_IN_SUBFORM_SUBFORM="Amháin i bhFoirm Fhoirm"
COM_FIELDS_SEARCHINDEX_MIGHT_REQUIRE_REINDEXING="Tabhair faoi deara, d'fhéadfadh go mbeadh ort an t-innéacs Cuardach Cliste a atógáil mar gheall ar do chuid athruithe sa Bhainisteoir Réimsí Saincheaptha."
COM_FIELDS_SYSTEM_PLUGIN_NOT_ENABLED="Tá an breiseán <a href=\"%s\">Córas - Réimsí</a> díchumasaithe. Ní thaispeánfar réimsí saincheaptha go dtí go gcumasóidh tú an breiseán seo."
COM_FIELDS_VIEW_FIELD_ADD_TITLE="%s: Réimse Nua"
COM_FIELDS_VIEW_FIELD_EDIT_TITLE="%s: Cuir Réimse in Eagar"
COM_FIELDS_VIEW_FIELD_FIELDSET_GENERAL="Ginearálta"
COM_FIELDS_VIEW_FIELDS_BATCH_OPTIONS="Próiseáil bhaisc na réimsí roghnaithe."
COM_FIELDS_VIEW_FIELDS_SELECT_CATEGORY="- Roghnaigh Catagóir Sannta -"
COM_FIELDS_VIEW_FIELDS_SELECT_GROUP="- Roghnaigh Grúpa Réimse -"
COM_FIELDS_VIEW_FIELDS_SORT_GROUP_ASC="Grúpa Réimse ag ardú"
COM_FIELDS_VIEW_FIELDS_SORT_GROUP_DESC="Grúpa Réimse ag ísliú"
COM_FIELDS_VIEW_FIELDS_SORT_TYPE_ASC="Cineál ag ardú"
COM_FIELDS_VIEW_FIELDS_SORT_TYPE_DESC="Cineál ag ísliú"
COM_FIELDS_VIEW_FIELDS_TITLE="%s: Réimsí"
COM_FIELDS_VIEW_GROUP_ADD_TITLE="%s: Grúpa Réimse Nua"
COM_FIELDS_VIEW_GROUP_EDIT_TITLE="%s: Cuir Grúpa Réimse in Eagar"
COM_FIELDS_VIEW_GROUPS_BATCH_OPTIONS="Próiseáil bhaisc na ngrúpaí réimse roghnaithe."
COM_FIELDS_VIEW_GROUPS_TITLE="%s: Grúpaí Réimse"
COM_FIELDS_XML_DESCRIPTION="Comhpháirt chun réimsí saincheaptha a bhainistiú."
