; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FINDER="Cuardach Cliste"
COM_FINDER_FILTERS="Scagairí"
COM_FINDER_FILTERS_VIEW_DEFAULT_DESC="Taispeáin scagairí cuardaigh."
COM_FINDER_FILTERS_VIEW_DEFAULT_TITLE="Scagairí Cuardaigh Cliste"
COM_FINDER_INDEX="Innéacs"
COM_FINDER_INDEX_VIEW_DEFAULT_DESC="Taispeáin ábhar innéacsaithe."
COM_FINDER_INDEX_VIEW_DEFAULT_TITLE="Ábhar Innéacsaithe Cuardaigh Cliste"
COM_FINDER_MAPS="Léarscáileanna Ábhair"
COM_FINDER_MAPS_VIEW_DEFAULT_DESC="Taispeáin léarscáiliú ábhair cuardaigh."
COM_FINDER_MAPS_VIEW_DEFAULT_TITLE="Léarscáiliú Ábhair Cuardaigh Cliste"
COM_FINDER_MENU_SEARCH_VIEW_DEFAULT_TEXT="Leagan amach cuardaigh réamhshocraithe."
COM_FINDER_MENU_SEARCH_VIEW_DEFAULT_TITLE="Cuardach"
COM_FINDER_SEARCH_VIEW_DEFAULT_DESC="Taispeáin torthaí cuardaigh."
COM_FINDER_SEARCH_VIEW_DEFAULT_TITLE="Torthaí Cuardaigh Cliste"
COM_FINDER_SEARCHES="Téarmaí Cuardaigh"
COM_FINDER_STATS_VIEW_DEFAULT_DESC="Taispeáin staitisticí cuardaigh."
COM_FINDER_STATS_VIEW_DEFAULT_TITLE="Staitisticí Cuardaigh Cliste"
COM_FINDER_XML_DESCRIPTION="Cuardach Cliste"
