; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_WRAPPER="Clúdach"
COM_WRAPPER_FIELD_ADD_DESC="De réir réamhshocraithe, cuirfear http:// leis mura n-aithníonn sé http:// nó https:// sa URL a sholáthraíonn tú. Ligeann sé seo duit an fheidhmiúlacht seo a mhúchadh."
COM_WRAPPER_FIELD_ADD_LABEL="Cuir go huathoibríoch"
COM_WRAPPER_FIELD_HEIGHT_LABEL="Airde"
COM_WRAPPER_FIELD_HEIGHTAUTO_LABEL="Airde Uathoibríoch"
COM_WRAPPER_FIELD_LABEL_SCROLLBARSPARAMS="Paraiméadair Bharra Scrollaigh"
COM_WRAPPER_FIELD_LAZYLOADING_LABEL="Lódáil Mhall"
COM_WRAPPER_FIELD_URL_LABEL="URL"
COM_WRAPPER_XML_DESCRIPTION="Taispeánann sé iframe chun leathanach nó suíomh seachtrach a chlúdach isteach i Joomla!"
