; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CHECKIN="Seiceáil isteach"
COM_CHECKIN_CONFIGURATION="Seiceáil isteach: Roghanna"
COM_CHECKIN_DATABASE_TABLE="Tábla Bunachar Sonraí"
COM_CHECKIN_DATABASE_TABLE_ASC="Tábla Bunachar Sonraí ag ardú"
COM_CHECKIN_DATABASE_TABLE_DESC="Tábla Bunachar Sonraí ag ísliú"
COM_CHECKIN_EMPTYSTATE_CONTENT="Níl aon táblaí le míreanna seiceáilte amach."
COM_CHECKIN_FILTER_SEARCH_DESC="Cuardaigh táblaí bunachar sonraí le míreanna le seiceáil isteach."
COM_CHECKIN_FILTER_SEARCH_LABEL="Cuardaigh Táblaí Bunachar Sonraí"
COM_CHECKIN_GLOBAL_CHECK_IN="Cothabháil: Seiceáil Isteach Domhanda"
COM_CHECKIN_ITEMS_TO_CHECK_IN="Míreanna le seiceáil isteach"
COM_CHECKIN_ITEMS_TO_CHECK_IN_ASC="Míreanna le seiceáil isteach ag ardú"
COM_CHECKIN_ITEMS_TO_CHECK_IN_DESC="Míreanna le seiceáil isteach ag ísliú"
COM_CHECKIN_N_ITEMS_CHECKED_IN_1="Mír seiceáilte isteach."
COM_CHECKIN_N_ITEMS_CHECKED_IN_MORE="%d míreanna seiceáilte isteach."
COM_CHECKIN_N_QUICKICON_SRONLY="Seiceáil Isteach Domhanda: Tá míreanna faoi ghlas ag %d táblaí."
COM_CHECKIN_N_QUICKICON_SRONLY_0="Seiceáil Isteach Domhanda: Níl míreanna faoi ghlas ag aon táblaí."
COM_CHECKIN_N_QUICKICON_SRONLY_1="Seiceáil Isteach Domhanda: Tá míreanna faoi ghlas ag tábla amháin."
COM_CHECKIN_NO_ITEMS="Níl aon táblaí le míreanna seiceáilte amach nó níl aon táblaí le míreanna seiceáilte amach a oireann do do chuardach."
COM_CHECKIN_TABLE="<em>%s</em> tábla"
COM_CHECKIN_TABLE_CAPTION="Míreanna Seiceáilte Amach"
COM_CHECKIN_XML_DESCRIPTION="Comhpháirt Seiceáil Isteach."

JLIB_RULES_SETTING_NOTES_COM_CHECKIN="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann sé i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus cuirtear i bhfeidhm ar gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé ar chumas an ghnímh don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
