; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_WORKFLOW="Sreafaí Oibre"
COM_WORKFLOW_BASIC_STAGE="Céim Bhunúsach"
COM_WORKFLOW_BASIC_WORKFLOW="Sreabhadh Oibre Bunúsach"
COM_WORKFLOW_MESSAGES_VIEW_DEFAULT_DESC="Tacaíocht sreafa oibre saincheaptha do shuíomh Joomla!"
COM_WORKFLOW_MESSAGES_VIEW_DEFAULT_TITLE="Sreafaí Oibre"
COM_WORKFLOW_WORKFLOWS_VIEW_DEFAULT_DESC="Taispeánann sé liosta de na sreafaí oibre go léir."
COM_WORKFLOW_WORKFLOWS_VIEW_DEFAULT_TITLE="Liostaigh Gach Sreabhadh Oibre"
COM_WORKFLOW_XML_DESCRIPTION="Tacaíocht sreafa oibre saincheaptha do shuíomh Joomla!"
