; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_BANNERS="Meirgí"
COM_BANNERS_BANNER_DETAILS="Sonraí"
COM_BANNERS_BANNER_EDIT="Eagar Meirge"
COM_BANNERS_BANNER_NEW="Meirge Nua"
COM_BANNERS_BANNER_SAVE_SUCCESS="Meirge sábháilte."
COM_BANNERS_BANNERS_FILTER_SEARCH_DESC="Cuardaigh i ainm agus ailias an mheirge. Cuir ID: roimh chun ID meirge a chuardach."
COM_BANNERS_BANNERS_FILTER_SEARCH_LABEL="Cuardaigh Meirgí"
COM_BANNERS_BANNERS_HTML_PIN_BANNER="Meirge a phionáil"
COM_BANNERS_BANNERS_HTML_UNPIN_BANNER="Meirge a dhíphionáil"
COM_BANNERS_BANNERS_N_ITEMS_ARCHIVED="%d meirge cartlainne."
COM_BANNERS_BANNERS_N_ITEMS_ARCHIVED_1="Meirge cartlainne."
COM_BANNERS_BANNERS_N_ITEMS_CHECKED_IN_1="Meirge seiceáil isteach."
COM_BANNERS_BANNERS_N_ITEMS_CHECKED_IN_MORE="%d meirge seiceáil isteach."
COM_BANNERS_BANNERS_N_ITEMS_DELETED="%d meirge scriosta."
COM_BANNERS_BANNERS_N_ITEMS_DELETED_1="Meirge scriosta."
COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED="%d meirge foilsithe."
COM_BANNERS_BANNERS_N_ITEMS_PUBLISHED_1="Meirge foilsithe."
COM_BANNERS_BANNERS_N_ITEMS_TRASHED="%d meirge bruscair."
COM_BANNERS_BANNERS_N_ITEMS_TRASHED_1="Meirge bruscair."
COM_BANNERS_BANNERS_N_ITEMS_UNPUBLISHED="%d meirge neamhfhoilsithe."
COM_BANNERS_BANNERS_N_ITEMS_UNPUBLISHED_1="Meirge neamhfhoilsithe."
COM_BANNERS_BANNERS_NO_ITEM_SELECTED="Gan Meirgí roghnaithe."
COM_BANNERS_BANNERS_PINNED="Meirge Pionáilte"
COM_BANNERS_BANNERS_TABLE_CAPTION="Meirgí"
COM_BANNERS_BANNERS_UNPINNED="Meirge Díphionáilte"
COM_BANNERS_BATCH_CLIENT_LABEL="Socraigh Cliant"
COM_BANNERS_BATCH_CLIENT_NOCHANGE="- Coinnigh an Cliant bunaidh -"
COM_BANNERS_BATCH_OPTIONS="Próiseáil bhaisc na meirgí roghnaithe"
COM_BANNERS_BATCH_TIP="Má roghnaítear catagóir le haghaidh bogadh/cóipeáil, cuirfear aon ghníomhartha roghnaithe i bhfeidhm ar na meirgí cóipeáilte nó bogtha. Seachas sin, cuirfear gach gníomh i bhfeidhm ar na meirgí roghnaithe."
COM_BANNERS_BEGIN_HINT="Dáta tosaigh (yyyy-mm-dd)"
COM_BANNERS_BEGIN_LABEL="Dáta Tosaigh"
COM_BANNERS_CANCEL="Cealaigh"
COM_BANNERS_CLICK="Cliceáil"
COM_BANNERS_CLIENT_EDIT="Eagar Cliant"
COM_BANNERS_CLIENT_EMPTYSTATE_BUTTON_ADD="Cuir do chéad chliant leis"
COM_BANNERS_CLIENT_EMPTYSTATE_CONTENT="Tá sonraí teagmhála agus tuilleadh faisnéise i gCliant Meirge mar roghanna rianaithe."
COM_BANNERS_CLIENT_EMPTYSTATE_TITLE="Níl aon Chliant cruthaithe go fóill."
COM_BANNERS_CLIENT_NEW="Cliant Nua"
COM_BANNERS_CLIENT_SAVE_SUCCESS="Cliant sábháilte."
COM_BANNERS_CLIENTS_FILTER_SEARCH_DESC="Cuardaigh i ainm an chliaint. Cuir ID: roimh chun ID cliaint a chuardach."
COM_BANNERS_CLIENTS_FILTER_SEARCH_LABEL="Cuardaigh Cliant"
COM_BANNERS_CLIENTS_N_ITEMS_ARCHIVED="%d cliant cartlainne."
COM_BANNERS_CLIENTS_N_ITEMS_ARCHIVED_1="Cliant cartlainne."
COM_BANNERS_CLIENTS_N_ITEMS_CHECKED_IN_1="Cliant seiceáil isteach."
COM_BANNERS_CLIENTS_N_ITEMS_CHECKED_IN_MORE="%d cliant seiceáil isteach."
COM_BANNERS_CLIENTS_N_ITEMS_DELETED="%d cliant scriosta."
COM_BANNERS_CLIENTS_N_ITEMS_DELETED_1="Cliant scriosta."
COM_BANNERS_CLIENTS_N_ITEMS_PUBLISHED="%d cliant foilsithe."
COM_BANNERS_CLIENTS_N_ITEMS_PUBLISHED_1="Cliant foilsithe."
COM_BANNERS_CLIENTS_N_ITEMS_TRASHED="%d cliant bruscair."
COM_BANNERS_CLIENTS_N_ITEMS_TRASHED_1="Cliant bruscair."
COM_BANNERS_CLIENTS_N_ITEMS_UNPUBLISHED="%d cliant neamhfhoilsithe."
COM_BANNERS_CLIENTS_N_ITEMS_UNPUBLISHED_1="Cliant neamhfhoilsithe."
COM_BANNERS_CLIENTS_NO_ITEM_SELECTED="Gan cliant roghnaithe."
COM_BANNERS_CLIENTS_TABLE_CAPTION="Cliant"
COM_BANNERS_CONFIGURATION="Meirgí: Roghanna"
COM_BANNERS_COUNT_ARCHIVED_ITEMS="Míreanna Cartlainne"
COM_BANNERS_COUNT_PUBLISHED_ITEMS="Míreanna Foilsithe"
COM_BANNERS_COUNT_TRASHED_ITEMS="Míreanna Bruscair"
COM_BANNERS_COUNT_UNPUBLISHED_ITEMS="Míreanna Neamhfhoilsithe"
COM_BANNERS_DEFAULT="Réamhshocrú (%s)"
COM_BANNERS_DELETE_MSG="An bhfuil tú cinnte gur mhaith leat na rianta seo go léir a scriosadh?"
COM_BANNERS_EDIT_CLIENT="Sonraí"
COM_BANNERS_EMPTYSTATE_BUTTON_ADD="Cuir do chéad meirgí leis"
COM_BANNERS_EMPTYSTATE_CONTENT="Is bloic ábhair iad meirgí ina bhfuil faisnéis fógraíochta agus coinnítear taifead ar líon na n-uaireanta a taispeánadh an meirgí. Is féidir leat an comhpháirt seo a úsáid chun do mheirgí a chruthú agus a bhainistiú."
COM_BANNERS_EMPTYSTATE_TITLE="Níor cruthaíodh Meirgí fós."
COM_BANNERS_END_HINT="Dáta deiridh (yyyy-mm-dd)"
COM_BANNERS_END_LABEL="Dáta Deiridh"
COM_BANNERS_ERR_ZIP_ADAPTER_FAILURE="Teip oiriúnaitheora Zip"
COM_BANNERS_ERR_ZIP_CREATE_FAILURE="Teip cruthaithe Zip"
COM_BANNERS_ERR_ZIP_DELETE_FAILURE="Teip scriosta Zip"
COM_BANNERS_ERROR_UNIQUE_ALIAS="Tá an t-ailias céanna ag Meirgí eile ón gcatagóir seo (cuimhnigh gur féidir gur mír truflais é)."
COM_BANNERS_EXTRA="Faisnéis Bhreise"
COM_BANNERS_FIELD_ALT_LABEL="Téacs Alt"
COM_BANNERS_FIELD_BANNEROWNPREFIX_LABEL="Úsáid Réimír Féin"
COM_BANNERS_FIELD_BASENAME_DESC="Patrún ainm comhaid ar féidir leis a bheith<br>__SITE__ don ainm láithreáin<br>__CATID__ don ID catagóire<br>__CATNAME__ don ainm catagóire<br>__CLIENTID__ don ID cliaint<br>__CLIENTNAME__ don ainm cliaint<br>__TYPE__ don cineál<br>__TYPENAME__ don ainm cineál<br>__BEGIN__ don dáta tosaigh<br>__END__ don dáta deiridh."
COM_BANNERS_FIELD_BASENAME_LABEL="Ainm Comhaid"
COM_BANNERS_FIELD_CLICKS_LABEL="Cliceanna Iomlána"
COM_BANNERS_FIELD_CLICKURL_LABEL="URL Cliceáil"
COM_BANNERS_FIELD_CLIENT_LABEL="Cliaint"
COM_BANNERS_FIELD_CLIENT_METAKEYWORDPREFIX_DESC="Agus Eochairfhocail á gcomhoiriúnú, cuardaigh ach Eochairfhocail leis an réimír seo (feabhsaíonn feidhmíocht)."
COM_BANNERS_FIELD_CLIENT_METAKEYWORDPREFIX_LABEL="Réimír Eochairfhocail"
COM_BANNERS_FIELD_CLIENTOWNPREFIX_LABEL="Úsáid Réimír Féin"
COM_BANNERS_FIELD_COMPRESSED_LABEL="Comhbhrúite"
COM_BANNERS_FIELD_CONTACT_LABEL="Ainm Teagmhála"
COM_BANNERS_FIELD_CREATED_BY_ALIAS_LABEL="Cruthaithe ag Ailias"
COM_BANNERS_FIELD_CREATED_BY_LABEL="Cruthaithe ag"
COM_BANNERS_FIELD_CREATED_LABEL="Dáta Cruthaithe"
COM_BANNERS_FIELD_CUSTOMCODE_LABEL="Cód Saincheaptha"
COM_BANNERS_FIELD_EMAIL_LABEL="Ríomhphost Teagmhála"
COM_BANNERS_FIELD_EXTRAINFO_LABEL="Faisnéis Bhreise"
COM_BANNERS_FIELD_HEIGHT_LABEL="Airde"
COM_BANNERS_FIELD_IMAGE_LABEL="Íomhá"
COM_BANNERS_FIELD_IMPMADE_LABEL="Imprisean Iomlána"
COM_BANNERS_FIELD_IMPTOTAL_LABEL="Uas. Imprisean"
COM_BANNERS_FIELD_METAKEYWORDPREFIX_DESC="Agus Eochairfhocail á gcomhoiriúnú, cuardaigh ach Eochairfhocail leis an réimír seo (feabhsaíonn feidhmíocht)."
COM_BANNERS_FIELD_METAKEYWORDPREFIX_LABEL="Réimír Eochairfhocail"
COM_BANNERS_FIELD_NAME_LABEL="Ainm"
COM_BANNERS_FIELD_PUBLISH_DOWN_LABEL="Críochnaigh Foilsiú"
COM_BANNERS_FIELD_PUBLISH_UP_LABEL="Tosaigh Foilsiú"
COM_BANNERS_FIELD_PURCHASETYPE_LABEL="Cineál Ceannaigh"
COM_BANNERS_FIELD_STICKY_DESC="Má tá ceann nó níos mó Meirgí i gCatagóir bioraithe, tabharfar tosaíocht dóibh thar Meirgí nach bhfuil bioraithe. Mar shampla, má tá dhá Mheirgí i gCatagóir bioraithe agus nach bhfuil tríú Meirgí bioraithe, ní thaispeánfar an tríú Meirgí má tá an socrú modúl 'Bioraithe, Randamach'. Ní thaispeánfar ach an dá Mheirgí bioraithe."
COM_BANNERS_FIELD_STICKY_LABEL="Bioraithe"
COM_BANNERS_FIELD_TRACKCLICK_LABEL="Rianaigh Cliceanna"
COM_BANNERS_FIELD_TRACKIMPRESSION_LABEL="Rianaigh Imprisean"
COM_BANNERS_FIELD_TRACKROBOTSIMPRESSION_LABEL="Cuir imprisean ó Inneall Cuardaigh san áireamh"
COM_BANNERS_FIELD_TYPE_LABEL="Cineál"
COM_BANNERS_FIELD_VALUE_CUSTOM="Saincheaptha"
COM_BANNERS_FIELD_VALUE_DAILY="Laethúil"
COM_BANNERS_FIELD_VALUE_IMAGE="Íomhá"
COM_BANNERS_FIELD_VALUE_MONTHLY="Míosúil"
COM_BANNERS_FIELD_VALUE_UNLIMITED="Neamhtheoranta"
COM_BANNERS_FIELD_VALUE_USECLIENTDEFAULT="- Úsáid Réamhshocrú an Chliaint -"
COM_BANNERS_FIELD_VALUE_WEEKLY="Seachtainiúil"
COM_BANNERS_FIELD_VALUE_YEARLY="Bliantúil"
COM_BANNERS_FIELD_VERSION_LABEL="Athbhreithniú"
COM_BANNERS_FIELD_WIDTH_LABEL="Leithead"
COM_BANNERS_FIELDSET_CONFIG_BANNER_OPTIONS_DESC="Baineann na socruithe seo le stair leaganacha do Bhratacha, Catagóirí Bratacha agus Cliaint Bratacha."
COM_BANNERS_FIELDSET_CONFIG_BANNER_OPTIONS_LABEL="Stair"
COM_BANNERS_FIELDSET_CONFIG_CLIENT_OPTIONS_DESC="Baineann na socruithe seo le gach cliant mura n-athraítear iad do chliant ar leith."
COM_BANNERS_FIELDSET_CONFIG_CLIENT_OPTIONS_LABEL="Cliant"
COM_BANNERS_GROUP_LABEL_BANNER_DETAILS="Sonraí Bratacha"
COM_BANNERS_GROUP_LABEL_PUBLISHING_DETAILS="Roghanna Foilsitheoireachta"
COM_BANNERS_HEADING_ACTIVE="Gníomhach"
COM_BANNERS_HEADING_BANNERS="Bratacha"
COM_BANNERS_HEADING_BANNERS_ASC="Bratacha ag ardú"
COM_BANNERS_HEADING_BANNERS_DESC="Bratacha ag ísliú"
COM_BANNERS_HEADING_CLICKS="Cliceanna"
COM_BANNERS_HEADING_CLICKS_ASC="Cliceanna ag ardú"
COM_BANNERS_HEADING_CLICKS_DESC="Cliceanna ag ísliú"
COM_BANNERS_HEADING_CLIENT="Cliant"
COM_BANNERS_HEADING_CLIENT_ASC="Cliant ag ardú"
COM_BANNERS_HEADING_CLIENT_DESC="Cliant ag ísliú"
COM_BANNERS_HEADING_CONTACT="Teagmháil"
COM_BANNERS_HEADING_CONTACT_ASC="Teagmháil ag ardú"
COM_BANNERS_HEADING_CONTACT_DESC="Teagmháil ag ísliú"
COM_BANNERS_HEADING_COUNT="Líon"
COM_BANNERS_HEADING_COUNT_ASC="Líon ag ardú"
COM_BANNERS_HEADING_COUNT_DESC="Líon ag ísliú"
COM_BANNERS_HEADING_IMPRESSIONS="Imprisean"
COM_BANNERS_HEADING_IMPRESSIONS_ASC="Imprisean ag ardú"
COM_BANNERS_HEADING_IMPRESSIONS_DESC="Imprisean ag ísliú"
COM_BANNERS_HEADING_NAME="Ainm"
COM_BANNERS_HEADING_PURCHASETYPE="Cineál Ceannaigh"
COM_BANNERS_HEADING_PURCHASETYPE_ASC="Cineál Ceannaigh ag ardú"
COM_BANNERS_HEADING_PURCHASETYPE_DESC="Cineál Ceannaigh ag ísliú"
COM_BANNERS_HEADING_STICKY="Greamaithe"
COM_BANNERS_HEADING_STICKY_ASC="Greamaithe ag ardú"
COM_BANNERS_HEADING_STICKY_DESC="Greamaithe ag ísliú"
COM_BANNERS_HEADING_TYPE="Cineál"
COM_BANNERS_HEADING_TYPE_ASC="Cineál ag ardú"
COM_BANNERS_HEADING_TYPE_DESC="Cineál ag ísliú"
COM_BANNERS_IMPRESSION="Imprisean"
COM_BANNERS_IMPRESSIONS="%1$s de %2$s"
COM_BANNERS_MANAGER_BANNER_EDIT="Bratacha: Cuir in Eagar"
COM_BANNERS_MANAGER_BANNER_NEW="Bratacha: Nua"
COM_BANNERS_MANAGER_BANNERS="Bratacha"
COM_BANNERS_MANAGER_CLIENT_EDIT="Bratacha: Cuir Cliant in Eagar"
COM_BANNERS_MANAGER_CLIENT_NEW="Bratacha: Cliant Nua"
COM_BANNERS_MANAGER_CLIENTS="Bratacha: Cliaint"
COM_BANNERS_MANAGER_TRACKS="Bratacha: Riananna"
COM_BANNERS_N_BANNERS_STUCK="%d bratacha greamaithe."
COM_BANNERS_N_BANNERS_STUCK_1="Bratach greamaithe."
COM_BANNERS_N_BANNERS_UNSTUCK="%d bratacha díghreamaithe."
COM_BANNERS_N_BANNERS_UNSTUCK_1="Bratach díghreamaithe."
COM_BANNERS_N_QUICKICON="Bratacha"
COM_BANNERS_N_QUICKICON_1="Bratach"
COM_BANNERS_N_QUICKICON_SRONLY="Bratacha: Tá %d bratacha foilsithe."
COM_BANNERS_N_QUICKICON_SRONLY_1="Bratacha: Tá bratach amháin foilsithe."
COM_BANNERS_NEW_BANNER="Bratach Nua"
COM_BANNERS_NEW_CLIENT="Cliant Nua"
COM_BANNERS_NO_BANNERS_SELECTED="Níl aon bhratacha roghnaithe."
COM_BANNERS_NO_CLIENT="- Níl aon chliant -"
COM_BANNERS_NOCATEGORYNAME="Gan chatagóir"
COM_BANNERS_NOCLIENTNAME="Gan chliant"
COM_BANNERS_PROVIDE_VALID_CONTACT="Tabhair ainm teagmhála bailí, neamhfholamh le do thoil"
COM_BANNERS_SEARCH_IN_TITLE="Cuardaigh sa teideal"
COM_BANNERS_SELECT_CLIENT="- Roghnaigh Cliant -"
COM_BANNERS_SELECT_TYPE="- Roghnaigh Cineál -"
COM_BANNERS_SUBMENU_BANNERS="Meirgí"
COM_BANNERS_SUBMENU_CATEGORIES="Catagóirí"
COM_BANNERS_SUBMENU_CLIENTS="Cliaint"
COM_BANNERS_SUBMENU_TRACKS="Rianta"
COM_BANNERS_TRACKS_DELETE="Scrios Rianta"
COM_BANNERS_TRACKS_DOWNLOAD="Íoslódáil rianta"
COM_BANNERS_TRACKS_EMPTYSTATE_CONTENT="Anseo is féidir leat faisnéis rianaithe do do mheirgí a fheiceáil agus a easpórtáil má tá rianú cumasaithe don mbratach sin."
COM_BANNERS_TRACKS_EMPTYSTATE_TITLE="Níl Rianta ann fós."
COM_BANNERS_TRACKS_EXPORT="Easpórtáil"
COM_BANNERS_TRACKS_FILTER_SEARCH_DESC="Cuardaigh i ainm an rian agus ainm an chliaint rian."
COM_BANNERS_TRACKS_FILTER_SEARCH_LABEL="Cuardaigh Rianta"
COM_BANNERS_TRACKS_N_ITEMS_DELETED="%d rianta scriosta."
COM_BANNERS_TRACKS_N_ITEMS_DELETED_1="Rian scriosta."
COM_BANNERS_TRACKS_NO_ITEMS_DELETED="Níl aon rianta le scriosadh."
COM_BANNERS_TRACKS_TABLE_CAPTION="Rianta"
COM_BANNERS_TYPE1="Imprisean"
COM_BANNERS_TYPE2="Cliceanna"
COM_BANNERS_UNLIMITED="Neamhtheoranta"
COM_BANNERS_WARNING_PROVIDE_VALID_NAME="Tabhair ainm bailí, neamhfholamh le do thoil"
COM_BANNERS_XML_DESCRIPTION="Bainistíonn an comhpháirt seo meirgí agus cliaint meirgí."

JLIB_RULES_SETTING_NOTES_COM_BANNERS="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus a bhaineann le gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas an chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
