; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS="Turas Treoraithe"
COM_GUIDEDTOURS_AUTOSTART_DESC="Tosaigh an turas go huathoibríoch nuair a shroicheann úsáideoir an comhthéacs ina cheart an turas a thaispeáint."
COM_GUIDEDTOURS_AUTOSTART_LABEL="Tosú Uathoibríoch"
COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_DESCRIPTION="An méid ama (i nóiméid) a chuirtear moill ar thuras tar éis é a bheith curtha ar ceal ag an úsáideoir agus go dtí go dtaispeántar arís é (ach amháin nuair a bhíonn turas socraithe chun tosú go huathoibríoch).<br>Mar shampla, cuir isteach 60 le haghaidh 1 uair an chloig, 1440 le haghaidh 24 uair an chloig, 10080 le haghaidh 1 seachtain."
COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_LABEL="Moill Ama Tosaithe Uathoibríoch (i nóiméid)"
COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_DESCRIPTION="Cas ar nó as an bhfeidhmiúlacht tosaithe uathoibríoch do thurais."
COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_LABEL="Ceadaigh Turais Tosaithe Uathoibríoch"
COM_GUIDEDTOURS_CONFIGURATION="Turas Treoraithe: Roghanna"
COM_GUIDEDTOURS_DESCRIPTION="Cur Síos"
COM_GUIDEDTOURS_DESCRIPTION_TRANSLATION="Cur Síos (%s)"
COM_GUIDEDTOURS_EDIT_TOUR="Eagar Turas"
COM_GUIDEDTOURS_ERROR_NO_GUIDEDTOURS_SELECTED="Níl aon turas roghnaithe."
COM_GUIDEDTOURS_EXTENSIONS_DESC="Teorannaigh an turas le taispeáint ach amháin nuair a bhíonn an comhpháirt roghnaithe gníomhach."
COM_GUIDEDTOURS_EXTENSIONS_LABEL="Roghnóir Comhpháirte"
COM_GUIDEDTOURS_FIELD_NOTE_LABEL="Nóta"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_BUTTON="Cnaipe"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_CHECKBOX_RADIO_FIELD="Bosca Seiceála/Raideó"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_FORM_SUBMIT="Foirm a Chur Isteach"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_OTHER="Eile"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_SELECT_LIST="Liosta Roghnaithe"
COM_GUIDEDTOURS_FIELD_VALUE_INTERACTIVESTEP_TYPE_TEXT_FIELD="Réimse Téacs"
COM_GUIDEDTOURS_FIELD_VALUE_STEP_TYPE_INTERACTIVE="Idirghníomhach"
COM_GUIDEDTOURS_FIELD_VALUE_STEP_TYPE_NEXT="Ar Aghaidh"
COM_GUIDEDTOURS_FIELD_VALUE_STEP_TYPE_REDIRECT="Athsheoladh"
COM_GUIDEDTOURS_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus i nóta. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID turais nó DESCRIPTION: chun cuardach a dhéanamh i gcur síos."
COM_GUIDEDTOURS_FILTER_SEARCH_LABEL="Cuardaigh Turais"
COM_GUIDEDTOURS_GUIDEDTOURS_TABLE_CAPTION="Turais"
COM_GUIDEDTOURS_MANAGER_STEP_EDIT="Turas Treoraithe: Eagar Céim"
COM_GUIDEDTOURS_MANAGER_STEP_NEW="Turas Treoraithe: Céim Nua"
COM_GUIDEDTOURS_MANAGER_TOUR_EDIT="Turas Treoraithe: Eagar Turas"
COM_GUIDEDTOURS_MANAGER_TOUR_NEW="Turas Treoraithe: Turas Nua"
COM_GUIDEDTOURS_N_ITEMS_ARCHIVED_1="Mír cartlannaithe."
COM_GUIDEDTOURS_N_ITEMS_ARCHIVED="%d míreanna cartlannaithe."
COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_1="Mír seiceáilte isteach."
COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_MORE="%d míreanna seiceáilte isteach."
COM_GUIDEDTOURS_N_ITEMS_DELETED_1="Mír scriosta."
COM_GUIDEDTOURS_N_ITEMS_DELETED="%d míreanna scriosta."
COM_GUIDEDTOURS_N_ITEMS_PUBLISHED_1="Mír foilsithe."
COM_GUIDEDTOURS_N_ITEMS_PUBLISHED="%d míreanna foilsithe."
COM_GUIDEDTOURS_N_ITEMS_TRASHED_1="Mír bruscair."
COM_GUIDEDTOURS_N_ITEMS_TRASHED="%d míreanna bruscair."
COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED_1="Mír neamhfhoilsithe."
COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED="%d míreanna neamhfhoilsithe."
COM_GUIDEDTOURS_NEW_TOUR="Turas Nua"
COM_GUIDEDTOURS_ORDER_TYPE_ASC="Cineál ag ardú"
COM_GUIDEDTOURS_ORDER_TYPE_DESC="Cineál ag ísliú"
COM_GUIDEDTOURS_PLUGIN_DISABLED="Tá an Breiseán Córas Turais Treoraithe díchumasaithe. Ní thaispeánfar an modúl Turais Treoraithe mura bhfuil sé seo cumasaithe."
COM_GUIDEDTOURS_STEP_DESCRIPTION_TRANSLATION="Cur Síos (%s)"
COM_GUIDEDTOURS_STEP_EDIT_STEP="Eagar Céim"
COM_GUIDEDTOURS_STEP_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus i nóta. Réamhtheachtaigh le ID: chun cuardach a dhéanamh ar ID céime nó CUR SÍOS: chun cuardach a dhéanamh sa chur síos."
COM_GUIDEDTOURS_STEP_FILTER_SEARCH_LABEL="Cuardaigh Céimeanna"
COM_GUIDEDTOURS_STEP_NEW_STEP="Céim Nua"
COM_GUIDEDTOURS_STEP_POSITION_DESC="Roghnaigh suíomh an phreabfhuinneog céime, i gcoibhneas leis an eilimint a léiríonn sé."
COM_GUIDEDTOURS_STEP_POSITION_LABEL="Suíomh"
COM_GUIDEDTOURS_STEP_TARGETNOTE_MESSAGE="Nuair a aithnítear céim mar idirghníomhach, d'fhéadfadh roghanna idirghníomhacha ar leith paraiméadair bhreise a iompar le haghaidh idirghníomhaíocht an úsáideora le sprioc."
COM_GUIDEDTOURS_STEP_TARGETVALUES_HEADING="Roghanna Luach Sprioc"
COM_GUIDEDTOURS_STEP_TITLE="Teideal"
COM_GUIDEDTOURS_STEP_TITLE_TRANSLATION="Teideal (%s)"
COM_GUIDEDTOURS_STEP_TARGET_DESC="An eilimint sprioc a ghabhfaidh an chéim leis. Roghanna: .classname, #id, aon roghnóir de réir shintéis CSS (déan cinnte gur eilimint fócasach í má tá an chéim idirghníomhach), nó fág bán í le haghaidh céim lárnaithe."
COM_GUIDEDTOURS_STEP_TARGET_LABEL="Sprioc"
COM_GUIDEDTOURS_STEP_TYPE="Cineál"
COM_GUIDEDTOURS_STEP_TYPE_LABEL="Cineál"
COM_GUIDEDTOURS_STEP_TYPE_DESC="Roghnaigh <em>Ar Aghaidh</em> le haghaidh siúlóide, <em>Athdhíriú</em> chun athdhíriú chuig leathanach eile, nó <em>Idirghníomhach</em> chun ligean d'úsáideoir idirghníomhú."
COM_GUIDEDTOURS_STEPS="Céimeanna"
COM_GUIDEDTOURS_STEPS_EMPTYSTATE_CONTENT="Ní féidir le turas a bheith feidhmiúil ach amháin má chruthaítear céimeanna."
COM_GUIDEDTOURS_STEPS_EMPTYSTATE_TITLE="Níor cruthaíodh céimeanna don turas seo fós."
COM_GUIDEDTOURS_STEPS_EMPTYSTATE_BUTTON_ADD="Cuir do chéad chéim leis"
COM_GUIDEDTOURS_STEPS_LIST="Turas Treoraithe: %s"
COM_GUIDEDTOURS_STEPS_TABLE_CAPTION="Céimeanna"
COM_GUIDEDTOURS_STEPS_UNKNOWN_TOUR="ID Turas in easnamh"
COM_GUIDEDTOURS_TITLE="Teideal"
COM_GUIDEDTOURS_TITLE_TRANSLATION="Teideal (%s)"
COM_GUIDEDTOURS_TOUR_UID_LABEL="Aitheantóir Turas"
COM_GUIDEDTOURS_TOUR_UID_DESC="Ní mór don Aitheantóir Turas a bheith uathúil.<br>Moltaimid formáid mar ainmúdair-ainmturas, ainmchuideachta-ainmturas, nó fearannsuíomh-ainmturas.<br>Mura gcuirtear aitheantóir ar fáil, ríomhfar luach duit."
COM_GUIDEDTOURS_TOUR_UID_HINT="Aitheantóir uathúil m.sh. údar-suíomh-fearann-ainm-turas"
COM_GUIDEDTOURS_TOURS_DUPLICATED="%d turas dúbláilte."
COM_GUIDEDTOURS_TOURS_DUPLICATED_1="Turas dúbláilte."
COM_GUIDEDTOURS_TOURS_LIST="Turas Treoraithe"
COM_GUIDEDTOURS_TOURS_LIST_EMPTYSTATE_BUTTON_ADD="Cuir do chéad turas leis"
COM_GUIDEDTOURS_TOURS_LIST_EMPTYSTATE_CONTENT="Cruthaigh turas chun é a dhéanamh feidhmiúil."
COM_GUIDEDTOURS_TOURS_LIST_EMPTYSTATE_TITLE="Níor cruthaíodh turais fós."
COM_GUIDEDTOURS_TYPE_INPUT_REQUIRED_DESC="Cumasaigh má theastaíonn ar an úsáideoir luach a sholáthar, cnaipe raidió a ghníomhachtú nó bosca a sheiceáil chun dul ar aghaidh go dtí an chéad chéim eile den turas."
COM_GUIDEDTOURS_TYPE_INPUT_REQUIRED_LABEL="Riachtanach"
COM_GUIDEDTOURS_TYPE_INPUT_REQUIREDVALUE_DESC="An luach cruinn atá le cur isteach, lena n-áirítear cás agus poncaíocht, chun dul ar aghaidh go dtí an chéad chéim eile (má tá an sprioc ina liosta míreanna, bain úsáid as luach eilimint rogha an roghnóra)."
COM_GUIDEDTOURS_TYPE_INPUT_REQUIREDVALUE_LABEL="Luach Riachtanach"
COM_GUIDEDTOURS_TYPE_INTERACTIVE_STEP_DESC="Roghnaigh <em>Foirm a Chur Isteach</em> chun foirm a chur isteach, <em>Réimse Téacs</em> le haghaidh ionchur úsáideora, <em>Cnaipe</em> le haghaidh cnaipí, <em>Bosca Seiceála/Raidió</em> nó <em>Roghnaigh Liosta</em> le haghaidh roghnú, nó <em>Eile</em> le haghaidh aon idirghníomhaíocht eile."
COM_GUIDEDTOURS_TYPE_INTERACTIVE_STEP_LABEL="Cineál Idirghníomhach"
COM_GUIDEDTOURS_TYPE_REDIRECT_URL_DESC="Iontráil URL coibhneasta an leathanaigh ar mhaith leat go ndíreodh an chéim air, m.sh. administrator/index.php?option=com_guidedtours&view=tours don leathanach liosta turas."
COM_GUIDEDTOURS_TYPE_REDIRECT_URL_LABEL="URL Coibhneasta"
COM_GUIDEDTOURS_URL_LABEL="URL Coibhneasta"
COM_GUIDEDTOURS_URL_DESC="Iontráil URL coibhneasta an leathanaigh ón áit ar mhaith leat an turas a thosú, m.sh. administrator/index.php?option=com_guidedtours&view=tours don leathanach liosta turas."
COM_GUIDEDTOURS_USERSTATE_BADTOURID="Ní mór don Turas aitheantas dearfach a bheith aige."
; 'Tour User states' are conditions in which a guided tour user leaves a tour, either by cancelling, completing or skipping a tour.
COM_GUIDEDTOURS_USERSTATE_CONNECTEDONLY="Níl taifeadadh ar Stáit Úsáideora do thuras ar fáil ach d’úsáideoirí atá logáilte isteach."
COM_GUIDEDTOURS_USERSTATE_STATENOTSAVED="Níor sábháladh Stát Úsáideora d’úsáideoir %1$s turas %2$s."
COM_GUIDEDTOURS_USERSTATE_STATESAVED="Sábháladh Stát Úsáideora d’úsáideoir %1$s turas %2$s."
COM_GUIDEDTOURS_USERSTATE_WRONGCONTEXT="Tá comhthéacs Stát Úsáideora an Turais mícheart."
COM_GUIDEDTOURS_XML_DESCRIPTION="Comhpháirt chun feidhmiúlacht Turas Treoraithe a bhainistiú."
