; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_TEMPLATES="Teimpléid"
COM_TEMPLATES_ARE_YOU_SURE="An bhfuil tú cinnte?"
COM_TEMPLATES_ASSIGNED_1="Sannaithe do mhír roghchláir amháin."
COM_TEMPLATES_ASSIGNED_MORE="Sannaithe do %d míreanna roghchláir."
COM_TEMPLATES_BUTTON_CHECK="Seiceáil Forluí"
COM_TEMPLATES_BUTTON_CHECK_LIST_ENTRY="Marcáilte Seiceáilte"
COM_TEMPLATES_BUTTON_CLOSE_FILE="Dún"
COM_TEMPLATES_BUTTON_COPY_FILE="Cóipeáil Comhad"
COM_TEMPLATES_BUTTON_COPY_TEMPLATE="Cóipeáil Teimpléad"
COM_TEMPLATES_BUTTON_CREATE="Cruthaigh"
COM_TEMPLATES_BUTTON_CROP="Bain"
COM_TEMPLATES_BUTTON_DELETE="Scrios"
COM_TEMPLATES_BUTTON_DELETE_FILE="Scrios Comhad"
COM_TEMPLATES_BUTTON_DELETE_LIST_ENTRY="Bain Taifead"
COM_TEMPLATES_BUTTON_EXTRACT_ARCHIVE="Bain As Seo"
COM_TEMPLATES_BUTTON_FILE="Comhad Nua"
COM_TEMPLATES_BUTTON_FOLDERS="Bainistigh Fillteáin"
COM_TEMPLATES_BUTTON_PREVIEW="Réamhamharc Teimpléid"
COM_TEMPLATES_BUTTON_RENAME="Athainmnigh"
COM_TEMPLATES_BUTTON_RENAME_FILE="Athainmnigh Comhad"
COM_TEMPLATES_BUTTON_RESIZE="Athraigh Méid"
COM_TEMPLATES_BUTTON_TEMPLATE_CHILD="Cruthaigh Teimpléad Leanbh"
COM_TEMPLATES_BUTTON_UNCHECK_LIST_ENTRY="Marcáilte Neamhseiceáilte"
COM_TEMPLATES_BUTTON_UPLOAD="Uaslódáil"
COM_TEMPLATES_CHECK_FILE_OWNERSHIP="Seiceáil úinéireacht comhaid"
COM_TEMPLATES_CHILD_SUCCESS="Cruthaíodh teimpléad leanbh."
COM_TEMPLATES_CLICK_TO_ENLARGE="Roghnaigh chun méadú."
COM_TEMPLATES_COMPILE_ERROR="Tharla earráid. Theip ar an tiomsú."
COM_TEMPLATES_COMPILE_LESS="Ba chóir duit %s a thiomsú chun comhad CSS a ghiniúint."
COM_TEMPLATES_CONFIGURATION="Teimpléad: Roghanna"
COM_TEMPLATES_CONFIG_FIELDSET_DESC="Cumraíocht dhomhanda do theimpléid."
COM_TEMPLATES_CONFIG_FONT_LABEL="Formáidí Cló Bailí"
COM_TEMPLATES_CONFIG_IMAGE_LABEL="Formáidí Íomhá Bailí"
COM_TEMPLATES_CONFIG_POSITIONS_LABEL="Réamhamharc ar Phoist Mhodúl"
COM_TEMPLATES_CONFIG_SOURCE_LABEL="Formáidí Foinse Bailí"
COM_TEMPLATES_CONFIG_UPLOAD_LABEL="Uasmhéid Uaslódála (MB)"
COM_TEMPLATES_COPY_CHILD_TEMPLATE_STYLES="%s, cóip de %s"
COM_TEMPLATES_COPY_SUCCESS="Suiteáladh teimpléad nua darb ainm %s."
COM_TEMPLATES_CROP_AREA_ERROR="Níor roghnaíodh limistéar bainte."
COM_TEMPLATES_DIFF_CORE="Bunaidh"
COM_TEMPLATES_DIFF_DIFFERENCES="Difríochtaí"
COM_TEMPLATES_DIFF_IDENTICAL="Tá an dá chomhad comhionann."
COM_TEMPLATES_DIFF_OPTIONS="Taispeáin Difríocht Comhad"
COM_TEMPLATES_DIFF_OPTIONS_INLINE="Inlíne"
COM_TEMPLATES_DIFF_OPTIONS_SIDE="Taobh-le-Taobh"
COM_TEMPLATES_DIFF_OVERRIDE="Forluí"
COM_TEMPLATES_DIRECTORY_NOT_WRITABLE="Níl an fillteán teimpléid inrite. B'fhéidir nach n-oibreoidh roinnt gnéithe."
COM_TEMPLATES_ERROR_ASSET_FILE_DELETE="Ní féidir an comhad joomla.asset.json a scriosadh. Déan athruithe san eagarthóir más mian leat an comhad a athrú."
COM_TEMPLATES_ERROR_ASSET_FILE_INVALID_JSON="Níl JSON bailí sa chomhad joomla.asset.json, ag cealú sábhála."
COM_TEMPLATES_ERROR_CANNOT_DELETE_LAST_STYLE="Ní féidir an stíl dheireanach de theimpléad a scriosadh. Arbh é do rún an teimpléad a <a href=\"index.php?option=com_installer&view=manage&filter[type]=template\" class=\"alert-link\">dhíshuiteáil</a>?"
COM_TEMPLATES_ERROR_CANNOT_UNSET_DEFAULT_STYLE="Ní féidir stíl réamhshocraithe a dhíshocrú."
COM_TEMPLATES_ERROR_COULD_NOT_COPY="Ní féidir comhaid teimpléid a chóipeáil chuig fillteán sealadach."
COM_TEMPLATES_ERROR_COULD_NOT_INSTALL="Ní féidir teimpléad nua a shuiteáil ón bhfillteán sealadach."
COM_TEMPLATES_ERROR_COULD_NOT_WRITE="Ní féidir an fillteán sealadach a scriosadh."
COM_TEMPLATES_ERROR_CREATE_NOT_PERMITTED="Ní féidir fillteán sealadach a chruthú."
COM_TEMPLATES_ERROR_DUPLICATE_TEMPLATE_NAME="Tá teimpléad leis an ainm seo suiteáilte cheana féin."
COM_TEMPLATES_ERROR_EDITOR_DISABLED="Ba chóir go mbeadh an breiseán eagarthóra CodeMirror nó None cumasaithe chun comhaid teimpléid a chur in eagar."
COM_TEMPLATES_ERROR_EXECUTABLE="Ní féidir comhaid inrite a uaslódáil."
COM_TEMPLATES_ERROR_EXTENSION_RECORD_NOT_FOUND="Níor aimsíodh taifead síneadh sa bhunachar sonraí."
COM_TEMPLATES_ERROR_FAILED_TO_SAVE_FILENAME="Tharla earráid. Níorbh fhéidir an comhad %s a shábháil."
COM_TEMPLATES_ERROR_FILE_CREATE="Theip ar chruthú comhaid."
COM_TEMPLATES_ERROR_FILE_DELETE="Tharla earráid. Theip ar scriosadh an chomhaid."
COM_TEMPLATES_ERROR_FILE_FORMAT="Ní thacaítear le formáid comhaid."
COM_TEMPLATES_ERROR_FILE_RENAME="Tharla earráid. Theip ar athainmniú comhaid."
COM_TEMPLATES_ERROR_FILE_UPLOAD="Theip ar uaslódáil comhaid."
COM_TEMPLATES_ERROR_FOLDER_CREATE="Theip ar chruthú fillteáin."
COM_TEMPLATES_ERROR_FONT_FILE_NOT_FOUND="Níor aimsíodh comhad cló."
COM_TEMPLATES_ERROR_IMAGE_FILE_NOT_FOUND="Níor aimsíodh comhad íomhá."
COM_TEMPLATES_ERROR_INDEX_DELETE="Ní féidir an comhad index.php a scriosadh. Déan athruithe san eagarthóir más mian leat an comhad a athrú."
COM_TEMPLATES_ERROR_INVALID_FROM_NAME="Ní féidir an teimpléad le cóipeáil uaidh a aimsiú."
COM_TEMPLATES_ERROR_INVALID_TEMPLATE_NAME="Ainm teimpléid neamhbhailí. Bain úsáid as litreacha, uimhreacha agus fo-thrasnaithe amháin le do thoil."
COM_TEMPLATES_ERROR_NO_FILE_SELECTED="Níl aon chomhad roghnaithe."
COM_TEMPLATES_ERROR_RENAME_ASSET_FILE="Ní féidir an comhad joomla.asset.json a athainmniú."
COM_TEMPLATES_ERROR_RENAME_INDEX="Ní féidir an comhad index.php a athainmniú."
COM_TEMPLATES_ERROR_ROOT_DELETE="Ní féidir an fillteán fréimhe a scriosadh."
COM_TEMPLATES_ERROR_SAVE_DISABLED_TEMPLATE="Ní féidir stíl a shábháil atá bainteach le teimpléad díchumasaithe."
COM_TEMPLATES_ERROR_SOURCE_FILE_NOT_FOUND="Níor aimsíodh comhad foinse."
COM_TEMPLATES_ERROR_SOURCE_FILE_NOT_UNWRITABLE="Ní féidir an comhad foinse a chur ar ais go stádas neamh-in-scríofa."
COM_TEMPLATES_ERROR_SOURCE_FILE_NOT_WRITABLE="Ní féidir comhad foinse a scríobh."
COM_TEMPLATES_ERROR_SOURCE_ID_FILENAME_MISMATCH="Ní hionann an ID stóráilte agus an ceann a cuireadh isteach."
COM_TEMPLATES_ERROR_STYLE_NOT_FOUND="Níor aimsíodh stíl."
COM_TEMPLATES_ERROR_STYLE_REQUIRES_TITLE="Teastaíonn teideal ón stíl."
COM_TEMPLATES_ERROR_TEMPLATE_FOLDER_NOT_FOUND="Níor aimsíodh fillteán teimpléid."
COM_TEMPLATES_ERROR_UPLOAD_INPUT="Ní bhfuarthas aon chomhad."
COM_TEMPLATES_ERROR_WARNFILENAME="Ainm comhaid neamhbhailí. Ceartaigh ainm an chomhaid agus uaslódáil arís le do thoil."
COM_TEMPLATES_ERROR_WARNFILETOOLARGE="Tá an comhad seo ró-mhór le híoslódáil."
COM_TEMPLATES_ERROR_WARNFILETYPE="Ní thacaítear le formáid comhaid."
COM_TEMPLATES_ERROR_WARNIEXSS="Ní féidir a uaslódáil. Tá XSS ann."
COM_TEMPLATES_ERR_XML="Níl sonraí XML teimpléid ar fáil"
COM_TEMPLATES_FIELD_CLIENT_LABEL="Suíomh"
COM_TEMPLATES_FIELD_HOME_LABEL="Réamhshocrú"
COM_TEMPLATES_FIELD_SOURCE_LABEL="Cód Foinse"
COM_TEMPLATES_FIELD_TEMPLATE_LABEL="Teimpléad"
COM_TEMPLATES_FIELD_TITLE_LABEL="Ainm Stíle"
COM_TEMPLATES_FILE_ARCHIVE_EXISTS="Tá roinnt comhad leis an ainm céanna ann cheana."
COM_TEMPLATES_FILE_ARCHIVE_EXTRACT_FAIL="Theip ar eastóscadh an chomhaid cartlainne."
COM_TEMPLATES_FILE_ARCHIVE_EXTRACT_SUCCESS="Comhad cartlainne eastósctha."
COM_TEMPLATES_FILE_ARCHIVE_NOT_FOUND="Níor aimsíodh comhad cartlainne."
COM_TEMPLATES_FILE_ARCHIVE_OPEN_FAIL="Theip ar oscailt an chomhaid cartlainne."
COM_TEMPLATES_FILE_COMPARE_PANE="Difríocht idir comhad bunaidh agus comhad forghníomhaithe"
COM_TEMPLATES_FILE_CONTENT_PREVIEW="Réamhamharc Ábhar Comhaid"
COM_TEMPLATES_FILE_COPY_FAIL="Theip ar chóipeáil an chomhaid."
COM_TEMPLATES_FILE_COPY_SUCCESS="Cóipeáladh an comhad reatha mar %s."
COM_TEMPLATES_FILE_CORE_PANE="Comhad bunaidh (léamh amháin)"
COM_TEMPLATES_FILE_CREATE_ERROR="Tharla earráid agus an comhad á chruthú."
COM_TEMPLATES_FILE_CREATE_SUCCESS="Cruthaíodh comhad."
COM_TEMPLATES_FILE_CROP_ERROR="Theip ar an íomhá a bhearradh."
COM_TEMPLATES_FILE_CROP_SUCCESS="Íomhá bearrtha."
COM_TEMPLATES_FILE_DELETE_ERROR="Ní féidir an comhad a scriosadh."
COM_TEMPLATES_FILE_DELETE_SUCCESS="Comhad scriosta."
COM_TEMPLATES_FILE_EXISTS="Tá comhad leis an ainm céanna ann cheana."
COM_TEMPLATES_FILE_INFO="Eolas Comhaid"
COM_TEMPLATES_FILE_NAME="Ainm Comhaid"
COM_TEMPLATES_FILE_NEW_NAME_LABEL="Ainm Comhaid Cóipeáilte"
COM_TEMPLATES_FILE_OVERRIDE_PANE="Comhad forghabhála (in eagar)"
COM_TEMPLATES_FILE_PERMISSIONS="Tá na Ceadanna Comhaid %s"
COM_TEMPLATES_FILE_RENAME_ERROR="Tharla earráid agus an comhad á athainmniú."
COM_TEMPLATES_FILE_RENAME_SUCCESS="Comhad athainmnithe."
COM_TEMPLATES_FILE_RESIZE_ERROR="Theip ar an íomhá a athmhéadú."
COM_TEMPLATES_FILE_RESIZE_SUCCESS="Íomhá athmhéadaithe."
COM_TEMPLATES_FILE_SAVE_SUCCESS="Comhad sábháilte."
COM_TEMPLATES_FILE_UNSUPPORTED_ARCHIVE="Tá comhaid neamhthacaithe sa chomhad zip."
COM_TEMPLATES_FILE_UPLOAD_ERROR="Tharla earráid agus an comhad á uaslódáil."
COM_TEMPLATES_FILE_UPLOAD_SUCCESS="Comhad uaslódáilte: %s"
COM_TEMPLATES_FILTER_TEMPLATE="- Roghnaigh Teimpléad -"
COM_TEMPLATES_FOLDER_CREATE_ERROR="Tharla earráid agus an fillteán á chruthú."
COM_TEMPLATES_FOLDER_CREATE_SUCCESS="Cruthaíodh fillteán."
COM_TEMPLATES_FOLDER_DELETE_ERROR="Tharla earráid. Theip ar an bhfillteán a scriosadh."
COM_TEMPLATES_FOLDER_DELETE_SUCCESS="Fillteán scriosta."
COM_TEMPLATES_FOLDER_ERROR="Ní féidir fillteán a chruthú."
COM_TEMPLATES_FOLDER_EXISTS="Tá fillteán leis an ainm céanna ann cheana."
COM_TEMPLATES_FOLDER_NAME="Ainm Fillteáin"
COM_TEMPLATES_FOLDER_NOT_EXISTS="Níl an fillteán ann."
COM_TEMPLATES_GD_EXTENSION_NOT_AVAILABLE="Níl an síneadh GD do PHP ar fáil.<br>Chun íomhánna a láimhseáil, teastaíonn síneadh breise ar do fhreastalaí. Féach ar an <a href='https://downloads.joomla.org/technical-requirements' target='_blank' rel='noopener noreferrer'>Riachtanais Theicniúla Oifigiúla</a> do thuilleadh sonraí."
COM_TEMPLATES_GRID_UNSET_LANGUAGE="Díshocraigh %s Réamhshocrú"
COM_TEMPLATES_HEADING_ASSIGNED="Sannaithe"
COM_TEMPLATES_HEADING_DEFAULT="Réamhshocrú"
COM_TEMPLATES_HEADING_DEFAULT_ASC="Réamhshocrú ag ardú"
COM_TEMPLATES_HEADING_DEFAULT_DESC="Réamhshocrú ag ísliú"
COM_TEMPLATES_HEADING_IMAGE="Íomhá"
COM_TEMPLATES_HEADING_PAGES="Leathanaigh"
COM_TEMPLATES_HEADING_STYLE="Stíl"
COM_TEMPLATES_HEADING_STYLE_ASC="Stíl ag ardú"
COM_TEMPLATES_HEADING_STYLE_DESC="Stíl ag ísliú"
COM_TEMPLATES_HEADING_TEMPLATE="Teimpléad"
COM_TEMPLATES_HEADING_TEMPLATE_ASC="Teimpléad ag ardú"
COM_TEMPLATES_HEADING_TEMPLATE_DESC="Teimpléad ag ísliú"
COM_TEMPLATES_HOME_BUTTON="Doiciméadú"
COM_TEMPLATES_HOME_HEADING="Roghnaigh Comhad"
COM_TEMPLATES_HOME_TEXT="Is féidir leat rogha a dhéanamh as roinnt roghanna chun cuma do theimpléid a shaincheapadh. Tacaíonn an Bainisteoir Teimpléad le Comhaid Foinse, Comhaid Íomhá, Comhaid Cló, Cartlanna Zip agus an chuid is mó de na hoibríochtaí is féidir a dhéanamh ar na comhaid sin. Roghnaigh comhad agus tá tú réidh le dul. Seiceáil an doiciméadú más mian leat tuilleadh a fháil amach."
COM_TEMPLATES_IMAGE_HEIGHT="Airde"
COM_TEMPLATES_IMAGE_WIDTH="Leithead"
COM_TEMPLATES_INVALID_FILE_NAME="Ainm comhaid neamhbhailí. Roghnaigh ainm comhaid le a-z, A-Z, 0-9, ., - agus _."
COM_TEMPLATES_INVALID_FILE_TYPE="Cineál comhaid gan roghnú."
COM_TEMPLATES_INVALID_FOLDER_NAME="Ainm fillteáin neamhbhailí. Roghnaigh ainm fillteáin le a-z, A-Z, 0-9, - agus _."
COM_TEMPLATES_LAYOUTS_DIFFVIEW_CORE="Taispeáin Comhad Bunaidh"
COM_TEMPLATES_LAYOUTS_DIFFVIEW_DIFF="Taispeáin Difríochtaí"
COM_TEMPLATES_MANAGER_ADD_STYLE="Teimpléid: Cuir Stíl leis"
COM_TEMPLATES_MANAGER_EDIT_STYLE="Teimpléid: Cuir Stíl in Eagar"
COM_TEMPLATES_MANAGER_STYLES="Teimpléid: Stíleanna"
COM_TEMPLATES_MANAGER_STYLES_ADMIN="Teimpléid: Stíleanna (Riarthóir)"
COM_TEMPLATES_MANAGER_STYLES_BUTTON="Stíleanna"
COM_TEMPLATES_MANAGER_STYLES_SITE="Teimpléid: Stíleanna (Suíomh)"
COM_TEMPLATES_MANAGER_TEMPLATES="Teimpléid"
COM_TEMPLATES_MANAGER_TEMPLATES_ADMIN="Teimpléid: Teimpléid (Riarthóir)"
COM_TEMPLATES_MANAGER_TEMPLATES_SITE="Teimpléid: Teimpléid (Suíomh)"
COM_TEMPLATES_MANAGER_VIEW_TEMPLATE="Teimpléid: Saincheap (%s)"
COM_TEMPLATES_MANAGE_FOLDERS="Bainistigh Fillteáin"
COM_TEMPLATES_MENUS_ASSIGNMENT="Sannadh Roghchláir"
COM_TEMPLATES_MENU_CHANGED_1="Sannadh nó dí-sannadh mír roghchláir amháin leis an stíl seo."
COM_TEMPLATES_MENU_CHANGED_MORE="Tá %d mír roghchláir sannadh nó dí-sannadh leis an stíl seo."
COM_TEMPLATES_MODAL_FILE_DELETE="Scriosfar an comhad %s."
COM_TEMPLATES_MSG_MANAGE_NO_STYLES="Níl aon stíleanna suiteáilte a oireann do d'fhiosrúchán."
COM_TEMPLATES_MSG_MANAGE_NO_TEMPLATES="Níl aon teimpléid suiteáilte a oireann do d'fhiosrúchán."
COM_TEMPLATES_NEW_FILE_HEADER="Cruthaigh nó Uaslódáil comhad nua."
COM_TEMPLATES_NEW_FILE_NAME="Ainm Comhaid Nua"
COM_TEMPLATES_NEW_FILE_SELECT="Roghnaigh cineál comhaid"
COM_TEMPLATES_NEW_FILE_TYPE="Cineál Comhaid"
COM_TEMPLATES_NO_TEMPLATE_SELECTED="Níl teimpléad roghnaithe."
COM_TEMPLATES_N_CONFLICT="%d Athruithe aimsithe"
COM_TEMPLATES_N_CONFLICT_1="Athrú aimsithe"
COM_TEMPLATES_N_ITEMS_DELETED="Scriosadh %d stíl teimpléid."
COM_TEMPLATES_N_ITEMS_DELETED_1="Scriosadh stíl teimpléid."
COM_TEMPLATES_N_OVERRIDE_CHECKED="Seiceáil %d taifead."
COM_TEMPLATES_N_OVERRIDE_CHECKED_1="Seiceáil taifead."
COM_TEMPLATES_N_OVERRIDE_DELETED="Baintear %d taifead."
COM_TEMPLATES_N_OVERRIDE_DELETED_1="Baintear taifead."
COM_TEMPLATES_N_OVERRIDE_UNCHECKED="Dí-seiceáil %d taifead."
COM_TEMPLATES_N_OVERRIDE_UNCHECKED_1="Dí-seiceáil taifead."
COM_TEMPLATES_OPTION_NONE=":: Dada ::"
COM_TEMPLATES_OPTION_SELECT_MENU_ITEM="- Roghnaigh Mír Roghchláir -"
COM_TEMPLATES_OVERRIDES="Comhaid Forghabhála"
COM_TEMPLATES_OVERRIDES_COMPONENTS="Comhpháirteanna"
COM_TEMPLATES_OVERRIDES_LAYOUTS="Leagan Amach"
COM_TEMPLATES_OVERRIDES_MODULES="Modúil"
COM_TEMPLATES_OVERRIDES_PLUGINS="Breiseáin"
COM_TEMPLATES_OVERRIDE_CHECKED="Seiceáilte"
COM_TEMPLATES_OVERRIDE_CORE_REMOVED="Baintear an comhad bunaidh"
COM_TEMPLATES_OVERRIDE_CREATED="Cruthaíodh forghabháil i "
COM_TEMPLATES_OVERRIDE_CREATED_DATE="Cuir leis an liosta"
COM_TEMPLATES_OVERRIDE_FAILED="Theip ar chruthú forghabhála."
COM_TEMPLATES_OVERRIDE_MODIFIED_DATE="An t-athrú deireanach trí Nuashonrú"
COM_TEMPLATES_OVERRIDE_NOT_UPTODATE="Tá an bunleagan de na comhaid forghabhála teimpléid atá liostaithe thíos nuashonraithe. Cabhraíonn an liosta seo leat na hathruithe sin a athbhreithniú agus iad a mharcáil mar sheiceáilte de réir mar a théann tú ar aghaidh."
COM_TEMPLATES_OVERRIDE_SOURCE="Foinse Nuashonraithe"
COM_TEMPLATES_OVERRIDE_TEMPLATE_FILE="Comhad Teimpléid"
COM_TEMPLATES_OVERRIDE_UPTODATE="Tá comhaid forghabhála cothrom le dáta. Níor athraíodh aon rud sa síneadh deireanach nó nuashonrú Joomla."
COM_TEMPLATES_OVERRIDE_UPDATED_FILES_CAPTION="Comhaid nuashonraithe le seiceáil."
COM_TEMPLATES_PREVIEW="Réamhamharc"
COM_TEMPLATES_RENAME_FILE="Athainmnigh comhad %s"
COM_TEMPLATES_RESIZE_IMAGE="Athraigh Méid Íomhá"
COM_TEMPLATES_SCREENSHOT="Gabháil Scáileáin %s"
COM_TEMPLATES_SOURCE_CODE="Foinse"
COM_TEMPLATES_STYLES_FILTER_SEARCH_DESC="Cuardaigh i dtuairisc stíle."
COM_TEMPLATES_STYLES_PAGES_ALL="Réamhshocrú do gach leathanach"
COM_TEMPLATES_STYLES_PAGES_ALL_LANGUAGE="Réamhshocrú do leathanaigh %s"
COM_TEMPLATES_STYLES_PAGES_NONE="Gan sannadh"
COM_TEMPLATES_STYLES_PAGES_SELECTED_1="Sannaithe ar %d leathanach"
COM_TEMPLATES_STYLES_PAGES_SELECTED="Sannaithe ar %d leathanaigh"
COM_TEMPLATES_STYLES_TABLE_CAPTION="Stíleanna Teimpléid"
COM_TEMPLATES_STYLE_CANNOT_DELETE_DEFAULT_STYLE="Ní féidir stíl réamhshocraithe a scriosadh."
COM_TEMPLATES_STYLE_FORM_EDIT="Cuir Stíl in Eagar"
COM_TEMPLATES_STYLE_SAVE_SUCCESS="Stíl sábháilte."
COM_TEMPLATES_SUBMENU_TEMPLATES="Teimpléid"
COM_TEMPLATES_SUCCESS_DUPLICATED="Stíl dúbláilte."
COM_TEMPLATES_SUCCESS_HOME_SET="Stíl réamhshocraithe socraithe."
COM_TEMPLATES_SUCCESS_HOME_UNSET="Stíl réamhshocraithe díshocraithe."
COM_TEMPLATES_TAB_DESCRIPTION="Cur Síos ar an Teimpléad"
COM_TEMPLATES_TAB_EDITOR="Eagarthóir"
COM_TEMPLATES_TAB_OVERRIDES="Cruthaigh Forluí"
COM_TEMPLATES_TAB_UPDATED_FILES="Comhaid Nuashonraithe"
COM_TEMPLATES_TEMPLATES_FILTER_SEARCH_DESC="Cuardaigh i ainm teimpléid nó ainm fillteáin."
COM_TEMPLATES_TEMPLATES_TABLE_CAPTION="Teimpléid"
COM_TEMPLATES_TEMPLATE_CHILD="Teimpléad Leanaí"
COM_TEMPLATES_TEMPLATE_CHILD_NAME_LABEL="Ainm Teimpléad Leanaí"
COM_TEMPLATES_TEMPLATE_CHILD_STYLE_LABEL="Stíleanna Teimpléid Breise"
COM_TEMPLATES_TEMPLATE_CLOSE="Dún"
COM_TEMPLATES_TEMPLATE_COPY="Cóipeáil Teimpléad"
COM_TEMPLATES_TEMPLATE_CORE_FILENAME="Comhad bunaidh &quot;%s&quot;."
COM_TEMPLATES_TEMPLATE_DESCRIPTION="Cur síos ar an teimpléad."
COM_TEMPLATES_TEMPLATE_DETAILS="%s Sonraí agus Comhaid"
COM_TEMPLATES_TEMPLATE_FILENAME="Ag cur comhad &quot;%s&quot; in eagar i dteimpléad &quot;%s&quot;."
COM_TEMPLATES_TEMPLATE_FILES="Comhaid Teimpléid"
COM_TEMPLATES_TEMPLATE_FOLDER="Fillteán Teimpléid"
COM_TEMPLATES_TEMPLATE_IS_CHILD_OF="Leanbh de <strong class=\"text-capitalize text-light\">%s</strong>"
COM_TEMPLATES_TEMPLATE_IS_PARENT="Tuismitheoir"
COM_TEMPLATES_TEMPLATE_MEDIA_FILES="Comhaid Meán"
COM_TEMPLATES_TEMPLATE_MEDIA_FOLDER="Fillteán Meán"
COM_TEMPLATES_TEMPLATE_NEW_NAME_DESC="Litreacha, uimhreacha agus fo-thrasnán amháin."
COM_TEMPLATES_TEMPLATE_NEW_NAME_LABEL="Ainm Nua Teimpléid"
COM_TEMPLATES_TEMPLATE_NEW_PREVIEW="Réamhamharc %s i bhfuinneog nua."
COM_TEMPLATES_TEMPLATE_NEW_STYLE_DESC="Dúbláil stíleanna atá ann cheana don teimpléad nua leanaí."
COM_TEMPLATES_TEMPLATE_NOT_SPECIFIED="Teimpléad gan sonraíocht."
COM_TEMPLATES_TEMPLATE_NO_PREVIEW="Níl réamhamharc ar fáil. Is féidir leat réamhamharc a chumasú sna roghanna."
COM_TEMPLATES_TEMPLATE_PREVIEW="Réamhamharc"
COM_TEMPLATES_TOOLBAR_SET_HOME="Réamhshocraithe"
COM_TEMPLATES_UPTODATE="Suas chun dáta"
COM_TEMPLATES_WARNING_FORMAT_WILL_NOT_BE_VISIBLE="Tá comhad nua cruthaithe agat leis an síneadh '%s'. Tá sé seo tacaíocht ach mar nach raibh an síneadh comhaid sin agat sa liosta de na formáidí tacaíochta ní féidir é seo a thaispeáint. Seiceáil na roghanna do Theimpléid agus cuir an fhormáid leis más gá."
COM_TEMPLATES_XML_DESCRIPTION="Bainistíonn an comhpháirt seo teimpléid"
JLIB_HTML_PUBLISH_ITEM="Marcáil mar sheiceáilte"
JLIB_HTML_UNPUBLISH_ITEM="Marcáil mar gan seiceáilte"
JLIB_RULES_SETTING_NOTES_COM_TEMPLATES="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Diúltaithe</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus cuirtear i bhfeidhm ar gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
