; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MENUS="Biachláir"
COM_MENUS_ACTION_COLLAPSE="Fill"
COM_MENUS_ACTION_DESELECT="Dídhéan"
COM_MENUS_ACTION_EXPAND="Leathnaigh"
COM_MENUS_ACTION_SELECT="Roghnaigh"
COM_MENUS_ADD_MENU_MODULE="Cuir modúl leis an mbiachlár seo"
COM_MENUS_ADMIN_ACCESS_LABEL="Rochtain"
COM_MENUS_ADMIN_AUTHOR_LABEL="Údar"
COM_MENUS_ADMIN_CATEGORY_LABEL="Catagóir"
COM_MENUS_ADMIN_FILTER_LABEL="Scagairí"
COM_MENUS_ADMIN_LANGUAGE_LABEL="Teanga"
COM_MENUS_ADMIN_LEVEL_LABEL="Leibhéil Fo-chatagóire"
COM_MENUS_ADMIN_TAGS_LABEL="Clibeanna"
COM_MENUS_BASIC_FIELDSET_LABEL="Roghanna"
COM_MENUS_BATCH_MENU_ITEM_CANNOT_CREATE="Níl cead agat míreanna nua biachláir a chruthú."
COM_MENUS_BATCH_MENU_ITEM_CANNOT_EDIT="Níl cead agat míreanna biachláir a chur in eagar."
COM_MENUS_BATCH_MENU_LABEL="Chun do rogha a bhogadh nó a chóipeáil, roghnaigh Biachlár nó mír thuismitheora le do thoil."
COM_MENUS_BATCH_OPTIONS="Próiseáil bhaisc na míreanna biachláir roghnaithe"
COM_MENUS_BATCH_TIP="Má roghnaítear biachlár nó tuismitheoir le haghaidh bogadh/cóipeáil, cuirfear aon ghníomhartha roghnaithe i bhfeidhm ar na míreanna biachláir cóipeáilte nó bogtha. Seachas sin, cuirtear gach gníomh i bhfeidhm ar na míreanna biachláir roghnaithe."
COM_MENUS_CONFIGURATION="Biachláir: Roghanna"
COM_MENUS_COUNT_PUBLISHED_ITEMS="Míreanna biachláir foilsithe"
COM_MENUS_COUNT_TRASHED_ITEMS="Míreanna biachláir sa bhruscar"
COM_MENUS_COUNT_UNPUBLISHED_ITEMS="Míreanna biachláir neamhfhoilsithe"
COM_MENUS_DASHBOARD_TITLE="Painéal Biachláir"
COM_MENUS_EDIT_MENU="Cuir Biachlár in Eagar"
COM_MENUS_EDIT_MENUITEM="Cuir Mír Biachláir in Eagar"
COM_MENUS_EDIT_MODULE_SETTINGS="Cuir socruithe modúil in eagar"
COM_MENUS_ERROR_ALL_LANGUAGE_ASSOCIATED="Ní féidir mír biachláir atá socraithe do Gach teanga a chomhcheangal. Níor socraíodh na comhlachais."
COM_MENUS_ERROR_ALREADY_HOME="Tá mír biachláir socraithe cheana féin mar bhaile."
COM_MENUS_ERROR_MENUTYPE="Athraigh an cineál Biachláir le do thoil. Tá an téarma 'príomh' in áirithe le haghaidh úsáide inmheánaí."
COM_MENUS_ERROR_MENUTYPE_HOME="Tá an téarma 'príomh' in áirithe le haghaidh úsáide inmheánaí."
COM_MENUS_ERROR_MENUTYPE_NOT_FOUND="Níl an cineál Biachláir ann."
COM_MENUS_ERROR_ONE_HOME="Ní féidir ach mír biachláir amháin a bheith mar nasc baile do gach teanga."
COM_MENUS_FIELD_FEEDLINK_DESC="Taispeáin nasc beatha don mhír biachláir seo."
COM_MENUS_FIELD_FEEDLINK_LABEL="Nasc beatha"
COM_MENUS_FIELD_PRESET_DESC="Roghnaigh réamhshocrú más mian leat an biachlár seo a líonadh leis na míreanna biachláir sa réamhshocrú sin. Seachas sin fág é seo folamh."
COM_MENUS_FIELD_PRESET_LABEL="Iompórtáil réamhshocrú"
COM_MENUS_FIELD_VALUE_IGNORE="Déan neamhaird"
COM_MENUS_FIELD_VALUE_NEW_WITH_NAV="Fuinneog Nua Le Loingseoireacht"
COM_MENUS_FIELD_VALUE_NEW_WITHOUT_NAV="Fuinneog Nua Gan Loingseoireacht"
COM_MENUS_FIELD_VALUE_PARENT="Tuismitheoir"
COM_MENUS_FIELDSET_RULES="Ceadanna"
COM_MENUS_FILTER_COMPONENT_LABEL="Comhpháirt"
COM_MENUS_FILTER_PARENT_MENU_ITEM_LABEL="Mír Biachláir Thuismitheora"
COM_MENUS_FILTER_SELECT_PARENT_MENU_ITEM="- Roghnaigh Mír Biachláir Thuismitheora -"
COM_MENUS_GRID_UNSET_LANGUAGE="Díshocraigh %s Réamhshocrú"
COM_MENUS_HEADING_ASSIGN_MODULE="Modúl"
COM_MENUS_HEADING_ASSOCIATION="Comhlachas"
COM_MENUS_HEADING_DISPLAY="Taispeáin"
COM_MENUS_HEADING_HOME="Baile"
COM_MENUS_HEADING_HOME_ASC="Baile ag ardú"
COM_MENUS_HEADING_HOME_DESC="Baile ag ísliú"
COM_MENUS_HEADING_LEVELS="Leibhéal Amharc"
COM_MENUS_HEADING_LINKED_MODULES="Modúil Nascáilte"
COM_MENUS_HEADING_MENU="Biachlár"
COM_MENUS_HEADING_MENU_ASC="Biachlár ag ardú"
COM_MENUS_HEADING_MENU_DESC="Biachlár ag ísliú"
COM_MENUS_HEADING_NUMBER_MENU_ITEMS="Líon na Míreanna Biachláir"
COM_MENUS_HEADING_POSITION="Seasamh"
COM_MENUS_HEADING_PUBLISHED_ITEMS="Foilsithe"
COM_MENUS_HEADING_TRASHED_ITEMS="Sa Bhruscar"
COM_MENUS_HEADING_UNPUBLISHED_ITEMS="Neamhfhoilsithe"
COM_MENUS_HOME="Baile"
COM_MENUS_INTEGRATION_FIELDSET_LABEL="Comhtháthú"
COM_MENUS_ITEM_DETAILS="Sonraí"
COM_MENUS_ITEM_FIELD_ALIAS_MENU_LABEL="Mír Roghchláir"
COM_MENUS_ITEM_FIELD_ALIAS_REDIRECT_LABEL="Úsáid Athsheoladh"
COM_MENUS_ITEM_FIELD_ANCHOR_CSS_LABEL="Aicme Nasc"
COM_MENUS_ITEM_FIELD_ANCHOR_REL_LABEL="Tréith Rel Nasc"
COM_MENUS_ITEM_FIELD_ANCHOR_TITLE_LABEL="Tréith Teideal Nasc"
COM_MENUS_ITEM_FIELD_ASSIGNED_LABEL="Roghchlár"
COM_MENUS_ITEM_FIELD_ASSOCIATION_NO_VALUE="- Gan comhcheangal -"
COM_MENUS_ITEM_FIELD_BROWSERNAV_LABEL="Fuinneog Sprioc"
COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_DESC="Roghnaigh na míreanna roghchláir ba chóir nó nár chóir a thaispeáint sa choimeádán seo. Mura bhfuil aon mhíreanna le taispeáint, beidh an coimeádán seo i bhfolach freisin.<br>Tabhair faoi deara go dtaispeánfar comhpháirt nua de réir réamhshocraithe nuair a shuiteáiltear é go dtí go dtiocfaidh tú ar ais anseo agus go bhfolóidh tú é freisin."
COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_LABEL="Taispeáin nó Foláir Míreanna Roghchláir"
COM_MENUS_ITEM_FIELD_DASHBOARD_DESC="Má chuirtear aitheantóir ar fáil, cruthaítear painéal don mhír roghchláir seo."
COM_MENUS_ITEM_FIELD_DASHBOARD_LABEL="Painéal"
COM_MENUS_ITEM_FIELD_HIDE_UNASSIGNED_LABEL="Modúil Neamhshannaithe"
COM_MENUS_ITEM_FIELD_HIDE_UNPUBLISHED_LABEL="Modúil Neamhfhoilsithe"
COM_MENUS_ITEM_FIELD_HOME_LABEL="Leathanach Réamhshocraithe"
COM_MENUS_ITEM_FIELD_ICON_TITLE_DESC="Má chuirtear aicme deilbhín isteach, glacann sé tosaíocht ar an íomhá nasc."
COM_MENUS_ITEM_FIELD_ICON_TITLE_LABEL="Aicme Deilbhín Nasc"
COM_MENUS_ITEM_FIELD_LINK_LABEL="Nasc"
COM_MENUS_ITEM_FIELD_MENU_IMAGE_CSS_LABEL="Aicme Íomhá"
COM_MENUS_ITEM_FIELD_MENU_IMAGE_LABEL="Íomhá Nasc"
COM_MENUS_ITEM_FIELD_MENU_SHOW_DESC="Roghnaigh 'Níl' más mian leat an mhír roghchláir seo a cheilt. Tabhair faoi deara go mbeidh aon mhíreanna fo-roghchláir i bhfolach freisin."
COM_MENUS_ITEM_FIELD_MENU_SHOW_LABEL="Taispeáin sa Roghchlár"
COM_MENUS_ITEM_FIELD_MENU_TEXT_LABEL="Teideal Mír Roghchláir a Thaispeáint"
COM_MENUS_ITEM_FIELD_ORDERING_LABEL="Ordú"
COM_MENUS_ITEM_FIELD_ORDERING_TEXT="Beidh ordú ar fáil tar éis sábhála."
COM_MENUS_ITEM_FIELD_ORDERING_VALUE_FIRST="- An Chéad -"
COM_MENUS_ITEM_FIELD_ORDERING_VALUE_LAST="- An Deireanach -"
COM_MENUS_ITEM_FIELD_PAGE_CLASS_LABEL="Aicme Leathanach"
COM_MENUS_ITEM_FIELD_PAGE_HEADING_LABEL="Ceannteideal Leathanach"
COM_MENUS_ITEM_FIELD_PAGE_TITLE_LABEL="Teideal Leathanach Brabhsálaí"
COM_MENUS_ITEM_FIELD_PARENT_LABEL="Mír Tuismitheora"
COM_MENUS_ITEM_FIELD_SHOW_PAGE_HEADING_LABEL="Taispeáin Ceannteideal Leathanach"
COM_MENUS_ITEM_FIELD_TEMPLATE_LABEL="Stíl Teimpléid"
COM_MENUS_ITEM_FIELD_TEXT_SEPARATOR_AS_LABEL="Lipéad"
COM_MENUS_ITEM_FIELD_TEXT_SEPARATOR_AS_SEPARATOR="Deighilteoir"
COM_MENUS_ITEM_FIELD_TEXT_SEPARATOR_LABEL="Taispeáin"
COM_MENUS_ITEM_FIELD_TITLE_LABEL="Teideal"
COM_MENUS_ITEM_FIELD_TYPE_LABEL="Cineál Mír Roghchláir"
COM_MENUS_ITEM_FORM_EDIT="Cuir Mír Roghchláir in Eagar"
COM_MENUS_ITEM_FORM_NEW="Mír Roghchláir Nua"
COM_MENUS_ITEM_MODULE_ASSIGNMENT="Sannadh Modúil"
COM_MENUS_ITEMS_N_QUICKICON="Míreanna Roghchláir"
COM_MENUS_ITEMS_N_QUICKICON_0="Míreanna Roghchláir"
COM_MENUS_ITEMS_N_QUICKICON_1="Mír Roghchláir"
COM_MENUS_ITEMS_N_QUICKICON_SRONLY="Míreanna Roghchláir: Tá %d mír roghchláir ar fáil."
COM_MENUS_ITEMS_N_QUICKICON_SRONLY_0="Míreanna Roghchláir: Níl aon mhír roghchláir ar fáil."
COM_MENUS_ITEMS_N_QUICKICON_SRONLY_1="Míreanna Roghchláir: Tá mír roghchláir amháin ar fáil."
COM_MENUS_ITEMS_REBUILD_FAILED="Theip ar atógáil liosta Míreanna Roghchláir."
COM_MENUS_ITEMS_REBUILD_SUCCESS="Atógadh liosta míreanna roghchláir."
COM_MENUS_ITEMS_SEARCH_FILTER="Cuardaigh i dteideal, ailias agus nótaí. Cuir ID: roimh chun ID mír roghchláir a chuardach."
COM_MENUS_ITEMS_SEARCH_FILTER_LABEL="Cuardaigh Míreanna Roghchláir"
```ini
COM_MENUS_ITEMS_SET_HOME_0="Níl aon mhír roghchláir socraithe mar bhaile."
COM_MENUS_ITEMS_SET_HOME_1="Mír roghchláir socraithe mar bhaile."
COM_MENUS_ITEMS_SET_HOME_MORE="%d míreanna roghchláir socraithe mar bhaile."
COM_MENUS_ITEMS_TABLE_CAPTION="Míreanna Roghchláir"
COM_MENUS_ITEMS_UNSET_HOME="Mír roghchláir díshuite mar bhaile."
COM_MENUS_LABEL_DISABLED="Comhpháirt díchumasaithe"
COM_MENUS_LABEL_HIDDEN="Folaigh"
COM_MENUS_LAYOUT_FEATURED_OPTIONS="Leagan Amach"
COM_MENUS_LINKTYPE_OPTIONS_LABEL="Cineál Nasc"
COM_MENUS_MENU_CONFIRM_DELETE="An bhfuil tú cinnte gur mhaith leat na roghchláir seo a scriosadh? Má dheimhnítear, scriosfar na cineálacha roghchláir roghnaithe, a gcuid míreanna roghchláir go léir agus na modúil roghchláir gaolmhara."
COM_MENUS_MENU_DETAILS="Sonraí Roghchláir"
COM_MENUS_MENU_EXPORT_BUTTON="Íoslódáil mar Réamhshocrú"
COM_MENUS_MENU_FORM_EDIT="Cuir Mír Roghchláir in Eagar"
COM_MENUS_MENU_FORM_NEW="Mír Roghchláir Nua"
COM_MENUS_MENU_ITEM_SAVE_SUCCESS="Mír roghchláir sábháilte."
COM_MENUS_MENU_MENUTYPE_LABEL="Ainm Uathúil"
COM_MENUS_MENU_SAVE_SUCCESS="Roghchlár sábháilte"
COM_MENUS_MENU_SEARCH_FILTER="Cuardaigh i dTeideal nó Cineál Roghchláir"
COM_MENUS_MENU_SPRINTF="Roghchlár: %s"
COM_MENUS_MENU_TYPE_PROTECTED_MAIN_LABEL="Príomh (Cosanta)"
COM_MENUS_MENUS="Míreanna Roghchláir"
COM_MENUS_MENUS_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus cineál roghchláir."
COM_MENUS_MENUS_FILTER_SEARCH_LABEL="Cuardaigh Roghchláir"
COM_MENUS_MENUS_TABLE_CAPTION="Roghchláir"
COM_MENUS_MODULE_ACCESS_POSITION="%1$s <small>(%2$s i %3$s)</small>"
COM_MENUS_MODULES="Modúil"
COM_MENUS_MODULES_TABLE_CAPTION="Sannadh Modúil"
COM_MENUS_N_ITEMS_CHECKED_IN_1="Mír roghchláir seiceáilte isteach."
COM_MENUS_N_ITEMS_CHECKED_IN_MORE="%d míreanna roghchláir seiceáilte isteach."
COM_MENUS_N_ITEMS_DELETED="%d míreanna roghchláir scriosta."
COM_MENUS_N_ITEMS_DELETED_1="Mír roghchláir scriosta."
COM_MENUS_N_ITEMS_FAILED_PUBLISHING="Theip ar fhoilsiú %d míreanna roghchláir mar tá ar a laghad ceann dá dtuismitheoirí neamhfhoilsithe nó tá ceann dá bpáistí seiceáilte amach."
COM_MENUS_N_ITEMS_FAILED_PUBLISHING_1="Theip ar fhoilsiú na míre roghchláir mar tá ar a laghad ceann dá tuismitheoirí neamhfhoilsithe nó tá ceann dá bpáistí seiceáilte amach."
COM_MENUS_N_ITEMS_PUBLISHED="%d míreanna roghchláir foilsithe."
COM_MENUS_N_ITEMS_PUBLISHED_1="Mír roghchláir foilsithe."
COM_MENUS_N_ITEMS_TRASHED="%d míreanna roghchláir bruscair."
COM_MENUS_N_ITEMS_TRASHED_1="Mír roghchláir bruscair."
COM_MENUS_N_ITEMS_UNPUBLISHED="%d míreanna roghchláir neamhfhoilsithe."
COM_MENUS_N_ITEMS_UNPUBLISHED_1="Mír roghchláir neamhfhoilsithe."
COM_MENUS_N_MENUS_DELETED="%d roghchláir scriosta."
COM_MENUS_N_MENUS_DELETED_1="Roghchlár scriosta."
COM_MENUS_NEW_MENUITEM="Mír Roghchláir Nua"
COM_MENUS_NO_ITEM_SELECTED="Níl aon mhír roghchláir roghnaithe."
COM_MENUS_NO_MENUS_SELECTED="Níl aon roghchlár roghnaithe."
COM_MENUS_OPTION_SELECT_COMPONENT="- Roghnaigh Comhpháirt -"
COM_MENUS_OPTION_SELECT_CONTEXT="- Roghnaigh Comhthéacs -"
COM_MENUS_OPTION_SELECT_LEVEL="- Roghnaigh Uasleibhéil -"
COM_MENUS_PAGE_OPTIONS_LABEL="Taispeáint Leathanach"
COM_MENUS_PRESET_IMPORT_FAILED="Sábháladh an roghchlár ach theip ar iompórtáil an réamhshocraithe: %s"
COM_MENUS_PRESET_IMPORT_SUCCESS="Sábháladh an roghchlár agus iompórtáladh na míreanna roghchláir ón réamhshocrú roghnaithe."
COM_MENUS_PRESET_LOAD_FAILED="Theip ar luchtú an réamhshocraithe sonraithe."
COM_MENUS_REQUEST_FIELDSET_LABEL="Socruithe Riachtanacha"
COM_MENUS_SAVE_SUCCESS="Mír roghchláir sábháilte."
COM_MENUS_SELECT_A_MENUITEM="Roghnaigh Mír Roghchláir"
COM_MENUS_SELECT_MENU="- Roghnaigh Roghchlár -"
COM_MENUS_SELECT_MENU_FILTER="Roghnaigh Roghchlár"
COM_MENUS_SELECT_MENU_FILTER_NOT_TRASHED="Scag an liosta de réir staid seachas bruscair nó glan an scagaire."
; Deprecated, will be removed with 6.0
```
COM_MENUS_SELECT_MENU_FIRST="Chun próiseáil bhaisc a úsáid, roghnaigh Roghchlár sa bhainisteoir ar dtús."
COM_MENUS_SELECT_MENU_FIRST_EXPORT="Chun onnmhairiú a úsáid, roghnaigh Roghchlár bailí sa bhainisteoir ar dtús."
COM_MENUS_SUBMENU_ITEMS="Míreanna Roghchláir"
COM_MENUS_SUBMENU_MENUS="Roghchláir"
COM_MENUS_TIP_ASSOCIATION="Míreanna roghchláir a bhaineann le chéile"
COM_MENUS_TITLE_TRANSLATION="Teideal (%s)"
COM_MENUS_TOOLBAR_SET_HOME="Baile"
COM_MENUS_TYPE_ALIAS="Ailias Mír Roghchláir"
COM_MENUS_TYPE_ALIAS_DESC="Cruthaigh ailias chuig mír roghchláir eile."
COM_MENUS_TYPE_CONTAINER="Coimeádán Roghchláir Comhpháirteanna"
COM_MENUS_TYPE_CONTAINER_DESC="Cruthóidh sé seo roghchlár coimeádáin a thaispeánfaidh na míreanna sa chineál roghchláir cosanta 'príomh'. Is féidir leat míreanna roghchláir a cheilt nó a thaispeáint go roghnach freisin."
COM_MENUS_TYPE_EXTERNAL_URL="URL"
COM_MENUS_TYPE_EXTERNAL_URL_DESC="URL seachtrach nó inmheánach."
COM_MENUS_TYPE_HEADING="Ceannteideal Roghchláir"
COM_MENUS_TYPE_HEADING_DESC="Ceannteideal don tuismitheoir de mhíreanna fo-roghchláir."
COM_MENUS_TYPE_SEPARATOR="Deighilteoir"
COM_MENUS_TYPE_SEPARATOR_DESC="Deighilteoir le nó gan lipéad téacs, úsáideach chun míreanna a dheighilt laistigh de roghchlár."
COM_MENUS_TYPE_SYSTEM="Naisc Chórais"
COM_MENUS_TYPE_UNEXISTING="Níl an Comhpháirt '%s' ann."
COM_MENUS_TYPE_UNKNOWN="Anaithnid"
COM_MENUS_VIEW_EDIT_ITEM_TITLE="Roghchláir: Cuir Mír in Eagar"
COM_MENUS_VIEW_EDIT_MENU_TITLE="Roghchláir: Cuir in Eagar"
COM_MENUS_VIEW_ITEMS_ALL_TITLE="Roghchláir: Gach Mír Roghchláir"
COM_MENUS_VIEW_ITEMS_MENU_TITLE="Roghchláir: Míreanna (%s)"
COM_MENUS_VIEW_MENUS_TITLE="Roghchláir"
COM_MENUS_VIEW_NEW_ITEM_TITLE="Roghchláir: Mír Nua"
COM_MENUS_VIEW_NEW_MENU_TITLE="Roghchláir: Cuir leis"
COM_MENUS_XML_DESCRIPTION="Comhpháirt chun roghchláir a chruthú."

JLIB_RULES_SETTING_NOTES_COM_MENUS="Ní bhaineann athruithe ach leis an gcomhpháirt seo.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> i gcónaí buaite - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus a bhaineann le gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas na comhpháirte seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda." ; Alternate language strings for the rules form field

JLIB_HTML_SETDEFAULT_ITEM="Socraigh mar Bhaile" ; Alternate language strings for the default menu item
JTOOLBAR_DEFAULT="Baile" ; Alternate language strings for the default menu item
