; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_INSTALLER="Suiteálaí"
COM_INSTALLER_DATABASE_VIEW_DEFAULT_DESC="Seiceáil agus nuashonraigh aon saincheisteanna struchtúir bunachar sonraí le do shuíomh gréasáin."
COM_INSTALLER_DATABASE_VIEW_DEFAULT_TITLE="Seiceáil Bunachar Sonraí"
COM_INSTALLER_DATABASE_VIEW_DISPLAY_BADGE="Taispeáin Suaitheantas"
COM_INSTALLER_DISCOVER_VIEW_DEFAULT_DESC="Faigh amach síntí nach bhfuil tar éis dul tríd an ngnáthphróiseas suiteála."
COM_INSTALLER_DISCOVER_VIEW_DEFAULT_TITLE="Faigh Amach Síntí"
COM_INSTALLER_DISCOVER_VIEW_DISPLAY_BADGE="Taispeáin Suaitheantas"
COM_INSTALLER_INSTALL_VIEW_DEFAULT_DESC="Suiteáil síntí isteach i do shuiteáil Joomla!"
COM_INSTALLER_INSTALL_VIEW_DEFAULT_TITLE="Suiteáil Síntí"
COM_INSTALLER_LANGUAGES_VIEW_DEFAULT_DESC="Suiteáil pacáistí Teanga isteach i do shuíomh gréasáin Joomla!"
COM_INSTALLER_LANGUAGES_VIEW_DEFAULT_TITLE="Suiteáil Teangacha"
COM_INSTALLER_MANAGE_VIEW_DEFAULT_DESC="Bainistigh síntí atá suiteáilte cheana féin ar do shuíomh gréasáin Joomla!"
COM_INSTALLER_MANAGE_VIEW_DEFAULT_TITLE="Bainistigh Síntí"
COM_INSTALLER_UPDATE_VIEW_DEFAULT_DESC="Faigh agus Suiteáil nuashonruithe do na síntí suiteáilte."
COM_INSTALLER_UPDATE_VIEW_DEFAULT_TITLE="Nuashonraigh Síntí"
COM_INSTALLER_UPDATE_VIEW_DISPLAY_BADGE="Taispeáin Suaitheantas"
COM_INSTALLER_UPDATESITES_VIEW_DEFAULT_DESC="Taispeánann liosta de na suíomhanna nuashonraithe go léir a bheidh á seiceáil."
COM_INSTALLER_UPDATESITES_VIEW_DEFAULT_TITLE="Suíomhanna Nuashonraithe"
COM_INSTALLER_WARNINGS_VIEW_DEFAULT_DESC="Taispeánann rabhaidh a bhaineann le do shíntí suiteáilte."
COM_INSTALLER_WARNINGS_VIEW_DEFAULT_TITLE="Rabhadh"
COM_INSTALLER_WARNINGS_VIEW_DISPLAY_BADGE="Taispeáin Suaitheantas"
COM_INSTALLER_XML_DESCRIPTION="Comhpháirt suiteálaí chun síntí a chur leis, a bhaint agus a uasghrádú."
