; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT="Ailt"
COM_CONTENT_ADD_NEW_MENU_ITEM="Mír Roghchláir Nua"
COM_CONTENT_ARTICLE_CONTENT="Ábhar"
COM_CONTENT_ARTICLES_TABLE_CAPTION="Ailt"
COM_CONTENT_ARTICLES_TITLE="Ailt"
COM_CONTENT_ATTRIBS_ARTICLE_SETTINGS_LABEL="Roghanna"
COM_CONTENT_ATTRIBS_FIELDSET_LABEL="Roghanna"
COM_CONTENT_BATCH_OPTIONS="Próiseáil bhaisc na hailt roghnaithe"
COM_CONTENT_BATCH_TIP="Má roghnaítear catagóir le haghaidh bogadh/cóipeáil, cuirfear aon ghníomhartha roghnaithe i bhfeidhm ar na hailt atá cóipeáilte nó bogtha. Seachas sin, cuirtear gach gníomh i bhfeidhm ar na hailt roghnaithe."
COM_CONTENT_CHANGE_STAGE="Athraigh céim"
COM_CONTENT_CHANGE_STAGE_AMBIGUOUS_TRANSITIONS="Tá roinnt aistrithe débhríoch don choinníoll seo. Roghnaigh do rogha aistrithe agus lean ar aghaidh."
COM_CONTENT_CONFIG_ARTICLE_SETTINGS_DESC="Baineann na socruithe seo le leagan amach na n-alt mura n-athraítear iad do mhír roghchláir nó alt ar leith."
COM_CONTENT_CONFIG_BLOG_SETTINGS_DESC="Baineann na socruithe seo le leagan amach blag nó leagan amach feiceálach mura n-athraítear iad do mhír roghchláir ar leith."
COM_CONTENT_CONFIG_BLOG_SETTINGS_LABEL="Leagan Amach Blag/Feiceálach"
COM_CONTENT_CONFIG_CATEGORIES_SETTINGS_DESC="Baineann na socruithe seo le Roghanna Catagóirí Ailt, mura n-athraítear iad ag na socruithe catagóire nó roghchláir aonair."
COM_CONTENT_CONFIG_CATEGORY_SETTINGS_DESC="Baineann na socruithe seo le Roghanna Catagóire Ailt mura n-athraítear iad ag na socruithe catagóire nó roghchláir aonair."
COM_CONTENT_CONFIG_EDITOR_LAYOUT="Rialaíonn na roghanna seo leagan amach an leathanaigh eagarthóireachta alt."
COM_CONTENT_CONFIG_INTEGRATION_SETTINGS_DESC="Socraíonn na socruithe seo conas a chomhtháthaíonn an Comhpháirt Alt le síntí eile."
COM_CONTENT_CONFIG_LIST_SETTINGS_DESC="Baineann na socruithe seo le Roghanna Leagan Amach Liosta mura n-athraítear iad do mhír roghchláir nó catagóir ar leith."
COM_CONTENT_CONFIGURATION="Ailt: Roghanna"
COM_CONTENT_CREATE_ARTICLE_CANCEL_REDIRECT_MENU_DESC="Roghnaigh an leathanach a ndéanfar an t-úsáideoir a atreorú chuige tar éis dó aighneacht alt a chealú. Is é an réamhshocrú ná atreorú chuig an leathanach céanna aighneachta alt (foirm ghlanadh)."
COM_CONTENT_CREATE_ARTICLE_CANCEL_REDIRECT_MENU_LABEL="Atreorú Cealaithe"
COM_CONTENT_CREATE_ARTICLE_CATEGORY_LABEL="Catagóir Sonrach"
COM_CONTENT_CREATE_ARTICLE_CUSTOM_CANCEL_REDIRECT_DESC="Má shocraítear é ar 'Tá', is féidir leat leathanach atreoraithe a shocrú, difriúil ón 'Aighneacht/Cealú Atreorú' thuas, chun atreorú chuige nuair a chealaíonn an t-úsáideoir aighneacht alt.<br>Mura bhfuil, nuair a chealaíonn an t-úsáideoir aighneacht alt, déantar an t-úsáideoir a atreorú chuig an leathanach 'Aighneacht/Cealú Atreorú' thuas."
COM_CONTENT_CREATE_ARTICLE_CUSTOM_CANCEL_REDIRECT_LABEL="Atreorú Saincheaptha ar Chealú"
COM_CONTENT_CREATE_ARTICLE_ERROR="Nuair a bhíonn catagóir sonrach cumasaithe, ba cheart catagóir a roghnú."
COM_CONTENT_CREATE_ARTICLE_REDIRECTMENU_DESC="Roghnaigh an leathanach a ndéanfar an t-úsáideoir a atreorú chuige tar éis aighneacht alt rathúil agus tar éis cealú (mura socraítear go difriúil thíos). Is é an réamhshocrú ná atreorú chuig an leathanach baile."
COM_CONTENT_CREATE_ARTICLE_REDIRECTMENU_LABEL="Aighneacht/Cealú Atreorú"
COM_CONTENT_DASHBOARD_TITLE="Painéal Ábhair"
COM_CONTENT_EDIT_ARTICLE="Cuir Alt in Eagar"
COM_CONTENT_EDIT_CATEGORY="Cuir Catagóir in Eagar"
COM_CONTENT_EDITING_LAYOUT="Leagan Amach Eagarthóireachta"
COM_CONTENT_EDITORCONFIG_FIELDSET_LABEL="Cumraigh Scáileán Eagarthóireachta"
COM_CONTENT_EMPTYSTATE_BUTTON_ADD="Cuir d’alt chéad uair leis"
COM_CONTENT_EMPTYSTATE_CONTENT="Is iad ailt an príomhábhar ar fhormhór na suíomhanna Joomla. Is féidir leat Eagarthóir Alt Joomla a úsáid chun d’ábhar a chruthú agus a bhainistiú."
COM_CONTENT_EMPTYSTATE_TITLE="Níl Ailt cruthaithe go fóill."
COM_CONTENT_ERROR_ALL_LANGUAGE_ASSOCIATED="Ní féidir mír ábhair atá socraithe do Gach teanga a chomhcheangal. Níor socraíodh na comhlachais."
COM_CONTENT_ERROR_CANNOT_ARCHIVE="Ní féidir ceann amháin nó níos mó de na hailt roghnaithe a shocrú mar chartlannaithe."
COM_CONTENT_ERROR_CANNOT_PUBLISH="Ní féidir ceann amháin nó níos mó de na hailt roghnaithe a shocrú mar fhoilsithe."
COM_CONTENT_ERROR_CANNOT_TRASH="Ní féidir ceann amháin nó níos mó de na hailt roghnaithe a shocrú mar bhruscar."
COM_CONTENT_ERROR_CANNOT_UNPUBLISH="Ní féidir ceann amháin nó níos mó de na hailt roghnaithe a shocrú mar neamhfhoilsithe."
COM_CONTENT_ERROR_UNIQUE_ALIAS="Tá an t-ailias céanna ag Ailt eile sa chatagóir seo."
COM_CONTENT_ERROR_UNIQUE_ALIAS_TRASHED="Tá an t-ailias céanna ag Ailt bruscair sa chatagóir seo."
COM_CONTENT_ERROR_UPDATE_STAGE="Ní féidir leat an t-aistriú seo a fhorghníomhú agus an chéim a nuashonrú."
COM_CONTENT_FEATURED_ARTICLES="Ailt Réadmhaoin"
COM_CONTENT_FEATURED_CATEGORIES_LABEL="Roghnaigh Catagóirí"
COM_CONTENT_FEATURED_N_QUICKICON="Ailt Réadmhaoin"
COM_CONTENT_FEATURED_N_QUICKICON_1="Alt Réadmhaoin"
COM_CONTENT_FEATURED_N_QUICKICON_SRONLY="Ailt Réadmhaoin: Tá %d alt réadmhaoin foilsithe."
COM_CONTENT_FEATURED_N_QUICKICON_SRONLY_1="Alt Réadmhaoin: Tá alt réadmhaoin amháin foilsithe."
COM_CONTENT_FEATURED_ORDER="Ord Ailt Réadmhaoin"
COM_CONTENT_FEATURED_TABLE_CAPTION="Ailt Réadmhaoin"
COM_CONTENT_FEATURED_TITLE="Ailt: Réadmhaoin"
COM_CONTENT_FIELD_ARTICLETEXT_LABEL="Téacs an Ailt"
COM_CONTENT_FIELD_BROWSER_PAGE_TITLE_LABEL="Teideal an Leathanaigh Brabhsálaí"
COM_CONTENT_FIELD_CAPTCHA_LABEL="Ceadaigh Captcha ar aighneacht"
COM_CONTENT_FIELD_CREATED_BY_ALIAS_LABEL="Cruthaithe ag Ailias"
COM_CONTENT_FIELD_CREATED_BY_LABEL="Cruthaithe ag"
COM_CONTENT_FIELD_CREATED_LABEL="Dáta Cruthaithe"
COM_CONTENT_FIELD_FEATURED_DOWN_LABEL="Críochnaigh Réadmhaoin"
COM_CONTENT_FIELD_FEATURED_UP_LABEL="Tosaigh Réadmhaoin"
COM_CONTENT_FIELD_FULL_LABEL="Íomhá Iomlán an Ailt"
COM_CONTENT_FIELD_FULLTEXT="Téacs iomlán"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_DESC="Íomhá Maisiúil - níl aon tuairisc ag teastáil"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_LABEL="Gan Tuairisc"
COM_CONTENT_FIELD_IMAGE_ALT_LABEL="Tuairisc Íomhá (Téacs Alt)"
COM_CONTENT_FIELD_IMAGE_CAPTION_LABEL="Fotheideal"
COM_CONTENT_FIELD_IMAGE_CLASS_DESC="Is féidir leat aon rang CSS a chur leis do do chuid smaointe stíle féin.<br>Chun suíomh íomhá a úsáid mar shampla float-start agus float-end."
COM_CONTENT_FIELD_IMAGE_CLASS_LABEL="Rang Íomhá"
COM_CONTENT_FIELD_IMAGE_OPTIONS="Roghanna Íomhá"
COM_CONTENT_FIELD_INFOBLOCK_POSITION_LABEL="Suíomh Faisnéise an Ailt"
COM_CONTENT_FIELD_INFOBLOCK_TITLE_LABEL="Teideal Faisnéise an Ailt"
COM_CONTENT_FIELD_INTRO_LABEL="Íomhá Réamhrá"
COM_CONTENT_FIELD_INTROTEXT="Téacs Réamhrá"
COM_CONTENT_FIELD_NOTE_LABEL="Nóta"
COM_CONTENT_FIELD_OPTION_ABOVE="Os cionn"
COM_CONTENT_FIELD_OPTION_BELOW="Faoi bhun"
COM_CONTENT_FIELD_OPTION_SPLIT="Roinn"
COM_CONTENT_FIELD_PUBLISH_DOWN_LABEL="Críochnaigh Foilsiú"
COM_CONTENT_FIELD_PUBLISH_UP_LABEL="Tosaigh Foilsiú"
COM_CONTENT_FIELD_SELECT_ARTICLE_LABEL="Roghnaigh Alt"
COM_CONTENT_FIELD_SHOW_CAT_TAGS_LABEL="Clibeanna"
COM_CONTENT_FIELD_SHOW_TAGS_LABEL="Clibeanna"
COM_CONTENT_FIELD_URLA_LABEL="Nasc A"
COM_CONTENT_FIELD_URLA_LINK_TEXT_LABEL="Téacs Nasc A"
COM_CONTENT_FIELD_URLB_LABEL="Nasc B"
COM_CONTENT_FIELD_URLB_LINK_TEXT_LABEL="Téacs Nasc B"
COM_CONTENT_FIELD_URLC_LABEL="Nasc C"
COM_CONTENT_FIELD_URLC_LINK_TEXT_LABEL="Téacs Nasc C"
COM_CONTENT_FIELD_URLS_OPTIONS="Roghanna URL"
COM_CONTENT_FIELD_URLSPOSITION_LABEL="Suíomh na Naisc"
```ini
COM_CONTENT_FIELD_VALUE_USE_ARTICLE_SETTINGS="Úsáid Socruithe Airteagal"
COM_CONTENT_FIELD_VERSION_LABEL="Athbhreithniú"
COM_CONTENT_FIELDS_ARTICLE_FIELD_ADD_TITLE="Airteagail: Réimse Nua"
COM_CONTENT_FIELDS_ARTICLE_FIELD_EDIT_TITLE="Airteagail: Cuir Réimse in Eagar"
COM_CONTENT_FIELDS_ARTICLE_FIELDS_TITLE="Airteagail: Réimsí"
COM_CONTENT_FIELDS_TYPE_MODAL_ARTICLE="Airteagal"
COM_CONTENT_FIELDSET_PUBLISHING="Foilsitheoireacht"
COM_CONTENT_FIELDSET_RULES="Ceadanna"
COM_CONTENT_FIELDSET_URLS_AND_IMAGES="Íomhánna agus Naisc"
COM_CONTENT_FILTER_AUTHORS_BY_ME="Cruthaithe agam"
COM_CONTENT_FILTER_FEATURED_NO="Airteagail Neamhbhuailte"
COM_CONTENT_FILTER_FEATURED_YES="Airteagail Bhuaite"
COM_CONTENT_FILTER_SEARCH_DESC="Cuardaigh i dteideal, ailias agus nóta. Réamhtheachtaigh le ID: nó ÚDAR: nó ÁBHAR: chun cuardach a dhéanamh ar ID airteagal, údar airteagal nó cuardach in ábhar airteagal. Réamhtheachtaigh le SEICEÁIL: chun cuardach a dhéanamh ar ábhar seiceáilte amach ag úsáideoir sonraithe."
COM_CONTENT_FILTER_SEARCH_LABEL="Cuardaigh Airteagail"
COM_CONTENT_FORM_TITLE_EDIT="Cuir Airteagal in Eagar"
COM_CONTENT_FORM_TITLE_NEW="Airteagal Nua"
COM_CONTENT_HEADING_ASSOCIATION="Comhlachas"
COM_CONTENT_HEADING_DATE_CREATED="Dáta Cruthaithe"
COM_CONTENT_HEADING_DATE_MODIFIED="Dáta Athraithe"
COM_CONTENT_HEADING_DATE_PUBLISH_DOWN="Críochnaigh Foilsitheoireacht"
COM_CONTENT_HEADING_DATE_PUBLISH_UP="Tosaigh Foilsitheoireacht"
COM_CONTENT_ID_LABEL="ID"
COM_CONTENT_IMAGE_FULLTEXT_CLASS_LABEL="Rang Íomhá Téacs Iomlán"
COM_CONTENT_IMAGE_INTRO_CLASS_LABEL="Rang Íomhá Réamhrá"
COM_CONTENT_MODIFIED_ASC="Dáta Athraithe ag ardú"
COM_CONTENT_MODIFIED_DESC="Dáta Athraithe ag ísliú"
COM_CONTENT_MONTH="Mí"
COM_CONTENT_N_ITEMS_ARCHIVED="%d airteagal cartlannaithe."
COM_CONTENT_N_ITEMS_ARCHIVED_1="Airteagal cartlannaithe."
COM_CONTENT_N_ITEMS_CHECKED_IN_1="Airteagal seiceáilte isteach."
COM_CONTENT_N_ITEMS_CHECKED_IN_MORE="%d airteagal seiceáilte isteach."
COM_CONTENT_N_ITEMS_DELETED="%d airteagal scriosta."
COM_CONTENT_N_ITEMS_DELETED_1="Airteagal scriosta."
COM_CONTENT_N_ITEMS_FEATURED="%d airteagal buaite."
COM_CONTENT_N_ITEMS_FEATURED_1="Airteagal buaite."
COM_CONTENT_N_ITEMS_PUBLISHED="%d airteagal foilsithe."
COM_CONTENT_N_ITEMS_PUBLISHED_1="Airteagal foilsithe."
COM_CONTENT_N_ITEMS_TRASHED="%d airteagal bruscair."
COM_CONTENT_N_ITEMS_TRASHED_1="Airteagal bruscair."
COM_CONTENT_N_ITEMS_UNFEATURED="%d airteagal neamhbhuailte."
COM_CONTENT_N_ITEMS_UNFEATURED_1="Airteagal neamhbhuailte."
COM_CONTENT_N_ITEMS_UNPUBLISHED="%d airteagal neamhfhoilsithe."
COM_CONTENT_N_ITEMS_UNPUBLISHED_1="Airteagal neamhfhoilsithe."
COM_CONTENT_N_QUICKICON="Airteagail"
COM_CONTENT_N_QUICKICON_0="Airteagail"
COM_CONTENT_N_QUICKICON_1="Airteagal"
COM_CONTENT_N_QUICKICON_SRONLY="Airteagail: Tá %d airteagal ar fáil."
COM_CONTENT_N_QUICKICON_SRONLY_0="Airteagail: Níl aon airteagal ar fáil."
COM_CONTENT_N_QUICKICON_SRONLY_1="Airteagail: Tá airteagal amháin ar fáil."
COM_CONTENT_NEW_ARTICLE="Airteagal Nua"
COM_CONTENT_NO_ARTICLES_LABEL="Teachtaireacht Gan Airteagail"
COM_CONTENT_NO_ITEM_SELECTED="Roghnaigh rud ón liosta ar dtús le do thoil."
COM_CONTENT_NUMBER_CATEGORY_ITEMS_LABEL="# Airteagail sa Chatagóir"
COM_CONTENT_OTHER_OPTIONS="Roghanna"
COM_CONTENT_PAGE_ADD_ARTICLE="Airteagail: Nua"
COM_CONTENT_PAGE_EDIT_ARTICLE="Airteagail: Cuir in Eagar"
COM_CONTENT_PAGE_VIEW_ARTICLE="Airteagail: Amharc"
COM_CONTENT_PAGEBREAK_DOC_TITLE="Briseadh Leathanaigh"
COM_CONTENT_PAGEBREAK_INSERT_BUTTON="Cuir Briseadh Leathanaigh isteach"
COM_CONTENT_PAGEBREAK_TITLE="Teideal Leathanaigh"
COM_CONTENT_PAGEBREAK_TOC="Ailias Tábla Ábhar"
COM_CONTENT_PUBLISH_DOWN_ASC="Críochnaigh Foilsitheoireacht ag ardú"
COM_CONTENT_PUBLISH_DOWN_DESC="Críochnaigh Foilsitheoireacht ag ísliú"
```
COM_CONTENT_PUBLISH_UP_ASC="Tús Foilsitheoireachta ag ardú"
COM_CONTENT_PUBLISH_UP_DESC="Tús Foilsitheoireachta ag ísliú"
COM_CONTENT_PUBLISHED="Foilsithe"
COM_CONTENT_RUN_TRANSITION="Rith Aistriú"
COM_CONTENT_RUN_TRANSITIONS="Rith Aistrithe"
COM_CONTENT_SAVE_SUCCESS="Airteagal sábháilte."
COM_CONTENT_SAVE_WARNING="Bhí ailias ann cheana, mar sin cuireadh uimhir leis ag an deireadh. Is féidir leat an t-alt a ath-eagarthóireacht chun an t-ailias a shaincheapadh."
COM_CONTENT_SELECT_AN_ARTICLE="Roghnaigh Airteagal"
COM_CONTENT_SELECT_FEATURED="- Roghnaigh Réadmhaoin -"
COM_CONTENT_SHARED_DESC="Baineann na socruithe seo le Roghanna Comhroinnte i Liosta, Blag agus Réadmhaoin mura n-athraítear iad ag socruithe an roghchláir."
COM_CONTENT_SHARED_LABEL="Comhroinnte"
COM_CONTENT_SHOW_ARTICLE_OPTIONS_LABEL="Roghanna Airteagal"
COM_CONTENT_SHOW_ASSOCIATIONS_LABEL="Comhlachais Ilteangacha"
COM_CONTENT_SHOW_CONFIGURE_EDIT_LABEL="Roghanna Scáileáin Eagarthóireachta"
COM_CONTENT_SHOW_IMAGES_URLS_BACK_LABEL="Íomhánna agus Naisc an Riarthóra"
COM_CONTENT_SHOW_IMAGES_URLS_FRONT_LABEL="Íomhánna agus Naisc an Tosaigh"
COM_CONTENT_SHOW_PERMISSIONS_LABEL="Ceadanna Airteagal"
COM_CONTENT_SHOW_PUBLISHING_OPTIONS_LABEL="Roghanna Foilsitheoireachta"
COM_CONTENT_SLIDER_EDITOR_CONFIG="Cumraigh Scáileán Eagarthóireachta"
COM_CONTENT_STAGE_ARTICLE_TITLE="%1$s <small>(ID: %2$d)</small>"
COM_CONTENT_SUBMENU_CATEGORIES="Catagóirí"
COM_CONTENT_SUBMENU_FEATURED="Airteagail Réadmhaoin"
COM_CONTENT_SUBMENU_WORKFLOWS="Sreafaí Oibre"
COM_CONTENT_TIP_ASSOCIATION="Airteagail Chomhcheangailte"
COM_CONTENT_TRANSITION="Aistriú"
COM_CONTENT_TRASHED="Bruscar"
COM_CONTENT_UNPUBLISHED="Neamhfhoilsithe"
COM_CONTENT_URL_FIELD_A_BROWSERNAV_LABEL="URL A Fuinneog Sprioc"
COM_CONTENT_URL_FIELD_B_BROWSERNAV_LABEL="URL B Fuinneog Sprioc"
COM_CONTENT_URL_FIELD_BROWSERNAV_LABEL="URL Fuinneog Sprioc"
COM_CONTENT_URL_FIELD_C_BROWSERNAV_LABEL="URL C Fuinneog Sprioc"
COM_CONTENT_WARNING_PROVIDE_VALID_NAME="Tabhair teideal bailí, neamhfholamh le do thoil."
COM_CONTENT_WORKFLOW="Sreabhadh Oibre"
COM_CONTENT_WORKFLOW_NOT_FOUND="Níl sreabhadh oibre réamhshocraithe ar fáil, sainigh ceann nó déan teagmháil le riarthóir."
COM_CONTENT_WORKFLOW_STAGE="Céim Sreafa Oibre"
COM_CONTENT_WORKFLOW_TRANSITION_NOT_ALLOWED="Níl cead agat an t-aistriú seo a chur i gcrích"
COM_CONTENT_WORKFLOWS="Sreafaí Oibre"
COM_CONTENT_XML_DESCRIPTION="Comhpháirt bainistíochta airteagal."
JGLOBAL_NO_ITEM_SELECTED="Níor roghnaíodh aon airteagal"
JLIB_APPLICATION_ERROR_BATCH_CANNOT_CREATE="Níl cead agat airteagail nua a chruthú sa chatagóir seo."
JLIB_APPLICATION_ERROR_BATCH_CANNOT_EDIT="Níl cead agat ceann nó níos mó de na hairteagail seo a chur in eagar."
JLIB_APPLICATION_ERROR_BATCH_CANNOT_EXECUTE_TRANSITION="Níl cead agat aistriú a chur i gcrích do cheann nó níos mó de na hairteagail seo."

JLIB_RULES_SETTING_NOTES_COM_CONTENT="Baineann athruithe leis an gcomhpháirt seo amháin.<br><em><strong>Oidhreachtaithe</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus cuirtear i bhfeidhm ar gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé an gníomh ar chumas an chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
JLIB_RULES_SETTING_NOTES_ITEM_COM_CONTENT_ARTICLE="Ní bhaineann athruithe ach leis an alt seo.<br><em><strong>Oidhreacht</strong></em> - cuirtear socrú Cumraíochta Domhanda nó socrú ar leibhéal níos airde i bhfeidhm.<br><em><strong>Séanadh</strong></em> buaileann sé i gcónaí - cibé rud atá socraithe ag an leibhéal Domhanda nó níos airde agus cuirtear i bhfeidhm ar gach eilimint leanaí.<br><em><strong>Ceadaithe</strong></em> cuirfidh sé ar chumas an ghnímh don chomhpháirt seo mura bhfuil sé sáraithe ag socrú Cumraíochta Domhanda."
COM_CONTENT_ARTICLE_CATEGORIES_TITLE="Ailt: Grúpaí Réimsí"
COM_CONTENT_ARTICLE_CATEGORY_ADD_TITLE="Ailt: Grúpa Réimse Nua"
COM_CONTENT_ARTICLE_CATEGORY_EDIT_TITLE="Ailt: Cuir Grúpa Réimse in Eagar"
