; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT="Ailt"
COM_CONTENT_ARCHIVE_VIEW_DEFAULT_DESC="Taispeáin gach alt cartlainne."
COM_CONTENT_ARCHIVE_VIEW_DEFAULT_OPTION="Réamhshocrú"
COM_CONTENT_ARCHIVE_VIEW_DEFAULT_TITLE="Ailt Chartlainne"
COM_CONTENT_ARTICLE_MANAGER="Ailt"
COM_CONTENT_ARTICLE_VIEW_DEFAULT_DESC="Taispeáin alt aonair."
COM_CONTENT_ARTICLE_VIEW_DEFAULT_OPTION="Réamhshocrú"
COM_CONTENT_ARTICLE_VIEW_DEFAULT_TITLE="Alt Aonair"
COM_CONTENT_ARTICLE_VIEW_EDIT_DESC="Taispeánann foirm chun Alt Nua a chruthú."
COM_CONTENT_ARTICLE_VIEW_EDIT_TITLE="Cruthaigh Alt"
COM_CONTENT_ARTICLES="Ailt"
COM_CONTENT_ARTICLES_VIEW_DEFAULT_DESC="Taispeánann liosta de na hailt go léir."
COM_CONTENT_ARTICLES_VIEW_DEFAULT_TITLE="Liostaigh Gach Alt"
COM_CONTENT_CATEGORIES="Catagóirí"
COM_CONTENT_CATEGORIES_VIEW_DEFAULT_DESC="Taispeánann liosta de na catagóirí go léir i gcrann catagóir alt roghnaithe."
COM_CONTENT_CATEGORIES_VIEW_DEFAULT_OPTION="Réamhshocrú"
COM_CONTENT_CATEGORIES_VIEW_DEFAULT_TITLE="Liostaigh Gach Catagóir i gCrann Catagóir Alt"
COM_CONTENT_CATEGORY_VIEW_BLOG_DESC="Taispeánann réamhráite alt i leagan amach aoncholúin nó ilcholúin."
COM_CONTENT_CATEGORY_VIEW_BLOG_OPTION="Blag"
COM_CONTENT_CATEGORY_VIEW_BLOG_TITLE="Blag Catagóire"
COM_CONTENT_CATEGORY_VIEW_DEFAULT_DESC="Taispeánann liosta d'ailt i gcatagóir."
COM_CONTENT_CATEGORY_VIEW_DEFAULT_OPTION="Liosta"
COM_CONTENT_CATEGORY_VIEW_DEFAULT_TITLE="Liosta Catagóire"
COM_CONTENT_CATEGORY_VIEW_FEATURED_DESC="Taispeáin gach alt feiceálach ó chatagóir amháin nó níos mó i leagan amach aoncholúin nó ilcholúin."
COM_CONTENT_CONTENT_TYPE_ARTICLE="Alt"
COM_CONTENT_CONTENT_TYPE_CATEGORY="Catagóir Alt"
COM_CONTENT_FEATURED="Feiceálach"
COM_CONTENT_FEATURED_VIEW_DEFAULT_DESC="Taispeánann liosta de na hailt feiceálacha go léir."
COM_CONTENT_FEATURED_VIEW_DEFAULT_OPTION="Réamhshocrú"
COM_CONTENT_FEATURED_VIEW_DEFAULT_TITLE="Ailt Fheiceálacha"
COM_CONTENT_FORM_VIEW_DEFAULT_DESC="Cruthaigh alt nua."
COM_CONTENT_FORM_VIEW_DEFAULT_OPTION="Cruthaigh"
COM_CONTENT_FORM_VIEW_DEFAULT_TITLE="Cruthaigh Alt"
COM_CONTENT_MENUS="Ábhar"
COM_CONTENT_MENUS_ARTICLE_MANAGER="Ailt"
COM_CONTENT_MENUS_CATEGORY_MANAGER="Catagóirí"
COM_CONTENT_MENUS_FEATURED="Ailt Fheiceálacha"
COM_CONTENT_MENUS_MANAGE="Socruithe Ábhair"
COM_CONTENT_MENUS_MISC="Modúil & Meáin"
COM_CONTENT_MENUS_NEW_ADMIN_MODULE="Cuir Modúl Riaracháin leis"
COM_CONTENT_MENUS_NEW_ARTICLE="Cuir Alt leis"
COM_CONTENT_MENUS_NEW_CATEGORY="Cuir Catagóir leis"
COM_CONTENT_MENUS_NEW_SITE_MODULE="Cuir Modúl Suímh leis"
COM_CONTENT_MENUS_PRESET_CONTENT="Réamhshocrú - Painéal Ábhair"
COM_CONTENT_MENUS_WORKFLOW="Sreafaí Oibre"
COM_CONTENT_MENUS_WORKFLOW_MANAGER="Sreafaí Oibre"
COM_CONTENT_TAGS_ARTICLE="Alt"
COM_CONTENT_TAGS_CATEGORY="Catagóir Alt"
COM_CONTENT_XML_DESCRIPTION="Comhpháirt bainistíochta alt."
