; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_NEW_TITLE="Roghnaigh an cnaipe 'Nua'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_NEW_DESCRIPTION="Roghnaigh 'Nua' chun turas nua a chruthú."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_TITLE_TITLE="Cuir teideal leis an turas"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_TITLE_DESCRIPTION="Iontráil teideal riachtanach don turas."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONTENT_TITLE="Cuir ábhar leis"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONTENT_DESCRIPTION="Iontráil ábhar ag cur síos ar an turas."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_COMPONENT_TITLE="Roghnaigh comhpháirt"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_COMPONENT_DESCRIPTION="Roghnaigh an síneadh/sínteanna ina bhfuil tú ag iarraidh do thuras a thaispeáint mar thosaíocht sa liosta de thurais indéanta. Mar shampla, má tá tú ag cruthú turas don síneadh 'Úsáideoirí', ansin roghnaigh 'Úsáideoirí'. Roghnaigh 'Uile' chun go mbeidh an turas le feiceáil ar gach leathanach."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_URL_TITLE="Cuir URL leis"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_URL_DESCRIPTION="Cuir URL coibhneasta an leathanaigh inar chóir an turas a thosú. Mar shampla, iontráil <em>administrator/index.php?option=com_users&view=users</em> chun an turas a thosú ar an leathanach Úsáideoirí."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_AUTOSTART_TITLE="Athraigh 'Tosú Uathoibríoch'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_AUTOSTART_DESCRIPTION="<p>Má shocraítear 'Tosú Uathoibríoch' go 'Tá', cuirfear tús leis an turas go huathoibríoch chomh luath agus a chomhlíontar na coinníollacha ábhartha.</p><p>Má tá ilthuras socraithe le tosú uathoibríoch faoi na coinníollacha céanna, ní thosóidh ach an chéad turas sa liosta go dtí go gcuirfear ar ceal é, go gcríochnófar é nó go scipeálfar é.</p>"

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_SAVECLOSE_TITLE="Roghnaigh 'Sábháil agus Dún'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_SAVECLOSE_DESCRIPTION="Sábháil agus dún an turas."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONGRATULATIONS_TITLE="Comhghairdeas!"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_CONGRATULATIONS_DESCRIPTION="Tá turas treoraithe cruthaithe agat. Anois caithfidh tú céimeanna a chruthú don turas."
