; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_NEW_TITLE="Roghnaigh an cnaipe 'Nua'"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_NEW_DESCRIPTION="Roghnaigh 'Nua' chun teagmháil nua a chruthú."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TITLE_TITLE="Cuir ainm leis"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TITLE_DESCRIPTION="Iontráil ainm riachtanach don teagmháil."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ALIAS_TITLE="Iontráil ailias"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ALIAS_DESCRIPTION="Is féidir leat ainm inmheánach na teagmhála seo a scríobh. Is féidir leat é seo a fhágáil bán agus úsáidfear luach réamhshocraithe i litreacha beaga le fleiscíní in ionad spásanna mar chuid den URL."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_DETAILS_TITLE="Iontráil eolas mionsonraithe"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_DETAILS_DESCRIPTION="Cuir na sonraí don teagmháil anseo."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_STATUS_TITLE="Roghnaigh an stádas"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_STATUS_DESCRIPTION="Roghnaigh stádas foilsithe na teagmhála."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CATEGORY_TITLE="Roghnaigh catagóir"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CATEGORY_DESCRIPTION="Roghnaigh an chatagóir don teagmháil seo. Is féidir leat catagóir nua a iontráil freisin trí ainm a chlóscríobh sa réimse agus brúigh iontráil."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_FEATURED_TITLE="Athraigh an rogha le feiceáil"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_FEATURED_DESCRIPTION="Roghnaigh 'Le feiceáil' chun do theagmháil a chur chun cinn."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ACCESS_TITLE="Socraigh an leibhéal rochtana"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_ACCESS_DESCRIPTION="Roghnaigh an leibhéal rochtana don teagmháil."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TAGS_TITLE="Cuir clibeanna leis"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_TAGS_DESCRIPTION="Roghnaigh clibeanna do do theagmháil. Is féidir leat clib nua a iontráil freisin trí ainm a chlóscríobh sa réimse agus brúigh iontráil."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_VERSIONNOTE_TITLE="Cuir nóta leagan leis"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_VERSIONNOTE_DESCRIPTION="Is réimse roghnach é seo chun leagan na teagmhála seo a aithint."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_SAVECLOSE_TITLE="Roghnaigh 'Sábháil agus Dún'"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_SAVECLOSE_DESCRIPTION="Sábháil agus dún an teagmháil."

COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CONGRATULATIONS_TITLE="Comhghairdeas!"
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_CONGRATULATIONS_DESCRIPTION="Tá teagmháil cruthaithe agat."
