; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_USERS_STEP_NEW_TITLE="Roghnaigh an cnaipe 'Nua'"
COM_GUIDEDTOURS_TOUR_USERS_STEP_NEW_DESCRIPTION="Roghnaigh 'Nua' chun úsáideoir nua a chruthú."

COM_GUIDEDTOURS_TOUR_USERS_STEP_NAME_TITLE="Cuir ainm leis"
COM_GUIDEDTOURS_TOUR_USERS_STEP_NAME_DESCRIPTION="Iontráil ainm riachtanach don úsáideoir."

COM_GUIDEDTOURS_TOUR_USERS_STEP_LOGINNAME_TITLE="Cuir ainm logála isteach leis"
COM_GUIDEDTOURS_TOUR_USERS_STEP_LOGINNAME_DESCRIPTION="Iontráil ainm logála isteach riachtanach don úsáideoir (ainm úsáideora)."

COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD_TITLE="Iontráil pasfhocal"
COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD_DESCRIPTION="Líon isteach pasfhocal (nua). Cé nach bhfuil an réimse seo riachtanach, ní bheidh an t-úsáideoir in ann logáil isteach nuair nach bhfuil pasfhocal socraithe."

COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD2_TITLE="Deimhnigh an pasfhocal"
COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORD2_DESCRIPTION="Líon isteach an pasfhocal ón réimse thuas arís, chun é a fhíorú. Tá an réimse seo riachtanach nuair a líonann tú isteach an réimse pasfhocal nua."

COM_GUIDEDTOURS_TOUR_USERS_STEP_EMAIL_TITLE="Cuir seoladh ríomhphoist leis"
COM_GUIDEDTOURS_TOUR_USERS_STEP_EMAIL_DESCRIPTION="Iontráil seoladh ríomhphoist don úsáideoir."

COM_GUIDEDTOURS_TOUR_USERS_STEP_SYSTEMEMAIL_TITLE="Athraigh faighte ríomhphoist an chórais"
COM_GUIDEDTOURS_TOUR_USERS_STEP_SYSTEMEMAIL_DESCRIPTION="Socraigh go bhfuil, má theastaíonn ar an úsáideoir ríomhphoist an chórais a fháil."

COM_GUIDEDTOURS_TOUR_USERS_STEP_STATUS_TITLE="Athraigh stádas"
COM_GUIDEDTOURS_TOUR_USERS_STEP_STATUS_DESCRIPTION="Cumasaigh nó blocáil an t-úsáideoir seo."

COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORDRESET_TITLE="Athraigh athshocrú pasfhocal"
COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORDRESET_DESCRIPTION="Má shocraítear go bhfuil, beidh ar an úsáideoir a pasfhocal a athshocrú an chéad uair eile a logálann siad isteach ar an suíomh."

COM_GUIDEDTOURS_TOUR_USERS_STEP_SAVECLOSE_TITLE="Roghnaigh 'Sábháil agus Dún'"
COM_GUIDEDTOURS_TOUR_USERS_STEP_SAVECLOSE_DESCRIPTION="Sábháil agus dún an t-úsáideoir."

COM_GUIDEDTOURS_TOUR_USERS_STEP_CONGRATULATIONS_TITLE="Comhghairdeas!"
COM_GUIDEDTOURS_TOUR_USERS_STEP_CONGRATULATIONS_DESCRIPTION="Tá úsáideoir cruthaithe agat."
