; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_MENUS_STEP_NEW_TITLE="Roghnaigh an cnaipe 'Nua'"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_NEW_DESCRIPTION="Roghnaigh 'Nua' chun roghchlár nua a chruthú."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_TITLE_TITLE="Cuir teideal leis an roghchlár"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_TITLE_DESCRIPTION="Iontráil teideal riachtanach don roghchlár."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_UNIQUENAME_TITLE="Cuir ainm uathúil leis"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_UNIQUENAME_DESCRIPTION="Iontráil ainm uathúil riachtanach don roghchlár."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_DESCRIPTION_TITLE="Cuir cur síos leis"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_DESCRIPTION_DESCRIPTION="Cuir cur síos ar chuspóir an roghchláir."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_SAVECLOSE_TITLE="Roghnaigh 'Sábháil agus Dún'"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_SAVECLOSE_DESCRIPTION="Sábháil agus dún an roghchlár."

COM_GUIDEDTOURS_TOUR_MENUS_STEP_CONGRATULATIONS_TITLE="Comhghairdeas!"
COM_GUIDEDTOURS_TOUR_MENUS_STEP_CONGRATULATIONS_DESCRIPTION="Tá roghchlár cruthaithe agat."
