; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_TITLE="Fáilte go Joomla!"
COM_GUIDEDTOURS_TOUR_WELCOMETOJOOMLA_DESCRIPTION="<p>Tabharfaidh an turas seo forbhreathnú tapa duit ar conas tosú le Joomla!</p><p>Tá tú i limistéar Riarthóir Joomla, ar a dtugtar an '<strong>Cúlra</strong>' freisin.<br>Seo an áit a socraíonn tú suas agus a bhainistíonn tú do Shuíomh Joomla ar fad.</p><p><strong>Ar mhaith leat níos mó a fhoghlaim?</strong></p><p>Tosaímis an turas agus tóg do shuíomh le cumhacht Joomla!</p>"
