; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_TAGS_STEP_NEW_TITLE="Roghnaigh an cnaipe 'Nua'"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_NEW_DESCRIPTION="Roghnaigh 'Nua' chun clib nua a chruthú."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_TITLE_TITLE="Cuir teideal leis an gclib"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_TITLE_DESCRIPTION="Iontráil teideal riachtanach don chlib."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_ALIAS_TITLE="Iontráil ailias"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_ALIAS_DESCRIPTION="Is féidir leat ainm inmheánach na clibe seo a scríobh. Is féidir leat é seo a fhágáil bán agus úsáidfear luach réamhshocraithe i litreacha beaga le fleiscíní in ionad spásanna mar chuid den URL."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONTENT_TITLE="Cuir ábhar leis"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONTENT_DESCRIPTION="Cuir ábhar do chlib san eagarthóir."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_PARENT_TITLE="Roghnaigh clib thuismitheora"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_PARENT_DESCRIPTION="Roghnaigh nó iontráil tuismitheoir na clibe."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_STATUS_TITLE="Roghnaigh an stádas"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_STATUS_DESCRIPTION="Roghnaigh stádas foilsithe na clibe."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_ACCESS_TITLE="Socraigh an leibhéal rochtana"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_ACCESS_DESCRIPTION="Roghnaigh an leibhéal rochtana don chlib."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_NOTE_TITLE="Cuir nóta leis"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_NOTE_DESCRIPTION="De ghnáth, tá sé seo le haghaidh úsáide an riarthóra agus ní thaispeántar é ar an tosaigh."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_VERSIONNOTE_TITLE="Cuir nóta leagan leis"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_VERSIONNOTE_DESCRIPTION="Is réimse roghnach é seo chun leagan na clibe seo a aithint."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_SAVECLOSE_TITLE="Roghnaigh 'Sábháil agus Dún'"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_SAVECLOSE_DESCRIPTION="Sábháil agus dún an chlib."

COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONGRATULATIONS_TITLE="Comhghairdeas!"
COM_GUIDEDTOURS_TOUR_TAGS_STEP_CONGRATULATIONS_DESCRIPTION="Tá clib cruthaithe agat."
