; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_NEW_TITLE="Roghnaigh an cnaipe 'Nua'"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_NEW_DESCRIPTION="Roghnaigh 'Nua' chun meirgí nua a chruthú."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_TITLE_TITLE="Cuir teideal leis an meirgí"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_TITLE_DESCRIPTION="Iontráil teideal riachtanach don meirgí."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_ALIAS_TITLE="Iontráil ailias"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_ALIAS_DESCRIPTION="Is féidir leat ainm inmheánach an meirgí seo a scríobh. Is féidir leat é seo a fhágáil bán agus úsáidfear luach réamhshocraithe i litreacha beaga le fleiscíní in ionad spásanna mar chuid den URL."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_TITLE="Iontráil faisnéis mhionsonraithe"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_DETAILS_DESCRIPTION="Cuir na sonraí don meirgí anseo."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_STATUS_TITLE="Roghnaigh an stádas"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_STATUS_DESCRIPTION="Roghnaigh stádas foilsithe an meirgí."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CATEGORY_TITLE="Roghnaigh catagóir"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CATEGORY_DESCRIPTION="Roghnaigh an chatagóir don meirgí seo. Is féidir leat catagóir nua a iontráil freisin trí ainm a chlóscríobh sa réimse agus brúigh iontráil."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_PINNED_TITLE="Athraigh bioraithe"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_PINNED_DESCRIPTION="Roghnaigh 'Bioraithe' chun tosaíocht a thabhairt don meirgí thar cinn nach bhfuil bioraithe."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_VERSIONNOTE_TITLE="Cuir nóta leagan leis"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_VERSIONNOTE_DESCRIPTION="Is réimse roghnach é seo chun leagan an meirgí seo a aithint."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_SAVECLOSE_TITLE="Roghnaigh 'Sábháil agus Dún'"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_SAVECLOSE_DESCRIPTION="Sábháil agus dún an meirgí."

COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_TITLE="Comhghairdeas!"
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_DESCRIPTION="Tá meirgí cruthaithe agat."
