; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_COUNTER_TITLE="Roghnaigh uimhir an chomhaireamh céime"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_COUNTER_DESCRIPTION="Roghnaigh an uimhir chun céim a chur leis. Léiríonn an uimhir líon na gcéimeanna a cruthaíodh don turas go dtí seo."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_NEW_TITLE="Roghnaigh an cnaipe 'Nua'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_NEW_DESCRIPTION="Roghnaigh 'Nua' chun céim nua a chruthú."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TITLE_TITLE="Cuir teideal leis an gcéim"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TITLE_DESCRIPTION="Iontráil teideal riachtanach don chéim. Is gníomh é seo de ghnáth a chaithfidh úsáideoir a chur i gcrích."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_DESCRIPTION_TITLE="Cuir míniú céime leis"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_DESCRIPTION_DESCRIPTION="Ba chóir go dtabharfadh an t-ábhar míniú don úsáideoir faoin gcéim."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_STATUS_TITLE="Roghnaigh an stádas"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_STATUS_DESCRIPTION="Roghnaigh stádas foilsithe na céime."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_POSITION_TITLE="Roghnaigh an seasamh"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_POSITION_DESCRIPTION="Seo é seasamh an phóipín i gcoibhneas leis an eilimint a bhfuil tú ag díriú uirthi ar an leathanach. Úsáidtear 'Lárnaithe' nuair nach bhfuil sprioc ar leith ann."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TARGET_TITLE="Iontráil an eilimint sprioc"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TARGET_DESCRIPTION="Seo é an eilimint ar an leathanach a bhfuil an chéim seo dírithe uirthi. Úsáideann sé an chomhréir a úsáideann CSS chun eilimint a dhíriú.<br>Mar shampla, díreoidh <code>#jform_title</code> ar an eilimint leis an id 'jform_title'."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TYPE_TITLE="Roghnaigh an cineál"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_TYPE_DESCRIPTION="Seo é an cineál céime atá tú ag iarraidh a chruthú. 'Ar Aghaidh' chun ligean don turas leanúint ar aghaidh gan idirghabháil, 'Athdhíriú' chun bogadh go leathanach eile, 'Idirghníomhach' chun ionchur úsáideora a iarraidh."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_SAVECLOSE_TITLE="Roghnaigh 'Sábháil agus Dún'"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_SAVECLOSE_DESCRIPTION="Sábháil agus dún an chéim."

COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_CONGRATULATIONS_TITLE="Comhghairdeas!"
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_STEP_CONGRATULATIONS_DESCRIPTION="Tá céim cruthaithe agat do thuras treoraithe."
