; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LOGINSUPPORT="Eolas Tacaíochta Logála Isteach"
MOD_LOGINSUPPORT_LAYOUT_DEFAULT="Réamhshocrú"
MOD_LOGINSUPPORT_XML_DESCRIPTION="Taispeánann an modúl seo roinnt nasc úsáideach chuig láithreáin tacaíochta Joomla ar an scáileán logála isteach."
