; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_QUICKICON="Deilbhíní Tapa"
MOD_QUICKICON_LAYOUT_DEFAULT="Réamhshocrú"
MOD_QUICKICON_XML_DESCRIPTION="Taispeánann an modúl seo Deilbhíní Tapa atá le feiceáil ar an bPainéal Baile (leathanach baile an riaracháin)"
