; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_USER="Roghchlár Úsáideora"
MOD_USER_LAYOUT_DEFAULT="Réamhshocrú"
MOD_USER_XML_DESCRIPTION="Taispeánann an modúl seo an Roghchlár Úsáideora agus tá sé beartaithe a thaispeáint sa suíomh 'stádas'."
