; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_POST_INSTALLATION_MESSAGES="Teachtaireachtaí Iarshuiteála"
MOD_POST_INSTALLATION_MESSAGES_XML_DESCRIPTION="Taispeánann an modúl seo cuntar agus nasc chuig na teachtaireachtaí iarshuiteála is déanaí. Ní thaispeántar é ach nuair a bhíonn teachtaireachtaí le léamh."
