; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_SUBMENU="Roghchlár Painéal an Riarthóra"
MOD_SUBMENU_FIELD_MENUTYPE_LABEL="Roghchlár"
MOD_SUBMENU_FIELD_MENUTYPE_OPTION_PREDEFINED="Úsáid Réamhshocrú"
MOD_SUBMENU_FIELD_PRESET_LABEL="Réamhshocrú"
MOD_SUBMENU_XML_DESCRIPTION="Taispeánann an modúl seo bailiúchán de roghchláir i bpainéal an riarthóra."
