; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_FRONTEND="Nasc Tosaigh"
MOD_FRONTEND_LAYOUT_DEFAULT="Réamhshocrú"
MOD_FRONTEND_XML_DESCRIPTION="Taispeánann an modúl seo nasc chuig an tosaigh agus tá sé beartaithe a thaispeáint sa suíomh 'stádas'."
