; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_QUICKICON="Deilbhíní Tapa"
MOD_QUICKICON_ARTICLE_MANAGER="Ailt"
MOD_QUICKICON_ARTICLE_MANAGER_ADD="Cuir Alt leis"
MOD_QUICKICON_ASSOCIATIONS_MANAGER="Comhlachais Ilteangacha"
MOD_QUICKICON_BANNER_MANAGER="Meirgí"
MOD_QUICKICON_BANNER_MANAGER_ADD="Cuir Meirge leis"
MOD_QUICKICON_CACHE="Taisce"
MOD_QUICKICON_CATEGORY_MANAGER="Catagóirí Alt"
MOD_QUICKICON_CATEGORY_MANAGER_ADD="Cuir Catagóir Alt leis"
MOD_QUICKICON_CHECKIN="Seiceáil Isteach"
MOD_QUICKICON_CHECKINS="Seiceáil Isteach Domhanda"
MOD_QUICKICON_CONFIGURATION="Cumraíocht"
MOD_QUICKICON_CONTACT_MANAGER="Teagmhálacha"
MOD_QUICKICON_CONTACT_MANAGER_ADD="Cuir Teagmháil leis"
MOD_QUICKICON_CONTENT="Ábhar"
MOD_QUICKICON_FEATURED_MANAGER="Ailt Réadmhaoin"
MOD_QUICKICON_FINDER_MANAGER="Cuardach Cliste"
MOD_QUICKICON_GLOBAL_CONFIGURATION="Cumraíocht Domhanda"
MOD_QUICKICON_GROUP_DESC="Grúpa an mhodúil seo (déantar an luach seo a chur i gcomparáid leis an luach grúpa a úsáidtear i mbreiseáin <strong>Deilbhíní Tapa</strong> chun deilbhíní a instealladh). Tá deilbhíní croí Joomla! ar fáil le húsáid in aon mhodúl Deilbhíní Tapa."
MOD_QUICKICON_GROUP_LABEL="Grúpa"
MOD_QUICKICON_HEADER_ICON_LABEL="Deilbhín Ceanntásc"
MOD_QUICKICON_INSTALL_EXTENSIONS="Suiteáil Síneadh"
MOD_QUICKICON_LANGUAGES_MANAGER="Teangacha"
MOD_QUICKICON_LANGUAGES_MANAGER_ADD="Cuir Teanga leis"
MOD_QUICKICON_LOAD_PLUGINS_LABEL="Luchtaigh breiseáin 3ú páirtí"
MOD_QUICKICON_MAINTENANCE="Cothabháil"
MOD_QUICKICON_MEDIA_MANAGER="Meáin"
MOD_QUICKICON_MENUITEMS_MANAGER="Míreanna Roghchláir"
MOD_QUICKICON_MENUITEMS_MANAGER_ADD="Cuir Mír Roghchláir leis"
MOD_QUICKICON_MODULE_MANAGER="Modúil"
MOD_QUICKICON_MODULE_MANAGER_ADD="Cuir Modúl Suímh leis"
MOD_QUICKICON_NAV_LABEL="Naisc Thapa"
MOD_QUICKICON_NEWSFEEDS_MANAGER="Beathaisnéisí Nuachta"
MOD_QUICKICON_NEWSFEEDS_MANAGER_ADD="Cuir Beathaisnéis Nuachta leis"
MOD_QUICKICON_PLUGIN_MANAGER="Breiseáin"
MOD_QUICKICON_REDIRECT_MANAGER="Athsheoltaí"
MOD_QUICKICON_REDIRECT_MANAGER_ADD="Cuir Athsheoladh leis"
MOD_QUICKICON_SHOW_ARTICLES_LABEL="Deilbhín Ailt"
MOD_QUICKICON_SHOW_ASSOCIATIONS_LABEL="Deilbhín Comhlachais Ilteangacha"
MOD_QUICKICON_SHOW_BANNERS_LABEL="Deilbhín Meirge"
MOD_QUICKICON_SHOW_CACHE_LABEL="Deilbhín Taisce"
MOD_QUICKICON_SHOW_CATEGORIES_LABEL="Deilbhín Catagóirí"
MOD_QUICKICON_SHOW_CHECKINS_LABEL="Deilbhín Seiceáil Isteach"
MOD_QUICKICON_SHOW_CHECKIN_LABEL="Deilbhín Seiceáil Isteach"
MOD_QUICKICON_SHOW_CONTACT_LABEL="Deilbhín Teagmhálacha"
MOD_QUICKICON_SHOW_EXTENSIONUPDATE_LABEL="Seiceáil Nuashonrú Síneadh"
MOD_QUICKICON_SHOW_FEATURED_LABEL="Deilbhín Ailt Réadmhaoin"
MOD_QUICKICON_SHOW_FINDER_LABEL="Deilbhín Cuardach Cliste"
MOD_QUICKICON_SHOW_GLOBAL_LABEL="Deilbhín Cumraíocht Domhanda"
MOD_QUICKICON_SHOW_JOOMLAUPDATE_LABEL="Seiceáil Nuashonrú Joomla"
MOD_QUICKICON_SHOW_LANGUAGES_LABEL="Deilbhín Teangacha"
MOD_QUICKICON_SHOW_MEDIA_LABEL="Deilbhín Meáin"
MOD_QUICKICON_SHOW_MENUITEMS_LABEL="Deilbhín Míreanna Roghchláir"
MOD_QUICKICON_SHOW_MODULES_LABEL="Deilbhín Modúil"
MOD_QUICKICON_SHOW_NEWSFEEDS_LABEL="Deilbhín Beathaisnéisí Nuachta"
MOD_QUICKICON_SHOW_OVERRIDEUPDATE_LABEL="Seiceáil Nuashonrú Forghníomhaithe"
MOD_QUICKICON_SHOW_PLUGINS_LABEL="Deilbhín Breiseáin"
MOD_QUICKICON_SHOW_PRIVACYREQUEST_LABEL="Iarratais Príobháideachta"
MOD_QUICKICON_SHOW_REDIRECT_LABEL="Deilbhín Athsheoltaí"
MOD_QUICKICON_SHOW_TAGS_LABEL="Deilbhín Clibeanna"
MOD_QUICKICON_SHOW_TEMPLATE_CODE_LABEL="Deilbhín Cód Teimpléid"
MOD_QUICKICON_SHOW_TEMPLATE_STYLES_LABEL="Deilbhín Stíleanna Teimpléid"
MOD_QUICKICON_SHOW_USERS_LABEL="Deilbhín Úsáideoir"
MOD_QUICKICON_SHOW_WORKFLOW_LABEL="Deilbhín Sreafaí Oibre"
MOD_QUICKICON_SITE="Suíomh Deilbhíní"
MOD_QUICKICON_STRUCTURE="Struchtúr"
MOD_QUICKICON_SYSTEM="Córas Deilbhíní"
MOD_QUICKICON_TAGS_MANAGER="Clibeanna"
MOD_QUICKICON_TAGS_MANAGER_ADD="Cuir Clib leis"
MOD_QUICKICON_TEMPLATE_CODE="Teimpléid"
MOD_QUICKICON_TEMPLATE_STYLES="Stíleanna Teimpléid"
MOD_QUICKICON_TYPE="Cineál Deilbhín"
MOD_QUICKICON_UPDATE="Nuashonrú Deilbhíní"
MOD_QUICKICON_USER_MANAGER="Úsáideoirí"
MOD_QUICKICON_USER_MANAGER_ADD="Cuir Úsáideoir Leis"
MOD_QUICKICON_WITH_COUNT="Taispeáin Míreanna le Líon"
MOD_QUICKICON_WORKFLOW_MANAGER="Sreafaí Oibre"
MOD_QUICKICON_WORKFLOW_MANAGER_ADD="Cuir Sreabhadh Oibre Leis"
MOD_QUICKICON_XML_DESCRIPTION="Taispeánann an modúl seo Deilbhíní Tapa atá le feiceáil ar an Dashboard (leathanach baile an limistéir riaracháin)."
