; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MENU="Riarachán Roghchláir"
MOD_MENU_ACCESS="Ceadanna Úsáideora"
MOD_MENU_ACCESS_GROUPS="Grúpaí"
MOD_MENU_ACCESS_LEVELS="Leibhéil Rochtana"
MOD_MENU_ACCESS_SETTINGS="Socruithe"
MOD_MENU_ACCESS_TEXT_FILTERS="Scagairí Téacs"
MOD_MENU_ARIA_CLOSE_SUBMENU="Dún Fo-roghchlár"
MOD_MENU_ARIA_MAIN_MENU="Príomh-Roghchlár"
MOD_MENU_CLEAR_CACHE="Glan Taisce"
MOD_MENU_COM_ACTIONLOGS="Loga Gníomhartha Úsáideora"
MOD_MENU_COM_CONTENT="Ábhar"
MOD_MENU_COM_LANGUAGES_SUBMENU_CONTENT="Teangacha Ábhair"
MOD_MENU_COM_LANGUAGES_SUBMENU_INSTALLED="Suiteáilte"
MOD_MENU_COM_LANGUAGES_SUBMENU_OVERRIDES="Forghníomhaithe"
MOD_MENU_COM_MAILS_TEMPLATES="Teimpléid Ríomhphoist"
MOD_MENU_COM_PRIVACY="Príobháideachas"
MOD_MENU_COM_PRIVACY_CAPABILITIES="Cumas"
MOD_MENU_COM_PRIVACY_CONSENTS="Toiliú"
MOD_MENU_COM_PRIVACY_DASHBOARD="Painéal"
MOD_MENU_COM_PRIVACY_REQUESTS="Iarratais"
MOD_MENU_COM_TEMPLATES_SUBMENU_STYLES="Stíleanna"
MOD_MENU_COM_TEMPLATES_SUBMENU_TEMPLATES="Teimpléid"
MOD_MENU_COM_USERS="Úsáideoirí"
MOD_MENU_COMPONENTS="Comhpháirteanna"
MOD_MENU_CONFIGURATION="Cumraíocht Domhanda"
MOD_MENU_CONFIGURATION_MAILS="Teimpléid Ríomhphoist"
MOD_MENU_CONTROL_PANEL="Painéal Baile"
MOD_MENU_DASHBOARD_LINK="Painéal %s"
MOD_MENU_EXTENSIONS_EXTENSION_MANAGER="Bainistiú"
MOD_MENU_EXTENSIONS_EXTENSIONS="Síntí"
MOD_MENU_EXTENSIONS_LANGUAGE_MANAGER="Teangacha"
MOD_MENU_EXTENSIONS_MODULE_MANAGER="Modúil"
MOD_MENU_EXTENSIONS_MODULE_MANAGER_ADMINISTRATOR="Modúil Riaracháin"
MOD_MENU_EXTENSIONS_MODULE_MANAGER_SITE="Modúil Suíomh"
MOD_MENU_EXTENSIONS_PLUGIN_MANAGER="Breiseáin"
MOD_MENU_EXTENSIONS_TEMPLATE_MANAGER="Teimpléid"
MOD_MENU_FIELD_CHECK_DESC="Seiceáil le haghaidh láithreacht míreanna roghchláir tábhachtacha."
MOD_MENU_FIELD_CHECK_LABEL="Seiceáil Roghchlár"
MOD_MENU_FIELD_FORUMURL_DESC="Cuir isteach an URL chuig fóram seachas an réamhshocrú."
MOD_MENU_FIELD_FORUMURL_LABEL="URL Fóram Tacaíochta Saincheaptha"
MOD_MENU_FIELD_MENUTYPE_LABEL="Roghchlár le Taispeáint"
MOD_MENU_FIELD_MENUTYPE_OPTION_PREDEFINED="Úsáid Réamhshocrú"
MOD_MENU_FIELD_PRESET_DESC="Roghnaigh réamhshocrú le húsáid mar roghchlár cúil"
MOD_MENU_FIELD_PRESET_LABEL="Roghnaigh Réamhshocrú"
MOD_MENU_FIELD_SHOWHELP="Roghchlár Cabhrach"
MOD_MENU_FIELD_SHOWNEW="Cuir Gearrthóga Nua leis"
MOD_MENU_FIELDS="Réimsí"
MOD_MENU_FIELDS_GROUP="Grúpaí Réimsí"
MOD_MENU_GLOBAL_CHECKIN="Seiceáil Isteach Domhanda"
MOD_MENU_HELP="Cabhair"
MOD_MENU_HELP_COMMUNITY="Tairseach Pobail"
MOD_MENU_HELP_COMMUNITY_NEWS="Nuacht an Phobail"
MOD_MENU_HELP_COMMUNITY_NEWSLETTER="Nuachtlitir an Phobail"
MOD_MENU_HELP_DEVELOPER="Acmhainní Forbróra"
MOD_MENU_HELP_DOCUMENTATION="Vicí Doiciméadúcháin"
MOD_MENU_HELP_EVENTS="Imeachtaí Joomla"
MOD_MENU_HELP_EXTENSIONS="Síntí Joomla!"
MOD_MENU_HELP_GITHUB="Joomla ar GitHub"
MOD_MENU_HELP_ISSUES_TRACKER="Rianaitheoir Fadhbanna"
MOD_MENU_HELP_JOOMLA="Cabhair Joomla!"
MOD_MENU_HELP_PARENT_FIND_HELP="Cabhair Bhreise"
MOD_MENU_HELP_PARENT_GET_INVOLVED="Bí Páirteach"
MOD_MENU_HELP_PARENT_MEET_JOOMLERS="Buail le Joomlers"
MOD_MENU_HELP_PARENT_NEWS="Nuacht"
MOD_MENU_HELP_PARENT_RESOURCES="Acmhainní"
MOD_MENU_HELP_PARENT_START_HERE="Tosaigh Anseo"
MOD_MENU_HELP_RESOURCES="Acmhainní Joomla!"
MOD_MENU_HELP_SECURITY="Ionad Slándála"
MOD_MENU_HELP_SHOP="Siopa Joomla!"
MOD_MENU_HELP_SUPPORT_CUSTOM_FORUM="Fóram Tacaíochta Saincheaptha"
MOD_MENU_HELP_SUPPORT_OFFICIAL_FORUM="Fóram Tacaíochta Oifigiúil"
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM="Fóraim Teanga Oifigiúla"
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM_VALUE="511"
MOD_MENU_HELP_TRANSLATIONS="Aistriúcháin Joomla!"
MOD_MENU_HELP_USER_GROUPS="Grúpaí Úsáideoirí Joomla"
MOD_MENU_HELP_XCHANGE="Stack Exchange"
MOD_MENU_HOME_DEFAULT="Baile"
MOD_MENU_HOME_MULTIPLE="Rabhadh! Il-bhaile!"
MOD_MENU_IMPORTANT_ITEM_COMPONENTS_CONTAINER="Coimeádán Comhpháirteanna"
MOD_MENU_IMPORTANT_ITEM_MENU_MANAGER="Bainisteoir Roghchláir"
MOD_MENU_IMPORTANT_ITEM_MODULE_MANAGER="Bainisteoir Modúl"
MOD_MENU_IMPORTANT_ITEMS_INACCESSIBLE_LIST_WARNING="Níl <strong>%2$s</strong> ag an roghchlár riarthóra <strong>%1$s</strong>. Roghnaigh chun <strong><a href='%3$s'>modh aisghabhála roghchláir a chasadh air</a></strong>."
MOD_MENU_INFORMATION="Eolas"
MOD_MENU_INFORMATION_POST_INSTALL_MESSAGES="Teachtaireachtaí Suiteála"
MOD_MENU_INFORMATION_WARNINGS="Rabhadh"
MOD_MENU_INSTALL="Suiteáil"
MOD_MENU_INSTALL_DISCOVER="Fionnachtain"
MOD_MENU_INSTALL_EXTENSIONS="Síneadh"
MOD_MENU_INSTALL_LANGUAGES="Teangacha"
MOD_MENU_INSTALLER_SUBMENU_DATABASE="Bunachar Sonraí"
MOD_MENU_INSTALLER_SUBMENU_DISCOVER="Fionnachtain"
MOD_MENU_INSTALLER_SUBMENU_INSTALL="Suiteáil"
MOD_MENU_INSTALLER_SUBMENU_LANGUAGES="Suiteáil Teangacha"
MOD_MENU_INSTALLER_SUBMENU_MANAGE="Bainistiú"
MOD_MENU_INSTALLER_SUBMENU_UPDATE="Nuashonrú"
MOD_MENU_INSTALLER_SUBMENU_UPDATESITES="Nuashonrú Suímh"
MOD_MENU_INSTALLER_SUBMENU_WARNINGS="Rabhadh"
MOD_MENU_LOGOUT="Logáil Amach"
MOD_MENU_MAINTAIN="Cothabháil"
MOD_MENU_MANAGE="Bainistiú"
MOD_MENU_MANAGE_EXTENSIONS="Síneadh"
MOD_MENU_MANAGE_GUIDEDTOURS="Turas Treoraithe"
MOD_MENU_MANAGE_LANGUAGES="Teangacha"
MOD_MENU_MANAGE_LANGUAGES_CONTENT="Teangacha Ábhair"
MOD_MENU_MANAGE_LANGUAGES_OVERRIDES="Forghníomhaithe Teanga"
MOD_MENU_MANAGE_PLUGINS="Breiseáin"
MOD_MENU_MANAGE_REDIRECTS="Athsheoltaí"
MOD_MENU_MANAGE_SCHEDULED_TASKS="Tascanna Sceidealta"
MOD_MENU_MASS_MAIL_USERS="Úsáideoirí Ríomhphoist Aonair"
MOD_MENU_MEDIA_MANAGER="Meáin"
MOD_MENU_MENU_MANAGER="Bainistiú"
MOD_MENU_MENU_MANAGER_NEW_ADMIN_MENU_ITEM="Cuir Mír Roghchláir Riarthóra leis"
MOD_MENU_MENU_MANAGER_NEW_SITE_MENU_ITEM="Cuir Mír Roghchláir Suímh leis"
MOD_MENU_MENUS="Roghchláir"
MOD_MENU_MENUS_ALL_ITEMS="Gach Mír Roghchláir"
MOD_MENU_MESSAGING="Teachtaireachtaí"
MOD_MENU_MESSAGING_NEW="Teachtaireacht Phríobháideach Nua"
MOD_MENU_MESSAGING_PRIVATE="Teachtaireachtaí Príobháideacha"
MOD_MENU_QUICKTASK_NEW="Mír Nua"
MOD_MENU_READ_PRIVATE_MESSAGES="Léigh Teachtaireachtaí Príobháideacha"
MOD_MENU_RECOVERY_EXIT="Scoir as Modh Aisghabhála"
MOD_MENU_RECOVERY_MENU_ROOT="Aisghabháil Roghchláir"
MOD_MENU_SETTINGS="Socruithe"
MOD_MENU_SYSTEM="Córas"
MOD_MENU_SYSTEM_INFORMATION="Eolas Córas"
MOD_MENU_SYSTEM_INFORMATION_DATABASE="Bunachar Sonraí"
MOD_MENU_SYSTEM_INFORMATION_SYSINFO="Eolas Córas"
MOD_MENU_SYSTEM_PARENT_SETUP="Socrú"
MOD_MENU_TEMPLATE_ADMIN_STYLES="Stíleanna Teimpléad Riarthóra"
MOD_MENU_TEMPLATE_ADMIN_TEMPLATES="Teimpléid Riarthóra"
MOD_MENU_TEMPLATE_SITE_STYLES="Stíleanna Teimpléad Suímh"
MOD_MENU_TEMPLATE_SITE_TEMPLATES="Teimpléid Suímh"
MOD_MENU_TEMPLATES="Teimpléid"
MOD_MENU_UPDATE="Nuashonrú"
MOD_MENU_UPDATE_EXTENSIONS="Síneadh"
MOD_MENU_UPDATE_JOOMLA="Joomla"
MOD_MENU_UPDATE_SOURCES="Nuashonrú Suímh"
MOD_MENU_USER_PROFILE="Mo Phróifíl"
MOD_MENU_XML_DESCRIPTION="Taispeánann an modúl seo modúl roghchláir riarthóra."
