; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LATEST="Ailt - Is Déanaí"
MOD_LATEST_CREATED="Cruthaithe"
MOD_LATEST_CREATED_BY="Cruthaithe Ag"
MOD_LATEST_FIELD_AUTHORS_LABEL="Údair"
MOD_LATEST_FIELD_COUNT_LABEL="Míreanna le Taispeáint"
MOD_LATEST_FIELD_ORDERING_LABEL="Ordú"
MOD_LATEST_FIELD_VALUE_AUTHORS_ANYONE="Duine ar bith"
MOD_LATEST_FIELD_VALUE_AUTHORS_BY_ME="Cuirte nó modhnaithe agam"
MOD_LATEST_FIELD_VALUE_AUTHORS_NOT_BY_ME="Níor cuireadh nó modhnaithe agam"
MOD_LATEST_FIELD_VALUE_ORDERING_ADDED="Cuirte le Déanaí ar dtús"
MOD_LATEST_FIELD_VALUE_ORDERING_MODIFIED="Modhnaithe le Déanaí ar dtús"
MOD_LATEST_HEADING_DATE_CREATED="Dáta Cruthaithe"
MOD_LATEST_HEADING_DATE_MODIFIED="Dáta Modhnaithe"
MOD_LATEST_LATEST_ITEMS="Míreanna is Déanaí"
MOD_LATEST_NO_MATCHING_RESULTS="Níl Torthaí Comhoiriúnacha"
MOD_LATEST_TITLE="Ailt Cruthaithe le Déanaí"
MOD_LATEST_TITLE_CREATED="Ailt Deireanacha Cuirte"
MOD_LATEST_TITLE_CREATED_1="Alt Deireanach Cuirte"
MOD_LATEST_TITLE_CREATED_BY_ME="Ailt Deireanacha Cuirte Agam"
MOD_LATEST_TITLE_CREATED_BY_ME_1="Alt Deireanach Cuirte Agam"
MOD_LATEST_TITLE_CREATED_BY_ME_MORE="Ailt Deireanacha %1$s Cuirte Agam"
MOD_LATEST_TITLE_CREATED_CATEGORY="Ailt Deireanacha Cuirte (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_1="Alt Deireanach Cuirte (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_BY_ME="Ailt Deireanacha Cuirte Agam (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_BY_ME_1="Alt Deireanach Cuirte Agam (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_BY_ME_MORE="Ailt Deireanacha %1$s Cuirte Agam (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_MORE="Ailt Deireanacha %1$s Cuirte (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_NOT_ME="Ailt Deireanacha Níor Cuirte Agam (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_NOT_ME_1="Alt Deireanach Níor Cuirte Agam (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_CATEGORY_NOT_ME_MORE="Ailt Deireanacha %1$s Níor Cuirte Agam (%2$s catagóir)"
MOD_LATEST_TITLE_CREATED_MORE="Ailt Deireanacha %1$s Cuirte"
MOD_LATEST_TITLE_CREATED_NOT_ME="Ailt Deireanacha Níor Cuirte Agam"
MOD_LATEST_TITLE_CREATED_NOT_ME_1="Alt Deireanach Níor Cuirte Agam"
MOD_LATEST_TITLE_CREATED_NOT_ME_MORE="Ailt Deireanacha %1$s Níor Cuirte Agam"
MOD_LATEST_TITLE_MODIFIED="Ailt Deireanacha Modhnaithe"
MOD_LATEST_TITLE_MODIFIED_1="Alt Deireanach Modhnaithe"
MOD_LATEST_TITLE_MODIFIED_BY_ME="Ailt Deireanacha Modhnaithe Agam"
MOD_LATEST_TITLE_MODIFIED_BY_ME_1="Alt Deireanach Modhnaithe Agam"
MOD_LATEST_TITLE_MODIFIED_BY_ME_MORE="Ailt Deireanacha %1$s Modhnaithe Agam"
MOD_LATEST_TITLE_MODIFIED_CATEGORY="Ailt Deireanacha Modhnaithe (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_1="Alt Deireanach Modhnaithe (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_BY_ME="Ailt Deireanacha Modhnaithe Agam (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_BY_ME_1="Alt Deireanach Modhnaithe Agam (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_BY_ME_MORE="Ailt Deireanacha %1$s Modhnaithe Agam (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_MORE="Ailt Deireanacha %1$s Modhnaithe (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_NOT_ME="Ailt Deireanacha Níor Modhnaithe Agam (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_NOT_ME_1="Alt Deireanach Níor Modhnaithe Agam (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_CATEGORY_NOT_ME_MORE="Ailt Deireanacha %1$s Níor Modhnaithe Agam (%2$s catagóir)"
MOD_LATEST_TITLE_MODIFIED_MORE="Ailt Deireanacha %1$s Modhnaithe"
MOD_LATEST_TITLE_MODIFIED_NOT_ME="Ailt Deireanacha Níor Modhnaithe Agam"
MOD_LATEST_TITLE_MODIFIED_NOT_ME_1="Alt Deireanach Níor Modhnaithe Agam"
MOD_LATEST_TITLE_MODIFIED_NOT_ME_MORE="Ailt Deireanacha %1$s Níor Modhnaithe Agam"
MOD_LATEST_UNEXISTING="<em>Neamhní ann</em>"
MOD_LATEST_XML_DESCRIPTION="Taispeánann an modúl seo liosta de na hAirteagail is déanaí a cruthaíodh."
