; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_POPULAR="Ailt Coitianta"
MOD_POPULAR_CREATED="Cruthaithe"
MOD_POPULAR_FIELD_AUTHORS_LABEL="Údair"
MOD_POPULAR_FIELD_COUNT_LABEL="Míreanna le Taispeáint"
MOD_POPULAR_FIELD_VALUE_ADDED_OR_MODIFIED_BY_ME="Cuirte nó modhnaithe agam"
MOD_POPULAR_FIELD_VALUE_ANYONE="Aon duine"
MOD_POPULAR_FIELD_VALUE_NOT_ADDED_OR_MODIFIED_BY_ME="Níor cuireadh nó modhnaithe agam"
MOD_POPULAR_ITEMS="Míreanna Coitianta"
MOD_POPULAR_NO_MATCHING_RESULTS="Gan Torthaí Comhoiriúnacha"
MOD_POPULAR_TITLE="Ailt Coitianta"
MOD_POPULAR_TITLE_1="An tAlt Coitianta is Fearr"
MOD_POPULAR_TITLE_BY_ME="Na hAilt Choitianta is Fearr Uaim"
MOD_POPULAR_TITLE_BY_ME_1="An tAlt Coitianta is Fearr Uaim"
MOD_POPULAR_TITLE_BY_ME_MORE="Na %1$s hAilt Choitianta is Fearr Uaim"
MOD_POPULAR_TITLE_CATEGORY="Na hAilt Choitianta is Fearr (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_1="An tAlt Coitianta is Fearr (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_BY_ME="Na hAilt Choitianta is Fearr Uaim (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_BY_ME_1="An tAlt Coitianta is Fearr Uaim (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_BY_ME_MORE="Na %1$s hAilt Choitianta is Fearr Uaim (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_MORE="Na %1$s hAilt Choitianta is Fearr (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_NOT_ME="Na hAilt Choitianta is Fearr Nach Uaim (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_NOT_ME_1="An tAlt Coitianta is Fearr Nach Uaim (%2$s catagóir)"
MOD_POPULAR_TITLE_CATEGORY_NOT_ME_MORE="Na %1$s hAilt Choitianta is Fearr Nach Uaim (%2$s catagóir)"
MOD_POPULAR_TITLE_MORE="Na %1$s hAilt Choitianta is Fearr"
MOD_POPULAR_TITLE_NOT_ME="Na hAilt Choitianta is Fearr Nach Uaim"
MOD_POPULAR_TITLE_NOT_ME_1="An tAlt Coitianta is Fearr Nach Uaim"
MOD_POPULAR_TITLE_NOT_ME_MORE="Na %1$s hAilt Choitianta is Fearr Nach Uaim"
MOD_POPULAR_UNEXISTING="<em>Neamh ann</em>"
MOD_POPULAR_XML_DESCRIPTION="Taispeánann an modúl seo liosta de na hAilt is coitianta atá foilsithe agus atá fós reatha. D'fhéadfadh go mbeadh cuid acu a thaispeántar imithe in éag cé go bhfuil siad ar na cinn is déanaí."
