; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LOGGED="Úsáideoirí Logáilte Isteach"
MOD_LOGGED_FIELD_COUNT_LABEL="Úsáideoirí le Taispeáint"
MOD_LOGGED_LOGOUT="Logáil Amach"
MOD_LOGGED_NAME="Ainm"
MOD_LOGGED_NO_SESSION_METADATA="Tá meiteashonraí seisiúin díchumasaithe, ní féidir liosta na n-úsáideoirí logáilte isteach a thaispeáint."
MOD_LOGGED_TITLE="Úsáideoirí Deireanacha Logáilte Isteach"
MOD_LOGGED_TITLE_1="Úsáideoir Deireanach Logáilte Isteach"
MOD_LOGGED_TITLE_MORE="Úsáideoirí Deireanacha Logáilte Isteach %d"
MOD_LOGGED_XML_DESCRIPTION="Taispeánann an modúl seo liosta de na hÚsáideoirí Logáilte Isteach."
