; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_PRIVACYCONSENT="Córas - Toiliú Príobháideachais"
PLG_SYSTEM_PRIVACYCONSENT_XML_DESCRIPTION="Breiseán bunúsach chun toiliú úsáideora a iarraidh le polasaí príobháideachais an tsuímh. Déanfar úsáideoirí atá ann cheana féin nach bhfuil tar éis toiliú a thabhairt fós a atreorú ar logáil isteach chun a bpróifíl a nuashonrú."
