; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SAMPLEDATA_MULTILANG="Sonraí Samplacha - Ilteangach"
PLG_SAMPLEDATA_MULTILANG_CONTENT_WORKFLOW_DESCRIPTION="Sreabhadh oibre samplach do \"Sonraí Samplacha - Ilteangach\""
PLG_SAMPLEDATA_MULTILANG_CONTENT_WORKFLOW_TITLE="Sreabhadh Oibre Samplach - Ilteangach"
PLG_SAMPLEDATA_MULTILANG_ERROR_ALLCATEGORIES="Céim %1$u: Theip ar chruthú an mhíre roghchláir 'Liosta Gach Catagóir (%2$s)'."
PLG_SAMPLEDATA_MULTILANG_ERROR_ARTICLE="Céim %1$u: Theip ar chruthú an Airteagal (%2$s)."
PLG_SAMPLEDATA_MULTILANG_ERROR_ASSOC_ALLCATEGORIES="Céim %1$u: Theip ar chomhcheangal na míreanna roghchláir 'Liosta Gach Catagóir'."
PLG_SAMPLEDATA_MULTILANG_ERROR_ASSOC_VARIOUS="Céim %1$u: Theip ar chomhcheangal roinnt catagóirí, airteagal nó míreanna roghchláir 'Blag Catagóire'."
PLG_SAMPLEDATA_MULTILANG_ERROR_BLOG="Céim %1$u: Theip ar chruthú an mhíre roghchláir 'Blag Catagóire (%2$s)'."
PLG_SAMPLEDATA_MULTILANG_ERROR_CATEGORY="Céim %1$u: Theip ar chruthú na Catagóire (%2$s)."
PLG_SAMPLEDATA_MULTILANG_ERROR_CONTENTLANGUAGES="Céim %1$u: Theip ar fhoilsiú roinnt teangacha ábhair."
PLG_SAMPLEDATA_MULTILANG_ERROR_LANGFILTER="Céim %1$u: Theip ar chumasú an breiseáin %2$s."
PLG_SAMPLEDATA_MULTILANG_ERROR_MAINMENU_MODULE="Céim %1$u: Theip ar dhífhoilsiú an Mhodúil 'Príomh-Roghchlár' ina bhfuil an mhír roghchláir 'Baile' socraithe do GACH teanga."
PLG_SAMPLEDATA_MULTILANG_ERROR_MENUMODULES="Céim %1$u: Theip ar chruthú an mhodúil roghchláir %2$s."
PLG_SAMPLEDATA_MULTILANG_ERROR_MENUS="Céim %1$u: Theip ar chruthú an Phríomh-roghchláir (%2$s)."
PLG_SAMPLEDATA_MULTILANG_ERROR_SWITCHER="Céim %1$u: Theip ar chruthú agus ar chumasú an %2$s."
PLG_SAMPLEDATA_MULTILANG_MISSING_LANGUAGE="Ba chóir go mbeadh ar a laghad 2 theanga suiteáilte ar an suíomh agus a dteangacha ábhair cruthaithe."
PLG_SAMPLEDATA_MULTILANG_OVERVIEW_DESC="Sonraí samplacha a bhunóidh suíomh ilteangach.<br>Sula seoltar é, déan cinnte go bhfuil ar a laghad 2 theanga suiteáilte agat lena dTeangacha Ábhair agus nach bhfuil aon sonraí samplacha suiteáilte."
PLG_SAMPLEDATA_MULTILANG_OVERVIEW_TITLE="Sonraí Samplacha Ilteangacha"
PLG_SAMPLEDATA_MULTILANG_STEP1_SUCCESS="Céim 1: Tá an breiseán Scagaire Teanga cumasaithe!"
PLG_SAMPLEDATA_MULTILANG_STEP2_SUCCESS="Céim 2: Tá an modúl Athraigh Teanga cruthaithe agus foilsithe!"
PLG_SAMPLEDATA_MULTILANG_STEP3_SUCCESS="Céim 3: Tá gach Teanga Ábhair foilsithe!"
PLG_SAMPLEDATA_MULTILANG_STEP4_SUCCESS="Céim 4: Tá Príomh-Roghchláir shonracha cruthaithe chomh maith le míreanna roghchláir 'Liosta Gach Catagóir' comhcheangailte!"
PLG_SAMPLEDATA_MULTILANG_STEP5_SUCCESS="Céim 5: Tá modúil Príomh-Roghchláir shonracha cruthaithe!"
PLG_SAMPLEDATA_MULTILANG_STEP6_SUCCESS="Céim 6: Tá sreabhadh oibre, catagóirí, airteagail agus míreanna roghchláir 'Blag Catagóire' cruthaithe agus comhcheangailte!"
PLG_SAMPLEDATA_MULTILANG_STEP7_SUCCESS="Céim 7: Tá an Modúl Príomh-Roghchláir ina bhfuil an mhír roghchláir Baile socraithe do GACH teanga dífhoilsithe!"
PLG_SAMPLEDATA_MULTILANG_STEP8_SUCCESS="Tá Sonraí Samplacha Ilteangacha suiteáilte!"
PLG_SAMPLEDATA_MULTILANG_STEP_FAILED="Theip ar Chéim %1$u: %2$s"
PLG_SAMPLEDATA_MULTILANG_STEP_SKIPPED="Céim %1$u Scipeáilte: níl '%2$s' suiteáilte nó cumasaithe."
PLG_SAMPLEDATA_MULTILANG_XML_DESCRIPTION="Soláthraíonn sé na sonraí samplacha ilteangacha. Is féidir é a shuiteáil ag úsáid an mhodúil sonraí samplacha."
