; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_BOOK="Schema.org - Leabhar"
PLG_SCHEMAORG_BOOK_DESCRIPTION_LABEL="Is féidir tuilleadh eolais ar an Cineál Leabhair Schema.org a fháil ag <a href=\"https://schema.org/Book\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/Book</a>"
PLG_SCHEMAORG_BOOK_FIELD_ABRIDGED_LABEL="Gearrtha"
PLG_SCHEMAORG_BOOK_FIELD_ADDRESS_LABEL="Seoladh"
PLG_SCHEMAORG_BOOK_FIELD_AUDIOBOOK_LABEL="Leabhar Fuaime"
PLG_SCHEMAORG_BOOK_FIELD_AUTHOR_LABEL="Údar"
PLG_SCHEMAORG_BOOK_FIELD_BOOK_EDITION_LABEL="Eagrán Leabhair"
PLG_SCHEMAORG_BOOK_FIELD_BOOK_FORMAT_LABEL="Formáid Leabhair"
PLG_SCHEMAORG_BOOK_FIELD_DATE_PUBLISHED_LABEL="Dáta Foilsithe"
PLG_SCHEMAORG_BOOK_FIELD_EMAIL_LABEL="Ríomhphost"
PLG_SCHEMAORG_BOOK_FIELD_E_BOOK_LABEL="R-leabhar"
PLG_SCHEMAORG_BOOK_FIELD_GENERIC_FIELD_LABEL="Réimse Ginearálta"
PLG_SCHEMAORG_BOOK_FIELD_GENERIC_TITLE_LABEL="Teideal"
PLG_SCHEMAORG_BOOK_FIELD_GENERIC_VALUE_LABEL="Luach"
PLG_SCHEMAORG_BOOK_FIELD_GRAPHIC_NOVEL="Úrscéal Grafach"
PLG_SCHEMAORG_BOOK_FIELD_HARDCOVER_LABEL="Clúdach Crua"
PLG_SCHEMAORG_BOOK_FIELD_ILLUSTRATOR_LABEL="Maisitheoir"
PLG_SCHEMAORG_BOOK_FIELD_ILLUSTRATOR_NAME_LABEL="Ainm"
PLG_SCHEMAORG_BOOK_FIELD_ISBN_LABEL="ISBN"
PLG_SCHEMAORG_BOOK_FIELD_LOCALITY_LABEL="Ceantar"
PLG_SCHEMAORG_BOOK_FIELD_NAME_LABEL="Teideal"
PLG_SCHEMAORG_BOOK_FIELD_NUMBER_OF_PAGES_LABEL="Líon na Leathanaigh"
PLG_SCHEMAORG_BOOK_FIELD_PAPERBACK_LABEL="Clúdach Bog"
PLG_SCHEMAORG_BOOK_FIELD_POSTAL_CODE_LABEL="Cód Poist"
PLG_SCHEMAORG_BOOK_FIELD_STREET_ADDRESS_LABEL="Seoladh Sráide"
PLG_SCHEMAORG_BOOK_FIELD_URL_LABEL="Url"
PLG_SCHEMAORG_BOOK_XML_DESCRIPTION="Cuireann sé Leabhar leis mar chineál scéime nua i scéimeanna atá ann cheana."
