; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_JOOMLA="Ábhar - Joomla"
PLG_CONTENT_JOOMLA_FIELD_CHECK_CATEGORIES_DESC="Seiceáil go bhfuil na catagóirí go hiomlán folamh sula mbaintear iad."
PLG_CONTENT_JOOMLA_FIELD_CHECK_CATEGORIES_LABEL="Seiceáil Bain Catagóir"
PLG_CONTENT_JOOMLA_FIELD_EMAIL_NEW_FE_DESC="Seol ríomhphost chuig úsáideoirí má tá 'Seol ríomhphost' ar siúl nuair a chuirtear alt nua isteach tríd an Tosaigh."
PLG_CONTENT_JOOMLA_FIELD_EMAIL_NEW_FE_LABEL="Ríomhphost ar Alt Nua Suímh"
PLG_CONTENT_JOOMLA_SCHEMA_CONTACT_DESC="Nuair atá sé gníomhach, gineann sé snippets saibhir teagmhála ón sonraí réamhshocraithe"
PLG_CONTENT_JOOMLA_SCHEMA_CONTACT_LABEL="Scéim Teagmhála"
PLG_CONTENT_JOOMLA_SCHEMA_CONTENT_DESC="Nuair atá sé gníomhach, gineann sé snippets saibhir ábhair ón sonraí réamhshocraithe"
PLG_CONTENT_JOOMLA_SCHEMA_CONTENT_LABEL="Scéim Ábhair"
PLG_CONTENT_JOOMLA_XML_DESCRIPTION="Déanann an breiseán seo próiseáil catagóirí do shíneadh croí; seolann sé ríomhphost nuair a chuirtear alt nua isteach sa Tosaigh nó nuair a dhéantar aistriú."
