; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_EMAIL="Fíordheimhniú Ilfhachtóra - Cód Fíordheimhnithe trí Ríomhphost"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_FORCE_ENABLE_DESC="Ar cheart dom an Cód Fíordheimhnithe trí Ríomhphost a chur leis go huathoibríoch mar rogha do <em>gach</em> úsáideoir? Úsáideach chun rogha cúltaca a sholáthar d'úsáideoirí a chaill rochtain ar a bpríomhfhíordheimhniú agus nach bhfuil cóip de na cóid cúltaca coinnithe acu, ar chostas áirithe rialaithe agus slándála."
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_FORCE_ENABLE_LABEL="Cumasaigh go Fórsa"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_120="Dhá nóiméad (molta)"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_180="Trí nóiméad"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_300="Cúig nóiméad"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_30="Leath nóiméad"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_60="Nóiméad amháin"
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_DESC="Gintear cód nua gach oiread seo nóiméad. Tabhair faoi deara go bhfuil cód ginte bailí ar a laghad an méid ama seo agus ar a mhéad faoi dhó an méid ama seo. Dá airde an tréimhse seo is ea is dóichí go ndéanfar an cód a bhrú fórsa, dá bhrí sin is lú slándáil atá ag do shuíomh. Is trádáil mhaith é tréimhse 2 nóiméad idir inúsáidteacht agus slándáil."
PLG_MULTIFACTORAUTH_EMAIL_CONFIG_TIMESTEP_LABEL="Tréimhse Giniúna Cód"
PLG_MULTIFACTORAUTH_EMAIL_EMAIL_BODY="Fíordheimhniú Ilfhachtóra ar {SITENAME}. Is é do chód fíordheimhnithe {CODE}."
PLG_MULTIFACTORAUTH_EMAIL_EMAIL_SUBJECT="Is é do chód fíordheimhnithe {SITENAME} -{CODE}-"
PLG_MULTIFACTORAUTH_EMAIL_ERR_INVALID_CODE="Cód neamhbhailí nó in éag. Athlódáil an leathanach le do thoil chun cód nua a sheoladh chugat féin. Déan cinnte an cód a iontráil laistigh de dhá nóiméad ó d'iarr tú an cód."
PLG_MULTIFACTORAUTH_EMAIL_LBL_DISPLAYEDAS="Cód trí Ríomhphost"
PLG_MULTIFACTORAUTH_EMAIL_LBL_LABEL="Cód Fíordheimhnithe"
PLG_MULTIFACTORAUTH_EMAIL_LBL_PRE_MESSAGE="Fuair tú cód Fíordheimhniú Ilfhachtóra sé dhigit i do ríomhphost. Cuir isteach é thíos le do thoil."
PLG_MULTIFACTORAUTH_EMAIL_LBL_SETUP_PLACEHOLDER="Cód Fíordheimhnithe Sé Dhigit"
PLG_MULTIFACTORAUTH_EMAIL_LBL_SHORTINFO="Faigh cóid sé dhigit trí ríomhphost."
PLG_MULTIFACTORAUTH_EMAIL_MAIL_MAIL_DESC="Seolta chuig úsáideoirí ón leathanach Fíordheimhniú Ilfhachtóra nuair a úsáidtear an rogha \"Cód Fíordheimhnithe trí Ríomhphost\"."
PLG_MULTIFACTORAUTH_EMAIL_MAIL_MAIL_TITLE="Cód seolta trí ríomhphost"
PLG_MULTIFACTORAUTH_EMAIL_XML_DESCRIPTION="Úsáid cóid slándála sé dhigit, teoranta ama a sheoltar chugat trí ríomhphost."
