; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_ROTATELOGS="Tasc - Rothlaigh Logaí"
PLG_TASK_ROTATELOGS_LOGSTOKEEP_LABEL="Logaí Uasta"
PLG_TASK_ROTATELOGS_ROTATION_DESC="Rothlaíonn sé comhaid loga go tréimhsiúil."
PLG_TASK_ROTATELOGS_ROTATION_TITLE="Rothlaigh Logaí"
PLG_TASK_ROTATELOGS_XML_DESCRIPTION="Gnáthaimh tascanna chun Rothlú Logaí a sceidealú."
