; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_ACTIONLOG_JOOMLA="Log Gníomhaíochta - Joomla"
PLG_ACTIONLOG_JOOMLA_API="Rinne úsáideoir <a href='{accountlink}'>{username}</a> {verb} ar {url}"
PLG_ACTIONLOG_JOOMLA_APPLICATION_ADMINISTRATOR="riarthóir"
PLG_ACTIONLOG_JOOMLA_APPLICATION_API="api"
PLG_ACTIONLOG_JOOMLA_APPLICATION_CLI="cli"
PLG_ACTIONLOG_JOOMLA_APPLICATION_SITE="suíomh"
PLG_ACTIONLOG_JOOMLA_XML_DESCRIPTION="Taifead gníomhartha úsáideoirí ar an suíomh do shíneadh croí Joomla ionas gur féidir iad a athbhreithniú más gá."
; Content types title
PLG_ACTIONLOG_JOOMLA_TYPE_ACCESS_LEVEL="leibhéal rochtana"
PLG_ACTIONLOG_JOOMLA_TYPE_APPLICATION_CONFIG="Cumraíocht Domhanda"
PLG_ACTIONLOG_JOOMLA_TYPE_ARTICLE="alt"
PLG_ACTIONLOG_JOOMLA_TYPE_BANNER="meirge"
PLG_ACTIONLOG_JOOMLA_TYPE_BANNER_CLIENT="cliant meirge"
PLG_ACTIONLOG_JOOMLA_TYPE_CATEGORY="catagóir"
PLG_ACTIONLOG_JOOMLA_TYPE_COMPONENT="comhpháirt"
PLG_ACTIONLOG_JOOMLA_TYPE_COMPONENT_CONFIG="Cumraíocht Comhpháirte"
PLG_ACTIONLOG_JOOMLA_TYPE_CONTACT="teagmháil"
PLG_ACTIONLOG_JOOMLA_TYPE_FIELD="réimse"
PLG_ACTIONLOG_JOOMLA_TYPE_FILE="comhad"
PLG_ACTIONLOG_JOOMLA_TYPE_LANGUAGE="teanga"
PLG_ACTIONLOG_JOOMLA_TYPE_LIBRARY="leabharlann"
PLG_ACTIONLOG_JOOMLA_TYPE_LINK="athsheoladh nasc"
PLG_ACTIONLOG_JOOMLA_TYPE_LINK_REDIRECT="athsheoladh nasc"
PLG_ACTIONLOG_JOOMLA_TYPE_MEDIA="meáin"
PLG_ACTIONLOG_JOOMLA_TYPE_MENU="biachlár"
PLG_ACTIONLOG_JOOMLA_TYPE_MENU_ITEM="míre biachláir"
PLG_ACTIONLOG_JOOMLA_TYPE_MODULE="módúl"
PLG_ACTIONLOG_JOOMLA_TYPE_NEWSFEED="beathaisnéis nuachta"
PLG_ACTIONLOG_JOOMLA_TYPE_PACKAGE="pacáiste"
PLG_ACTIONLOG_JOOMLA_TYPE_PLUGIN="breiseán"
PLG_ACTIONLOG_JOOMLA_TYPE_STYLE="stíl teimpléid"
PLG_ACTIONLOG_JOOMLA_TYPE_TAG="clib"
PLG_ACTIONLOG_JOOMLA_TYPE_TASK="Tasc"
PLG_ACTIONLOG_JOOMLA_TYPE_TEMPLATE="teimpléad"
PLG_ACTIONLOG_JOOMLA_TYPE_USER="úsáideoir"
PLG_ACTIONLOG_JOOMLA_TYPE_USER_GROUP="grúpa úsáideoirí"
PLG_ACTIONLOG_JOOMLA_TYPE_USER_NOTE="nóta úsáideoirí"
PLG_ACTIONLOG_JOOMLA_USER_BLOCK="Chuir úsáideoir <a href='{accountlink}'>{username}</a> bac ar úsáideoir <a href='{itemlink}'>{title}</a>"
PLG_ACTIONLOG_JOOMLA_USER_CACHE="Scrios úsáideoir <a href='{accountlink}'>{username}</a> grúpa taisce {group}"
PLG_ACTIONLOG_JOOMLA_USER_CHECKIN="Rinne úsáideoir <a href='{accountlink}'>{username}</a> seiceáil isteach chuig tábla {table}"
PLG_ACTIONLOG_JOOMLA_USER_LOG="Ghlan úsáideoir <a href='{accountlink}'>{username}</a> asraon nó níos mó ón log gníomhaíochta"
PLG_ACTIONLOG_JOOMLA_USER_LOGEXPORT="D'onnmhairigh úsáideoir <a href='{accountlink}'>{username}</a> asraon nó níos mó ón log gníomhaíochta"
PLG_ACTIONLOG_JOOMLA_USER_LOGGED_IN="Logáil úsáideoir <a href='{accountlink}'>{username}</a> isteach chuig {app}"
PLG_ACTIONLOG_JOOMLA_USER_LOGGED_OUT="Logáil úsáideoir <a href='{accountlink}'>{username}</a> amach ó {app}"
PLG_ACTIONLOG_JOOMLA_USER_LOGIN_FAILED="Theip ar iarracht logáil isteach mar <a href='{accountlink}'>{username}</a> chuig {app}"
PLG_ACTIONLOG_JOOMLA_USER_REGISTERED="Chláraigh úsáideoir <a href='{accountlink}'>{username}</a> le haghaidh cuntas"
PLG_ACTIONLOG_JOOMLA_USER_REGISTRATION_ACTIVATE="Gníomhachtaigh úsáideoir <a href='{accountlink}'>{username}</a> an cuntas"
PLG_ACTIONLOG_JOOMLA_USER_REMIND="D'iarr úsáideoir <a href='{accountlink}'>{username}</a> meabhrúchán ainm úsáideora dá gcuntas"
PLG_ACTIONLOG_JOOMLA_USER_RESET_COMPLETE="Chríochnaigh úsáideoir <a href='{accountlink}'>{username}</a> athshocrú pasfhocail dá gcuntas"
PLG_ACTIONLOG_JOOMLA_USER_RESET_REQUEST="D'iarr úsáideoir <a href='{accountlink}'>{username}</a> athshocrú pasfhocail dá gcuntas"
PLG_ACTIONLOG_JOOMLA_USER_UNBLOCK="D'úsáideoir <a href='{accountlink}'>{username}</a> dhíghlasáil úsáideoir <a href='{itemlink}'>{title}</a>"
PLG_ACTIONLOG_JOOMLA_USER_UPDATE="D'úsáideoir <a href='{accountlink}'>{username}</a> nuashonraigh Joomla ó {oldversion} go {version}"
; Component
PLG_ACTIONLOG_JOOMLA_APPLICATION_CONFIG_UPDATED="D'úsáideoir <a href='{accountlink}'>{username}</a> d'athraigh socruithe chumraíocht na feidhmchláir"
PLG_ACTIONLOG_JOOMLA_COMPONENT_CONFIG_UPDATED="D'úsáideoir <a href='{accountlink}'>{username}</a> d'athraigh socruithe an chomhpháirt {extension_name}"
; Extensions
PLG_ACTIONLOG_JOOMLA_EXTENSION_INSTALLED="D'úsáideoir <a href='{accountlink}'>{username}</a> shuiteáil an {type} {extension_name}"
PLG_ACTIONLOG_JOOMLA_EXTENSION_UNINSTALLED="D'úsáideoir <a href='{accountlink}'>{username}</a> dhíshuiteáil an {type} {extension_name}"
PLG_ACTIONLOG_JOOMLA_EXTENSION_UPDATED="D'úsáideoir <a href='{accountlink}'>{username}</a> nuashonraigh an {type} {extension_name}"
PLG_ACTIONLOG_JOOMLA_PLUGIN_INSTALLED="D'úsáideoir <a href='{accountlink}'>{username}</a> shuiteáil an breiseán <a href='index.php?option=com_plugins&task=plugin.edit&extension_id={id}'>{extension_name}</a>"
; Guided Tours
PLG_ACTIONLOG_JOOMLA_GUIDEDTOURS_TOURCOMPLETED="D'úsáideoir <a href='{accountlink}'>{username}</a> chríochnaigh an turas '{title}'"
PLG_ACTIONLOG_JOOMLA_GUIDEDTOURS_TOURDELAYED="D'úsáideoir <a href='{accountlink}'>{username}</a> chuir moill ar an turas '{title}'"
PLG_ACTIONLOG_JOOMLA_GUIDEDTOURS_TOURSKIPPED="D'úsáideoir <a href='{accountlink}'>{username}</a> scipeáil an turas '{title}'"
