; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_CHECK_FILES="Tasc - Seiceáil Comhaid"
PLG_TASK_CHECK_FILES_LABEL_DIMENSION_LIMIT="Teorainn (px)"
PLG_TASK_CHECK_FILES_LABEL_MAXIMAGES="Uasmhéid Íomhánna"
PLG_TASK_CHECK_FILES_LABEL_MAXIMAGES_DESC="An líon uasta íomhánna le próiseáil i rith amháin. Má shocraítear an uimhir seo ró-ard, d'fhéadfadh an tasc am a chaitheamh."
PLG_TASK_CHECK_FILES_LABEL_DIRECTORY="Eolaire"
PLG_TASK_CHECK_FILES_LABEL_IMAGE_DIMENSION="Toise"
PLG_TASK_CHECK_FILES_LOG_IMAGE_PATH_NA="Níl cosán na híomhá ann!"
PLG_TASK_CHECK_FILES_LOG_IMAGE_SAVE_FAIL="Theip ar shábháil comhad íomhá"
PLG_TASK_CHECK_FILES_LOG_RESIZE_FAIL="Theip ar athmhéid íomhá mar gheall ar earráid i loighic an bhreiseáin..."
PLG_TASK_CHECK_FILES_LOG_RESIZING_IMAGE="Aimsíodh íomhá de mhéid %1$sx%2$s px; athmhéid go %3$sx%4$s px. Comhad: %5$s"
PLG_TASK_CHECK_FILES_TASK_IMAGE_SIZE_DESC="Seiceáil íomhánna, athmhéid má tá siad níos mó ná mar a cheadaítear. Aird: Déanfar an comhad bunaidh a fhorscríobh!"
PLG_TASK_CHECK_FILES_TASK_IMAGE_SIZE_TITLE="Seiceáil Méid Íomhá"
PLG_TASK_CHECK_FILES_XML_DESCRIPTION="Cuireann sé gnáthaimh tasc ar fáil chun comhaid ró-mhóra a sheiceáil, agus gníomhartha gaolmhara más féidir."
