; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_UPDATENOTIFICATION="Tasc - Fógra Nuashonraithe Joomla!"
PLG_TASK_UPDATENOTIFICATION_XML_DESCRIPTION="Seiceálann an tasc seo go tréimhsiúil le haghaidh leaganacha nua de Joomla! Nuair a aimsítear ceann, seolfar ríomhphost chugat, ag meabhrú duit nuashonrú a dhéanamh. Is féidir leat an ríomhphost a shaincheapadh ag Córas &rarr; Teimpléid Ríomhphoist."
