; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_TERMS="Úsáideoir - Téarmaí agus Coinníollacha"
PLG_USER_TERMS_FIELD_ARTICLE_DESC="Roghnaigh an t-alt ón liosta nó cruthaigh ceann nua."
PLG_USER_TERMS_FIELD_ARTICLE_LABEL="Alt Téarmaí & Coinníollacha"
PLG_USER_TERMS_FIELD_ERROR="Tá gá le comhaontú le Téarmaí & Coinníollacha an tsuímh."
PLG_USER_TERMS_FIELD_LABEL="Téarmaí & Coinníollacha"
PLG_USER_TERMS_LABEL="Téarmaí & Coinníollacha"
PLG_USER_TERMS_LOGGING_CONSENT_TO_TERMS="Thug úsáideoir <a href='{accountlink}'>{username}</a> a thoiliú do na téarmaí agus coinníollacha le linn clárúcháin."
PLG_USER_TERMS_NOTE_FIELD_DEFAULT="Trí chlárú leis an suíomh gréasáin seo, glacann tú leis na Téarmaí & Coinníollacha."
PLG_USER_TERMS_NOTE_FIELD_DESC="Achoimre ar théarmaí & coinníollacha an tsuímh. Má fhágtar bán é, úsáidfear an teachtaireacht réamhshocraithe."
PLG_USER_TERMS_NOTE_FIELD_LABEL="Téarmaí & Coinníollacha Gearra"
PLG_USER_TERMS_OPTION_AGREE="Aontaím"
PLG_USER_TERMS_OPTION_DO_NOT_AGREE="Ní aontaím"
PLG_USER_TERMS_SUBJECT="Polasaí Príobháideachais"
PLG_USER_TERMS_XML_DESCRIPTION="Breiseán bunúsach chun toiliú úsáideora a iarraidh do théarmaí agus coinníollacha an tsuímh."
