; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_USERGROUPLIST="Réimsí - Liosta Grúpaí Úsáideoirí"
PLG_FIELDS_USERGROUPLIST_DEFAULT_VALUE_DESC="Liosta de IDanna grúpaí úsáideoirí, scartha le camóg."
PLG_FIELDS_USERGROUPLIST_DEFAULT_VALUE_LABEL="Grúpaí Úsáideoirí Réamhshocraithe"
PLG_FIELDS_USERGROUPLIST_LABEL="Grúpaí Úsáideoirí (%s)"
PLG_FIELDS_USERGROUPLIST_PARAMS_MULTIPLE_LABEL="Il"
PLG_FIELDS_USERGROUPLIST_XML_DESCRIPTION="Ligeann an breiseán seo duit réimsí nua de chineál 'liosta grúpaí úsáideoirí' a chruthú in aon síneadh ina dtacaítear le réimsí saincheaptha."
