; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_TOKEN="Úsáideoir - Tócan API Joomla"
PLG_USER_TOKEN_ALLOWEDUSERGROUPS_DESC="Cé na Grúpaí Úsáideoirí Joomla atá ceadaithe tócáin Joomla a úsáid chun fíordheimhniú a dhéanamh ar an bhfeidhmchlár API Joomla. Rialaíonn sé freisin cé na grúpaí úsáideoirí a fheiceann an comhéadan bainistíochta Tócan Joomla ina bpróifíl úsáideora. Réamhshocrú: Grúpa Super Users ionsuite Joomla (ID Grúpa Úsáideora 8)."
PLG_USER_TOKEN_ALLOWEDUSERGROUPS_LABEL="Grúpaí Úsáideoirí Ceadaithe"
PLG_USER_TOKEN_XML_DESCRIPTION="Ceadaíonn bainistíocht na dtócan slándála a úsáidtear chun fíordheimhniú a dhéanamh ar an bhfeidhmchlár API Joomla (rochtain iargúlta ar do shuíomh). Tá na tócáin seo go docht pearsanta. Is féidir leat do thócan féin a fheiceáil ach ní féidir leat tócáin úsáideoirí eile a dhíchumasú nó a athshocrú ach amháin."
