; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTACTCREATOR_ERR_FAILED_CREATING_CONTACT="Theip cruthú teagmhála uathoibríoch. Déan teagmháil le riarthóir an tsuímh le do thoil."
PLG_CONTACTCREATOR_ERR_NO_CATEGORY="Theip cruthú uathoibríoch teagmhála toisc nach bhfuil catagóir teagmhála socraithe!"
PLG_CONTACTCREATOR_FIELD_AUTOMATIC_WEBPAGE_DESC="Sreang formáidithe chun leathanach gréasáin teagmhála a ghiniúint go huathoibríoch. Cuirtear [name] in ionad an ainm, [username] in ionad an ainm úsáideora, [userid] in ionad an ID úsáideora agus [email] in ionad an ríomhphoist."
PLG_CONTACTCREATOR_FIELD_AUTOMATIC_WEBPAGE_LABEL="Leathanach Gréasáin Uathoibríoch"
PLG_CONTACTCREATOR_FIELD_AUTOPUBLISH_LABEL="Foilsigh an Teagmháil go huathoibríoch"
PLG_CONTACTCREATOR_XML_DESCRIPTION="Breiseán chun faisnéis teagmhála a chruthú go huathoibríoch do úsáideoirí nua."
PLG_USER_CONTACTCREATOR="Úsáideoir - Cruthaitheoir Teagmhála"
