; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_EMAILCLOAK="Ábhar - Clúdach Ríomhphoist"
PLG_CONTENT_EMAILCLOAK_LINKABLE="Mar sheoladh mailto in-nascach"
PLG_CONTENT_EMAILCLOAK_MODE_LABEL="Mód"
PLG_CONTENT_EMAILCLOAK_NONLINKABLE="Téacs Neamh-in-nascach"
PLG_CONTENT_EMAILCLOAK_XML_DESCRIPTION="Clúdaíonn sé gach seoladh ríomhphoist san ábhar ó spambots ag úsáid JavaScript."
