; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_PRIVACYCONSENT="Córas - Toiliú Príobháideachais"
PLG_SYSTEM_PRIVACYCONSENT_BODY="<p>Thug an t-úsáideoir cead a gcuid faisnéise úsáideora a stóráil ag úsáid an seoladh IP <strong>%s</strong></p><p>Ba é sreangán gníomhaire úsáideora bhrabhsálaí an úsáideora:<br>%s</p><p>Taifeadadh an fhaisnéis seo go huathoibríoch nuair a chuir an t-úsáideoir a gcuid sonraí isteach ar an suíomh gréasáin agus a sheiceáil an bosca dearbhaithe.</p>"
PLG_SYSTEM_PRIVACYCONSENT_CONSENT="Thug úsáideoir <a href='{accountlink}'>{username}</a> cead don bheartas príobháideachais."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ARTICLE_DESC="Roghnaigh an t-alt ón liosta nó cruthaigh ceann nua."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ARTICLE_LABEL="Alt Príobháideachais"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ERROR="Tá ceadú ar Bheartas Príobháideachais an tsuímh riachtanach."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_LABEL="Beartas Príobháideachais"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_MENU_ITEM_LABEL="Mír Roghchláir Príobháideachais"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_ARTICLE="Alt"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_LABEL="Cineál Príobháideachais"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_MENU_ITEM="Mír Roghchláir"
PLG_SYSTEM_PRIVACYCONSENT_LABEL="Príobháideachas Suíomh Gréasáin"
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT="Trí chlárú leis an suíomh gréasáin seo agus glacadh leis an mBeartas Príobháideachais aontaíonn tú go stórálfaidh an suíomh gréasáin seo do chuid faisnéise."
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DESC="Achoimre ar bheartas príobháideachais an tsuímh. Má fhágtar bán é úsáidfear an teachtaireacht réamhshocraithe."
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_LABEL="Beartas Príobháideachais Gearr"
PLG_SYSTEM_PRIVACYCONSENT_OPTION_AGREE="Aontaím"
PLG_SYSTEM_PRIVACYCONSENT_OPTION_DO_NOT_AGREE="Ní aontaím"
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_DEFAULT="Deimhnigh le do thoil go dtoilíonn tú leis an suíomh gréasáin seo do chuid faisnéise a stóráil trí aontú leis an mBeartas Príobháideachais."
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_DESC="Teachtaireacht saincheaptha le taispeáint ar atreorú. Má fhágtar bán é úsáidfear an teachtaireacht réamhshocraithe."
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_LABEL="Teachtaireacht Atreoraithe"
PLG_SYSTEM_PRIVACYCONSENT_SUBJECT="Beartas Príobháideachais"
PLG_SYSTEM_PRIVACYCONSENT_XML_DESCRIPTION="Breiseán bunúsach chun cead úsáideora a iarraidh ar bheartas príobháideachais an tsuímh. Atreorófar úsáideoirí atá ann cheana nach bhfuil tar éis aontú fós ar logáil isteach chun a bpróifíl a nuashonrú."

; All the following strings are deprecated and will be removed with 6.0
PLG_SYSTEM_PRIVACYCONSENT_CACHETIMEOUT_DESC="Cé chomh minic a dhéantar an seiceáil."
PLG_SYSTEM_PRIVACYCONSENT_CACHETIMEOUT_LABEL="Seiceáil tréimhsiúil (laethanta)"
PLG_SYSTEM_PRIVACYCONSENT_CONSENTEXPIRATION_DESC="Líon na laethanta tar éis a rachaidh an toiliú príobháideachais in éag."
PLG_SYSTEM_PRIVACYCONSENT_CONSENTEXPIRATION_LABEL="Éag"
PLG_SYSTEM_PRIVACYCONSENT_EMAIL_REMIND_BODY="Rachaidh do Thoiliú Príobháideachais a tugadh ag {URL} in éag i gceann cúpla lá, is féidir leat an toiliú príobháideachais don suíomh gréasáin seo a athnuachan.\n\nChun é seo a dhéanamh, is féidir leat ceann de na tascanna seo a leanas a chomhlánú:\n\n1. Tabhair cuairt ar an URL seo a leanas: {TOKENURL}\n\n2. Cóipeáil do thicéad ón ríomhphost seo, tabhair cuairt ar an URL tagartha, agus greamaigh do thicéad isteach sa fhoirm.\nURL: {FORMURL}\nTicéad: {TOKEN}\n\nTabhair faoi deara nach bhfuil an ticéad seo bailí ach don chuntas seo."
PLG_SYSTEM_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT="Toiliú Príobháideachais ag {SITENAME}"
PLG_SYSTEM_PRIVACYCONSENT_EXPIRATION_FIELDSET_LABEL="Éag"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ENABLED_DESC="Nuair a chuirtear ar chumas é déanann sé seiceálacha ar éag toiliú."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ENABLED_LABEL="Cumasaigh"
PLG_SYSTEM_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_DESC="Meabhrúchán chun an toiliú príobháideachais don suíomh gréasáin seo a athnuachan."
PLG_SYSTEM_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_TITLE="Córas - Toiliú Príobháideachais: Athnuaigh Toiliú"
PLG_SYSTEM_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE="Tá toiliú príobháideachais imithe in éag do %1$s."
PLG_SYSTEM_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_SUBJECT="Toiliú Príobháideachais Imbhuailte"
PLG_SYSTEM_PRIVACYCONSENT_REMINDBEFORE_DESC="Líon na laethanta chun meabhrúchán a sheoladh roimh dheireadh an toiliú príobháideachais."
PLG_SYSTEM_PRIVACYCONSENT_REMINDBEFORE_LABEL="Meabhraigh"
