; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_GLOBALCHECKIN="Tasc - Seiceáil Isteach Domhanda"
PLG_TASK_GLOBALCHECKIN_DELAY_LABEL="Tréimhse Íosta Roimh Sheiceáil Isteach (uaireanta)"
PLG_TASK_GLOBALCHECKIN_DESC="Seiceáil isteach míreanna atá seiceáilte amach."
PLG_TASK_GLOBALCHECKIN_TITLE="Seiceáil Isteach Domhanda"
PLG_TASK_GLOBALCHECKIN_XML_DESCRIPTION="Breiseán chun seiceáil isteach domhanda a dhéanamh ar mhíreanna atá seiceáilte amach."
