; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SKIPTO="Córas - Nascleanúint Skip-To"
PLG_SYSTEM_SKIPTO_XML_DESCRIPTION="Cruthaíonn an breiseán roghchlár anuas a bhfuil na naisc chuig na háiteanna tábhachtacha ar leathanach gréasáin ar leith ann. Déanann sé seo níos éasca d'úsáideoirí méarchláir agus léitheoirí scáileáin léim go tapa chuig an áit atá ag teastáil trína roghnú ón liosta roghanna."
