; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_DOWNLOADKEY="Deilbhín Tapa - Fógra Eochair Íoslódála in Iarraidh"
PLG_QUICKICON_DOWNLOADKEY_XML_DESCRIPTION="Seiceálann sé cé na suíomhanna nuashonraithe de shíneadh (íoslódáil íoctha) atá in easnamh ar an eolas comhfhreagrach Eochair Íoslódála agus tugann sé fógra duit nuair a thugann tú cuairt ar an leathanach Painéal Baile."
