; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SAMPLEDATA_BLOG="Sonraí Samplacha - Blag"
PLG_SAMPLEDATA_BLOG_XML_DESCRIPTION="Soláthraíonn sé sonraí samplacha blag do Cassiopeia. Is féidir é a shuiteáil ag úsáid an mhodúil sonraí samplacha."
