; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_YUBIKEY="Fíordheimhniú Ilfhachtóra - YubiKey"
PLG_MULTIFACTORAUTH_YUBIKEY_XML_DESCRIPTION="Ligeann sé d'úsáideoirí ar do shuíomh Fíordheimhniú Ilfhachtóra a úsáid ag baint úsáide as sliseanna crua-earraí slán YubiKey. Teastaíonn a YubiKey féin ó úsáideoirí atá ar fáil ó <a href=\"https://www.yubico.com\" target=\"_blank\" rel=\"noopener noreferrer\">www.yubico.com</a>. Chun Fíordheimhniú Ilfhachtóra a úsáid, caithfidh úsáideoirí a bpróifíl úsáideora a chur in eagar agus Fíordheimhniú Ilfhachtóra a chumasú."
