; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_JOOMLA="Ábhar - Joomla"
PLG_CONTENT_JOOMLA_XML_DESCRIPTION="Déanann an breiseán seo próiseáil catagóire do shíneadh croí; seolann sé ríomhphost nuair a chuirtear alt nua isteach sa Tosaigh."
