; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SEF_DOMAIN_DESCRIPTION="Má tá rochtain ar do shuíomh trí níos mó ná fearann amháin, cuir isteach an fearann is fearr leat (uaireanta tugtar canónach air) anseo. <br><strong>Nóta:</strong> is fearainn éagsúla iad https://example.com agus https://www.example.com."
PLG_SEF_DOMAIN_LABEL="Fearann an tSuímh"
PLG_SEF_ENFORCESUFFIX_DESCRIPTION="Nuair atá sé cumasaithe agus \"Cuir Iarmhír le URL\" cumasaithe freisin, déanfar atreorú ar URLanna gan iarmhír chuig an gceann ceart. Ó leagan 6.0 ar aghaidh, beidh sé seo mar iompar caighdeánach agus ní rogha a thuilleadh."
PLG_SEF_ENFORCESUFFIX_LABEL="Déan iarmhír a fhorfheidhmiú trí atreorú"
PLG_SEF_INDEXPHP_DESCRIPTION="Cumasaíonn an rogha seo láimhseáil níos déine ar 'index.php' i URLanna nuair atá 'Úsáid Athscríobh URL' cumasaithe sa Chumraíocht Dhomhanda. Bainfidh sé 'index.php' má tá sé fós i URL agus déanfaidh sé atreorú ar iarratais isteach le 'index.php' chuig an leagan gan an 'index.php'."
PLG_SEF_INDEXPHP_LABEL="Láimhseáil dhian ar index.php"
PLG_SEF_STRICTROUTING_DESCRIPTION="Cosc a chur ar an ródálaí glacadh le go leor URLanna a mheastar mar dhúbailtí agus a dhéanfaidh atreorú go huathoibríoch chuig an URL ceart le 301."
PLG_SEF_STRICTROUTING_LABEL="Ródáil Dhian"
PLG_SEF_TRAILINGSLASH_DESCRIPTION="Cuir iallach ar Joomla URLanna a úsáid le nó gan slaise deiridh amháin. Nuair a shocraítear é, cuirfidh sé iallach ar an URL ceart le atreoruithe agus ní chuirtear i bhfeidhm é ach nuair atá 'Cuir iarmhír le URL' díchumasaithe."
PLG_SEF_TRAILINGSLASH_LABEL="Slaise deiridh do URLanna"
PLG_SEF_TRAILINGSLASH_OPTION_NONE="Gan athrú"
PLG_SEF_TRAILINGSLASH_OPTION_NO_SLASH="URLanna a fhorfheidhmiú gan slaise deiridh"
PLG_SEF_TRAILINGSLASH_OPTION_SLASH="URLanna a fhorfheidhmiú le slaise deiridh"
PLG_SEF_XML_DESCRIPTION="Cuireann sé tacaíocht SEF le naisc sa doiciméad. Oibríonn sé go díreach ar an HTML agus ní éilíonn sé clib speisialta."
PLG_SYSTEM_SEF="Córas - SEF"
