; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_FIELDS="Ábhar - Réimsí"
PLG_CONTENT_FIELDS_XML_DESCRIPTION="<p>Ligeann an breiseán seo duit réimse saincheaptha a thaispeáint a cuireadh isteach leis an mbreiseán 'Cnaipe - Réimsí' nó ag úsáid Comhréir: {field #} go díreach isteach sa limistéar eagarthóra.</p><p><strong>Comhréir Féideartha:</strong></p><ul><li><code>{field 1}</code> taispeánfaidh sé an réimse leis an ID 1</li><li><code>{field 1,foo}</code> taispeánfaidh sé an réimse roghnaithe ag úsáid an leagan amach malartach 'foo'.</li><li><code>{fieldgroup 2}</code> taispeánfaidh sé gach réimse laistigh den ghrúpa réimsí leis an ID 2.</li></ul>"
