; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_ACTIONLOG_JOOMLA="Log Gníomhaíochta - Joomla"
PLG_ACTIONLOG_JOOMLA_XML_DESCRIPTION="Taifead gníomhartha úsáideoirí ar an suíomh do shíntí croí Joomla ionas gur féidir iad a athbhreithniú más gá."
