; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_TASK_NOTIFICATION="Córas - Fógra Tasc"
PLG_SYSTEM_TASK_NOTIFICATION_XML_DESCRIPTION="Freagrach as fógraí ríomhphoist a sheoladh maidir le tascanna sceidealta a chur i gcrích."
