; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CACHE_FIELD_BROWSERCACHE_LABEL="Úsáid Taisce Brabhsálaí"
PLG_CACHE_FIELD_EXCLUDE_DESC="Sonraigh na URLanna ar mhaith leat a eisiamh ón taisce, gach ceann ar líne ar leith. Tacaítear le rialta léirithe, m.sh. <br><strong>about\-[a-z]+</strong> - eiseoidh sé gach URL a bhfuil 'about-' acu, mar shampla 'about-us', 'about-me', 'about-joomla' srl.<br><strong>/component/users/</strong> - eiseoidh sé gach URL a bhfuil /component/users/ acu.<br><strong>com_users</strong> - eiseoidh sé gach leathanach de chomhpháirt na nÚsáideoirí."
PLG_CACHE_FIELD_EXCLUDE_LABEL="Eisiamh URLanna"
PLG_CACHE_FIELD_EXCLUDE_MENU_ITEMS_LABEL="Eisiamh Míreanna Roghchláir"
PLG_CACHE_XML_DESCRIPTION="Soláthraíonn sé taisce leathanach. Níl sé seo oiriúnach ach do shuíomhanna a bhfuil ábhar statach acu nó ábhar nach n-athraíonn go minic."
PLG_SYSTEM_CACHE="Córas - Taisce Leathanach"
