; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SCHEMAORG="Córas - Schema.org"
PLG_SYSTEM_SCHEMAORG_BASETYPE_DESCRIPTION="Roghnaigh an léiríonn do shuíomh gréasáin eagraíocht nó duine aonair."
PLG_SYSTEM_SCHEMAORG_BASETYPE_LABEL="Cineál Bonn"
PLG_SYSTEM_SCHEMAORG_BASETYPE_OPTION_ORGANIZATION="Eagraíocht"
PLG_SYSTEM_SCHEMAORG_BASETYPE_OPTION_PERSON="Duine"
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION="Is formáid chaighdeánaithe é sonraí struchtúrtha chun eolas a eagrú agus a léiriú ar an ngréasán. Soláthraíonn sé bealach chun cur síos a dhéanamh ar ábhar agus brí na sonraí ar bhealach struchtúrtha, rud a fhágann go bhfuil sé níos éasca do innill chuardaigh agus feidhmchláir eile an t-eolas a thuiscint agus a phróiseáil. <a href=\"https://schema.org\" target=\"_blank\" rel=\"noopener noreferrer\">Tuilleadh eolais ar schema.org</a>."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION_NOT_CONFIGURATED="Chun feidhmiúlacht schema.org a úsáid, ní mór duit an breiseán a chumrú ar dtús. Déan teagmháil le riarthóir an leathanaigh chun é a chumrú."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_DESCRIPTION_NOT_CONFIGURATED_ADMIN="Chun feidhmiúlacht schema.org a úsáid, ní mór duit an breiseán a chumrú ar dtús. Roghnaigh <a href=\"index.php?option=com_plugins&amp;task=plugin.edit&amp;extension_id=%s\" target=\"_blank\">an nasc seo chun an breiseán a oscailt</a>, cumraigh agus sábháil."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_EXTEND_JED_DESC="<strong>An bhfuil níos mó cineálacha Schema uait?</strong> Leathnaigh le <a href=\"https://extensions.joomla.org/category/core-enhancements/schema-plugins\" target=\"_blank\" rel=\"noopener noreferrer\">Breiseáin Schema ó Eolaire Breiseán Joomla!</a>."
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_LABEL="Scéim"
PLG_SYSTEM_SCHEMAORG_FIELD_SCHEMA_TYPE_LABEL="Cineál Scéime"
PLG_SYSTEM_SCHEMAORG_IMAGE_LABEL="Íomhá"
PLG_SYSTEM_SCHEMAORG_NAME_LABEL="Ainm"
PLG_SYSTEM_SCHEMAORG_SOCIALMEDIA_LABEL="Cuntais Meán Sóisialta"
PLG_SYSTEM_SCHEMAORG_SOCIALMEDIA_URL_LABEL="URL"
PLG_SYSTEM_SCHEMAORG_USER_LABEL="Roghnaigh Úsáideoir"
PLG_SYSTEM_SCHEMAORG_XML_DESCRIPTION="Cuireann sé réimse foirme saincheaptha leis i dtuairim alt agus ansin insteallann sé na sonraí sin i bhformáid JSON+LD i gceannteideal an ailt áirithe sin."
