; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_OVERRIDECHECK="Deilbhín Tapa - Fógra Nuashonraithe Forghabhálacha Joomla!"
PLG_QUICKICON_OVERRIDECHECK_XML_DESCRIPTION="<p>Seiceálann sé forghabhálacha ar nuashonrú agus cumasaíonn sé fógraí nuair a thugann tú cuairt ar leathanach an Taispeántais Baile.</p><p><strong>Rabhadh! Caithfidh tú breiseán forghabhála suiteálaí a bheith cumasaithe chun torthaí a fheiceáil.</strong></p>"
