; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_DELETEACTIONLOGS="Tasc - Scrios Logaí Gníomhaíochta"
PLG_TASK_DELETEACTIONLOGS_XML_DESCRIPTION="Cuireann an breiseán seo tascanna sceidealaithe scriosta Logaí Gníomhaíochta ar fáil."
