; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_PRIVACYCONSENT="Tasc - Toilithe Príobháideachais"
PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_DESC="Líon na laethanta tar éis a rachaidh an toilithe príobháideachais in éag."
PLG_TASK_PRIVACYCONSENT_CONSENTEXPIRATIONDAYS_LABEL="In éag"
PLG_TASK_PRIVACYCONSENT_INVALIDATE_TITLE="In éag na dtoilithe príobháideachais"
PLG_TASK_PRIVACYCONSENT_INVALIDATE_DESC="Bainistigh in éag na dtoilithe príobháideachais"
PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_BODY="Rachaidh do Thoilithe Príobháideachais a tugadh ag {URL} in éag i gceann cúpla lá, is féidir leat an toilithe príobháideachais don suíomh gréasáin seo a athnuachan.\n\nChun é seo a dhéanamh, is féidir leat ceann de na tascanna seo a leanas a chomhlánú:\n\n1. Tabhair cuairt ar an URL seo a leanas: {TOKENURL}\n\n2. Cóipeáil do thócan ón ríomhphost seo, tabhair cuairt ar an URL tagartha, agus greamaigh do thócan isteach sa fhoirm.\nURL: {FORMURL}\nTócan: {TOKEN}\n\nTabhair faoi deara go bhfuil an tócan seo bailí don chuntas seo amháin."
PLG_TASK_PRIVACYCONSENT_EMAIL_REMIND_SUBJECT="Toilithe Príobháideachais ag {SITENAME}"
PLG_TASK_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_DESC="Meabhrúchán chun an toilithe príobháideachais don suíomh gréasáin seo a athnuachan."
PLG_TASK_PRIVACYCONSENT_MAIL_REQUEST_REMINDER_TITLE="Tasc - Toilithe Príobháideachais: Athnuachan Toilithe"
PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE="Tá an toilithe príobháideachais in éag do %1$s."
PLG_TASK_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_SUBJECT="Toilithe Príobháideachais in éag"
PLG_TASK_PRIVACYCONSENT_REMINDBEFORE_DESC="Líon na laethanta chun meabhrúchán a sheoladh roimh in éag an toilithe príobháideachais."
PLG_TASK_PRIVACYCONSENT_REMINDBEFORE_LABEL="Meabhrúchán"
PLG_TASK_PRIVACYCONSENT_XML_DESCRIPTION="Tasc chun meabhrúcháin a thabhairt ar toilithe in éag agus toilithe in éag a scriosadh"
