; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT_SELECT_AN_ARTICLE="Roghnaigh Alt"
PLG_USER_PROFILE="Úsáideoir - Próifíl"
PLG_USER_PROFILE_ERROR_INVALID_DOB="Tá an dáta breithe a chuir tú isteach neamhbhailí. Cuir isteach dáta bailí le do thoil."
PLG_USER_PROFILE_ERROR_INVALID_DOB_FUTURE_DATE="Tá an dáta breithe a chuir tú isteach sa todhchaí."
PLG_USER_PROFILE_FIELD_ABOUT_ME_LABEL="Fúmsa"
PLG_USER_PROFILE_FIELD_ADDRESS1_LABEL="Seoladh 1"
PLG_USER_PROFILE_FIELD_ADDRESS2_LABEL="Seoladh 2"
PLG_USER_PROFILE_FIELD_CITY_LABEL="Cathair"
PLG_USER_PROFILE_FIELD_COUNTRY_LABEL="Tír"
PLG_USER_PROFILE_FIELD_DOB_DESCRIPTION="Bliain-Mí-Lá, m.sh. 2019-01-27." ; Adapt to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
PLG_USER_PROFILE_FIELD_DOB_HINT="BBBB-MM-LA" ; Adapt to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
PLG_USER_PROFILE_FIELD_DOB_LABEL="Dáta Breithe"
PLG_USER_PROFILE_FIELD_FAVORITE_BOOK_LABEL="Leabhar Is Fearr Liom"
PLG_USER_PROFILE_FIELD_NAME_PROFILE_REQUIRE_USER="Réimsí próifíle úsáideora don fhoirm eagarthóireachta próifíle"
PLG_USER_PROFILE_FIELD_NAME_REGISTER_REQUIRE_USER="Réimsí próifíle úsáideora do fhoirmeacha clárúcháin agus riaracháin úsáideora"
PLG_USER_PROFILE_FIELD_PHONE_LABEL="Fón"
PLG_USER_PROFILE_FIELD_POSTAL_CODE_LABEL="Cód Poist/Cód ZIP"
PLG_USER_PROFILE_FIELD_REGION_LABEL="Réigiún"
PLG_USER_PROFILE_FIELD_TOS_ARTICLE_LABEL="Roghnaigh Alt TOS"
PLG_USER_PROFILE_FIELD_TOS_DESC_SITE="Glac leis na Téarmaí Seirbhíse le do thoil. Ní bheidh tú in ann clárú mura n-aontaíonn tú leo."
PLG_USER_PROFILE_FIELD_TOS_LABEL="Téarmaí Seirbhíse"
PLG_USER_PROFILE_FIELD_WEB_SITE_LABEL="Láithreán Gréasáin"
PLG_USER_PROFILE_FILL_FIELD_DESC_SITE="Más gá, líon isteach an réimse seo le do thoil."
PLG_USER_PROFILE_OPTION_AGREE="Aontaím"
PLG_USER_PROFILE_OPTION_DO_NOT_AGREE="Ní aontaím"
PLG_USER_PROFILE_SLIDER_LABEL="Próifíl Úsáideora"
PLG_USER_PROFILE_XML_DESCRIPTION="Breiseán Próifíl Úsáideora"
