; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_STATS="Córas - Staitisticí Joomla!"
PLG_SYSTEM_STATS_BTN_NEVER_SEND="Níl"
PLG_SYSTEM_STATS_BTN_SEND_ALWAYS="Sea, cabhróidh mé le Joomla!"
PLG_SYSTEM_STATS_BTN_SEND_NOW="Uair amháin"
PLG_SYSTEM_STATS_INTERVAL_LABEL="Eatramh (uaireanta)"
PLG_SYSTEM_STATS_LABEL_CMS_VERSION="Leagan CMS"
PLG_SYSTEM_STATS_LABEL_DB_TYPE="Cineál DB"
PLG_SYSTEM_STATS_LABEL_DB_VERSION="Leagan DB"
PLG_SYSTEM_STATS_LABEL_MESSAGE_TITLE="Cabhraigh linn Joomla! a fheabhsú!"
PLG_SYSTEM_STATS_LABEL_PHP_VERSION="Leagan PHP"
PLG_SYSTEM_STATS_LABEL_SERVER_OS="Córas Oibriúcháin Freastalaí"
PLG_SYSTEM_STATS_LABEL_UNIQUE_ID="ID Uathúil"
PLG_SYSTEM_STATS_MODE_LABEL="Mód"
PLG_SYSTEM_STATS_MODE_OPTION_ALWAYS_SEND="Seol i gcónaí"
PLG_SYSTEM_STATS_MODE_OPTION_NEVER_SEND="Ná seol riamh"
PLG_SYSTEM_STATS_MODE_OPTION_ON_DEMAND="Iarr arís"
PLG_SYSTEM_STATS_MSG_ALLOW_SENDING_DATA="Cumasaigh Staitisticí Joomla?"
PLG_SYSTEM_STATS_MSG_JOOMLA_WANTS_TO_SEND_DATA="Ba mhaith linn comhoiriúnacht ár mbogearraí Joomla! a mhéadú le socruithe freastalaí ár n-úsáideoirí. Dá bhrí sin, teastaíonn sonraí gan ainm uainn ó do shuíomh chun bonn suiteála agus timpeallachtaí úsáideoirí deiridh a thuiscint níos fearr. Déantar gach sonraí a anaithnidiú agus ní sheoltar iad ach chuig freastalaí lárnach rialaithe ag Joomla! Is féidir leat na socruithe seo a athrú níos déanaí ó Breiseáin &rarr; Córas - Staitisticí Joomla!"
PLG_SYSTEM_STATS_MSG_WHAT_DATA_WILL_BE_SENT="Ní bhailítear aon sonraí aitheantais ag aon phointe. Roghnaigh anseo chun athbhreithniú a dhéanamh."
PLG_SYSTEM_STATS_RESET_UNIQUE_ID="Athshocraigh ID Uathúil"
PLG_SYSTEM_STATS_SETTING="Socrú"
PLG_SYSTEM_STATS_STATISTICS="Staitisticí"
PLG_SYSTEM_STATS_UNIQUE_ID_LABEL="ID Uathúil"
PLG_SYSTEM_STATS_VALUE="Luach"
PLG_SYSTEM_STATS_XML_DESCRIPTION="Breiseán Córas a sheolann staitisticí timpeallachta chuig freastalaí rialaithe ag tionscadal Joomla! le haghaidh anailís staitistiúil. Áirítear ar na staitisticí a sheoltar leagan PHP, leagan CMS, cineál Bunachar Sonraí, leagan Bunachar Sonraí agus cineál Freastalaí."
