; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_CONTACT="Ábhar - Teagmháil"
PLG_CONTENT_CONTACT_PARAM_ALIAS_DESCRIPTION="Nasc leis na sonraí fíor-úsáideora fiú má tá ailias údar socraithe i roghanna an ailt."
PLG_CONTENT_CONTACT_PARAM_ALIAS_LABEL="Cuir nasc i bhfeidhm freisin ar ainm ailias"
PLG_CONTENT_CONTACT_PARAM_URL_DESCRIPTION="Is féidir leat ainm an údair a nascadh le:<ul><li>Leathanach teagmhála gaolmhar.<li>Leathanach gréasáin sonraithe sa phróifíl teagmhála gaolmhar.<li>Ríomhphost sonraithe sa phróifíl teagmhála gaolmhar.</ul>"
PLG_CONTENT_CONTACT_PARAM_URL_EMAIL="Ríomhphost ó theagmháil"
PLG_CONTENT_CONTACT_PARAM_URL_LABEL="Athsheoladh"
PLG_CONTENT_CONTACT_PARAM_URL_URL="Leathanach teagmhála inmheánach"
PLG_CONTENT_CONTACT_PARAM_URL_WEBPAGE="Leathanach gréasáin ó theagmháil"
PLG_CONTENT_CONTACT_XML_DESCRIPTION="Soláthraíonn nasc idir údar an ábhair agus an mhír teagmhála is féidir a úsáid le haghaidh Próifíl Údair."
