; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MEDIA-ACTION_ROTATE="Gníomh Meán - Rothlú"
PLG_MEDIA-ACTION_ROTATE_LABEL="Rothlú"
PLG_MEDIA-ACTION_ROTATE_PARAM_ANGLE="Uillinn"
PLG_MEDIA-ACTION_ROTATE_PARAM_BUTTONS="Cnaipí Uillinne"
PLG_MEDIA-ACTION_ROTATE_QUALITY="Cáilíocht"
PLG_MEDIA-ACTION_ROTATE_XML_DESCRIPTION="Cuireann feidhm rothlaithe le haghaidh íomhánna leis."
