; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_SESSIONGC="Tasc - Glanadh Sonraí Seisiúin"
PLG_TASK_SESSIONGC_DESC="Breiseán Tasc a ghlanann sonraí agus meiteashonraí atá imithe in éag ag brath ar an láimhseálaí seisiúin atá socraithe sa Chumraíocht Dhomhanda."
PLG_TASK_SESSIONGC_ENABLE_SESSION_GC_DESC="Nuair atá sé cumasaithe, déanfaidh an breiseán seo iarracht sonraí atá imithe in éag a ghlanadh."
PLG_TASK_SESSIONGC_ENABLE_SESSION_GC_LABEL="Cumasaigh Glanadh Sonraí Seisiúin"
PLG_TASK_SESSIONGC_ENABLE_SESSION_METADATA_GC_DESC="Nuair atá sé cumasaithe, glanfaidh an breiseán seo meiteashonraí roghnacha seisiúin ón mbunachar sonraí. Tabhair faoi deara nach rithfidh an oibríocht seo nuair atá an láimhseálaí bunachar sonraí in úsáid mar go bhfuil na sonraí sin glanta mar chuid den oibríocht Glanadh Sonraí Seisiúin."
PLG_TASK_SESSIONGC_ENABLE_SESSION_METADATA_GC_LABEL="Cumasaigh Glanadh Meiteashonraí Seisiúin"
PLG_TASK_SESSIONGC_TITLE="Glanadh Sonraí Seisiúin"
PLG_TASK_SESSIONGC_XML_DESCRIPTION="Breiseán Tasc a ghlanann sonraí agus meiteashonraí atá imithe in éag ag brath ar an láimhseálaí seisiúin atá socraithe sa Chumraíocht Dhomhanda."
