; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_TOKEN="Úsáideoir - Tócan API Joomla"
PLG_USER_TOKEN_COPY="Cóipeáil"
PLG_USER_TOKEN_COPY_DESC="Cóipeáil an tócan chuig do ghearrthaisce"
PLG_USER_TOKEN_COPY_FAIL="Theip ar chóipeáil an tócain."
PLG_USER_TOKEN_COPY_SUCCESS="Tócan cóipeáilte."
PLG_USER_TOKEN_ENABLED_DESC="Socraigh go Níl chun rochtain ar do shuíomh a chosc go sealadach leis an tócan seo."
PLG_USER_TOKEN_ENABLED_LABEL="Gníomhach"
PLG_USER_TOKEN_GROUP_DESC="Bainistigh na tócain slándála a úsáidtear chun fíordheimhniú a dhéanamh ar an bhfeidhmchlár API Joomla (rochtain iargúlta ar do shuíomh). Mura bhfuil tú cinnte cad a dhéanann sé seo, is dócha nach bhfuil sé ag teastáil uait agus is féidir leat neamhaird a dhéanamh go sábháilte ar na socruithe seo."
PLG_USER_TOKEN_GROUP_LABEL="Tócan API Joomla"
PLG_USER_TOKEN_NOTOKENFOROTHERPEOPLE_DESC="Ní féidir leat an tócan a fheiceáil do úsáideoirí seachas tú féin. Fós is féidir leat a dtócan a chumasú, a dhíchumasú nó a athshocrú m.sh. nuair a bhíonn amhras ann go bhfuil a dtócan sceite chuig daoine neamhúdaraithe."
PLG_USER_TOKEN_RESET_DESC="Socraigh go Tá agus sábháil do phróifíl úsáideora chun tócan nua a chruthú, ag athsholáthar an tsean-tócain."
PLG_USER_TOKEN_RESET_LABEL="Athshocraigh"
PLG_USER_TOKEN_SAVEME_DESC="Níl tócan agat fós. Sábháil do phróifíl úsáideora le tócan a ghiniúint. Fill ar an leathanach seo chun do thócan a fheiceáil agus a bhainistiú."
PLG_USER_TOKEN_SAVEMEFOROTHERPEOPLE_DESC="Níl tócan ag an úsáideoir seo fós. Má shábhálann tú a bpróifíl, ginfear tócan nua ach ní bheidh tú in ann é a fheiceáil ar chúiseanna slándála. Fós beidh tú in ann a dtócan a chumasú, a dhíchumasú nó a athshocrú."
PLG_USER_TOKEN_TOKEN_DESC="Seo é do thócan. Úsáid é i bhfeidhmchláir tríú páirtí a éilíonn rochtain iargúlta ar do shuíomh tríd an bhfeidhmchlár API Joomla."
PLG_USER_TOKEN_TOKEN_LABEL="Tócan"
PLG_USER_TOKEN_XML_DESCRIPTION="Ceadaíonn bainistíocht na dtócain slándála a úsáidtear chun fíordheimhniú a dhéanamh ar an bhfeidhmchlár API Joomla (rochtain iargúlta ar do shuíomh). Tá na tócain seo go docht pearsanta. Is féidir leat do thócan féin a fheiceáil ach ní féidir leat ach tócain úsáideoirí eile a dhíchumasú nó a athshocrú."
