; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_PAGENAVIGATION="Ábhar - Loingseoireacht Leathanach"
PLG_PAGENAVIGATION_ARIA_LABEL="Loingseoireacht Leathanach"
PLG_PAGENAVIGATION_FIELD_DISPLAY_LABEL="Téacs an Naisc"
PLG_PAGENAVIGATION_FIELD_POSITION_LABEL="Seasamh"
PLG_PAGENAVIGATION_FIELD_RELATIVE_LABEL="Gaolmhar Le"
PLG_PAGENAVIGATION_FIELD_VALUE_ABOVE="Os cionn"
PLG_PAGENAVIGATION_FIELD_VALUE_ARTICLE="Alt Iomlán"
PLG_PAGENAVIGATION_FIELD_VALUE_BELOW="Faoi bhun"
PLG_PAGENAVIGATION_FIELD_VALUE_NEXTPREV="Ar Aghaidh/Roimhe (téacs statach)"
PLG_PAGENAVIGATION_FIELD_VALUE_TEXT="Téacs"
PLG_PAGENAVIGATION_FIELD_VALUE_TITLE="Teideal an Ailt"
PLG_PAGENAVIGATION_XML_DESCRIPTION="Cumasaíonn sé duit naisc <em>Ar Aghaidh &amp; Roimhe</em> a chur le hAlt."
