; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_WORKFLOW_BASIC_STAGE="Céim Bhunúsach"
COM_WORKFLOW_NOTIFICATION_FIELDSET_LABEL="Fógra"
PLG_WORKFLOW_NOTIFICATION="Sreabhadh Oibre - Fógra"
PLG_WORKFLOW_NOTIFICATION_ADDTEXT="Tá an chéim athraithe"
PLG_WORKFLOW_NOTIFICATION_ADDTEXT_DESC="Seolfar an téacs seo: Teideal [title], athraithe ag [user], stát nua: [state]. Is féidir leat do théacs féin a chur leis an teachtaireacht seo agus is féidir leat an téacs a logánú trí eochair teanga a úsáid agus forluí teanga a chruthú."
PLG_WORKFLOW_NOTIFICATION_ADDTEXT_LABEL="Téacs Breise Teachtaireachta"
PLG_WORKFLOW_NOTIFICATION_ON_TRANSITION_MSG="Teideal: %1$s. Aistriú \"%2$s\" curtha i gcrích ag %3$s. Stát nua: %4$s."
PLG_WORKFLOW_NOTIFICATION_ON_TRANSITION_SUBJECT="Tá stádas \"%s\" athraithe"
PLG_WORKFLOW_NOTIFICATION_NO_RECEIVER="Níor seoladh aon fhógraí mar níl aon úsáideoirí ann chun an teachtaireacht seo a sheoladh chucu."
PLG_WORKFLOW_NOTIFICATION_NO_TITLE="Teideal anaithnid"
PLG_WORKFLOW_NOTIFICATION_RECEIVERS_LABEL="Úsáideoirí"
PLG_WORKFLOW_NOTIFICATION_SENDMAIL_LABEL="Seol Fógra"
PLG_WORKFLOW_NOTIFICATION_SENT="Fógraí seolta"
PLG_WORKFLOW_NOTIFICATION_USERGROUP_DESC="Faigheann na húsáideoirí sa ghrúpa úsáideoirí seo fógra má tá an t-aistriú seo curtha i gcrích."
PLG_WORKFLOW_NOTIFICATION_USERGROUP_LABEL="Grúpaí Úsáideoirí"
PLG_WORKFLOW_NOTIFICATION_XML_DESCRIPTION="Seol fógra má tá aistriú curtha i gcrích i sreabhadh oibre."
