; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_API-AUTHENTICATION_BASIC="Fíordheimhniú API - Fíordheimhniú Bunúsach Seirbhísí Gréasáin"
PLG_API-AUTHENTICATION_BASIC_XML_DESCRIPTION="Úsáidtear chun fíordheimhniú bunúsach a cheadú do sheirbhísí Gréasáin i Joomla."
