; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_INSTALLER_OVERRIDE="Suiteálaí - Forluí"
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED="%1$s comhaid a bhfuil forluí agat dóibh i do theimpléad atá nuashonraithe agus ba cheart duit <a href=\"%2$s\">na hathruithe sin a athbhreithniú</a>."
PLG_INSTALLER_OVERRIDE_N_FILE_UPDATED_1="Comhad a bhfuil forluí agat dó i do theimpléad atá nuashonraithe agus ba cheart duit <a href=\"%2$s\">na hathruithe sin a athbhreithniú</a>."

PLG_INSTALLER_OVERRIDE_PLUGIN_XML_DESCRIPTION="Cumasaíonn an breiseán seo fógraí agus láimhseáil forluíthe tar éis nuashonraithe i gcás athruithe."
