; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_RECIPE="Schema.org - Oideas"
PLG_SCHEMAORG_RECIPE_DESCRIPTION_LABEL="Is féidir tuilleadh eolais ar an Cineál Oideas Schema.org a fháil ag <a href=\"https://schema.org/Recipe\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/Recipe</a>"
PLG_SCHEMAORG_RECIPE_FIELD_AUTHOR_LABEL="Údar"
PLG_SCHEMAORG_RECIPE_FIELD_CALORIES_LABEL="Calraí"
PLG_SCHEMAORG_RECIPE_FIELD_CARBOHYDRATE_LABEL="Carbaihiodráit"
PLG_SCHEMAORG_RECIPE_FIELD_CATEGORY_LABEL="Catagóir"
PLG_SCHEMAORG_RECIPE_FIELD_CHOLESTEROL_CONTENT_LABEL="Colaistéaról"
PLG_SCHEMAORG_RECIPE_FIELD_COOKING_METHOD_LABEL="Modh Cócaireachta"
PLG_SCHEMAORG_RECIPE_FIELD_COOK_TIME_LABEL="Am Cócaireachta"
PLG_SCHEMAORG_RECIPE_FIELD_CUISINE_LABEL="Cistin"
PLG_SCHEMAORG_RECIPE_FIELD_DATE_PUBLISHED_LABEL="Dáta Foilsithe"
PLG_SCHEMAORG_RECIPE_FIELD_DESCRIPTION_LABEL="Cur Síos"
PLG_SCHEMAORG_RECIPE_FIELD_FAT_LABEL="Saill"
PLG_SCHEMAORG_RECIPE_FIELD_FIBER_LABEL="Snáithín"
PLG_SCHEMAORG_RECIPE_FIELD_GENERIC_FIELD_LABEL="Réimse Ginearálta"
PLG_SCHEMAORG_RECIPE_FIELD_GENERIC_TITLE_LABEL="Teideal"
PLG_SCHEMAORG_RECIPE_FIELD_GENERIC_VALUE_LABEL="Luach"
PLG_SCHEMAORG_RECIPE_FIELD_HOUR_LABEL="Uaireanta"
PLG_SCHEMAORG_RECIPE_FIELD_IMAGE_LABEL="Íomhá"
PLG_SCHEMAORG_RECIPE_FIELD_INGREDIENTS_LABEL="Comhábhair"
PLG_SCHEMAORG_RECIPE_FIELD_INSTRUCTIONS_LABEL="Treoracha"
PLG_SCHEMAORG_RECIPE_FIELD_MINUTE_LABEL="Nóiméid"
PLG_SCHEMAORG_RECIPE_FIELD_NAME_LABEL="Teideal"
PLG_SCHEMAORG_RECIPE_FIELD_NUTRITION_LABEL="Cothú"
PLG_SCHEMAORG_RECIPE_FIELD_PREPARATION_TIME_LABEL="Am Ullmhúcháin"
PLG_SCHEMAORG_RECIPE_FIELD_PROTEIN_LABEL="Próitéin"
PLG_SCHEMAORG_RECIPE_FIELD_SATURATED_FAT_LABEL="Saill Sháithithe"
PLG_SCHEMAORG_RECIPE_FIELD_SERVING_SIZE_LABEL="Méid Freastail"
PLG_SCHEMAORG_RECIPE_FIELD_SODIUM_LABEL="Sóidiam"
PLG_SCHEMAORG_RECIPE_FIELD_SUGAR_LABEL="Siúcra"
PLG_SCHEMAORG_RECIPE_FIELD_SUITABLE_FOR_DIET_LABEL="Oiriúnach don Aiste Bia"
PLG_SCHEMAORG_RECIPE_FIELD_TRANS_FAT_LABEL="Saill Tras"
PLG_SCHEMAORG_RECIPE_FIELD_UNSATURATED_FAT_LABEL="Saill Neamhsháithithe"
PLG_SCHEMAORG_RECIPE_FIELD_YIELD_LABEL="Toradh"
PLG_SCHEMAORG_RECIPE_XML_DESCRIPTION="Cuireann sé Oideas leis mar chineál scéime nua i scéimeanna atá ann cheana."
