; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_FINDER="Ábhar - Cuardach Cliste"
PLG_CONTENT_FINDER_XML_DESCRIPTION="Ní dhéanfaidh athruithe ar ábhar an t-innéacs Cuardaigh Chliste a nuashonrú mura gcumasaíonn tú an breiseán seo."
PLG_FINDER_QUERY_FILTER_BRANCH_P__="Uile"
PLG_FINDER_QUERY_FILTER_BRANCH_P_CATEGORY="Catagóirí"
PLG_FINDER_QUERY_FILTER_BRANCH_P_LANGUAGE="Teangacha"
PLG_FINDER_QUERY_FILTER_BRANCH_P_TYPE="Cineálacha"
PLG_FINDER_QUERY_FILTER_BRANCH_S_CATEGORY="Catagóir"
PLG_FINDER_QUERY_FILTER_BRANCH_S_LANGUAGE="Teanga"
PLG_FINDER_QUERY_FILTER_BRANCH_S_TYPE="Cineál"
