; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_WEBAUTHN="Fíordheimhniú Ilfhachtóra - Eochracha Pas"
PLG_MULTIFACTORAUTH_WEBAUTHN_XML_DESCRIPTION="Úsáid eochracha pas brabhsálaí mar mhodh Fíordheimhnithe Ilfhachtóra. Tacaíonn gach brabhsálaí nua-aimseartha leis. Cuireann an chuid is mó de na brabhsálaithe fíordheimhniú sonracha feiste ar fáil atá cosanta ag focal faire agus/nó bithmhéadracht (braiteoir méarloirg, scanadh aghaidhe, &hellip;)."
