; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_LANGUAGECODE="Córas - Cód Teanga"
PLG_SYSTEM_LANGUAGECODE_FIELD_DESC="Athraíonn sé an cód teanga a úsáidtear don teanga <em>%s</em>."
PLG_SYSTEM_LANGUAGECODE_FIELDSET_DESC="Athraíonn sé an cód teanga don doiciméad HTML a ghintear. Sampla úsáide: Tá an pacáiste teanga fr-FR suiteáilte agat agus ba mhaith leat go n-aithneodh na hInneall Cuardaigh an leathanach mar cheann dírithe ar Cheanada labhartha Fraincise. Cuir an clib 'fr-CA' leis an réimse comhfhreagrach do 'fr-FR' chun é seo a réiteach."
PLG_SYSTEM_LANGUAGECODE_FIELDSET_LABEL="Cóid Teanga"
PLG_SYSTEM_LANGUAGECODE_XML_DESCRIPTION="Soláthraíonn sé an cumas chun an cód teanga a athrú sa doiciméad HTML a ghintear chun SEO a fheabhsú.<br>Beidh na réimsí le feiceáil nuair a bheidh an breiseán cumasaithe agus sábháilte."
