; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_BEHAVIOUR_COMPAT="Iompar - Comhoiriúnacht Siar"
PLG_COMPAT_FIELD_CLASSES_ALIASES_LABEL="Ainmneacha Aicmí"
PLG_COMPAT_FIELD_CLASSES_ALIASES_DESCRIPTION="Cuir ainmneacha aicmí leis do ranganna a athainmníodh nó a bogadh go dtí spásainm."
PLG_COMPAT_FIELD_ES5_ASSETS_DESCRIPTION="Gníomhachtaigh an rogha seo má theastaíonn sócmhainní *.es5 ó do shíneadh a chruthaigh eisceacht. Tá na sócmhainní a chuirtear ar fáil folamh ach cuireann siad cosc ar an eisceacht."
PLG_COMPAT_FIELD_ES5_ASSETS_LABEL="Sócmhainní ES5"
PLG_COMPAT_FIELD_REMOVED_ASSETS_DESCRIPTION="Gníomhachtaigh an rogha seo má theastaíonn sócmhainní bainte ó do shíneadh a chruthaigh eisceacht. Tá na sócmhainní a chuirtear ar fáil folamh ach cuireann siad cosc ar an eisceacht."
PLG_COMPAT_FIELD_REMOVED_ASSETS_LABEL="Sócmhainní Bainte"
PLG_COMPAT_XML_DESCRIPTION="Má úsáideann tú síntí nach bhfuil ag úsáid na gcaighdeán códaithe Joomla reatha, ansin cuirfidh an breiseán seo, nuair a bheidh sé cumasaithe, comhoiriúnacht siar ar fáil don leagan mór roimhe seo."
