; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_PRIVACYCHECK="Deilbhín Tapa - Fógra Iarrataí Príobháideachais Joomla!"
PLG_QUICKICON_PRIVACYCHECK_XML_DESCRIPTION="Seiceálann sé iarrataí príobháideachais a bhfuil gá le láimhseáil agus cuireann sé fógra chugat nuair a thugann tú cuairt ar leathanach Painéal Baile."
