; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_WEBSERVICES_CONTENT="Seirbhísí Gréasáin - Ábhar"
PLG_WEBSERVICES_CONTENT_XML_DESCRIPTION="Cuir bealaí alt leis an API do do shuíomh gréasáin."
