; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EXTENSION_NAMESPACEMAP="Síneadh - Nuashonraitheoir Spásainm"
PLG_EXTENSION_NAMESPACEMAP_XML_DESCRIPTION="<p>Tógann agus nuashonraíonn sé an comhad <strong>administrator/cache/autoload_psr4.php</strong> go huathoibríoch a úsáidtear chun síneadh a luchtú go huathoibríoch.</p><p><strong>Rabhadh! Caithfidh an breiseán seo a bheith cumasaithe</strong> mar a ritheann sé ar shuiteáil, nuashonrú agus díshuiteáil síneadh.</p>"
