; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_EXTENSIONUPDATE="Deilbhín Tapa - Fógra Nuashonruithe Breiseán Joomla!"
PLG_QUICKICON_EXTENSIONUPDATE_CHECKING="Ag seiceáil breiseáin &hellip;"
PLG_QUICKICON_EXTENSIONUPDATE_ERROR="Breiseáin anaithnid &hellip;"
PLG_QUICKICON_EXTENSIONUPDATE_GROUP_DESC="Grúpa an bhreiseáin seo (déantar an luach seo a chur i gcomparáid leis an luach grúpa a úsáidtear i modúil <strong>Deilbhíní Tapa</strong> chun deilbhíní a instealladh)."
PLG_QUICKICON_EXTENSIONUPDATE_GROUP_LABEL="Grúpa"
PLG_QUICKICON_EXTENSIONUPDATE_UPDATEFOUND="Tá nuashonruithe ar fáil! %s"
PLG_QUICKICON_EXTENSIONUPDATE_UPTODATE="Tá breiseáin cothrom le dáta."
PLG_QUICKICON_EXTENSIONUPDATE_XML_DESCRIPTION="Seiceálann sé le haghaidh nuashonruithe ar do bhreiseáin tríú páirtí atá suiteáilte agus tugann sé fógra duit nuair a thugann tú cuairt ar leathanach an Tairseach Baile."
