; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_ACCESSIBILITY="Córas - Gnéithe Inrochtaineachta Breise"
PLG_SYSTEM_ACCESSIBILITY_CLOSE="Dún"
PLG_SYSTEM_ACCESSIBILITY_CURSOR="Cúrsóir Mór"
PLG_SYSTEM_ACCESSIBILITY_DECREASE_SPACING="Laghdaigh Spásáil Téacs"
PLG_SYSTEM_ACCESSIBILITY_DECREASE_TEXT="Laghdaigh Méid an Téacs"
PLG_SYSTEM_ACCESSIBILITY_EMOJIS="Deilbhíní"
PLG_SYSTEM_ACCESSIBILITY_EMOJIS_FALSE="Úsáid Cló Ábhar Google"
PLG_SYSTEM_ACCESSIBILITY_EMOJIS_TRUE="Úsáid Emojis"
PLG_SYSTEM_ACCESSIBILITY_GREY="Dathanna Liath"
PLG_SYSTEM_ACCESSIBILITY_INCREASE_SPACING="Méadaigh Spásáil Téacs"
PLG_SYSTEM_ACCESSIBILITY_INCREASE_TEXT="Méadaigh Méid an Téacs"
PLG_SYSTEM_ACCESSIBILITY_INVERT_COLORS="Aisiompaigh Dathanna"
PLG_SYSTEM_ACCESSIBILITY_MENU_TITLE="Roghanna Inrochtaineachta"
PLG_SYSTEM_ACCESSIBILITY_READING="Treoir Léitheoireachta"
PLG_SYSTEM_ACCESSIBILITY_RESET="Athshocraigh"
PLG_SYSTEM_ACCESSIBILITY_SECTION="Rannóg an tSuímh"
PLG_SYSTEM_ACCESSIBILITY_SECTION_ADMIN="Riarthóir (Cúlra)"
PLG_SYSTEM_ACCESSIBILITY_SECTION_BOTH="An Dá Rud"
PLG_SYSTEM_ACCESSIBILITY_SECTION_SITE="Suíomh (Tosaigh)"
PLG_SYSTEM_ACCESSIBILITY_STT="Óráid go Téacs"
PLG_SYSTEM_ACCESSIBILITY_TTS="Téacs go hÓráid"
PLG_SYSTEM_ACCESSIBILITY_UNDERLINE="Féach Naisc"
PLG_SYSTEM_ACCESSIBILITY_XML_DESCRIPTION="Cuireann an breiseán seo barra uirlisí inrochtaineachta le do shuíomh le roghanna inrochtaineachta breise. Nuair a bheidh sé cumasaithe is féidir an barra uirlisí a oscailt le luch nó leis an eochair te <strong>CTRL + ALT + A</strong>, nó <strong>CTRL + OPTION + A</strong> ar MacOS."
