; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SCHEMAORG="Córas - Schema.org"
PLG_SYSTEM_SCHEMAORG_XML_DESCRIPTION="Cuireann sé réimse foirme saincheaptha leis sa radharc alt agus ansin insteallann sé na sonraí sin i bhformáid JSON+LD i gceannteideal an ailt áirithe sin."
