; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_CUSTOM="Schema.org - Saincheaptha"
PLG_SCHEMAORG_CUSTOM_XML_DESCRIPTION="Cuireann réimse saincheaptha leis chun aon chineál scéime a chur leis."
PLG_SCHEMAORG_CUSTOM_DESCRIPTION_LABEL="Úsáid aon chód JSON-LD anseo chun cineálacha scéime nach bhfuil tacaíocht acu faoi láthair a chur leis."
PLG_SCHEMAORG_CUSTOM_JSON_ERROR="Níl an cód JSON bailí nó tá @context nó @type ar iarraidh."
PLG_SCHEMAORG_CUSTOM_JSON_FIELD_LABEL="Cód JSON"
