; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_ACCESSIBILITY="Córas - Gnéithe Inrochtaineachta Breise"
PLG_SYSTEM_ACCESSIBILITY_XML_DESCRIPTION="Cuireann an breiseán seo barra uirlisí inrochtaineachta le do shuíomh le roghanna breise inrochtaineachta. Nuair a bheidh sé cumasaithe, is féidir an barra uirlisí a oscailt le luch nó leis an eochair the <strong>CTRL + ALT + A</strong>, nó <strong>CTRL + OPTION + A</strong> ar MacOS."
