; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_MEDIA="Réimsí - Meáin"
PLG_FIELDS_MEDIA_LABEL="Meáin (%s)"
PLG_FIELDS_MEDIA_PARAMS_DIRECTORY_LABEL="Eolaire"
PLG_FIELDS_MEDIA_PARAMS_IMAGE_CLASS_LABEL="Aicme Íomhá"
PLG_FIELDS_MEDIA_PARAMS_PREVIEW_INLINE="Inlíne"
PLG_FIELDS_MEDIA_PARAMS_PREVIEW_LABEL="Réamhamharc"
PLG_FIELDS_MEDIA_XML_DESCRIPTION="Ligeann an breiseán seo duit réimsí nua de chineál 'meáin' a chruthú in aon síneadh ina dtacaítear le réimsí saincheaptha."
