; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_RADIO="Réimsí - Raidió"
PLG_FIELDS_RADIO_LABEL="Raidió (%s)"
PLG_FIELDS_RADIO_PARAMS_FORM_LAYOUT_BUTTONS="Cnaipí"
PLG_FIELDS_RADIO_PARAMS_FORM_LAYOUT_SWITCHER="Athraigh"
PLG_FIELDS_RADIO_PARAMS_OPTIONS_LABEL="Luachanna Raidió"
PLG_FIELDS_RADIO_PARAMS_OPTIONS_NAME_LABEL="Téacs"
PLG_FIELDS_RADIO_PARAMS_OPTIONS_VALUE_LABEL="Luach"
PLG_FIELDS_RADIO_XML_DESCRIPTION="Ligeann an breiseán seo duit réimsí nua de chineál 'raidió' a chruthú in aon síneadh ina dtacaítear le réimsí saincheaptha."
