; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_FIXED="Fíordheimhniú Ilfhachtóra - Cód Seasta"
PLG_MULTIFACTORAUTH_FIXED_XML_DESCRIPTION="Breiseán taispeána Fíordheimhnithe Ilfhachtóra ag úsáid cód seasta (a &ldquo;dara pasfhocal&rdquo;). <strong>Ná húsáid ar shuímh bheo, níl sé slán.</strong> Níl an breiseán seo ceaptha ach le húsáid mar shampla do fhorbróirí ar spéis leo a gcuid breiseán féin a chruthú."
