; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_SCHEDULERUNNER="Córas - Rith Sceideal"
PLG_SYSTEM_SCHEDULERUNNER_XML_DESCRIPTION="Tá an breiseán seo freagrach as an sceidealú leisciúil, webcron agus cliceáil chun rith feidhmiúlachtaí de com_scheduler. Chomh maith leis sin, cuireann sé feabhsaitheoirí/manipulators foirme i bhfeidhm do chumraíocht an chomhpháirt com_scheduler."
