; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_PAGEBREAK="Ábhar - Briseadh Leathanaigh"
PLG_CONTENT_PAGEBREAK_ALL_PAGES="Gach Leathanach"
PLG_CONTENT_PAGEBREAK_ARTICLE_INDEX="Innéacs Airteagal"
PLG_CONTENT_PAGEBREAK_NO_TITLE="Gan teideal"
PLG_CONTENT_PAGEBREAK_PAGE_NUM="Leathanach %d"
PLG_CONTENT_PAGEBREAK_PAGES="Leathanaigh"
PLG_CONTENT_PAGEBREAK_SHOW_ALL_LABEL="Taispeáin Gach Rud"
PLG_CONTENT_PAGEBREAK_SITE_ARTICLEINDEX_LABEL="Ceannteideal Innéacs Airteagal"
PLG_CONTENT_PAGEBREAK_SITE_ARTICLEINDEXTEXT="Ceannteideal Saincheaptha Innéacs Airteagal"
PLG_CONTENT_PAGEBREAK_SITE_TITLE_LABEL="Teideal an tSuímh"
PLG_CONTENT_PAGEBREAK_SLIDERS="Sleamhnáin"
PLG_CONTENT_PAGEBREAK_STYLE_LABEL="Stíl na Cur i Láthair"
PLG_CONTENT_PAGEBREAK_TABS="Cluaisíní"
PLG_CONTENT_PAGEBREAK_TOC_LABEL="Clár Ábhair"
PLG_CONTENT_PAGEBREAK_XML_DESCRIPTION="<p>Ceadaigh cruthú airteagal leathanachaithe le clár ábhair roghnach.</p><p>Cuir isteach briseadh leathanaigh tríd an gcnaipe briseadh leathanaigh a úsáid a fhaightear de ghnáth i mbarra uirlisí an eagarthóra WYSIWYG. Taispeánfar suíomh an bhriseadh leathanaigh in airteagal san eagarthóir mar líne chothrománach shimplí.</p><p>Braitheann an téacs a thaispeántar ar na roghanna a roghnaítear agus féadfaidh sé a bheith ina theideal, téacs malartach (má chuirtear ar fáil é) nó uimhreacha leathanaigh.</p><p>Is é an úsáid HTML:<br>&lt;hr class=&quot;system-pagebreak&quot; /&gt;<br>&lt;hr class=&quot;system-pagebreak&quot; title=&quot;Teideal an leathanaigh&quot; /&gt; nó <br>&lt;hr class=&quot;system-pagebreak&quot; alt=&quot;An chéad leathanach&quot; /&gt; nó <br>&lt;hr class=&quot;system-pagebreak&quot; title=&quot;Teideal an leathanaigh&quot; alt=&quot;An chéad leathanach&quot; /&gt; nó <br>&lt;hr class=&quot;system-pagebreak&quot; alt=&quot;An chéad leathanach&quot; title=&quot;Teideal an leathanaigh&quot; /&gt;</p>"
