; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_TOTP="Fíordheimhniú Ilfhachtóra - Cód Fíoraithe"
PLG_MULTIFACTORAUTH_TOTP_CAPTIVE_PROMPT="Oscail d'fheidhmchlár fíordheimhnithe nó do bhainisteoir pasfhocal agus cóipeáil an cód sé dhigit don suíomh seo sa bhosca téacs thíos, ansin cliceáil ar an gcnaipe Bailíochtaithe. Má tá an cód seo líonta isteach go huathoibríoch duit, cliceáil ar an gcnaipe Bailíochtaithe."
PLG_MULTIFACTORAUTH_TOTP_ERR_VALIDATIONFAILED="Níor chuir tú isteach cód fíoraithe bailí. Seiceáil socrú d’aip fíordheimhnithe, agus déan cinnte go bhfuil an t-am agus an crios ama ar do ghléas socraithe i gceart."
PLG_MULTIFACTORAUTH_TOTP_LBL_LABEL="Cuir isteach an cód fíoraithe sé dhigit"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_INSTRUCTIONS="Socraigh do chód fíoraithe (ar a dtugtar \"cód fíordheimhnithe\" freisin) ag úsáid an eolais thíos. Is féidir leat aip fíordheimhnithe a úsáid (mar Google Authenticator, Authy, LastPass Authenticator, srl), do bhainisteoir pasfhocal is fearr leat (1Password, BitWarden, Keeper, KeePassXC, Strongbox, srl) nó, i gcásanna áirithe, do bhrabhsálaí."
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_PLACEHOLDER="Cód Sé Dhigit"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_HEADING="Socrú aip fíordheimhnithe"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_KEY="Cuir isteach an eochair seo"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_LINK="Cliceáil an nasc seo"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_LINK_NOTE="<small>Ní oibríonn ach ar bhrabhsálaithe tacaíochta, m.sh. Safari.</small>"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_LINK_TEXT="<a href=\"%s\">Socraigh do chód fíoraithe</a>"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_QR="Scan nó cliceáil deas / tapáil fada an cód QR seo"
PLG_MULTIFACTORAUTH_TOTP_LBL_SETUP_TABLE_SUBHEAD="Úsáid <em>ceann</em> de na modhanna malartacha seo a leanas chun an cód fíoraithe a shocrú i d’fheidhmchlár fíordheimhnithe, bainisteoir pasfhocal nó brabhsálaí."
PLG_MULTIFACTORAUTH_TOTP_METHOD_TITLE="Cód fíoraithe"
PLG_MULTIFACTORAUTH_TOTP_SHORTINFO="Úsáid cóid 6 dhigit a ghintear ag aip gach 30 soicind."
PLG_MULTIFACTORAUTH_TOTP_XML_DESCRIPTION="Fíordheimhniú Ilfhachtóra do úsáideoirí do shuíomh ag úsáid cóid fíoraithe sé dhigit a ghintear ag aip fíordheimhnithe (Google Authenticator, Authy, LastPass Authenticator, srl), bainisteoir pasfhocal (1Password, BitWarden, Keeper, KeePassXC, Strongbox, srl) nó, i gcásanna áirithe, a mbrabhsálaí."
