; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_WORKFLOW_FEATURING="Sreabhadh Oibre - Réadmhaoin"
PLG_WORKFLOW_FEATURING_CHANGE_STATE_NOT_ALLOWED="Níl cead agat staid réadmhaoin an mhíre seo a athrú. Bain úsáid as aistriú sreafa oibre le do thoil."
PLG_WORKFLOW_FEATURING_FEATURED="Réadmhaoin: %s"
PLG_WORKFLOW_FEATURING_TRANSITION_ACTIONS_FEATURING_DESC="Sainigh an staid réadmhaoin ar chóir mír a shocrú, nuair a chuirtear an t-aistriú seo i bhfeidhm."
PLG_WORKFLOW_FEATURING_TRANSITION_ACTIONS_FEATURING_LABEL="Staid Réadmhaoin"
PLG_WORKFLOW_FEATURING_XML_DESCRIPTION="Cuir gníomhartha réadmhaoin le haistrithe sreafa oibre do do mhíreanna."
