; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_READMORE="Cnaipe - Léigh níos mó"
PLG_READMORE_ALREADY_EXISTS="Tá nasc Léigh níos mó &hellip; ann cheana féin a cuireadh isteach. Ní cheadaítear ach nasc amháin. Úsáid {pagebreak} chun an leathanach a roinnt níos mó."
PLG_READMORE_BUTTON_READMORE="Léigh Níos Mó"
PLG_READMORE_XML_DESCRIPTION="Cumasaíonn cnaipe a ligeann duit an nasc <em>Léigh níos mó &hellip;</em> a chur isteach in Airteagal."
