; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS_TINYMCE="Eagarthóir - TinyMCE"
PLG_TINY_BUILDER="Tógálaí Cumraíochta TinyMCE"
PLG_TINY_BUTTON_TOGGLE_EDITOR="Athraigh Eagarthóir"
PLG_TINY_CONFIG_TEXTFILTER_ACL_LABEL="Úsáid Scagaire Téacs Joomla"
PLG_TINY_CORE_BUTTONS="Ábhar CMS"
PLG_TINY_DND_ADDITIONALDATA="Sonraí Breise"
PLG_TINY_DND_ALTTEXT="Cur Síos Íomhá (Téacs Alt)"
PLG_TINY_DND_EMPTY_ALT="Gan Cur Síos"
PLG_TINY_DND_FILE_EXISTS_ERROR="Tá an comhad \"%s\" ann cheana."
PLG_TINY_DND_LAZYLOADED="Beidh an íomhá luchtaithe go mall"
PLG_TINY_ERR_CUSTOMCSSFILENOTPRESENT="Cuireadh isteach an t-ainm comhaid %s sa réimse CSS Saincheaptha TinyMCE. Níorbh fhéidir an comhad seo a fháil sa fhillteán teimpléid réamhshocraithe. Níl aon stíleanna ar fáil."
PLG_TINY_ERR_EDITORCSSFILENOTPRESENT="Níorbh fhéidir an comhad 'editor.css' a fháil sa teimpléad nó sa fhillteán system/templates. Níl aon stíleanna ar fáil."
PLG_TINY_ERR_UNSUPPORTEDBROWSER="Níl uaslódáil íomhá tarraing agus scaoil ar fáil do do bhrabhsálaí. Smaoinigh ar bhrabhsálaí atá comhoiriúnach go hiomlán le HTML5 a úsáid."
PLG_TINY_FIELD_ADVIMAGE_LABEL="Íomhá Ardleibhéil"
PLG_TINY_FIELD_ADVLIST_LABEL="Liosta Ardleibhéil"
PLG_TINY_FIELD_CONTENTCODE_LABEL="Cód Teanga"
PLG_TINY_FIELD_CONTENTLANGS_DESC="Ligeann teanga na gcodanna duit focal nó frása a mharcáil mar theanga dhifriúil. Chun an liosta teangacha a chruthú, ní mór duit ainm teanga agus cód teanga a chur isteach. Is féidir leis an gcód seo a bheith díreach don teanga m.sh.: de nó is féidir leis an réigiún a áireamh m.sh. de-AT."
PLG_TINY_FIELD_CONTENTLANGS_LABEL="Teanga na gCodanna"
PLG_TINY_FIELD_CONTENTLANGUAGE_LABEL="Ainm Teanga"
PLG_TINY_FIELD_CONTEXTMENU_LABEL="Roghchlár Comhthéacs"
PLG_TINY_FIELD_CSS_DESC="De réir réamhshocraithe, lorgaíonn an Breiseán comhad editor.css. Mura féidir leis ceann a fháil i bhfillteán CSS an teimpléid réamhshocraithe, lódálann sé an comhad editor.css ón teimpléad córas."
PLG_TINY_FIELD_CSS_LABEL="Ranganna CSS Teimpléid"
PLG_TINY_FIELD_CUSTOMBUTTON_LABEL="Cnaipe Saincheaptha"
PLG_TINY_FIELD_CUSTOMPLUGIN_LABEL="Breiseán Saincheaptha"
PLG_TINY_FIELD_CUSTOM_CONTENT_TEMPLATE_PATH_DESC="Eolaire darb ainm \"tinymce\" i do theimpléad láithreáin."
PLG_TINY_FIELD_CUSTOM_CONTENT_TEMPLATE_PATH_LABEL="Eolaire Teimpléad Ábhair"
PLG_TINY_FIELD_CUSTOM_CSS_DESC="Comhad CSS roghnach a dhéanfaidh comhad caighdeánach editor.css a shárú. Cuir isteach ainm comhaid chun tagairt a dhéanamh do chomhad i bhfillteán CSS an teimpléid réamhshocraithe (mar shampla, media/templates/site/cassiopeia/css/). Nó cuir isteach cosán URL iomlán chuig an gcomhad CSS saincheaptha. Má chuireann tú luach isteach sa réimse seo, úsáidfear an comhad seo in ionad an chomhaid editor.css."
PLG_TINY_FIELD_CUSTOM_CSS_LABEL="Ranganna CSS Saincheaptha"
PLG_TINY_FIELD_CUSTOM_PATH_LABEL="Eolaire Íomhánna"
PLG_TINY_FIELD_DIRECTION_LABEL="Treoir Téacs"
PLG_TINY_FIELD_DRAG_DROP_LABEL="Íomhánna Tarraing agus Scaoil"
PLG_TINY_FIELD_ELEMENTS_LABEL="Eilimintí Bailí Leathnaithe"
PLG_TINY_FIELD_ENCODING_LABEL="Ionchódú Eintiteas"
PLG_TINY_FIELD_EXTERNALPLUGINS_DESC="Soláthair péire comhdhéanta d'Ainm Breiseáin agus cosán foinse chuig comhad JavaScript an Bhreiseáin. Ba chóir go mbeadh an Cosán coibhneasta le fréamh an láithreáin, nó URL iomlán."
PLG_TINY_FIELD_EXTERNALPLUGINS_LABEL="URLanna Breiseán Seachtracha"
PLG_TINY_FIELD_EXTERNALPLUGINS_NAME_LABEL="Ainm Breiseáin"
PLG_TINY_FIELD_EXTERNALPLUGINS_PATH_LABEL="Cosán"
PLG_TINY_FIELD_HTMLHEIGHT_LABEL="Airde HTML"
PLG_TINY_FIELD_HTMLWIDTH_LABEL="Leithead HTML"
PLG_TINY_FIELD_LABEL_ADVANCEDPARAMS="Ardleibhéil"
PLG_TINY_FIELD_LANGCODE_LABEL="Cód Teanga"
PLG_TINY_FIELD_LANGSELECT_LABEL="Roghnú Teanga Uathoibríoch"
PLG_TINY_FIELD_LINK_CLASSES_LIST_DESC="Cuir ranganna réamhshocraithe leis an liosta anuas ranganna sa dialóg cruthú nasc."
PLG_TINY_FIELD_LINK_CLASSES_LIST_LABEL="Liosta Ranganna Nasc"
PLG_TINY_FIELD_LINK_CLASS_LIST_LABEL="Liosta Ranganna"
PLG_TINY_FIELD_LINK_CLASS_NAME_LABEL="Ainm"
PLG_TINY_FIELD_LINK_CLASS_NONE="Dada"
PLG_TINY_FIELD_NEWLINES_LABEL="Línte Nua"
PLG_TINY_FIELD_NUMBER_OF_SETS_LABEL="Líon na Socruithe"
PLG_TINY_FIELD_PASTE_AS_TEXT_LABEL="Greamaigh Mar Théacs"
PLG_TINY_FIELD_PATH_LABEL="Conair an Eilimint"
PLG_TINY_FIELD_PROHIBITED_LABEL="Eilimintí Toirmiscthe"
PLG_TINY_FIELD_RESIZE_HORIZONTAL_LABEL="Athmhéid Chothrománach"
PLG_TINY_FIELD_RESIZING_LABEL="Athmhéid"
PLG_TINY_FIELD_SANDBOX_IFRAMES_DESC="Is gné slándála é seo a chuireann srian ar cad is féidir leis an iframe a dhéanamh trí tréith bosca gainimh a shocrú do gach iframe. Moltar an ghné seo a chumasú ar chúiseanna slándála. Ná díghníomhachtaigh ach amháin má tá an iframe ag teip a luchtú agus tá tú cinnte go bhfuil an t-ábhar iframe sábháilte."
PLG_TINY_FIELD_SANDBOX_IFRAMES_LABEL="Iframes Bosca Gainimh"
PLG_TINY_FIELD_SETACCESS_LABEL="Sann an Socrú seo do"
PLG_TINY_FIELD_SKIN_ADMIN_DARK_LABEL="Craiceann an Riarthóra (Mód Dorcha)"
PLG_TINY_FIELD_SKIN_ADMIN_LABEL="Craiceann an Riarthóra"
PLG_TINY_FIELD_SKIN_DARK_LABEL="Craiceann an tSuímh (Mód Dorcha)"
PLG_TINY_FIELD_SKIN_INFO_DESC="Cóipeáil do chraicne nua chuig: /media/vendor/tinymce/skins/ui."
PLG_TINY_FIELD_SKIN_INFO_LABEL="Chun craicne saincheaptha a fháil téigh chuig: <a href=\"https://skin.tiny.cloud/t5/\" target=\"_blank\" rel=\"noopener noreferrer\">Cruthaitheoir Craicne</a>"
PLG_TINY_FIELD_SKIN_LABEL="Craiceann an tSuímh"
PLG_TINY_FIELD_SOURCECODE_LABEL="Sainmhíniú ar Chód Foinse"
PLG_TINY_FIELD_TEXTPATTERN_DESC="Úsáid sintéis Markdown chun ábhar a chumadh le naisc, liostaí, agus stíleanna eile."
PLG_TINY_FIELD_TEXTPATTERN_LABEL="Markdown"
PLG_TINY_FIELD_TOOLBAR_MODE_LABEL="Mód an Bharra Uirlisí"
PLG_TINY_FIELD_URLS_LABEL="URLanna"
PLG_TINY_FIELD_VALIDELEMENTS_DESC="Sainmhíníonn sé cé na heilimintí a fhanfaidh sa téacs in eagar nuair a shábhálann an t-eagarthóir (is meascán de shonraíocht iomlán HTML5 agus HTML4 é an tacar rialacha réamhshocraithe don rogha seo)."
PLG_TINY_FIELD_VALIDELEMENTS_LABEL="Eilimintí Bailí"
PLG_TINY_FIELD_VALUE_ABSOLUTE="Aibhsithe"
PLG_TINY_FIELD_VALUE_ADVANCED="Ardleibhéal"
PLG_TINY_FIELD_VALUE_BR="Eilimintí BR"
PLG_TINY_FIELD_VALUE_EXTENDED="Leathnaithe"
PLG_TINY_FIELD_VALUE_FLOATING="Snámh"
PLG_TINY_FIELD_VALUE_LTR="Ó Chlé go Deas"
PLG_TINY_FIELD_VALUE_NAMED="ainmnithe"
PLG_TINY_FIELD_VALUE_NUMERIC="uimhriúil"
PLG_TINY_FIELD_VALUE_P="Eilimintí P"
PLG_TINY_FIELD_VALUE_RAW="amh"
PLG_TINY_FIELD_VALUE_RELATIVE="Coibhneasta"
PLG_TINY_FIELD_VALUE_RTL="Ó Dheas go Clé"
PLG_TINY_FIELD_VALUE_SCROLLING="Scoráil"
PLG_TINY_FIELD_VALUE_SIMPLE="Simplí"
PLG_TINY_FIELD_VALUE_SLIDING="Sleamhnán"
PLG_TINY_FIELD_VALUE_WRAP="Timfhilleadh"
PLG_TINY_FIELD_WORDCOUNT_LABEL="Líon Focal"
PLG_TINY_LEGACY_WARNING="<p>Tá an <a href=\"%s\">Breiseán Eagarthóir TinyMCE</a> nuashonraithe. Faoi láthair úsáideann sé do chumraíocht atá ann cheana. Trí an breiseán a chur in eagar, is féidir leat leagan amach éagsúla a shannadh agus a shaincheapadh do ghrúpaí úsáideoirí ar leith.</p><p>Rabhadh: nuair a chuireann tú an breiseán in eagar, caillfidh tú do shocruithe roimhe seo go léir!</p>"
PLG_TINY_MENU_CONTAINER="Coimeádán"
PLG_TINY_SET_PRESET_BUTTON_ADVANCED="Úsáid réamhshocrú ardleibhéil"
PLG_TINY_SET_PRESET_BUTTON_MEDIUM="Úsáid réamhshocrú meánleibhéil"
PLG_TINY_SET_PRESET_BUTTON_SIMPLE="Úsáid réamhshocrú simplí"
PLG_TINY_SET_SOURCE_PANEL_DESCRIPTION="<strong>Gach roghchlár agus cnaipe atá ar fáil.</strong>"
PLG_TINY_SET_TARGET_PANEL_DESCRIPTION="Úsáid an painéal thíos chun TinyMCE a shaincheapadh (tarraing agus scaoil) do gach socrú."
PLG_TINY_SET_TARGET_PANEL_TITLE="Socruithe TinyMCE"
PLG_TINY_SET_TITLE="Socrú %d"
PLG_TINY_TOOLBAR_BUTTON_FONTSELECT="Roghnaigh Cló"
PLG_TINY_TOOLBAR_BUTTON_FONTSIZESELECT="Roghnaigh Méid Cló"
PLG_TINY_TOOLBAR_BUTTON_FORMATSELECT="Roghnaigh Formáid"
PLG_TINY_TOOLBAR_BUTTON_SEPARATOR="Deighilteoir"
PLG_TINY_TOOLBAR_BUTTON_STYLESELECT="Roghnaigh Stíl"
PLG_TINY_XML_DESCRIPTION="Is eagarthóir WYSIWYG HTML JavaScript bunaithe ar an ngréasán é TinyMCE atá neamhspleách ar ardán. Ag baint úsáide as <strong>tacair</strong> is féidir leat an t-eagarthóir a chumrú agus a shaincheapadh do gach grúpa úsáideoirí."
