; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_REDIRECT="Córas - Athsheoladh"
PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE="Tharla earráid agus an bunachar sonraí á nuashonrú."
PLG_SYSTEM_REDIRECT_FIELD_COLLECT_URLS_LABEL="Bailigh URLanna"
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_DESC="Sainmhínigh rialtaiscí nó téarmaí nach ceart a shábháil."
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_LABEL="Eisiamh URLanna"
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_REGEXP_LABEL="Rialtaisc"
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_TERM_DESC="Rialtaisc nó téarma nach ceart a shábháil."
PLG_SYSTEM_REDIRECT_FIELD_EXCLUDE_URLS_TERM_LABEL="Téarma"
PLG_SYSTEM_REDIRECT_FIELD_STORE_FULL_URL_DESC="Sábháil an URL imithe in éag mar iomlán (lena n-áirítear fearann) nó coibhneasta (gan fearann)."
PLG_SYSTEM_REDIRECT_FIELD_STORE_FULL_URL_LABEL="Cuir Ainm Fearainn san URL Imithithe in Éag san áireamh"
PLG_SYSTEM_REDIRECT_XML_DESCRIPTION="Cuireann an breiseán athsheolta córais ar chumas an chórais Athsheolta Joomla leathanaigh ar iarraidh a ghabháil agus úsáideoirí a atreorú."
