; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_LOGOUT="Córas - Logáil Amach"
PLG_SYSTEM_LOGOUT_XML_DESCRIPTION="Cuireann an breiseán logála amach córas ar chumas Joomla an t-úsáideoir a atreorú chuig an leathanach baile má roghnaíonn siad logáil amach agus iad ar leathanach rochtana cosanta."
