; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_CALENDAR="Réimsí - Féilire"
PLG_FIELDS_CALENDAR_XML_DESCRIPTION="Ligeann an breiseán seo duit réimsí nua de chineál 'féilire' a chruthú in aon síneadh ina dtacaítear le réimsí saincheaptha."
