; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FIELDS_CHECKBOXES="Réimsí - Boscaí Seiceála"
PLG_FIELDS_CHECKBOXES_LABEL="Boscaí Seiceála (%s)"
PLG_FIELDS_CHECKBOXES_PARAMS_OPTIONS_LABEL="Luachanna Bosca Seiceála"
PLG_FIELDS_CHECKBOXES_PARAMS_OPTIONS_NAME_LABEL="Téacs"
PLG_FIELDS_CHECKBOXES_PARAMS_OPTIONS_VALUE_LABEL="Luach"
PLG_FIELDS_CHECKBOXES_XML_DESCRIPTION="Ligeann an breiseán seo duit réimsí nua de chineál 'boscaí seiceála' a chruthú in aon síneadh ina dtacaítear le réimsí saincheaptha."
