; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_INSTALLER_PACKAGEINSTALLER_DRAG_FILE_HERE="Tarraing agus scaoil comhad anseo chun uaslódáil."
PLG_INSTALLER_PACKAGEINSTALLER_EXTENSION_PACKAGE_FILE="Comhad pacáiste síneadh"
PLG_INSTALLER_PACKAGEINSTALLER_INSTALLING="Ag suiteáil &hellip;"
PLG_INSTALLER_PACKAGEINSTALLER_NO_PACKAGE="Roghnaigh pacáiste le híoslódáil le do thoil."
PLG_INSTALLER_PACKAGEINSTALLER_PLUGIN_XML_DESCRIPTION="Ligeann an breiseán seo duit síneadh a shuiteáil ó do ríomhaire áitiúil."
PLG_INSTALLER_PACKAGEINSTALLER_SELECT_FILE="Nó brabhsáil le haghaidh comhaid"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_AND_INSTALL="Uaslódáil & Suiteáil"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_ERROR_EMPTY="Earráid: Freagra folamh ón bhfreastalaí."
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_ERROR_UNKNOWN="Earráid: Earráid anaithnid nó aschur JSON neamhbhailí."
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_INSTALL_JOOMLA_EXTENSION="Uaslódáil & Suiteáil Síneadh Joomla"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOAD_PACKAGE_FILE="Uaslódáil Comhad Pacáiste"
PLG_INSTALLER_PACKAGEINSTALLER_UPLOADING="Ag uaslódáil &hellip;"
