; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_PRIVACYCHECK="Deilbhín Tapa - Fógra Iarrataí Príobháideachais Joomla!"
PLG_QUICKICON_PRIVACYCHECK_CHECKING="Ag seiceáil iarrataí &hellip;"
PLG_QUICKICON_PRIVACYCHECK_ERROR="Iarrataí anaithnid &hellip;"
PLG_QUICKICON_PRIVACYCHECK_GROUP_DESC="Grúpa an bhreiseáin seo (déantar an luach seo a chur i gcomparáid leis an luach grúpa a úsáidtear i modúil <strong>Deilbhíní Tapa</strong> chun deilbhíní a instealladh)."
PLG_QUICKICON_PRIVACYCHECK_GROUP_LABEL="Grúpa"
PLG_QUICKICON_PRIVACYCHECK_NOREQUEST="Níl aon iarrataí práinneacha príobháideachais."
PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND="Iarrataí práinneacha príobháideachais!"
PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_BUTTON="Féach ar Iarrataí"
PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_MESSAGE="%s Iarratas Príobháideachais Práinneach le bainistiú."
PLG_QUICKICON_PRIVACYCHECK_XML_DESCRIPTION="Seiceálann sé iarrataí príobháideachais a bhfuil gá le láimhseáil agus tugann sé fógra duit nuair a thugann tú cuairt ar an bPainéal Baile."
