; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS-XTD_IMAGE="Cnaipe - Meán"
PLG_IMAGE_BUTTON_IMAGE="Meán"
PLG_IMAGE_BUTTON_INSERT="Ionsáigh Meán"
PLG_IMAGE_XML_DESCRIPTION="Taispeánann sé cnaipe chun meán a chur isteach i limistéar eagarthóra. Taispeánann sé fuinneog aníos a ligeann duit airíonna an mheáin a chumrú agus comhaid nua meán a uaslódáil."
