; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_OVERRIDECHECK="Deilbhín Tapa - Fógra Nuashonraithe Forghabhálacha Joomla!"
PLG_QUICKICON_OVERRIDECHECK_CHECKING="Ag seiceáil forghabhálacha &hellip;"
PLG_QUICKICON_OVERRIDECHECK_ERROR="Earráid ar sheiceáil forghabhálacha."
PLG_QUICKICON_OVERRIDECHECK_ERROR_ENABLE="Cumasaigh breiseán <strong>Suiteálaí - forghabháil</strong>."
PLG_QUICKICON_OVERRIDECHECK_GROUP_DESC="Grúpa an bhreiseáin seo (déantar an luach seo a chur i gcomparáid leis an luach grúpa a úsáidtear i modúil <strong>Deilbhíní Tapa</strong> chun deilbhíní a instealladh)."
PLG_QUICKICON_OVERRIDECHECK_GROUP_LABEL="Grúpa"
PLG_QUICKICON_OVERRIDECHECK_OVERRIDEFOUND="Forghabháil(eacha) le seiceáil! %s"
PLG_QUICKICON_OVERRIDECHECK_UPTODATE="Tá forghabhálacha cothrom le dáta."
PLG_QUICKICON_OVERRIDECHECK_XML_DESCRIPTION="<p>Seiceálann sé forghabhálacha ar nuashonrú agus cumasaíonn sé fógraí nuair a thugann tú cuairt ar leathanach an Tosaigh Dhashboard.</p><p><strong>Rabhadh! Ní mór duit breiseán forghabhála suiteálaí a bheith cumasaithe chun torthaí a fheiceáil.</strong></p>"
