; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_DEBUG_FIELD_ALLOWED_GROUPS_LABEL="Grúpaí Ceadaithe"
PLG_DEBUG_FIELD_LANGUAGE_ERRORFILES_LABEL="Earráidí Agus Comhaid Teanga Á bParsiú"
PLG_DEBUG_FIELD_LANGUAGE_FILES_LABEL="Comhaid Teanga"
PLG_DEBUG_FIELD_LANGUAGE_STRING_LABEL="Téacs Teanga"
PLG_DEBUG_FIELD_LOG_DEPRECATED_CORE_LABEL="Roinn API Lárnach as Úsáid"
PLG_DEBUG_FIELD_LOGS_LABEL="Iontrálacha Loga"
PLG_DEBUG_FIELD_MEMORY_LABEL="Úsáid Cuimhne"
PLG_DEBUG_FIELD_PROFILING_LABEL="Próifíliú"
PLG_DEBUG_FIELD_QUERIES_LABEL="Fiosruithe"
PLG_DEBUG_FIELD_QUERY_EXPLAINS_LABEL="Míniú Fiosruithe"
PLG_DEBUG_FIELD_QUERY_PROFILES_LABEL="Próifílí Fiosruithe"
PLG_DEBUG_FIELD_QUERY_TRACES_LABEL="Rian Fiosruithe"
PLG_DEBUG_FIELD_REFRESH_ASSETS_DESC="Má tá sé cumasaithe, cuirfidh sé hash difriúil le gach comhad script/stíleán le leagan uathoibríoch ar gach athlódáil leathanach ionas nach n-úsáidfidh siad taisce an bhrabhsálaí riamh."
PLG_DEBUG_FIELD_REFRESH_ASSETS_LABEL="Athnuaigh Sócmhainní"
PLG_DEBUG_FIELD_REQUEST_LABEL="Iarraidh"
PLG_DEBUG_FIELD_SESSION_LABEL="Sonraí Seisiúin"
PLG_DEBUG_FIELD_STRIP_FIRST_LABEL="Bain an Chéad Fhocal"
PLG_DEBUG_FIELD_STRIP_PREFIX_DESC="Bain focail ó thús an téacs. Chun focail iolracha a úsáid, bain úsáid as an bhformáid: (focal1|focal2)."
PLG_DEBUG_FIELD_STRIP_PREFIX_LABEL="Bain Ó Thús"
PLG_DEBUG_FIELD_STRIP_SUFFIX_DESC="Bain focail ó dheireadh an téacs. Chun focail iolracha a úsáid, bain úsáid as an bhformáid: (focal1|focal2)."
PLG_DEBUG_FIELD_STRIP_SUFFIX_LABEL="Bain Ó Dheireadh"
PLG_DEBUG_FIELD_TRACK_REQUEST_HISTORY_LABEL="Rianaigh Stair na nIarratas"
PLG_DEBUG_FIELD_TRACK_REQUEST_HISTORY_DESC="Nuair a bhíonn sé cumasaithe, sábhálann sé sonraí stair na n-iarratas sa chóras comhad le haghaidh anailíse amach anseo. D’fhéadfadh go n-áireofaí leis na sonraí seo pasfhocail agus comharthaí rúnda. Níor cheart é seo a chumasú ach ar feadh tréimhse ghearr ama mar is féidir le duine ar bith a bhfuil rochtain léitheoireachta aige ar an bhfillteán taisce an comhad a léamh. Nuair a dhíchumasaítear an socrú seo ina dhiaidh sin, moltar go láidir an Taisce Suíomh a ghlanadh!"
PLG_DEBUG_LANGUAGE_FIELDSET_LABEL="Teanga"
PLG_DEBUG_LOGGING_FIELDSET_LABEL="Logáil"
PLG_DEBUG_XML_DESCRIPTION="Soláthraíonn an breiseán seo réimse leathan faisnéise córais chomh maith le cabhair chun comhaid aistriúcháin a chruthú."
PLG_SYSTEM_DEBUG="Córas - Dífhabhtú"
