; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_WEBSERVICES_PLUGINS="Seirbhísí Gréasáin - Breiseáin"
PLG_WEBSERVICES_PLUGINS_XML_DESCRIPTION="Cuir bealaí breiseáin leis an API do do shuíomh gréasáin."
