; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_EDITORS_TINYMCE="Eagarthóir - TinyMCE"
PLG_TINY_XML_DESCRIPTION="Is eagarthóir WYSIWYG HTML JavaScript bunaithe ar an ngréasán é TinyMCE atá neamhspleách ar ardán. Ag úsáid <strong>tacair</strong> is féidir leat an t-eagarthóir a chumrú agus a shaincheapadh do gach grúpa úsáideoirí."
