; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_JOOA11Y="Córas - Seiceálaí Inrochtaineachta Joomla"
PLG_SYSTEM_JOOA11Y_XML_DESCRIPTION="Leagann an Seiceálaí Inrochtaineachta Joomla béim amhairc ar shaincheisteanna coitianta inrochtaineachta agus inúsáidteachta. Dírithe ar údair ábhair, aithníonn an breiseán earráidí nó rabhaidh agus soláthraíonn sé treoir ar conas iad a shocrú. Tabhair faoi deara nach dtugann an breiseán seo anailís uileghabhálach ar do shuíomh Gréasáin, agus ní chinntíonn sé go huathoibríoch inrochtaineacht do shuíomh Gréasáin. Tá sé tábhachtach teimpléad atá inrochtana go bunúsach a roghnú chun a chinntiú go gcomhlíonann do shuíomh caighdeáin inrochtaineachta."
