; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_INSTALLER_OVERRIDE="Suiteálaí - Sárú"
PLG_INSTALLER_OVERRIDE_PLUGIN_XML_DESCRIPTION="Cumasaíonn an breiseán seo fógraí agus láimhseáil sárú tar éis nuashonraithe i gcás athruithe."
