; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_AUTHENTICATION_LDAP="Fíordheimhniú - LDAP"
PLG_LDAP_FIELD_AUTHMETHOD_LABEL="Modh Údaraithe"
PLG_LDAP_FIELD_BASEDN_LABEL="Bun DN"
PLG_LDAP_FIELD_CACERT_LABEL="Cosán chuig teastas an fhreastalaí"
PLG_LDAP_FIELD_CACERT_DESC="Cosán iomlán chuig an gcomhad nó an eolaire ina féidir le Joomla teastas an fhreastalaí LDAP (Údarás Teastais) a fháil. Má tá sé seo folamh, úsáidtear réamhshocruithe an chórais do na roghanna cliant TLS_CACERT agus TLS_CACERTDIR LDAP."
PLG_LDAP_FIELD_ENCRYPTION_LABEL="Slándáil Ceangail"
PLG_LDAP_FIELD_EMAIL_DESC="Tréith LDAP ina bhfuil seoladh ríomhphoist an Úsáideora."
PLG_LDAP_FIELD_EMAIL_LABEL="Léarscáil: Ríomhphost"
PLG_LDAP_FIELD_FULLNAME_DESC="Tréith LDAP ina bhfuil ainm iomlán an Úsáideora."
PLG_LDAP_FIELD_FULLNAME_LABEL="Léarscáil: Ainm Iomlán"
PLG_LDAP_FIELD_HOST_LABEL="Óstach"
PLG_LDAP_FIELD_IGNORE_REQCERT_TLS_LABEL="Neamhaird a dhéanamh ar an Teastas"
PLG_LDAP_FIELD_LDAPDEBUG_DESC="Cumasaíonn dífhabhtú crua-chódaithe go leibhéal 7"
PLG_LDAP_FIELD_LDAPDEBUG_LABEL="Dífhabhtú"
PLG_LDAP_FIELD_PASSWORD_DESC="Is é an Pasfhocal Ceangail pasfhocal cuntas riaracháin."
PLG_LDAP_FIELD_PASSWORD_LABEL="Pasfhocal Ceangail"
PLG_LDAP_FIELD_PORT_LABEL="Calafoirt"
PLG_LDAP_FIELD_REFERRALS_DESC="Socraíonn an rogha seo luach an bhratach LDAP_OPT_REFERRALS. Beidh ort é a shocrú go Níl do fhreastalaithe Windows 2003."
PLG_LDAP_FIELD_REFERRALS_LABEL="Lean Atreoruithe"
PLG_LDAP_FIELD_SEARCHSTRING_DESC="Téacs fiosrúcháin a úsáidtear chun cuardach a dhéanamh ar Úsáideoir ar leith. Déantar an eochairfhocal [search] a athsholáthar go dinimiciúil leis an logáil isteach a sholáthraíonn an tÚsáideoir. Sampla de théacs is ea: uid=[search]. Is féidir roinnt téacsanna a úsáid scartha le leathcholúin. Úsáidtear tar éis an ceangal tosaigh do gach modh."
PLG_LDAP_FIELD_SEARCHSTRING_LABEL="Téacs Cuardaigh"
PLG_LDAP_FIELD_UID_DESC="Tréith LDAP ina bhfuil ID Logála an Úsáideora. Maidir le Eolaire Gníomhach is é seo sAMAccountName."
PLG_LDAP_FIELD_UID_LABEL="Léarscáil: ID Úsáideora"
PLG_LDAP_FIELD_USERNAME_DESC="Sainmhíníonn an t-Úsáideoir Ceangail agus an Pasfhocal Ceangail paraiméadair ceangail don chéim breathnaithe DN. Tá dhá rogha ar fáil: breathnú DN gan ainm (Fág an dá réimse folamh) agus ceangal riaracháin (Is é an t-Úsáideoir Ceangail ainm úsáideora cuntas riaracháin, mar shampla Riarthóir). Úsáidtear ach amháin i modh Ceangail agus Cuardaigh."
PLG_LDAP_FIELD_USERNAME_LABEL="Úsáideoir Ceangail"
PLG_LDAP_FIELD_USERSDN_DESC="Déantar an eochairfhocal [username] a athsholáthar go dinimiciúil leis an logáil isteach a sholáthraíonn an tÚsáideoir. Sampla de théacs is ea: uid=[username], dc=mo-fearann, dc=com. Is féidir roinnt téacsanna a úsáid, scartha le leathcholúin. Úsáidtear ach amháin do mhodh Ceangail go Díreach mar Úsáideoir."
PLG_LDAP_FIELD_USERSDN_LABEL="DN an Úsáideora"
PLG_LDAP_FIELD_V3_DESC="Is é LDAP2 an réamhshocrú, ach éilíonn na leaganacha is déanaí de OpenLdap ar chliaint LDAPV3 a úsáid."
PLG_LDAP_FIELD_V3_LABEL="LDAP V3"
PLG_LDAP_FIELD_VALUE_BINDSEARCH="Ceangail agus Cuardaigh"
PLG_LDAP_FIELD_VALUE_BINDUSER="Ceangail go Díreach mar Úsáideoir"
PLG_LDAP_FIELD_VALUE_ENCRYPTIONNONE="Dada"
PLG_LDAP_FIELD_VALUE_ENCRYPTIONSSL="SSL/TLS"
PLG_LDAP_FIELD_VALUE_ENCRYPTIONTLS="STARTTLS"
PLG_LDAP_XML_DESCRIPTION="<p>Déileálann sé le Fíordheimhniú Úsáideora i gcoinne freastalaí LDAP.</p><p><strong>Rabhadh! Caithfidh tú ar a laghad breiseán fíordheimhnithe amháin a bheith cumasaithe agat nó caillfidh tú rochtain ar do shuíomh.</strong></p>"
