; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_LANGUAGEFILTER="Córas - Scagaire Teanga"
PLG_SYSTEM_LANGUAGEFILTER_BROWSER_SETTINGS="Socruithe Brabhsálaí"
PLG_SYSTEM_LANGUAGEFILTER_ERROR_NO_CONTENT_LANGUAGE="Níl aon teanga ábhair foilsithe agat, ach tá an breiseán Scagaire Teanga cumasaithe agat. Cuirfidh sé seo go leor earráidí faoi deara!"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_ALTERNATE_META_LABEL="Cuir Clibeanna Meta Malartacha leis"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_AUTOMATIC_CHANGE_LABEL="Athrú Teanga Uathoibríoch"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_COOKIE_LABEL="Saolré Fianán"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_DETECT_BROWSER_LABEL="Roghnú Teanga do Chuairteoirí Nua"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_ITEM_ASSOCIATIONS_LABEL="Comhlachais Míreanna"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_REMOVE_DEFAULT_PREFIX_LABEL="Bain Cód Teanga URL"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_XDEFAULT_LABEL="Cuir Clib Meta x-default leis"
PLG_SYSTEM_LANGUAGEFILTER_FIELD_XDEFAULT_LANGUAGE_LABEL="Teanga x-default"
PLG_SYSTEM_LANGUAGEFILTER_OPTION_DEFAULT_LANGUAGE="Teanga réamhshocraithe an chomhéadain"
PLG_SYSTEM_LANGUAGEFILTER_OPTION_SESSION="Seisiún"
PLG_SYSTEM_LANGUAGEFILTER_OPTION_YEAR="Bliain"
PLG_SYSTEM_LANGUAGEFILTER_PRIVACY_CAPABILITY_LANGUAGE_COOKIE="Ar shuíomh a thacaíonn le teangacha iolracha, is féidir an breiseán seo a chumrú chun fianán a shocrú ar bhrabhsálaí an úsáideora a chuimhníonn ar a rogha teanga. Úsáidtear an fianán seo chun úsáideoirí a atreorú chuig a dteanga roghnaithe nuair a thugann siad cuairt ar an suíomh agus nuair a chruthaítear seisiún nua. Tá ainm an fhianáin bunaithe ar hash a ghintear go randamach agus mar sin níl aitheantóir seasta aige."
PLG_SYSTEM_LANGUAGEFILTER_SITE_LANGUAGE="Teanga an tSuímh"
PLG_SYSTEM_LANGUAGEFILTER_XML_DESCRIPTION="Scagann an breiseán seo an t-ábhar taispeánta ag brath ar an teanga."
