; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MULTIFACTORAUTH_TOTP="Fíordheimhniú Ilfhachtóra - Cód Fíoraithe"
PLG_MULTIFACTORAUTH_TOTP_XML_DESCRIPTION="Fíordheimhniú Ilfhachtóra do úsáideoirí do shuímh ag úsáid cóid fíoraithe sé dhigit a ghintear le feidhmchlár fíordheimhnithe (Google Authenticator, Authy, LastPass Authenticator, srl), bainisteoir pasfhocal (1Password, BitWarden, Keeper, KeePassXC, Strongbox, srl) nó, i gcásanna áirithe, a mbrabhsálaí."
