; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FILESYSTEM_LOCAL="Córas Comhad - Áitiúil"
PLG_FILESYSTEM_LOCAL_XML_DESCRIPTION="Breiseán córas comhad chun ceann nó níos mó de eolairí áitiúla a shainiú chun do chuid comhad meán a stóráil."
