; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SCHEMAORG_ARTICLE="Schema.org - Alt"
PLG_SCHEMAORG_ARTICLE_DESCRIPTION_LABEL="Tuilleadh eolais ar an Cineál Alt Schema.org ar fáil ag <a href=\"https://schema.org/Article\" target=\"_blank\" rel=\"noopener noreferrer\">https://schema.org/Article</a>"
PLG_SCHEMAORG_ARTICLE_FIELD_ADDRESS_LABEL="Seoladh"
PLG_SCHEMAORG_ARTICLE_FIELD_AUTHOR_LABEL="Údar"
PLG_SCHEMAORG_ARTICLE_FIELD_DATE_MODIFIED_LABEL="Dáta Athraithe"
PLG_SCHEMAORG_ARTICLE_FIELD_DATE_PUBLISHED_LABEL="Dáta Foilsithe"
PLG_SCHEMAORG_ARTICLE_FIELD_DESCRIPTION_LABEL="Cur Síos"
PLG_SCHEMAORG_ARTICLE_FIELD_EMAIL_LABEL="Ríomhphost"
PLG_SCHEMAORG_ARTICLE_FIELD_GENERIC_FIELD_LABEL="Réimse Ginearálta"
PLG_SCHEMAORG_ARTICLE_FIELD_GENERIC_TITLE_LABEL="Teideal"
PLG_SCHEMAORG_ARTICLE_FIELD_GENERIC_VALUE_LABEL="Luach"
PLG_SCHEMAORG_ARTICLE_FIELD_HEADLINE_LABEL="Ceannteideal"
PLG_SCHEMAORG_ARTICLE_FIELD_IMAGE_LABEL="Íomhá"
PLG_SCHEMAORG_ARTICLE_FIELD_LOCALITY_LABEL="Ceantar"
PLG_SCHEMAORG_ARTICLE_FIELD_LOGO_LABEL="Lógó"
PLG_SCHEMAORG_ARTICLE_FIELD_NAME_LABEL="Ainm"
PLG_SCHEMAORG_ARTICLE_FIELD_ORGANIZATION_LABEL="Eagraíocht"
PLG_SCHEMAORG_ARTICLE_FIELD_PERSON_LABEL="Duine"
PLG_SCHEMAORG_ARTICLE_FIELD_POSTAL_CODE_LABEL="Cód Poist"
PLG_SCHEMAORG_ARTICLE_FIELD_STREET_ADDRESS_LABEL="Seoladh Sráide"
PLG_SCHEMAORG_ARTICLE_FIELD_TYPE_LABEL="Cineál"
PLG_SCHEMAORG_ARTICLE_FIELD_URL_LABEL="Url"
PLG_SCHEMAORG_ARTICLE_XML_DESCRIPTION="Cuireann sé Alt leis mar chineál scéime nua i scéimeanna atá ann cheana."
