; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_SITE_STATUS="Tasc - Stádas an tSuímh"
PLG_TASK_SITE_STATUS_DESC="Athraíonn stádas an tSuímh ar gach rith."
PLG_TASK_SITE_STATUS_ERROR_CONFIGURATION_PHP_NOTUNWRITABLE="Níorbh fhéidir configuration.php a dhéanamh neamh-in-scríofa."
PLG_TASK_SITE_STATUS_ERROR_CONFIGURATION_PHP_NOTWRITABLE="Níorbh fhéidir configuration.php a dhéanamh in-scríofa."
PLG_TASK_SITE_STATUS_ERROR_WRITE_FAILED="Níorbh fhéidir scríobh chuig an gcomhad cumraíochta!"
PLG_TASK_SITE_STATUS_ROUTINE_END_LOG_MESSAGE="Cód tuairisce ToggleOffline: %1$d. Am Próiseála: %2$.2f soicind."
PLG_TASK_SITE_STATUS_TASK_LOG_SITE_STATUS="Bhí an Suíomh %1$s, tá sé anois %2$s."
PLG_TASK_SITE_STATUS_SET_OFFLINE_DESC="Socraíonn stádas an tSuímh go as líne ar gach rith."
PLG_TASK_SITE_STATUS_SET_OFFLINE_ROUTINE_END_LOG_MESSAGE="Cód tuairisce SetOffline: %1$d. Am Próiseála: %2$.2f soicind."
PLG_TASK_SITE_STATUS_SET_OFFLINE_TITLE="Socraigh an Suíomh As Líne"
PLG_TASK_SITE_STATUS_SET_ONLINE_DESC="Socraíonn stádas an tSuímh go ar líne ar gach rith."
PLG_TASK_SITE_STATUS_SET_ONLINE_ROUTINE_END_LOG_MESSAGE="Cód tuairisce SetOnline: %1$d. Am Próiseála: %2$.2f soicind."
PLG_TASK_SITE_STATUS_SET_ONLINE_TITLE="Socraigh an Suíomh Ar Líne"
PLG_TASK_SITE_STATUS_TITLE="Athraigh As Líne"
PLG_TASK_SITE_STATUS_XML_DESCRIPTION="Cuireann sé gnáthaimh tasc ar fáil chun stádas as líne an tSuímh a athrú."
