; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_TASK_DELETEACTIONLOGS="Tasc - Scrios Logaí Gníomhaíochta"
PLG_TASK_DELETEACTIONLOGS_DELETE_DESC="Scrios logaí gníomhaíochta tar éis na laethanta sonraithe."
PLG_TASK_DELETEACTIONLOGS_DELETE_TITLE="Scrios Logaí Gníomhaíochta"
PLG_TASK_DELETEACTIONLOGS_LOG_DELETE_PERIOD="Laethanta chun logaí gníomhaíochta a scriosadh tar éis"
PLG_TASK_DELETEACTIONLOGS_XML_DESCRIPTION="Breiseán seo chun tascanna scriosta Logaí Gníomhaíochta a sceidealú."
