; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CACHE_XML_DESCRIPTION="Soláthraíonn sé taisce leathanach. Níl sé seo oiriúnach ach do shuíomhanna a bhfuil ábhar statach acu nó ábhar nach n-athraíonn go minic."
PLG_SYSTEM_CACHE="Córas - Taisce Leathanach"
