; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_CATEGORIES="Cuardach Cliste - Catagóirí"
PLG_FINDER_CATEGORIES_FIELD_SEARCH_ARCHIVED_DESC="Nuair a athraíonn tú an socrú seo, caithfidh tú an t-ordú innéacs a rith i gCuardach Cliste sula dtiocfaidh sé seo i bhfeidhm."
PLG_FINDER_CATEGORIES_FIELD_SEARCH_ARCHIVED_LABEL="Cuardaigh Ábhar Cartlainne"
PLG_FINDER_CATEGORIES_TAXONOMIES_LABEL="Tacsanomaíochtaí le hInnéacsú"
PLG_FINDER_CATEGORIES_TAXONOMIES_LANGUAGE="Teanga"
PLG_FINDER_CATEGORIES_TAXONOMIES_TYPE="Cineál"
PLG_FINDER_CATEGORIES_XML_DESCRIPTION="Innéacsaíonn an breiseán seo Catagóirí Joomla!"
