; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_MEDIA-ACTION_RESIZE="Gníomh Meán - Athrú Méid"
PLG_MEDIA-ACTION_RESIZE_BATCH_DESC="Socruithe do ghníomhartha taobh freastalaí nuair a chruthaítear íomhánna."
PLG_MEDIA-ACTION_RESIZE_BATCH_LABEL="Socruithe Baisc"
PLG_MEDIA-ACTION_RESIZE_BATCH_MAX_HEIGHT_LABEL="Airde Uasta Íomhá"
PLG_MEDIA-ACTION_RESIZE_BATCH_MAX_WIDTH_LABEL="Leithead Uasta Íomhá"
PLG_MEDIA-ACTION_RESIZE_LABEL="Athrú Méid"
PLG_MEDIA-ACTION_RESIZE_PARAM_HEIGHT="Airde"
PLG_MEDIA-ACTION_RESIZE_PARAM_WIDTH="Leithead"
PLG_MEDIA-ACTION_RESIZE_QUALITY="Cáilíocht"
PLG_MEDIA-ACTION_RESIZE_XML_DESCRIPTION="Feidhmiúlacht athraithe méide d'íomhánna."
