; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_INSTALLER_WEBINSTALLER="Suiteálaí - Suiteáil ón nGréasán"
PLG_INSTALLER_WEBINSTALLER_CANNOT_INSTALL_EXTENSION_IN_PLUGIN="Ní féidir an síneadh seo a shuiteáil tríd an gcóras suiteála ón ngréasán. Tabhair cuairt ar shuíomh Gréasáin an fhorbróra le ceannach/íoslódáil."
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_CONFIRM="Deimhnigh an suiteáil trí chnaipe an Suiteáil a roghnú"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_CONFIRM_NAME="Ainm an tSínidh"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_CONFIRM_URL="Suiteáil ó"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_LOADING="Ag luchtú &hellip;"
PLG_INSTALLER_WEBINSTALLER_INSTALL_WEB_LOADING_ERROR="Ní féidir ceangal leis an bhfreastalaí Joomla! Bain triail eile as níos déanaí."
PLG_INSTALLER_WEBINSTALLER_REDIRECT_TO_EXTERNAL_SITE_TO_INSTALL="Déanfar tú a atreorú chuig an nasc seo a leanas chun an clárú/ceannach a chríochnú: [SITEURL]" ; The [SITEURL] placeholder should not be translated as it is used in the JavaScript API to insert the correct URL
PLG_INSTALLER_WEBINSTALLER_TAB_LABEL="Suiteáil ón nGréasán"
PLG_INSTALLER_WEBINSTALLER_XML_DESCRIPTION="Ligeann an breiseán seo duit suiteáil go díreach ón Eolaire Síneadh Joomla!"
