; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_JOOMLA="Úsáideoir - Joomla!"
PLG_USER_JOOMLA_XML_DESCRIPTION="<p>Déanann sé láimhseáil ar shioncrónú Úsáideoirí réamhshocraithe Joomla.</p><p><strong>Rabhadh! Caithfidh tú ar a laghad breiseán amháin a chumasú a láimhseálann bainistíocht seisiúin úsáideora nó caillfidh tú rochtain ar fad ar do shuíomh.</strong></p>"
