; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_WEBAUTHN="Córas - Logáil Isteach Gan Focal Faire (Passkey)"
PLG_SYSTEM_WEBAUTHN_DESCRIPTION="Cumasaíonn fíordheimhniú gan focal faire ag úsáid eochracha pas. Tabhair faoi deara nach mbeidh an cluaisín eochracha pas san eagarthóir próifíl úsáideora agus na cnaipí logála isteach eochracha pas le feiceáil ach amháin má tá an t-úsáideoir ag rochtain an tsuímh thar HTTPS. Ní oibreoidh clárú eochracha pas agus iad a úsáid chun logáil isteach ar do shuíomh ach amháin nuair atá do shuíomh ag úsáid teastas bailí, sínithe ag Údarás Teastais a bhfuil muinín ag brabhsálaí an úsáideora as."
