; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_TASK_NOTIFICATION="Córas - Fógra Tasc"
PLG_SYSTEM_TASK_NOTIFICATION_FAILURE_MAIL_BODY="Dia dhuit,\n\n\nTheip ar fheidhmiú pleanáilte Tasc Sceidealta#{TASK_ID}, {TASK_TITLE}, le cód imeachta {EXIT_CODE} ag {EXEC_DATE_TIME}.\n\nTabhair cuairt ar chúlra Joomla! le haghaidh tuilleadh eolais.\n\n{TASK_OUTPUT}"
PLG_SYSTEM_TASK_NOTIFICATION_FAILURE_MAIL_SUBJECT="Teip Tasc"
PLG_SYSTEM_TASK_NOTIFICATION_FAILURE_USERGROUP_LABEL="Grúpaí Úsáideoirí le Fógra a Thabhairt"
PLG_SYSTEM_TASK_NOTIFICATION_FATAL_MAIL_BODY="Dia dhuit,\n\nD'éirigh le feidhmiú pleanáilte Tasc Sceidealaithe#{TASK_ID}, {TASK_TITLE}, téarnamh ó theip mharfach.\n\nD'fhéadfadh sé seo a chiallaíonn go ndearna feidhmiú an tasc acmhainní an chórais a ídiú nó na srianta ón PHP INI.\n\nTabhair cuairt ar chúlra Joomla! le haghaidh tuilleadh eolais."
PLG_SYSTEM_TASK_NOTIFICATION_FATAL_MAIL_SUBJECT="Tasc Téarnaimh ó Theip Mharfach"
PLG_SYSTEM_TASK_NOTIFICATION_FATAL_USERGROUP_LABEL="Grúpaí Úsáideoirí le Fógra a Thabhairt"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_FAILURE_MAIL_TOGGLE="Teip Tasc"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_FATAL_FAILURE_MAIL_TOGGLE="Teipeanna Marfacha/Timpistí (Moltar)"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_ORPHANED_TASK_MAIL_TOGGLE="Tascanna Dílleachta (Moltar)"
PLG_SYSTEM_TASK_NOTIFICATION_LABEL_SUCCESS_MAIL_TOGGLE="Rath Tasc"
PLG_SYSTEM_TASK_NOTIFICATION_NO_MAIL_SENT="Níorbh fhéidir fógra tasc a sheoladh chuig aon úsáideoir. Ciallaíonn sé seo ceachtar nach bhfuil an postálaí socraithe i gceart nó nach bhfuil aon úsáideoir le ríomhphoist chórais cumasaithe, pribhléid `core.manage` com_scheduler ann."
PLG_SYSTEM_TASK_NOTIFICATION_ORPHAN_MAIL_BODY="Dia dhuit,\n\nTá Tasc Sceidealta#{TASK_ID}, {TASK_TITLE}, dílleachta. Is dócha go gciallaíonn sé seo gur baineadh nó gur dhíchumasadh an breiseán soláthraí ó do shuiteáil Joomla!.\n\nTabhair cuairt ar chúlra Joomla! chun fiosrú a dhéanamh."
PLG_SYSTEM_TASK_NOTIFICATION_ORPHAN_MAIL_SUBJECT="Tasc Dílleachta Nua"
PLG_SYSTEM_TASK_NOTIFICATION_ORPHAN_USERGROUP_LABEL="Grúpaí Úsáideoirí le Fógra a Thabhairt"
PLG_SYSTEM_TASK_NOTIFICATION_SUCCESS_MAIL_BODY="Dia dhuit,\n\nTá Tasc Sceidealta#{TASK_ID}, {TASK_TITLE}, curtha i gcrích go rathúil ag {EXEC_DATE_TIME}.\n\n{TASK_OUTPUT}"
PLG_SYSTEM_TASK_NOTIFICATION_SUCCESS_MAIL_SUBJECT="Tasc Rathúil"
PLG_SYSTEM_TASK_NOTIFICATION_SUCCESS_USERGROUP_LABEL="Grúpaí Úsáideoirí le Fógra a Thabhairt"
PLG_SYSTEM_TASK_NOTIFICATION_USER_FETCH_FAIL="Theip ar úsáideoirí a fháil chun fógraí a sheoladh chucu."
PLG_SYSTEM_TASK_NOTIFICATION_XML_DESCRIPTION="Freagrach as fógraí ríomhphoist do fheidhmiú tascanna Sceidealta."
