; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_USER_JOOMLA="Úsáideoir - Joomla!"
PLG_USER_JOOMLA_FIELD_AUTOREGISTER_LABEL="Cruthaigh Úsáideoirí go huathoibríoch"
PLG_USER_JOOMLA_FIELD_FORCELOGOUT_LABEL="Dífhostaigh go fórsa do gach Seisiún?"
PLG_USER_JOOMLA_FIELD_MAILTOUSER_LABEL="Ríomhphost Fógra do Úsáideoir"
PLG_USER_JOOMLA_MAIL_MAIL_DESC="Seolta chuig úsáideoir nua nuair a chruthaítear é sa chúlra."
PLG_USER_JOOMLA_MAIL_MAIL_TITLE="Úsáideoirí: Úsáideoir Nua"
PLG_USER_JOOMLA_NEW_USER_EMAIL_BODY="Dia duit {NAME},\n\n\nCuireadh thú mar Úsáideoir chuig {SITENAME} ag Riarthóir.\n\nTá d'ainm úsáideora agus do phasfhocal sa ríomhphost seo chun logáil isteach chuig {URL}\n\nAinm Úsáideora: {USERNAME}\nPasfhocal: {PASSWORD}\n\n\nNá freagair an teachtaireacht seo le do thoil mar go bhfuil sé ginte go huathoibríoch agus tá sé chun críocha faisnéise amháin."
PLG_USER_JOOMLA_NEW_USER_EMAIL_SUBJECT="Sonraí Úsáideora Nua"
PLG_USER_JOOMLA_XML_DESCRIPTION="<p>Déileálann sé le sioncrónú Úsáideoirí réamhshocraithe Joomla.</p><p><strong>Rabhadh! Caithfidh tú ar a laghad breiseán amháin a láimhseálann bainistíocht seisiún úsáideora a bheith cumasaithe agat nó caillfidh tú gach rochtain ar do shuíomh.</strong></p>"
