; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_FINDER_CONTENT="Cuardach Cliste - Ábhar"
PLG_FINDER_CONTENT_XML_DESCRIPTION="Nuashonraíonn sé innéacsanna Airteagail Joomla! aon uair a chruthaítear, a mhodhnófar nó a scriostar alt. TABHAIR FAOI DEARA go gcaithfear an breiseán Ábhar - Cuardach Cliste a chumasú."
PLG_FINDER_STATISTICS_ARTICLE="Alt"
