; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_CONTENT_LOADMODULE="Ábhar - Lódáil Modúil"
PLG_LOADMODULE_FIELD_STYLE_LABEL="Stíl"
PLG_LOADMODULE_FIELD_VALUE_DIVS="Fillte ag Divs"
PLG_LOADMODULE_FIELD_VALUE_RAW="Gan fillte (aschur amh)"
PLG_LOADMODULE_FIELD_VALUE_TABLE="Fillte ag tábla (colún)"
PLG_LOADMODULE_XML_DESCRIPTION="Laistigh de ábhar, lódálann an breiseán seo Modúl de réir ID, Sintéis: {loadmoduleid 1} nó Modúl de réir suíomh, Sintéis: {loadposition user1} nó Modúl de réir ainm, Sintéis: {loadmodule mod_login}. Go roghnach is féidir stíl modúil a shonrú agus do loadmodule modúl ar leith de réir teidil, Sintéis: {loadmodule mod_login,teideal modúil,stíl}."
; Deprecated, will be removed with 6.0
PLG_LOADMODULE_FIELD_VALUE_HORIZONTAL="Fillte ag tábla (cothrománach)"
PLG_LOADMODULE_FIELD_VALUE_MULTIPLEDIVS="Fillte ag Ilroinnte"
