; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

ATUM="Teimpléad Riaracháin Atum"
TPL_ATUM_POSITION_BOTTOM="Bun"
TPL_ATUM_POSITION_CPANEL="Painéal Rialúcháin"
TPL_ATUM_POSITION_CUSTOMTOP="Barr Saincheaptha"
TPL_ATUM_POSITION_DEBUG="Dífhabhtú"
TPL_ATUM_POSITION_ICON="Deilbhíní Tapa"
TPL_ATUM_POSITION_LOGIN="Logáil Isteach"
TPL_ATUM_POSITION_MENU="Roghchlár"
TPL_ATUM_POSITION_SIDEBAR="Barra Taoibh"
TPL_ATUM_POSITION_STATUS="Stádas"
TPL_ATUM_POSITION_TITLE="Teideal"
TPL_ATUM_POSITION_TOOLBAR="Barra Uirlisí"
TPL_ATUM_POSITION_TOP="Barr"
TPL_ATUM_XML_DESCRIPTION="Ag leanúint téama déithe/ban-déithe na hÉigipte (Khepri ó 1.5, Hathor ó 1.6, Isis ó 3.0), is é Atum ainm an teimpléid riaracháin do Joomla 4 agus Joomla 5."
