; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_USERS_ACTIVATION_TOKEN_NOT_FOUND="Níor aimsíodh an cód fíoraithe. Seiceáil an bhfuil do chuntas gníomhachtaithe cheana féin agus déan iarracht logáil isteach."
COM_USERS_CAPTCHA_LABEL="Captcha"
COM_USERS_DATABASE_ERROR="Earráid ag fáil an úsáideora ón mbunachar sonraí: %s"
COM_USERS_EDIT_PROFILE="Cuir Próifíl in Eagar"
COM_USERS_EMAIL_ACCOUNT_DETAILS="Sonraí Cuntais do {NAME} ag {SITENAME}"
COM_USERS_EMAIL_ACTIVATED_BY_ADMIN_ACTIVATION_BODY="Dia duit {NAME},\n\nTá do chuntas gníomhachtaithe ag riarthóir. Is féidir leat logáil isteach anois ag {SITEURL} ag úsáid an ainm úsáideora {USERNAME} agus an focal faire a roghnaigh tú agus tú ag clárú."
COM_USERS_EMAIL_ACTIVATED_BY_ADMIN_ACTIVATION_SUBJECT="Cuntas gníomhachtaithe do {NAME} ag {SITENAME}"
COM_USERS_EMAIL_ACTIVATE_WITH_ADMIN_ACTIVATION_BODY="Dia duit riarthóir,\n\nTá úsáideoir nua cláraithe ag {SITENAME}.\nTá a seoladh ríomhphoist fíoraithe ag an úsáideoir agus iarrann sé/sí ort a gcuntas a cheadú.\nTá a gcuid sonraí sa ríomhphost seo:\n\n  Ainm :  {NAME} \n  ríomhphost:  {EMAIL} \n  Ainm Úsáideora:  {USERNAME} \n\nIs féidir leat an t-úsáideoir a ghníomhachtú trí roghnú an nasc thíos:\n{ACTIVATE}"
COM_USERS_EMAIL_ACTIVATE_WITH_ADMIN_ACTIVATION_SUBJECT="Ceadaithe clárúcháin ag teastáil do chuntas {NAME} ag {SITENAME}"
COM_USERS_EMAIL_PASSWORD_RESET_BODY="Dia duit,\n\nRinneadh iarratas chun do phasfhocal cuntais {SITENAME} a athshocrú. Chun do phasfhocal a athshocrú, beidh ort an cód fíoraithe seo a chur isteach chun a dhearbhú go raibh an t-iarratas dlisteanach.\n\nIs é an cód fíoraithe {TOKEN}\n\nRoghnaigh an URL thíos agus lean ar aghaidh le do phasfhocal a athshocrú.\n\n{LINK_TEXT} \n\nGo raibh maith agat."
COM_USERS_EMAIL_PASSWORD_RESET_SUBJECT="D'iarratas athshocraithe pasfhocal {SITENAME}"
COM_USERS_EMAIL_REGISTERED_BODY="Dia duit {NAME},\n\nGo raibh maith agat as clárú ag {SITENAME}.\n\nIs féidir leat logáil isteach anois ag {SITEURL} ag úsáid an ainm úsáideora agus an pasfhocal seo a leanas:\n\nAinm Úsáideora: {USERNAME}\nPasfhocal: {PASSWORD_CLEAR}"
COM_USERS_EMAIL_REGISTERED_BODY_NOPW="Dia duit {NAME},\n\nGo raibh maith agat as clárú ag {SITENAME}.\n\nIs féidir leat logáil isteach anois ag {SITEURL} ag úsáid an ainm úsáideora agus an pasfhocal a chláraigh tú leis."
COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY="Dia duit riarthóir, \n\nTá úsáideoir nua '{NAME}', ainm úsáideora '{USERNAME}', cláraithe ag {SITEURL}."
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_BODY="Dia duit {NAME},\n\nGo raibh maith agat as clárú ag {SITENAME}. Tá do chuntas cruthaithe agus caithfear é a ghníomhachtú sula féidir leat é a úsáid.\nChun an cuntas a ghníomhachtú roghnaigh an nasc seo a leanas nó cóipeáil agus greamaigh é i do bhrabhsálaí:\n{ACTIVATE} \n\nTar éis gníomhachtaithe is féidir leat logáil isteach ag {SITEURL} ag úsáid an ainm úsáideora agus an pasfhocal seo a leanas:\n\nAinm Úsáideora: {USERNAME}\nPasfhocal: {PASSWORD_CLEAR}"
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_BODY_NOPW="Dia duit {NAME},\n\nGo raibh maith agat as clárú ag {SITENAME}. Tá do chuntas cruthaithe agus caithfear é a ghníomhachtú sula féidir leat é a úsáid.\nChun an cuntas a ghníomhachtú roghnaigh an nasc seo a leanas nó cóipeáil agus greamaigh é i do bhrabhsálaí:\n{ACTIVATE} \n\nTar éis gníomhachtaithe is féidir leat logáil isteach ag {SITEURL} ag úsáid an ainm úsáideora agus an pasfhocal a chuir tú isteach le linn clárúcháin:\n\nAinm Úsáideora: {USERNAME}"
COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_BODY="Dia duit {NAME},\n\nGo raibh maith agat as clárú ag {SITENAME}. Tá do chuntas cruthaithe agus caithfear é a fhíorú sula féidir leat é a úsáid.\n\nChun an cuntas a fhíorú roghnaigh an nasc seo a leanas nó cóipeáil-ghreamaigh é i do bhrabhsálaí:\n{ACTIVATE} \n\nTar éis fíoraithe cuirfear fógra chuig riarthóir chun do chuntas a ghníomhachtú. Gheobhaidh tú dearbhú nuair a bheidh sé déanta.\n\nNuair a bheidh an cuntas sin gníomhachtaithe féadfaidh tú logáil isteach chuig {SITEURL} ag úsáid an t-ainm úsáideora agus an focal faire seo a leanas:\n\nAinm Úsáideora: {USERNAME}\nFocal Faire: {PASSWORD_CLEAR}"
COM_USERS_EMAIL_REGISTERED_WITH_ADMIN_ACTIVATION_BODY_NOPW="Dia duit {NAME},\n\nGo raibh maith agat as clárú ag {SITENAME}. Tá do chuntas cruthaithe agus caithfear é a fhíorú sula féidir leat é a úsáid.\n\nChun an cuntas a fhíorú roghnaigh an nasc seo a leanas nó cóipeáil-ghreamaigh é i do bhrabhsálaí:\n{ACTIVATE} \n\nTar éis fíoraithe cuirfear fógra chuig riarthóir chun do chuntas a ghníomhachtú. Gheobhaidh tú dearbhú nuair a bheidh sé déanta.\n\nNuair a bheidh an cuntas sin gníomhachtaithe féadfaidh tú logáil isteach chuig {SITEURL} ag úsáid an t-ainm úsáideora seo a leanas agus an focal faire a chuir tú isteach le linn clárúcháin:\n\nAinm Úsáideora: {USERNAME}"
COM_USERS_EMAIL_USERNAME_REMINDER_BODY="Dia duit,\n\nIarradh meabhrúchán ainm úsáideora do do chuntas {SITENAME}.\n\nDo ainm úsáideora: {USERNAME}\n\nChun logáil isteach i do chuntas, roghnaigh an nasc thíos.\n\n{LINK_TEXT} \n\nGo raibh maith agat."
COM_USERS_EMAIL_USERNAME_REMINDER_SUBJECT="Do ainm úsáideora {SITENAME}"
COM_USERS_FIELD_PASSWORD_RESET_LABEL="Seoladh Ríomhphoist"
COM_USERS_FIELD_REMIND_EMAIL_LABEL="Seoladh Ríomhphoist"
COM_USERS_FIELD_RESET_CONFIRM_TOKEN_LABEL="Cód Fíoraithe"
COM_USERS_FIELD_RESET_CONFIRM_USERNAME_LABEL="Ainm Úsáideora"
COM_USERS_FIELD_RESET_PASSWORD1_LABEL="Focal Faire"
COM_USERS_FIELD_RESET_PASSWORD1_MESSAGE="Níl na focail faire a chuir tú isteach ag teacht le chéile. Cuir isteach an focal faire atá uait sa réimse focal faire agus deimhnigh do iontráil trí é a chur isteach sa réimse deimhnithe focal faire."
COM_USERS_FIELD_RESET_PASSWORD2_LABEL="Deimhnigh Focal Faire"
COM_USERS_FRONTEND_LOGOUT_SUCCESS="Tá tú dílogáilte amach."
COM_USERS_INVALID_EMAIL="Seoladh ríomhphoist neamhbhailí"
COM_USERS_LBL_SELECT_INSTRUCTIONS="Roghnaigh conas is mian leat do logáil isteach ar an suíomh seo a fhíorú."
COM_USERS_LOGIN_DEFAULT_LABEL="Logáil Isteach Úsáideora"
COM_USERS_LOGIN_REGISTER="Nach bhfuil cuntas agat?"
COM_USERS_LOGIN_REMEMBER_ME="Cuimhnigh orm"
COM_USERS_LOGIN_REMIND="An ndearna tú dearmad ar d'ainm úsáideora?"
COM_USERS_LOGIN_RESET="An ndearna tú dearmad ar do phasfhocal?"
COM_USERS_LOGIN_USERNAME_LABEL="Ainm Úsáideora"
COM_USERS_MAIL_FAILED="Theip ar sheoladh ríomhphoist."
COM_USERS_MAIL_SEND_FAILURE_BODY="Tharla earráid agus an ríomhphost clárúcháin úsáideora á sheoladh. Is é an t-úsáideoir a rinne iarracht clárú: %s"
COM_USERS_MAIL_SEND_FAILURE_SUBJECT="Earráid ag seoladh ríomhphoist"
COM_USERS_MFA_ADD_AUTHENTICATOR_OF_TYPE="Cuir %s nua leis"
COM_USERS_MFA_ADD_PAGE_HEAD="Cuir Modh Fíordheimhnithe Ilfhachtóra leis"
COM_USERS_MFA_BACKUPCODES_PRINT_PROMPT="Ligeann Cód Cúltaca duit logáil isteach ar an suíomh má theipeann ar do mhodh Fíordheimhnithe Ilfhachtóra rialta nó mura bhfuil rochtain agat air a thuilleadh. Ní féidir gach cód a úsáid ach <em>uair amháin</em>."
COM_USERS_MFA_BACKUPCODES_PRINT_PROMPT_HEAD="<a href=\"%1s\" class=\"%2s\">Priontáil na cóid seo</a> agus coinnigh iad i do sparán."
COM_USERS_MFA_BACKUPCODES_RESET="Athghin Cóid Cúltaca"
COM_USERS_MFA_BACKUPCODES_RESET_INFO="Úsáid an cnaipe thíos chun sraith nua de Chóid Cúltaca a ghiniúint. Molaimid duit é seo a dhéanamh má cheapann tú go bhfuil do Chóid Cúltaca i mbaol, m.sh. má fuair duine greim ar phrionta leo, nó má tá tú ag rith íseal ar Chóid Cúltaca atá ar fáil."
COM_USERS_MFA_EDIT_FIELD_DEFAULT="Déan é seo mar an modh réamhshocraithe Fíordheimhnithe Ilfhachtóra"
COM_USERS_MFA_EDIT_FIELD_TITLE="Teideal"
COM_USERS_MFA_EDIT_FIELD_TITLE_DESC="Feicfidh tú agus riarthóirí an tsuímh an t-ainm seo sa liosta de mhodhanna Fíordheimhnithe Ilfhachtóra atá ar fáil do do chuntas úsáideora. Ná cuir aon fhaisnéis íogair nó inaitheanta phearsanta san áireamh le do thoil."
COM_USERS_MFA_EDIT_PAGE_HEAD="Modh Fíordheimhnithe Ilfhachtóra a mhodhnú"
COM_USERS_MFA_FIRSTTIME_INSTRUCTIONS_HEAD="Úsáid Fíordheimhniú Ilfhachtóra le haghaidh slándála breise"
COM_USERS_MFA_FIRSTTIME_INSTRUCTIONS_WHATITDOES="Seo mar a oibríonn sé. Cuir modh Fíordheimhnithe Ilfhachtóra thíos. As seo amach, gach uair a logálann tú isteach ar an suíomh iarrfar ort an modh seo a úsáid chun an logáil isteach a chríochnú. Fiú má ghoid duine d'ainm úsáideora agus do phasfhocal ní bheidh rochtain acu ar do chuntas ar an suíomh seo."
COM_USERS_MFA_FIRSTTIME_NOTINTERESTED="Ná taispeáin seo arís"
COM_USERS_MFA_FIRSTTIME_PAGE_HEAD="Socraigh do Fhíordheimhniú Ilfhachtóra"
COM_USERS_MFA_INVALID_CODE="Theip ar an bhFíordheimhniú Ilfhachtóra. Bain triail eile as le do thoil."
COM_USERS_MFA_INVALID_METHOD="Modh Fíordheimhnithe Ilfhachtóra neamhbhailí."
COM_USERS_MFA_LBL_CREATEDON="Curtha leis: %s"
COM_USERS_MFA_LBL_DATE_FORMAT_PAST="F d, Y"
COM_USERS_MFA_LBL_DATE_FORMAT_TODAY="H:i"
COM_USERS_MFA_LBL_DATE_FORMAT_YESTERDAY="H:i"
COM_USERS_MFA_LBL_LASTUSED="Úsáidte go deireanach: %s"
COM_USERS_MFA_LBL_PAST="%s"
COM_USERS_MFA_LBL_TODAY="Inniu, %s"
COM_USERS_MFA_LBL_YESTERDAY="Inné, %s"
COM_USERS_MFA_LIST_DEFAULTTAG="Réamhshocrú"
COM_USERS_MFA_LIST_INSTRUCTIONS="Cuir ar a laghad modh amháin Fíordheimhnithe Ilfhachtóra leis. Gach uair a logálann tú isteach ar an suíomh iarrfar ort é a sholáthar."
COM_USERS_MFA_LIST_PAGE_HEAD="Do roghanna Fíordheimhnithe Ilfhachtóra"
COM_USERS_MFA_LIST_REMOVEALL="Múch"
COM_USERS_MFA_LIST_STATUS_OFF="Níl Fíordheimhniú Ilfhachtóra <strong>cumasaíodh</strong>."
COM_USERS_MFA_LIST_STATUS_ON="Tá Fíordheimhniú Ilfhachtóra cumasaithe."
COM_USERS_MFA_LOGOUT="Logáil Amach"
COM_USERS_MFA_MANDATORY_NOTICE_BODY="Cuir modh Fíordheimhnithe Ilfhachtóra ar fáil do do chuntas úsáideora. Ní bheidh tú in ann leanúint ar aghaidh ag úsáid an tsuímh go dtí go ndéanfaidh tú amhlaidh."
COM_USERS_MFA_MANDATORY_NOTICE_HEAD="Tá Fíordheimhniú Ilfhachtóra éigeantach do do chuntas úsáideora"
COM_USERS_MFA_SELECT_PAGE_HEAD="Roghnaigh modh Fíordheimhnithe Ilfhachtóra"
COM_USERS_MFA_USE_DIFFERENT_METHOD="Roghnaigh modh difriúil"
COM_USERS_MFA_TRY_LIMIT_REACHED="Shroich tú an teorainn iarrachtaí don mhodh Fíordheimhnithe atá roghnaithe faoi láthair. Roghnaigh modh difriúil nó fan le do thoil."
COM_USERS_MFA_VALIDATE="Bailíochtú"
COM_USERS_OR="nó"
COM_USERS_PROFILE="Próifíl Úsáideora"
COM_USERS_PROFILE_CORE_LEGEND="Próifíl"
COM_USERS_PROFILE_DEFAULT_LABEL="Cuir do Phróifíl in Eagar"
COM_USERS_PROFILE_EMAIL1_LABEL="Seoladh Ríomhphoist"
COM_USERS_PROFILE_LAST_VISITED_DATE_LABEL="Dáta Cuairte Deireanaí"
COM_USERS_PROFILE_MULTIFACTOR_AUTH="Fíordheimhniú Ilfhachtóra"
COM_USERS_PROFILE_NAME_LABEL="Ainm"
COM_USERS_PROFILE_NEVER_VISITED="Seo an chéad uair a thug tú cuairt ar an suíomh seo."
COM_USERS_PROFILE_NOCHANGE_USERNAME_DESC="Má theastaíonn uait d'ainm úsáideora a athrú, déan teagmháil le riarthóir an tsuímh le do thoil."
COM_USERS_PROFILE_PASSWORD1_LABEL="Pasfhocal"
```ini
COM_USERS_PROFILE_PASSWORD1_MESSAGE="Níl na pasfhocail a chuir tú isteach ag teacht le chéile. Cuir isteach an pasfhocal atá uait sa réimse pasfhocal agus deimhnigh d'iontráil trí é a chur isteach sa réimse deimhnigh pasfhocal."
COM_USERS_PROFILE_PASSWORD2_LABEL="Deimhnigh Pasfhocal"
COM_USERS_PROFILE_REGISTERED_DATE_LABEL="Dáta Cláraithe"
COM_USERS_PROFILE_SAVE_FAILED="Níorbh fhéidir an próifíl a shábháil: %s"
COM_USERS_PROFILE_SAVE_SUCCESS="Próifíl sábháilte."
COM_USERS_PROFILE_USERNAME_LABEL="Ainm Úsáideora"
COM_USERS_PROFILE_USERNAME_MESSAGE="Níl an t-ainm úsáideora a chuir tú isteach ar fáil. Roghnaigh ainm úsáideora eile le do thoil."
COM_USERS_PROFILE_VALUE_NOT_FOUND="Réamhshocrú Suíomh Gréasáin"
COM_USERS_REGISTER_EMAIL1_LABEL="Seoladh Ríomhphoist"
COM_USERS_REGISTER_NAME_LABEL="Ainm"
COM_USERS_REGISTER_REQUIRED="<strong class=\"red\">*</strong> Réimse riachtanach"
COM_USERS_REGISTER_USERNAME_LABEL="Ainm Úsáideora"
COM_USERS_REGISTER_USERNAME_MESSAGE="Níl an t-ainm úsáideora a chuir tú isteach ar fáil. Roghnaigh ainm úsáideora eile le do thoil."
COM_USERS_REGISTRATION="Clárú Úsáideora"
COM_USERS_REGISTRATION_ACL_ADMIN_ACTIVATION="Logáil isteach le do thoil chun a dhearbhú go bhfuil tú údaraithe chun cuntais nua a ghníomhachtú."
COM_USERS_REGISTRATION_ACL_ADMIN_ACTIVATION_PERMISSIONS="Níl tú údaraithe chun cuntais nua a ghníomhachtú, logáil isteach le cuntas pribhléideach le do thoil."
COM_USERS_REGISTRATION_ACTIVATE_SUCCESS="Tá do Chuntas gníomhachtaithe. Is féidir leat logáil isteach anois ag úsáid an ainm úsáideora agus an pasfhocal a roghnaigh tú le linn an chláraithe."
COM_USERS_REGISTRATION_ACTIVATION_NOTIFY_SEND_MAIL_FAILED="Tharla earráid agus an ríomhphost fógra gníomhachtaithe á sheoladh"
COM_USERS_REGISTRATION_ACTIVATION_SAVE_FAILED="Theip ar shábháil sonraí gníomhachtaithe: %s"
COM_USERS_REGISTRATION_ADMINACTIVATE_SUCCESS="Tá cuntas an úsáideora gníomhachtaithe agus tá an t-úsáideoir curtha ar an eolas faoi."
COM_USERS_REGISTRATION_COMPLETE_ACTIVATE="Tá do chuntas cruthaithe agus tá nasc gníomhachtaithe seolta chuig an seoladh ríomhphoist a chuir tú isteach. Tabhair faoi deara go gcaithfidh tú an cuntas a ghníomhachtú trí roghnú an nasc gníomhachtaithe nuair a fhaigheann tú an ríomhphost sula féidir leat logáil isteach."
COM_USERS_REGISTRATION_COMPLETE_VERIFY="Tá do chuntas cruthaithe agus tá nasc fíoraithe seolta chuig an seoladh ríomhphoist a chuir tú isteach. Tabhair faoi deara go gcaithfidh tú an cuntas a fhíorú trí roghnú an nasc fíoraithe nuair a fhaigheann tú an ríomhphost agus ansin gníomhóidh riarthóir do chuntas sula féidir leat logáil isteach."
COM_USERS_REGISTRATION_DEFAULT_LABEL="Clárú Úsáideora"
COM_USERS_REGISTRATION_SAVE_FAILED="Theip ar an gclárú: %s"
COM_USERS_REGISTRATION_SAVE_SUCCESS="Go raibh maith agat as clárú. Is féidir leat logáil isteach anois ag úsáid an ainm úsáideora agus an pasfhocal a chláraigh tú leis."
COM_USERS_REGISTRATION_SEND_MAIL_FAILED="Tharla earráid agus an ríomhphost clárúcháin á sheoladh. Tá teachtaireacht seolta chuig riarthóir an tsuímh seo."
COM_USERS_REGISTRATION_VERIFY_SUCCESS="Tá do sheoladh ríomhphoist fíoraithe. Nuair a cheadóidh riarthóir do chuntas cuirfear in iúl duit trí ríomhphost agus is féidir leat logáil isteach ar an suíomh."
COM_USERS_REMIND="Meabhrúchán"
COM_USERS_REMIND_DEFAULT_LABEL="Cuir isteach an seoladh ríomhphoist a bhaineann le do chuntas Úsáideora le do thoil. Seolfar d'ainm úsáideora chuig an seoladh ríomhphoist atá ar chomhad."
COM_USERS_REMIND_LIMIT_ERROR_N_HOURS="Tá an líon uasta athshocruithe pasfhocal ceadaithe sáraithe agat. Bain triail eile as i %d uair an chloig."
COM_USERS_REMIND_LIMIT_ERROR_N_HOURS_1="Tá an líon uasta athshocruithe pasfhocal ceadaithe sáraithe agat. Bain triail eile as i gceann uair an chloig."
```
COM_USERS_REMIND_REQUEST="Má tá an seoladh ríomhphoist a chuir tú isteach cláraithe ar an suíomh seo gheobhaidh tú ríomhphost le meabhrúchán go luath."
COM_USERS_REMIND_REQUEST_ERROR="Earráid ag iarraidh meabhrúchán pasfhocail."
COM_USERS_REMIND_REQUEST_FAILED="Theip ar an meabhrúchán: %s"
COM_USERS_REMIND_REQUEST_SUCCESS="Seoladh meabhrúchán. Seiceáil do phost le do thoil."
COM_USERS_REMIND_SUPERADMIN_ERROR="Ní féidir le Super User meabhrúchán pasfhocail a iarraidh. Déan teagmháil le Super User eile nó bain úsáid as modh malartach."
COM_USERS_RESET="Athshocrú Pasfhocail"
COM_USERS_RESET_COMPLETE_ERROR="Earráid ag críochnú athshocrú pasfhocail."
COM_USERS_RESET_COMPLETE_FAILED="Theip ar chríochnú athshocrú pasfhocail: %s"
COM_USERS_RESET_COMPLETE_LABEL="Chun an próiseas athshocrú pasfhocail a chríochnú, cuir isteach pasfhocal nua le do thoil."
COM_USERS_RESET_COMPLETE_SUCCESS="D'éirigh le hathshocrú pasfhocail. Is féidir leat logáil isteach ar an suíomh anois."
COM_USERS_RESET_COMPLETE_TOKENS_MISSING="Theip ar do dhearbhú athshocrú pasfhocail mar bhí an cód fíoraithe ar iarraidh."
COM_USERS_RESET_CONFIRM_ERROR="Earráid agus an pasfhocal á dhearbhú."
COM_USERS_RESET_CONFIRM_FAILED="Theip ar do dhearbhú athshocrú pasfhocail mar bhí an cód fíoraithe neamhbhailí. %s"
COM_USERS_RESET_CONFIRM_LABEL="Seoladh ríomhphost chuig do sheoladh ríomhphoist. Tá cód fíoraithe sa ríomhphost, cuir isteach an cód fíoraithe sa réimse thíos le do thoil chun a chruthú gur tusa úinéir an chuntais seo."
COM_USERS_RESET_REQUEST="Má tá an seoladh ríomhphoist a chuir tú isteach cláraithe ar an suíomh seo gheobhaidh tú ríomhphost le nasc chun an pasfhocal do do chuntas a athshocrú go luath."
COM_USERS_RESET_REQUEST_ERROR="Earráid ag iarraidh athshocrú pasfhocail."
COM_USERS_RESET_REQUEST_FAILED="Theip ar athshocrú pasfhocail: %s"
COM_USERS_RESET_REQUEST_LABEL="Cuir isteach an seoladh ríomhphoist do do chuntas le do thoil. Seolfar cód fíoraithe chugat. Nuair a bheidh an cód fíoraithe faighte agat, beidh tú in ann pasfhocal nua a roghnú do do chuntas."
COM_USERS_SETTINGS_FIELDSET_LABEL="Socruithe Bunúsacha"
COM_USERS_USER_ALLOWTOURAUTOSTART_LABEL="Ceadaigh Tús Uathoibríoch ar Thurais"
COM_USERS_USER_BACKUPCODE="Cód Cúltaca"
COM_USERS_USER_BACKUPCODES="Cóid Chúltaca"
COM_USERS_USER_BACKUPCODES_CAPTIVE_PROMPT="Mura bhfuil rochtain agat ar do ghnáth-mhodh Fíordheimhnithe Ilfhachtóra bain úsáid as aon cheann de do Chóid Chúltaca sa réimse thíos. Cuimhnigh le do thoil nach féidir an cód cúltaca éigeandála seo a athúsáid."
COM_USERS_USER_BACKUPCODES_DESC="Mura bhfuil rochtain agat ar do ghléas Fíordheimhnithe Ilfhachtóra is féidir leat aon cheann de na pasfhocail seo a úsáid in ionad gnáthchód slándála. Scriostar gach ceann de na cóid éigeandála seo láithreach tar éis iad a úsáid. Molaimid na cóid seo a phriontáil agus an prionta a choinneáil in áit shábháilte agus inrochtana, m.sh. do sparán nó bosca taisce sábháilte."
COM_USERS_USER_BLOCKED="Tá an t-úsáideoir seo blocáilte. Má tá sé seo ina earráid, déan teagmháil le riarthóir le do thoil."
COM_USERS_USER_COLORSCHEME_LABEL="Mód Dorcha"
COM_USERS_USER_COLORSCHEME_OPTION_DARK="Úsáid scéim dathanna Dorcha"
COM_USERS_USER_COLORSCHEME_OPTION_FOLLOW_OS="Lean socruithe an OS"
COM_USERS_USER_COLORSCHEME_OPTION_LIGHT="Úsáid scéim dathanna Éadrom"
COM_USERS_USER_FIELD_BACKEND_LANGUAGE_LABEL="Teanga an Chúlra"
COM_USERS_USER_FIELD_BACKEND_TEMPLATE_LABEL="Stíl Teimpléid an Chúlra"
COM_USERS_USER_FIELD_EDITOR_LABEL="Eagarthóir"
COM_USERS_USER_FIELD_FRONTEND_LANGUAGE_LABEL="Teanga an Tosaigh"
COM_USERS_USER_FIELD_TIMEZONE_LABEL="Crios Ama"
COM_USERS_USER_MULTIFACTOR_AUTH="Fíordheimhniú Ilfhachtóra"
COM_USERS_USER_NOT_FOUND="Níor aimsíodh an t-úsáideoir."
COM_USERS_USER_SAVE_FAILED="Theip ar shábháil úsáideora: %s"
