; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MEDIA="Meáin"
COM_MEDIA_ACTIONS_TOOLBAR_LABEL="Mír: %s"
COM_MEDIA_ACTION_DELETE="Scrios"
COM_MEDIA_ACTION_DOWNLOAD="Íoslódáil"
COM_MEDIA_ACTION_EDIT="Eagar"
COM_MEDIA_ACTION_PREVIEW="Réamhamharc"
COM_MEDIA_ACTION_RENAME="Athainmnigh"
COM_MEDIA_ACTION_SHARE="Faigh Nasc"
COM_MEDIA_ALIGN="Snámh Íomhá"
COM_MEDIA_ALIGN_DESC="Cuirfidh sé seo na ranganna 'float-start', 'pull-center' nó 'float-end' i bhfeidhm ar an eilimint '<figure>' nó '<img>'."
COM_MEDIA_BREADCRUMB_LABEL="Blúire Aráin"
COM_MEDIA_BROWSE_FILES="Brabhsáil Comhaid"
COM_MEDIA_CAPTION="Fotheideal"
COM_MEDIA_CAPTION_CLASS_DESC="Cuirfidh sé seo an rang iontráilte i bhfeidhm ar an eilimint '<figcaption>'. Mar shampla: 'text-start', 'text-end', 'text-center'."
COM_MEDIA_CAPTION_CLASS_LABEL="Rang Fhotheideal"
COM_MEDIA_CHANGE_ORDERING="Athraigh Ordú"
COM_MEDIA_CLEAR_LIST="Glan Liosta"
COM_MEDIA_CONFIGURATION="Meáin: Roghanna"
COM_MEDIA_CONFIRM_DELETE_MODAL="Scrios"
COM_MEDIA_CONFIRM_DELETE_MODAL_HEADING="Deimhnigh Scriosadh"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE_FILE_ALREADY_EXISTS="Ní féidir comhad a chóipeáil mar go bhfuil comhad ceann scríbe ann cheana"
COM_MEDIA_COPY_FILE_NOT_POSSIBLE="Ní féidir comhad a chóipeáil"
COM_MEDIA_COPY_FOLDER_ALREADY_EXISTS="Ní féidir fillteán a chóipeáil mar go bhfuil fillteán ceann scríbe ann cheana"
COM_MEDIA_COPY_FOLDER_DESTINATION_CAN_NOT_DELETE="Ní féidir fillteán a chóipeáil mar go bhfuil fillteán ceann scríbe ina chomhad agus ní féidir é a scriosadh"
COM_MEDIA_COPY_FOLDER_NOT_POSSIBLE="Ní féidir fillteán a chóipeáil"
COM_MEDIA_CREATE_FOLDER="Cruthaigh Fillteán"
COM_MEDIA_CREATE_NEW_FOLDER="Cruthaigh Fillteán Nua"
COM_MEDIA_CREATE_NEW_FOLDER_ERROR="Earráid ag cruthú fillteáin."
COM_MEDIA_CREATE_NEW_FOLDER_SUCCESS="Cruthaíodh fillteán."
COM_MEDIA_CURRENT_PROGRESS="Dul chun cinn reatha"
COM_MEDIA_DECREASE_GRID="Laghdú méid greille"
COM_MEDIA_DELETE_ERROR="Earráid ag scriosadh na míre."
COM_MEDIA_DELETE_NOT_POSSIBLE="Ní féidir scriosadh!"
COM_MEDIA_DELETE_SUCCESS="Scriosadh mír."
COM_MEDIA_DETAIL_VIEW="Amharc Sonraí"
COM_MEDIA_DIRECTORY="Fillteán"
COM_MEDIA_DIRECTORY_UP="Fillteán Suas"
COM_MEDIA_DROP_FILE="Scaoil comhad(aí) le hUaslódáil"
COM_MEDIA_ERROR="Tharla earráid."
COM_MEDIA_ERROR_BAD_REQUEST="Iarratas Droch"
COM_MEDIA_ERROR_FILE_EXISTS="Tá comhad ann cheana."
COM_MEDIA_ERROR_NOT_AUTHENTICATED="Níl tú fíordheimhnithe. Logáil isteach le do thoil."
COM_MEDIA_ERROR_NOT_AUTHORIZED="Níl tú údaraithe"
COM_MEDIA_ERROR_NOT_FOUND="Níor aimsíodh Comhad nó Fillteán"
COM_MEDIA_ERROR_UNABLE_TO_BROWSE_FOLDER_WARNDIRNAME="Ní féidir brabhsáil:&#160;%s. Ní mór go mbeadh carachtair alfanumeracha amháin agus gan aon spásanna i n-ainm an fhillteáin."
COM_MEDIA_ERROR_UNABLE_TO_CREATE_FOLDER_WARNDIRNAME="Ní féidir fillteán a chruthú. Ní mór go mbeadh carachtair alfanumeracha amháin agus gan aon spásanna i n-ainm an fhillteáin."
COM_MEDIA_ERROR_UNABLE_TO_DELETE="Ní féidir scriosadh:&#160;"
COM_MEDIA_ERROR_UNABLE_TO_DELETE_FILE_WARNFILENAME="Ní féidir scriosadh:&#160;%s. Ní mór go mbeadh carachtair alfanumeracha amháin agus gan aon spásanna i n-ainm an chomhaid."
COM_MEDIA_ERROR_UNABLE_TO_DELETE_FOLDER_NOT_EMPTY="Ní féidir scriosadh:&#160;%s. Níl an fillteán folamh!"
COM_MEDIA_ERROR_UNABLE_TO_DELETE_FOLDER_WARNDIRNAME="Ní féidir scriosadh:&#160;%s. Ní mór go mbeadh carachtair alfanumeracha amháin agus gan aon spásanna i n-ainm an fhillteáin."
COM_MEDIA_ERROR_WARNFILETOOLARGE="Tá an comhad seo ró-mhór le híoslódáil."
COM_MEDIA_ERROR_WARNUPLOADTOOLARGE="Sáraíonn méid iomlán an uaslódála an teorainn."
COM_MEDIA_FIELD_CHECK_MIME_DESC="Úsáid MIME Magic nó Fileinfo chun iarracht a dhéanamh comhaid a fhíorú. Bain triail as an rogha seo a dhíchumasú má fhaigheann tú earráidí cineál mime neamhbhailí."
COM_MEDIA_FIELD_CHECK_MIME_LABEL="Seiceáil Cineálacha MIME"
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_DESC="Síneadh comhaid neamhairdte le haghaidh seiceáil cineál MIME agus uaslódálacha srianta."
COM_MEDIA_FIELD_IGNORED_EXTENSIONS_LABEL="Síneadh Neamhairdte"
COM_MEDIA_FIELD_LEGAL_EXTENSIONS_DESC="Síneadh (cineálacha comhaid) atá ceadaithe agat a uaslódáil (scartha le camóg)."
COM_MEDIA_FIELD_LEGAL_EXTENSIONS_LABEL="Síneadh Dlíthiúil (Cineálacha Comhaid)"
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_DESC="Síneadh íomhá (cineálacha comhaid) atá ceadaithe agat a uaslódáil (scartha le camóg). Úsáidtear iad seo chun ceannteidil íomhá bailí a sheiceáil."
COM_MEDIA_FIELD_LEGAL_IMAGE_EXTENSIONS_LABEL="Síneadh Íomhá Dlíthiúil (Cineálacha Comhaid)"
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_DESC="Liosta de chineálacha MIME dlíthiúla le huaslódáil, scartha le camóg."
COM_MEDIA_FIELD_LEGAL_MIME_TYPES_LABEL="Cineálacha MIME Dlíthiúla"
COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Úsáid nialas le haghaidh gan teorainn. Nóta: tá teorainn uasta ag do fhreastalaí."
COM_MEDIA_FIELD_MAXIMUM_SIZE_LABEL="Méid Uasta (i MB)"
COM_MEDIA_FIELD_PATH_FILE_FOLDER_DESC="Cuir isteach an cosán chuig an bhfillteán comhaid i gcoibhneas leis an bhfréamh."
COM_MEDIA_FIELD_PATH_FILE_FOLDER_LABEL="Cosán chuig Fillteán Comhaid"
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_DESC="Cuir isteach an cosán chuig an bhfillteán íomhá i gcoibhneas leis an bhfréamh."
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_LABEL="Cosán chuig Fillteán Íomhá"
COM_MEDIA_FIELD_RESTRICT_UPLOADS_DESC="Srian a chur ar uaslódálacha d'úsáideoirí níos ísle ná bainisteoir chuig íomhánna mura bhfuil Fileinfo nó MIME Magic suiteáilte."
COM_MEDIA_FIELD_RESTRICT_UPLOADS_LABEL="Srian a Chur ar Uaslódálacha"
COM_MEDIA_FILE_EXISTS_AND_OVERRIDE="%s ann cheana. An bhfuil tú ag iarraidh é a athsholáthar?"
COM_MEDIA_FILES="Comhaid"
COM_MEDIA_FILESIZE="Méid comhaid"
COM_MEDIA_FOLDER="Fillteán"
COM_MEDIA_FOLDER_NAME="Ainm Fillteáin"
COM_MEDIA_FOLDERS="Fillteáin"
COM_MEDIA_IMAGE_DESCRIPTION="Cur síos ar Íomhá"
COM_MEDIA_IMAGE_URL="URL Íomhá"
COM_MEDIA_INCREASE_GRID="Méid greille a mhéadú"
COM_MEDIA_INSERT="Ionsáigh"
COM_MEDIA_INSERT_IMAGE="Ionsáigh Íomhá"
COM_MEDIA_MANAGE_ITEM="Bainistigh mír: %s"
COM_MEDIA_MAXIMUM_SIZE="Méid Uasta"
COM_MEDIA_MEDIA="Meáin"
COM_MEDIA_MEDIA_DATE_CREATED="Dáta cruthaithe"
COM_MEDIA_MEDIA_DATE_MODIFIED="Dáta modhnaithe"
COM_MEDIA_MEDIA_DIMENSION="Toisí"
COM_MEDIA_MEDIA_EXTENSION="Síneadh"
COM_MEDIA_MEDIA_MIME_TYPE="Cineál MIME"
COM_MEDIA_MEDIA_NAME="Ainm"
COM_MEDIA_MEDIA_SIZE="Méid"
COM_MEDIA_MEDIA_TYPE="Cineál"
COM_MEDIA_MOVE_FILE_ALREADY_EXISTS="Ní féidir comhad a bhogadh mar tá comhad ceann scríbe ann cheana"
COM_MEDIA_MOVE_FILE_EXTENSION_INVALID="Ní féidir comhad a bhogadh mar tá an síneadh neamhbhailí"
COM_MEDIA_MOVE_FILE_NOT_POSSIBLE="Ní féidir comhad a bhogadh"
COM_MEDIA_MOVE_FOLDER_ALREADY_EXISTS="Ní féidir fillteán a bhogadh mar tá fillteán ceann scríbe ann cheana"
COM_MEDIA_MOVE_FOLDER_EXISTING_DESTINATION_FAILED="Theip ar bhogadh fillteán chuig ceann scríbe atá ann cheana"
COM_MEDIA_MOVE_FOLDER_NOT_POSSIBLE="Ní féidir fillteán a bhogadh mar is comhad é an fillteán ceann scríbe agus ní féidir é a scriosadh"
COM_MEDIA_NAME="Ainm Íomhá"
COM_MEDIA_NO_IMAGES_FOUND="Níor Aimsíodh Íomhánna"
COM_MEDIA_NOT_SET="Gan Socrú"
COM_MEDIA_ORDER_ASC="Ag Ardú"
COM_MEDIA_ORDER_BY="Ordú De réir"
COM_MEDIA_ORDER_DESC="Ag Laghdu"
COM_MEDIA_ORDER_DIRECTION="Treoir Ordaithe"
COM_MEDIA_OVERALL_PROGRESS="Dul Chun Cinn Iomlán"
COM_MEDIA_PIXEL_DIMENSIONS="Toisí Picteilín (w x h)"
COM_MEDIA_PLEASE_SELECT_ITEM="Roghnaigh mír le do thoil."
COM_MEDIA_RENAME="Athainmnigh"
COM_MEDIA_RENAME_ERROR="Earráid ag athainmniú mír."
COM_MEDIA_RENAME_SUCCESS="Athainmníodh mír."
COM_MEDIA_SEARCH="Cuardaigh..."
COM_MEDIA_SELECT_ALL="Roghnaigh go léir a athrú"
COM_MEDIA_SERVER_ERROR="Earráid inmheánach freastalaí"
COM_MEDIA_SHARE="Comhad a roinnt"
COM_MEDIA_SHARE_COPY="Cóipeáil chuig an gearrthaisce"
COM_MEDIA_SHARE_COPY_FAILED_ERROR="Earráid ag cóipeáil chuig an gearrthaisce"
COM_MEDIA_SHARE_DESC="Is féidir le duine ar bith leis an nasc an comhad a fheiceáil."
COM_MEDIA_START_UPLOAD="Tosaigh Uaslódáil"
COM_MEDIA_THUMBNAIL_VIEW="Amharc Mionsamhail"
COM_MEDIA_TITLE="Teideal Íomhá"
COM_MEDIA_TOGGLE_INFO="Athraigh eolas mír"
COM_MEDIA_TOGGLE_LIST_VIEW="Athraigh idir amharc greille agus tábla"
COM_MEDIA_TOGGLE_SELECT_ITEM="Athraigh roghnú mír"
COM_MEDIA_TOOLBAR_LABEL="Bainisteoir Meán"
COM_MEDIA_UP="Suas"
COM_MEDIA_UPLOAD="Uaslódáil"
COM_MEDIA_UPLOAD_COMPLETE="Uaslódáil Críochnaithe"
COM_MEDIA_UPLOAD_FILE="Uaslódáil comhad"
COM_MEDIA_UPLOAD_SUCCESS="Mír uaslódáilte."
