; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_AJAX="Comhéadan Ajax"
COM_AJAX_FILE_NOT_EXISTS="Níl an comhad ag %s ann."
COM_AJAX_METHOD_NOT_EXISTS="Níl an modh %s ann."
COM_AJAX_MODULE_NOT_ACCESSIBLE="Níl an modúl %s foilsithe, níl rochtain agat air, nó níl sé sannaithe don mhír roghchláir reatha."
COM_AJAX_SPECIFY_FORMAT="Sonraigh formáid freagartha bailí, seachas HTML, mar shampla json, amh, dífhabhtú, srl."
COM_AJAX_TEMPLATE_NOT_ACCESSIBLE="Níl an teimpléad %s sannaithe don mhír roghchláir reatha."
COM_AJAX_XML_DESCRIPTION="Comhéadan Ajax in-fhairsingithe do Joomla."
