; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_MEDIA_SHARE_COPY="Cóipeáil chuig an ghearrthaisce"
COM_MEDIA_SHARE_COPY_FAILED_ERROR="Earráid ag cóipeáil chuig an ghearrthaisce"
COM_MEDIA_SHARE_DESC="Is féidir le duine ar bith leis an nasc an comhad a fheiceáil."
COM_MEDIA_START_UPLOAD="Tosaigh Uaslódáil"
COM_MEDIA_THUMBNAIL_VIEW="Amharc Mionsamhail"
COM_MEDIA_TITLE="Teideal Íomhá"
COM_MEDIA_TOGGLE_INFO="Athraigh eolas mír"
COM_MEDIA_TOGGLE_LIST_VIEW="Athraigh idir amharc greille agus tábla"
COM_MEDIA_TOGGLE_SELECT_ITEM="Athraigh roghnú mír"
COM_MEDIA_TOOLBAR_LABEL="Bainisteoir Meán"
COM_MEDIA_UP="Suas"
COM_MEDIA_UPLOAD="Uaslódáil"
COM_MEDIA_UPLOAD_COMPLETE="Uaslódáil Críochnaithe"
COM_MEDIA_UPLOAD_FILE="Uaslódáil comhad"
COM_MEDIA_UPLOAD_SUCCESS="Mír uaslódáilte."
