; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_FINDER="Cuardach Cliste"
COM_FINDER_ADVANCED_SEARCH_TOGGLE="Cuardach Casta"
COM_FINDER_ADVANCED_TIPS_AND="<p>Má chuireann tú isteach <strong>seo agus siúd</strong> sa fhoirm chuardaigh, gheobhaidh tú torthaí ina bhfuil an dá cheann &quot;seo&quot; agus &quot;siúd&quot;.</p>"
COM_FINDER_ADVANCED_TIPS_INTRO="<p>Seo cúpla sampla de conas is féidir leat an ghné cuardaigh a úsáid:</p>"
COM_FINDER_ADVANCED_TIPS_NOT="<p>Má chuireann tú isteach <strong>seo ní siúd</strong> sa fhoirm chuardaigh, gheobhaidh tú torthaí ina bhfuil &quot;seo&quot; agus ní &quot;siúd&quot;.</p>"
COM_FINDER_ADVANCED_TIPS_OR="<p>Má chuireann tú isteach <strong>seo nó siúd</strong> sa fhoirm chuardaigh, gheobhaidh tú torthaí ina bhfuil ceachtar &quot;seo&quot; nó &quot;siúd&quot;.</p>"
COM_FINDER_ADVANCED_TIPS_OUTRO="<p>Is féidir torthaí cuardaigh a scagadh freisin ag úsáid réimse critéar. Roghnaigh scagaire amháin nó níos mó thíos chun tosú.</p>"
COM_FINDER_ADVANCED_TIPS_PHRASE="<p>Má chuireann tú isteach <strong>&quot;seo agus siúd&quot;</strong> (le comharthaí athfhriotail) sa fhoirm chuardaigh, gheobhaidh tú torthaí ina bhfuil an frása cruinn &quot;seo agus siúd&quot;.</p>"
COM_FINDER_DEFAULT_PAGE_TITLE="Torthaí Cuardaigh"
COM_FINDER_FILTER_BRANCH_LABEL="Cuardaigh de réir %s"
COM_FINDER_FILTER_DATE1="Dáta Tosaigh"
COM_FINDER_FILTER_DATE1_DESC="Cuir isteach dáta i bhformáid YYYY-MM-DD."
COM_FINDER_FILTER_DATE1_OPERATOR="Oibreoir Dáta Tosaigh"
COM_FINDER_FILTER_DATE2="Dáta Deiridh"
COM_FINDER_FILTER_DATE2_DESC="Cuir isteach dáta i bhformáid YYYY-MM-DD."
COM_FINDER_FILTER_DATE2_OPERATOR="Oibreoir Dáta Deiridh"
COM_FINDER_FILTER_DATE_AFTER="Tar éis"
COM_FINDER_FILTER_DATE_BEFORE="Roimh"
COM_FINDER_FILTER_DATE_EXACTLY="Go díreach"
COM_FINDER_FILTER_SELECT_ALL_LABEL="Cuardaigh Uile"
COM_FINDER_FILTER_WHEN_AFTER="Tar éis"
COM_FINDER_FILTER_WHEN_BEFORE="Roimh"
COM_FINDER_OPENSEARCH_NAME="Cuardach"
COM_FINDER_QUERY_DATE_CONDITION_AFTER="tar éis"
COM_FINDER_QUERY_DATE_CONDITION_BEFORE="roimh"
COM_FINDER_QUERY_DATE_CONDITION_EXACT="go díreach ar"
COM_FINDER_QUERY_END_DATE="dáta deiridh <span class=\"when\">%s</span> <span class=\"date\">%s</span>"
COM_FINDER_QUERY_FILTER_BRANCH_VENUE="ionad"
COM_FINDER_QUERY_OPERATOR_AND="agus"
COM_FINDER_QUERY_OPERATOR_NOT="ní"
COM_FINDER_QUERY_OPERATOR_OR="nó"
COM_FINDER_QUERY_RESULTS="Ag glacadh leis %2$s, fuarthas <a href=\"#search-result-list\">%d torthaí.</a>"
COM_FINDER_QUERY_RESULTS_0="Ag glacadh leis %2$s, níor aimsíodh torthaí. <a href=\"#q\">Cuardaigh arís.</a>"
COM_FINDER_QUERY_RESULTS_1="Ag glacadh leis %2$s, fuarthas an toradh seo a leanas."
COM_FINDER_QUERY_START_DATE="dáta tosaigh <span class=\"when\">%s</span> <span class=\"date\">%s</span>"
COM_FINDER_QUERY_TAXONOMY_NODE="le <span class=\"node\">%s</span> mar <span class=\"branch\">%s</span> "
COM_FINDER_QUERY_TOKEN_EXCLUDED="<span class=\"term\">%s</span> ba chóir a eisiamh"
COM_FINDER_QUERY_TOKEN_GLUE=", agus "
COM_FINDER_QUERY_TOKEN_OPTIONAL="tá <span class=\"term\">%s</span> roghnach"
COM_FINDER_QUERY_TOKEN_REQUIRED="tá <span class=\"term\">%s</span> riachtanach"
COM_FINDER_SEARCH_ADVANCED_LEGEND="Cuardach Casta"
COM_FINDER_SEARCH_FORM_LEGEND="Fhoirm Cuardaigh"
COM_FINDER_SEARCH_FORM_LIST_LABEL="Torthaí Cuardaigh"
COM_FINDER_SEARCH_NO_RESULTS_BODY="Níorbh fhéidir torthaí cuardaigh a fháil don cheist: %s."
COM_FINDER_SEARCH_NO_RESULTS_BODY_MULTILANG="Níorbh fhéidir torthaí cuardaigh i mBéarla (en-GB) a fháil don cheist: %s."
COM_FINDER_SEARCH_NO_RESULTS_HEADING="Níor Aimsíodh Torthaí"
COM_FINDER_SEARCH_RESULTS_OF="Torthaí <strong>%s</strong> - <strong>%s</strong> de <strong>%s</strong>"
COM_FINDER_SEARCH_SIMILAR="An raibh i gceist agat: %s?"
COM_FINDER_SEARCH_TERMS="Téarmaí Cuardaigh:"
COM_FINDER_SORT_BY="Sórtáil De Réir:"
COM_FINDER_SORT_BY_PRICE_ASC="Praghas liosta ag ardú"
COM_FINDER_SORT_BY_PRICE_DESC="Praghas liosta ag titim"
COM_FINDER_SORT_BY_RELEVANCE_ASC="Ábharthacht ag ardú"
COM_FINDER_SORT_BY_RELEVANCE_DESC="Ábharthacht ag titim"
COM_FINDER_SORT_BY_SALES_PRICE_ASC="Praghas díola ag ardú"
COM_FINDER_SORT_BY_SALES_PRICE_DESC="Praghas díola ag titim"
