; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

```ini
COM_CONTENT_ON_NEW_CONTENT="Tá Alt nua curtha isteach ag '%1$s' dar teideal '%2$s'."
COM_CONTENT_ORDERING="Ordú:<br>De réir réamhshocraithe, cuirtear ailt nua sa chéad áit sa Chatagóir. Is féidir an t-ordú a athrú sa Chúlra."
COM_CONTENT_PAGEBREAK_DOC_TITLE="Briseadh Leathanaigh"
COM_CONTENT_PAGEBREAK_INSERT_BUTTON="Cuir Briseadh Leathanaigh Isteach"
COM_CONTENT_PAGEBREAK_TITLE="Teideal an Leathanaigh:"
COM_CONTENT_PAGEBREAK_TOC="Ainm Cleite an Chlár Ábhair:"
COM_CONTENT_PARENT="Catagóir Tuismitheora: %s"
COM_CONTENT_PUBLISHED_DATE="Dáta Foilsithe"
COM_CONTENT_PUBLISHED_DATE_ON="Foilsithe: %s"
COM_CONTENT_PUBLISHING="Foilsiú"
COM_CONTENT_RATINGS="Rátáil"
COM_CONTENT_RATINGS_COUNT="Rátáil: %s"
COM_CONTENT_READ_MORE="Léigh níos mó &hellip;"
COM_CONTENT_READ_MORE_TITLE="Léigh níos mó: %s"
COM_CONTENT_REGISTER_TO_READ_MORE="Cláraigh chun níos mó a léamh &hellip;"
COM_CONTENT_RUN_TRANSITION="Rith Aistriú"
COM_CONTENT_SAVE_SUCCESS="Alt sábháilte."
COM_CONTENT_SAVE_WARNING="Bhí an t-ainm cleite ann cheana, mar sin cuireadh uimhir leis ag an deireadh. Má theastaíonn uait an t-ainm cleite a athrú, téigh i dteagmháil le riarthóir an tsuímh le do thoil."
COM_CONTENT_SELECT_AN_ARTICLE="Roghnaigh Alt"
COM_CONTENT_STATE="Staid"
COM_CONTENT_SUBMIT_SAVE_SUCCESS="Alt curtha isteach."
COM_CONTENT_TITLE_FILTER_LABEL="Scagaire Teidil"
COM_CONTENT_TRANSITION="Aistriú"
COM_CONTENT_VOTES="Vóta"
COM_CONTENT_VOTES_COUNT="Vóta: %s"
COM_CONTENT_WORKFLOW="Sreabhadh Oibre"
COM_CONTENT_WORKFLOW_STAGE="Céim Sreabhadh Oibre"
COM_CONTENT_WRITTEN_BY="Scríofa ag: %s"
```
