; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONFIG="Seirbhísí Riaracháin"
COM_CONFIG_CONFIGURATION="Cumraíocht Seirbhísí Riaracháin"
COM_CONFIG_ERROR_CONTROLLER_NOT_FOUND="Rialtóir Ní bhfuarthas!"
COM_CONFIG_FIELD_DEFAULT_ACCESS_LEVEL_DESC="Socraigh an Leibhéal Rochtana Réamhshocraithe do mhíreanna nua-chruthaithe."
COM_CONFIG_FIELD_DEFAULT_ACCESS_LEVEL_LABEL="Leibhéal Rochtana Réamhshocraithe"
COM_CONFIG_FIELD_DEFAULT_LIST_LIMIT_LABEL="Teorainn Liosta Réamhshocraithe"
COM_CONFIG_FIELD_METADESC_LABEL="Cur Síos Meta an tSuímh"
COM_CONFIG_FIELD_SEF_URL_DESC="Má dhíchumasaítear an rogha seo, ní bheidh aon eochairfhocail i URLanna Joomla agus ina ionad sin beidh cuma orthu mar <code>index.php?option=com_example&task=item.display&id=1</code> nach bhfuil éasca a chur in iúl ó bhéal nó i scríbhinn. Tá URLanna Cairdiúla do Inneall Cuardaigh (SEF) níos inléite ag daoine, m.sh. <code>index.php/example/display/something</code>. In ainneoin ainm na socruithe, a coinníodh ar chúiseanna stairiúla, níl aon tionchar ag an bhformáid URL ar an gcaoi a rangú do leathanaigh an tsuímh ag innill chuardaigh a thuilleadh."
COM_CONFIG_FIELD_SEF_URL_LABEL="URLanna Cairdiúla do Inneall Cuardaigh"
COM_CONFIG_FIELD_SITE_NAME_LABEL="Ainm an tSuímh"
COM_CONFIG_FIELD_SITE_OFFLINE_LABEL="Suíomh As Líne"
COM_CONFIG_FIELD_SITENAME_PAGETITLES_LABEL="Ainm an tSuímh i dTeidil na Leathanach"
COM_CONFIG_FIELD_VALUE_AFTER="Tar éis"
COM_CONFIG_FIELD_VALUE_BEFORE="Roimh"
COM_CONFIG_METADATA_SETTINGS="Socruithe Meiteashonraí"
COM_CONFIG_MODULES_MODULE_NAME="Ainm an Mhodúil"
COM_CONFIG_MODULES_MODULE_TYPE="Cineál an Mhodúil"
COM_CONFIG_MODULES_SAVE_SUCCESS="Sábháladh an modúl."
COM_CONFIG_MODULES_SETTINGS_TITLE="Socruithe an Mhodúil"
COM_CONFIG_SAVE_SUCCESS="Sábháladh an chumraíocht."
COM_CONFIG_SEO_SETTINGS="Socruithe Sinsearach"
COM_CONFIG_SITE_SETTINGS="Socruithe an tSuímh"
COM_CONFIG_TEMPLATE_SETTINGS="Socruithe an Teimpléid"
COM_CONFIG_XML_DESCRIPTION="Bainisteoir Cumraíochta Seirbhísí Riaracháin Tosaigh."
