; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

```ini
COM_CONTACT_NUM_ITEMS="Líon Teagmhálacha:"
COM_CONTACT_OTHER_INFORMATION="Eolas Ilghnéitheach"
COM_CONTACT_POSITION="Post"
COM_CONTACT_PROFILE="Próifíl"
COM_CONTACT_SELECT_CONTACT="Roghnaigh teagmhálaí:"
COM_CONTACT_SESSION_INVALID="Fianán seisiúin neamhbhailí. Seiceáil le do thoil go bhfuil fianáin cumasaithe i do bhrabhsálaí gréasáin."
COM_CONTACT_STATE="Stát"
COM_CONTACT_SUBURB="Bruachbhaile"
COM_CONTACT_TABLE_CAPTION="Teagmhálacha"
COM_CONTACT_TELEPHONE="Fón"
COM_CONTACT_TELEPHONE_NUMBER="Fón: %s"
COM_CONTACT_USER_FIELDS="Réimsí"
COM_CONTACT_VCARD="vCard"
COM_CONTACT_WEBPAGE="Láithreán Gréasáin"
```
