; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTACT_ADDRESS="Seoladh"
COM_CONTACT_CAPTCHA_LABEL="Captcha"
COM_CONTACT_CAT_NUM="# de Theagmhálaithe :"
COM_CONTACT_CHECKED_OUT_BY="Seiceáilte amach ag %s"
COM_CONTACT_CONTACT_DEFAULT_LABEL="Seol Ríomhphost"
COM_CONTACT_CONTACT_DETAILS="Sonraí"
COM_CONTACT_CONTACT_EMAIL_A_COPY_LABEL="Seol cóip chugat féin"
COM_CONTACT_CONTACT_EMAIL_NAME_LABEL="Ainm"
COM_CONTACT_CONTACT_ENTER_MESSAGE_LABEL="Teachtaireacht"
COM_CONTACT_CONTACT_MESSAGE_SUBJECT_LABEL="Ábhar"
COM_CONTACT_CONTACT_REQUIRED="<strong class=\"red\">*</strong> Réimse riachtanach"
COM_CONTACT_CONTACT_SEND="Seol Ríomhphost"
COM_CONTACT_COPYSUBJECT_OF="Cóip de: {SUBJECT}"
COM_CONTACT_COPYTEXT_OF="Seo cóip den teachtaireacht a sheol tú chuig {CONTACTNAME} trí {SITENAME}\n\n{BODY}"
COM_CONTACT_COUNT="Líon teagmhálaithe:"
COM_CONTACT_COUNTRY="Tír"
COM_CONTACT_DEFAULT_PAGE_TITLE="Teagmhálaithe"
COM_CONTACT_DETAILS="Teagmháil"
COM_CONTACT_DOWNLOAD_INFORMATION_AS="Íoslódáil faisnéis mar:"
COM_CONTACT_EDIT_CONTACT="Cuir Teagmháil in Eagar"
COM_CONTACT_EDIT_PUBLISHED_CONTACT="Teagmháil Foilsithe"
COM_CONTACT_EDIT_UNPUBLISHED_CONTACT="Teagmháil Neamhfhoilsithe"
COM_CONTACT_EMAIL_FORM="Foirm Teagmhála"
COM_CONTACT_EMAIL_LABEL="Ríomhphost"
COM_CONTACT_EMAIL_THANKS="Go raibh maith agat as do ríomhphost."
COM_CONTACT_ENQUIRY_SUBJECT="{SITENAME}: {SUBJECT}"
COM_CONTACT_ENQUIRY_TEXT="Seo ríomhphost fiosraithe trí {URL} ó:\n{NAME} {EMAIL}\n\n{BODY}\n\n{CUSTOMFIELDS}"
COM_CONTACT_ERROR_CONTACT_NOT_FOUND="Níor aimsíodh teagmháil"
COM_CONTACT_ERROR_UNIQUE_ALIAS="Tá an t-ailias céanna ag Teagmháil eile sa chatagóir seo."
COM_CONTACT_ERROR_UNIQUE_ALIAS_TRASHED="Tá an t-ailias céanna ag Teagmháil trufáilte sa chatagóir seo."
COM_CONTACT_FAX="Facs"
COM_CONTACT_FAX_NUMBER="Facs: %s"
COM_CONTACT_FIELD_CREATED_BY_ALIAS_LABEL="Cruthaithe ag Ailias"
COM_CONTACT_FIELD_INFORMATION_ADDRESS_LABEL="Seoladh"
COM_CONTACT_FIELD_INFORMATION_COUNTRY_LABEL="Tír"
COM_CONTACT_FIELD_INFORMATION_FAX_LABEL="Facs"
COM_CONTACT_FIELD_INFORMATION_MISC_LABEL="Faisnéis Ilghnéitheach"
COM_CONTACT_FIELD_INFORMATION_MOBILE_LABEL="Soghluaiste"
COM_CONTACT_FIELD_INFORMATION_POSITION_LABEL="Post"
COM_CONTACT_FIELD_INFORMATION_POSTCODE_LABEL="Cód Poist/ZIP"
COM_CONTACT_FIELD_INFORMATION_STATE_LABEL="Stát nó Contae"
COM_CONTACT_FIELD_INFORMATION_SUBURB_LABEL="Cathair nó Bruachbhaile"
COM_CONTACT_FIELD_INFORMATION_TELEPHONE_LABEL="Teileafón"
COM_CONTACT_FIELD_INFORMATION_WEBPAGE_LABEL="Láithreán Gréasáin"
COM_CONTACT_FIELD_LINKED_USER_LABEL="Úsáideoir Nascaithe"
COM_CONTACT_FIELD_NAME_LABEL="Ainm"
COM_CONTACT_FIELD_PARAMS_IMAGE_LABEL="Íomhá"
COM_CONTACT_FIELD_PUBLISH_DOWN_LABEL="Críochnaigh Foilsiú"
COM_CONTACT_FIELD_PUBLISH_UP_LABEL="Tosaigh Foilsiú"
COM_CONTACT_FIELD_SORTNAME1_LABEL="Céad Réimse Sórtála"
COM_CONTACT_FIELD_SORTNAME2_LABEL="Dara Réimse Sórtála"
COM_CONTACT_FIELD_SORTNAME3_LABEL="Tríú Réimse Sórtála"
COM_CONTACT_FIELDSET_METADATA="Meiteashonraí"
COM_CONTACT_FIELDSET_MISCELLANEOUS="Faisnéis Ilghnéitheach"
COM_CONTACT_FIELDSET_PUBLISHING="Foilsiú"
COM_CONTACT_FILTER_LABEL="Réimse Scagaire"
COM_CONTACT_FILTER_SEARCH_DESC="Scagaire Teidil"
COM_CONTACT_FORM_EDIT_CONTACT="Cuir teagmháil in eagar"
COM_CONTACT_FORM_FILTER_LEGEND="Scagairí"
COM_CONTACT_FORM_LABEL="Seol Ríomhphost. Tá gach réimse le réiltín (*) riachtanach."
COM_CONTACT_IMAGE_DETAILS="Íomhá teagmhála"
COM_CONTACT_LINKS="Naisc"
COM_CONTACT_MOBILE="Soghluaiste"
COM_CONTACT_MOBILE_NUMBER="Soghluaiste: %s"
COM_CONTACT_NEW_CONTACT="Teagmháil Nua"
COM_CONTACT_NO_CONTACTS="Níl aon Teagmhálaithe le taispeáint"
COM_CONTACT_NOT_MORE_THAN_ONE_EMAIL_ADDRESS="Ní féidir leat níos mó ná seoladh ríomhphoist amháin a iontráil."
COM_CONTACT_NUM_ITEMS="Líon Teagmhálacha:"
COM_CONTACT_OTHER_INFORMATION="Eolas Ilghnéitheach"
COM_CONTACT_POSITION="Post"
COM_CONTACT_PROFILE="Próifíl"
COM_CONTACT_SELECT_CONTACT="Roghnaigh teagmhálaí:"
COM_CONTACT_SESSION_INVALID="Fianán seisiúin neamhbhailí. Seiceáil le do thoil go bhfuil fianáin cumasaithe i do bhrabhsálaí gréasáin."
COM_CONTACT_STATE="Stát"
COM_CONTACT_SUBURB="Bruachbhaile"
COM_CONTACT_TABLE_CAPTION="Teagmhálacha"
COM_CONTACT_TELEPHONE="Fón"
COM_CONTACT_TELEPHONE_NUMBER="Fón: %s"
COM_CONTACT_USER_FIELDS="Réimsí"
COM_CONTACT_VCARD="vCard"
COM_CONTACT_WEBPAGE="Láithreán Gréasáin"
