; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_CONTENT_ARTICLE_CONTENT="Ábhar"
COM_CONTENT_ARTICLE_HITS="Buailtí: %d"
COM_CONTENT_ARTICLE_INFO="Sonraí"
COM_CONTENT_ARTICLE_VOTE_FAILURE="Tá an t-alt seo rátáilte agat cheana inniu!"
COM_CONTENT_ARTICLE_VOTE_SUCCESS="Go raibh maith agat as an t-alt seo a rátáil."
COM_CONTENT_ARTICLES_TABLE_CAPTION="Ailt"
COM_CONTENT_AUTHOR_FILTER_LABEL="Scagaire Údair"
COM_CONTENT_CAPTCHA_DESC="Déan an seiceáil slándála le do thoil."
COM_CONTENT_CAPTCHA_LABEL="Captcha"
COM_CONTENT_CATEGORY="Catagóir: %s"
COM_CONTENT_CATEGORY_LIST_TABLE_CAPTION="Ailt sa chatagóir %s"
COM_CONTENT_CHECKED_OUT_BY="Seiceáilte amach ag %s"
COM_CONTENT_CONTENT_TYPE_ARTICLE="Alt"
COM_CONTENT_CONTENT_TYPE_CATEGORY="Catagóir Alt"
COM_CONTENT_CREATED_DATE="Dáta Cruthaithe"
COM_CONTENT_CREATED_DATE_ON="Cruthaithe: %s"
COM_CONTENT_EDIT_ITEM="Cuir Alt in Eagar"
COM_CONTENT_EDIT_PUBLISHED_ARTICLE="Alt Foilsithe"
COM_CONTENT_EDIT_UNPUBLISHED_ARTICLE="Alt Neamhfhoilsithe"
COM_CONTENT_ERROR_ARTICLE_NOT_FOUND="Níor aimsíodh an t-alt"
COM_CONTENT_ERROR_LOGIN_TO_VIEW_ARTICLE="Logáil isteach le do thoil chun an t-alt a fheiceáil"
COM_CONTENT_ERROR_PARENT_CATEGORY_NOT_FOUND="Níor aimsíodh an chatagóir thuismitheora"
COM_CONTENT_ERROR_PRINT_POPUP="Tá brón orainn, ní thacaíonn Joomla le print_popup a thuilleadh"
COM_CONTENT_ERROR_UNIQUE_ALIAS="Tá an t-ailias céanna ag Alt eile sa chatagóir seo."
COM_CONTENT_ERROR_UNIQUE_ALIAS_TRASHED="Tá an t-ailias céanna ag Alt sa bhruscar sa chatagóir seo."
COM_CONTENT_FEED_READMORE="Léigh Tuilleadh &hellip;"
COM_CONTENT_FIELD_ARTICLETEXT_LABEL="Téacs an Ailt"
COM_CONTENT_FIELD_FEATURED_DOWN_LABEL="Críochnaigh Réadmhaoin"
COM_CONTENT_FIELD_FEATURED_UP_LABEL="Tosaigh Réadmhaoin"
COM_CONTENT_FIELD_FULL_LABEL="Íomhá Iomlán an Ailt"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_DESC="Íomhá Maisiúil - níl aon tuairisc ag teastáil"
COM_CONTENT_FIELD_IMAGE_ALT_EMPTY_LABEL="Gan Tuairisc"
COM_CONTENT_FIELD_IMAGE_ALT_LABEL="Tuairisc Íomhá (Téacs Alt)"
COM_CONTENT_FIELD_IMAGE_CAPTION_LABEL="Fotheideal"
COM_CONTENT_FIELD_IMAGE_CLASS_LABEL="Rang Íomhá"
COM_CONTENT_FIELD_INTRO_LABEL="Íomhá Réamhrá"
COM_CONTENT_FIELD_NOTE_LABEL="Nóta"
COM_CONTENT_FIELD_URL_LINK_TEXT_LABEL="Téacs an Naisc"
COM_CONTENT_FIELD_URLA_LABEL="Nasc A"
COM_CONTENT_FIELD_URLA_LINK_TEXT_LABEL="Téacs Nasc A"
COM_CONTENT_FIELD_URLB_LABEL="Nasc B"
COM_CONTENT_FIELD_URLB_LINK_TEXT_LABEL="Téacs Nasc B"
COM_CONTENT_FIELD_URLC_LABEL="Nasc C"
COM_CONTENT_FIELD_URLC_LINK_TEXT_LABEL="Téacs Nasc C"
COM_CONTENT_FILTER_SEARCH_DESC="Cuardach Scagaire Ábhair"
COM_CONTENT_FLOAT_LABEL="Snámh Íomhá"
COM_CONTENT_FORM_EDIT_ARTICLE="Cuir alt in eagar"
COM_CONTENT_FORM_FILTER_LEGEND="Scagairí"
COM_CONTENT_FORM_FILTER_SUBMIT="Scagaire"
COM_CONTENT_HEADING_TITLE="Teideal"
COM_CONTENT_HITS_FILTER_LABEL="Scagaire Buailtí"
COM_CONTENT_IMAGES_AND_URLS="Íomhánna agus Naisc"
COM_CONTENT_INTROTEXT="Caithfidh ábhar a bheith san alt."
COM_CONTENT_INVALID_RATING="Rátáil an Ailt: Rátáil Neamhbhailí: %s"
COM_CONTENT_LAST_UPDATED="Nuashonraithe Deireanach: %s"
COM_CONTENT_METADATA="Meiteashonraí"
COM_CONTENT_MODAL_FILTER_SEARCH_DESC="Cuardaigh i dteideal agus ailiase. Cuir ID: nó ÚDAR: roimh chun ID ailt nó údar ailt a chuardach."
COM_CONTENT_MODAL_FILTER_SEARCH_LABEL="Cuardaigh Ailt"
COM_CONTENT_MODIFIED_DATE="Dáta Modhnaithe"
COM_CONTENT_MONTH="Mí"
COM_CONTENT_MORE_ARTICLES="Tuilleadh Ailt &hellip;"
COM_CONTENT_NEW_ARTICLE="Alt Nua"
COM_CONTENT_NO_ARTICLES="Níl aon ailt sa chatagóir seo. Má tá fo-chatagóirí le feiceáil ar an leathanach seo, b'fhéidir go bhfuil ailt acu."
COM_CONTENT_NUM_ITEMS="Líon na nAilt:"
COM_CONTENT_ON_NEW_CONTENT="Tá Airteagal nua curtha isteach ag '%1$s' dar teideal '%2$s'."
COM_CONTENT_ORDERING="Ordú:<br>Is é an t-ordú réamhshocraithe d'airteagail nua an chéad áit sa Chatagóir. Is féidir an t-ordú a athrú sa Chúlra."
COM_CONTENT_PAGEBREAK_DOC_TITLE="Briseadh Leathanaigh"
COM_CONTENT_PAGEBREAK_INSERT_BUTTON="Cuir Briseadh Leathanaigh Isteach"
COM_CONTENT_PAGEBREAK_TITLE="Teideal an Leathanaigh:"
COM_CONTENT_PAGEBREAK_TOC="Ainm Cleite an Chlár Ábhair:"
COM_CONTENT_PARENT="Catagóir Tuismitheora: %s"
COM_CONTENT_PUBLISHED_DATE="Dáta Foilsithe"
COM_CONTENT_PUBLISHED_DATE_ON="Foilsithe: %s"
COM_CONTENT_PUBLISHING="Foilsiú"
COM_CONTENT_RATINGS="Rátáil"
COM_CONTENT_RATINGS_COUNT="Rátáil: %s"
COM_CONTENT_READ_MORE="Léigh níos mó &hellip;"
COM_CONTENT_READ_MORE_TITLE="Léigh níos mó: %s"
COM_CONTENT_REGISTER_TO_READ_MORE="Cláraigh chun níos mó a léamh &hellip;"
COM_CONTENT_RUN_TRANSITION="Rith Aistriú"
COM_CONTENT_SAVE_SUCCESS="Airteagal sábháilte."
COM_CONTENT_SAVE_WARNING="Bhí an t-ainm cleite ann cheana mar sin cuireadh uimhir leis ag an deireadh. Má theastaíonn uait an t-ainm cleite a athrú, téigh i dteagmháil le riarthóir an tsuímh le do thoil."
COM_CONTENT_SELECT_AN_ARTICLE="Roghnaigh Airteagal"
COM_CONTENT_STATE="Staid"
COM_CONTENT_SUBMIT_SAVE_SUCCESS="Airteagal curtha isteach."
COM_CONTENT_TITLE_FILTER_LABEL="Scagaire Teidil"
COM_CONTENT_TRANSITION="Aistriú"
COM_CONTENT_VOTES="Vóta"
COM_CONTENT_VOTES_COUNT="Vóta: %s"
COM_CONTENT_WORKFLOW="Sreabhadh Oibre"
COM_CONTENT_WORKFLOW_STAGE="Céim Sreabhadh Oibre"
COM_CONTENT_WRITTEN_BY="Scríofa ag: %s"
