; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

FINDER_CLI="Innéacsóir Cuardaigh Chliste"
FINDER_CLI_BATCH_COMPLETE=" * Baisc próiseáilte %d i %s soicind."
FINDER_CLI_BATCH_CONTINUING=" * Ag leanúint ar aghaidh le próiseáil na baisce ..."
FINDER_CLI_BATCH_PAUSING=" * Ag cur sos ar phróiseáil ar feadh %d soicind ..."
FINDER_CLI_FILTER_RESTORE_WARNING="Rabhadh: Níor aimsíodh tacsanomaíocht %s/%s i scagaire %s"
FINDER_CLI_INDEX_PURGE="Glan innéacs"
FINDER_CLI_INDEX_PURGE_FAILED="- theip ar ghlanadh innéacs."
FINDER_CLI_INDEX_PURGE_SUCCESS="- glanadh innéacs rathúil"
FINDER_CLI_PEAK_MEMORY_USAGE="Úsáid chuimhne buaic: %s bearta"
FINDER_CLI_PROCESS_COMPLETE="Am Iomlán Próiseála: %s soicind."
FINDER_CLI_RESTORE_FILTER_COMPLETED="- líon na scagairí athchóirithe: %s"
FINDER_CLI_RESTORE_FILTERS="Ag athchóiriú scagairí"
FINDER_CLI_SAVE_FILTER_COMPLETED="- líon na scagairí sábháilte: %s"
FINDER_CLI_SAVE_FILTERS="Ag sábháil scagairí"
FINDER_CLI_SETTING_UP_PLUGINS="Ag socrú breiseán Cuardaigh Chliste"
FINDER_CLI_SETUP_ITEMS="Socraigh %d míreanna i %s soicind."
FINDER_CLI_SKIPPING_PAUSE_LOW_BATCH_PROCESSING_TIME=" * Ag scipeáil sos, mar bhí am próiseála an-íseal ag an mbaisc roimhe seo (%ss < %ds)"
FINDER_CLI_STARTING_INDEXER="Ag tosú Innéacsóir"
