; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

; Database types (allows for a more descriptive label than the internal name)
MYSQL="MySQL (PDO)"
MYSQLI="MySQLi"
ORACLE="Oracle"
PGSQL="PostgreSQL (PDO)"
POSTGRESQL="PostgreSQL"
SQLITE="SQLite"

; Search tools
JFILTER_OPTIONS="Roghanna Scagaire"
JSEARCH_TOOLS="Uirlisí Cuardaigh"
JSEARCH_TOOLS_DESC="Scag na míreanna liosta."
JSEARCH_TOOLS_ORDERING="Ordú de réir:"
JTABLE_OPTIONS="Roghanna Tábla"
JTABLE_OPTIONS_ORDERING="Ordú de réir:"

; Read more layout
JGLOBAL_READ_MORE="Léigh níos mó &hellip;"
JGLOBAL_READ_MORE_TITLE="Léigh níos mó: %s"
JGLOBAL_REGISTER_TO_READ_MORE="Cláraigh chun níos mó a léamh &hellip;"

; States assets translations
ARCHIVE="Cartlann"
ARCHIVED="Cartlannaithe"
FEATURE="Gné"
UNFEATURE="Bain Gné"
PUBLISH="Foilsigh"
PUBLISHED="Foilsithe"
PUBLISH_AND_FEATURE="Foilsigh & Gné"
TRASH="Bruscar"
TRASHED="Bruscartha"
UNPUBLISH="Dífhoilsigh"
UNPUBLISHED="Dífhoilsithe"
