; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

LIB_PHPASS="phpass"
LIB_PHPASS_XML_DESCRIPTION="Is creatlach iniompartha haisiú pasfhocal é phpass le húsáid in iarratais PHP. Is é an modh haisiúcháin is fearr (is sláine) a thacaíonn phpass leis ná an bcrypt stíl OpenBSD (ar a dtugtar CRYPT_BLOWFISH i PHP), le titim siar go haisí stíl BSDI bunaithe ar DES leathnaithe (ar a dtugtar CRYPT_EXT_DES i PHP) agus mar rogha dheiridh titim siar go modh haisiúcháin pasfhocal comhaireamh athrá athraitheach bunaithe ar MD5 a chuirtear i bhfeidhm i phpass féin."
