; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_CATEGORIES="Ailt - Catagóirí"
MOD_ARTICLES_CATEGORIES_FIELD_COUNT_DESC="Roghnaigh líon na bhfochatagóirí den chéad leibhéal le taispeáint. Is é an réamhshocrú ná gach ceann."
MOD_ARTICLES_CATEGORIES_FIELD_COUNT_LABEL="# Fochatagóirí Céad Leibhéal"
MOD_ARTICLES_CATEGORIES_FIELD_MAXLEVEL_LABEL="Doimhneacht Uasta Leibhéil"
MOD_ARTICLES_CATEGORIES_FIELD_NUMITEMS_LABEL="Líon na nAilt"
MOD_ARTICLES_CATEGORIES_FIELD_PARENT_LABEL="Catagóir Tuismitheora"
MOD_ARTICLES_CATEGORIES_FIELD_SHOW_CHILDREN_LABEL="Fochatagóirí"
MOD_ARTICLES_CATEGORIES_FIELD_SHOW_DESCRIPTION_LABEL="Cur Síos ar Chatagóirí"
MOD_ARTICLES_CATEGORIES_TITLE_HEADING_LABEL="Stíl Ceanntásca"
MOD_ARTICLES_CATEGORIES_XML_DESCRIPTION="Taispeánann an modúl seo liosta de chatagóirí ó chatagóir tuismitheora amháin."
