; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_WHOSONLINE="Cé atá Ar Líne"
MOD_WHOSONLINE_FIELD_FILTER_GROUPS_DESC="Roghnaigh chun scagadh de réir grúpaí an úsáideora ceangailte"
MOD_WHOSONLINE_FIELD_FILTER_GROUPS_LABEL="Scag Grúpaí"
MOD_WHOSONLINE_FIELD_VALUE_BOTH="An Dá Rud"
MOD_WHOSONLINE_FIELD_VALUE_NAMES="Ainmneacha Úsáideoirí"
MOD_WHOSONLINE_FIELD_VALUE_NUMBER="# de Aíonna / Úsáideoirí"
MOD_WHOSONLINE_GUESTS="%s&#160;aíonna"
MOD_WHOSONLINE_GUESTS_0="gan aíonna"
MOD_WHOSONLINE_GUESTS_1="aon aoi amháin"
MOD_WHOSONLINE_MEMBERS="%s&#160;baill"
MOD_WHOSONLINE_MEMBERS_0="gan baill"
MOD_WHOSONLINE_MEMBERS_1="aon bhall amháin"
MOD_WHOSONLINE_NO_SESSION_METADATA="Ní féidir sonraí úsáideoirí ar líne a thaispeáint faoi láthair."
MOD_WHOSONLINE_SAME_GROUP_MESSAGE="Liosta d'Úsáideoirí a bhaineann le do ghrúpaí úsáideoirí nó le grúpaí leanaí do ghrúpaí úsáideoirí"
MOD_WHOSONLINE_SHOWMODE_LABEL="Taispeáin"
MOD_WHOSONLINE_XML_DESCRIPTION="Taispeánann an Modúl Cé atá Ar Líne líon na nÚsáideoirí Gan Ainm (m.sh. Aíonna) agus na nÚsáideoirí Cláraithe (siúd atá logáilte isteach) atá ag rochtain ar an suíomh gréasáin faoi láthair."
MOD_WHOSONLINE_WE_HAVE="Tá %1$s agus %2$s againn ar líne"
