; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_NEWS="Ailt - Nuachtán (Oidhreacht)"
MOD_ARTICLES_NEWS_LAYOUT_DEFAULT="Réamhshocrú"
MOD_ARTICLES_NEWS_LAYOUT_HORIZONTAL="Cothrománach"
MOD_ARTICLES_NEWS_LAYOUT_VERTICAL="Ingearach"
MOD_ARTICLES_NEWS_XML_DESCRIPTION="Taispeánfaidh an Modúl Nuachtáin líon seasta alt ó chatagóir ar leith. Tá an modúl seo in ionad an mhodúil \"Ailt\"."
