; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_TAGS_POPULAR="Clibeanna - Coitianta"
MOD_TAGS_POPULAR_LAYOUT_CLOUD="Scamall"
MOD_TAGS_POPULAR_LAYOUT_DEFAULT="Réamhshocrú"
MOD_TAGS_POPULAR_XML_DESCRIPTION="Taispeánann an modúl seo clibeanna a úsáidtear ar an suíomh i leagan amach liosta nó scamall. Is féidir clibeanna a ordú de réir teidil nó de réir líon na n-ítimí clibáilte agus teoranta do thréimhse ama ar leith."
