; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LOGIN="Logáil Isteach"
MOD_LOGIN_FIELD_GREETING_LABEL="Beannacht"
MOD_LOGIN_FIELD_LOGIN_REDIRECTURL_DESC="Mura roghnaítear mír roghchláir, fanfaidh úsáideoirí ar an leathanach céanna tar éis logáil isteach."
MOD_LOGIN_FIELD_LOGIN_REDIRECTURL_LABEL="Leathanach Athsheolta Logála Isteach"
MOD_LOGIN_FIELD_LOGOUT_REDIRECTURL_DESC="Mura roghnaítear mír roghchláir, fanfaidh úsáideoirí ar an leathanach céanna tar éis logáil amach."
MOD_LOGIN_FIELD_LOGOUT_REDIRECTURL_LABEL="Leathanach Athsheolta Logála Amach"
MOD_LOGIN_FIELD_NAME_LABEL="Ainm/Ainm Úsáideora"
MOD_LOGIN_FIELD_POST_TEXT_LABEL="Iar-théacs"
MOD_LOGIN_FIELD_PRE_TEXT_LABEL="Réamhtheacs"
MOD_LOGIN_FIELD_PROFILE_LABEL="Nasc Próifíle"
MOD_LOGIN_FIELD_REGISTRATION_MENU_LABEL="Leathanach Clárúcháin"
MOD_LOGIN_FIELD_USETEXT_LABEL="Taispeáin Lipéid"
MOD_LOGIN_FORGOT_YOUR_PASSWORD="Ar dhearmad do phasfhocal?"
MOD_LOGIN_FORGOT_YOUR_USERNAME="Ar dhearmad d'ainm úsáideora?"
MOD_LOGIN_HINAME="Dia dhuit %s,"
MOD_LOGIN_PROFILE="Féach ar an bPróifíl"
MOD_LOGIN_REGISTER="Cruthaigh cuntas"
MOD_LOGIN_REMEMBER_ME="Cuimhnigh Orm"
MOD_LOGIN_VALUE_ICONS="Deilbhíní"
MOD_LOGIN_VALUE_NAME="Ainm"
MOD_LOGIN_VALUE_TEXT="Téacs"
MOD_LOGIN_VALUE_USERNAME="Ainm Úsáideora"
MOD_LOGIN_XML_DESCRIPTION="Taispeánann an modúl seo foirm logála isteach ainm úsáideora agus pasfhocal. Taispeánann sé nasc freisin chun pasfhocal dearmadta a aisghabháil. Má tá clárú úsáideora cumasaithe (i nÚsáideoirí &rarr; Bainistigh &rarr; Roghanna), taispeánfar nasc eile chun féinchlárú a chumasú d'úsáideoirí."
