; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_FIELD_ONLYARCHIVED_LABEL="Ailt Chartlainne"
MOD_ARTICLES_FIELD_RELATIVEDATE_LABEL="Dáta Coibhneasta"
MOD_ARTICLES_FIELD_SELECT_ARTICLE_LABEL="Roghnaigh Alt"
MOD_ARTICLES_FIELD_SHOWCATEGORYLINK_LABEL="Nasc Catagóire"
MOD_ARTICLES_FIELD_SHOWCHILDCATEGORYARTICLES_DESC="Cuir san áireamh nó eisiamh ailt i bhfo-chatagóirí na gcatagóirí roghnaithe."
MOD_ARTICLES_FIELD_SHOWCHILDCATEGORYARTICLES_LABEL="Ailt Fochatagóire"
MOD_ARTICLES_FIELD_SHOWFEATURED_LABEL="Ailt Réadmhaoin"
MOD_ARTICLES_FIELD_SHOWHITS_LABEL="Buailtí"
MOD_ARTICLES_FIELD_SHOWINTROTEXT_LABEL="Réamhtheacs"
MOD_ARTICLES_FIELD_SHOWONARTICLEPAGE_DESC="Roghnaigh chun Liosta Alt a Thaispeáint nó a cheilt ó Leathanaigh Alt. Ciallaíonn sé seo go dtaispeánfaidh an modúl é féin go dinimiciúil ar Leathanaigh Catagóire amháin."
MOD_ARTICLES_FIELD_SHOWONARTICLEPAGE_LABEL="Taispeáin ar Leathanach Alt"
MOD_ARTICLES_FIELD_STARTDATE_LABEL="Raon Dáta Tosaigh"
MOD_ARTICLES_FIELD_TITLEONLY_LABEL="Teideal Amháin (liostaí)"
MOD_ARTICLES_FIELD_TITLE_HEADING="Leibhéal Ceanntásc"
MOD_ARTICLES_FIELD_TITLE_HEADING_NONE="Dada"
MOD_ARTICLES_FIELD_TITLE_LABEL="Teideal an Ailt"
MOD_ARTICLES_FIELD_TRIGGER_EVENTS_DESC="Cumasaigh an rogha seo chun trí imeacht breiseán a spreagadh (afterDisplayTitle, beforeDisplayContent, afterDisplayContent) do gach alt sa liosta torthaí."
MOD_ARTICLES_FIELD_TRIGGER_EVENTS_LABEL="Spreag Imeachtaí Breiseán"
MOD_ARTICLES_INFO="Sonraí"
MOD_ARTICLES_OPTION_ASCENDING_VALUE="Ardú"
MOD_ARTICLES_OPTION_CREATED_VALUE="Dáta Cruthaithe"
MOD_ARTICLES_OPTION_DATERANGE_VALUE="Raon Dáta"
MOD_ARTICLES_OPTION_DESCENDING_VALUE="Ísliú"
MOD_ARTICLES_OPTION_DYNAMIC_VALUE="Dinimiciúil"
MOD_ARTICLES_OPTION_EXCLUDE_VALUE="Eisiamh"
MOD_ARTICLES_OPTION_EXCLUSIVE_VALUE="Eisiach"
MOD_ARTICLES_OPTION_FINISHPUBLISHING_VALUE="Dáta Críochnaithe Foilsithe"
MOD_ARTICLES_OPTION_FULLIMAGE="Íomhá Iomlán"
MOD_ARTICLES_OPTION_HITS_VALUE="Buailtí"
MOD_ARTICLES_OPTION_ID_VALUE="ID"
MOD_ARTICLES_OPTION_INCLUDE_VALUE="Cuir san áireamh"
MOD_ARTICLES_OPTION_INCLUSIVE_VALUE="Cuimsitheach"
MOD_ARTICLES_OPTION_INTROIMAGE="Íomhá Réamhrá"
MOD_ARTICLES_OPTION_MODIFIED_VALUE="Dáta Modhnaithe"
MOD_ARTICLES_OPTION_MONTHYEAR_VALUE="Mí agus Bliain"
MOD_ARTICLES_OPTION_NORMAL_VALUE="Gnáth"
MOD_ARTICLES_OPTION_OFF_VALUE="As"
MOD_ARTICLES_OPTION_ONLYARCHIVEDHIDE_VALUE="Dada"
MOD_ARTICLES_OPTION_ONLYARCHIVEDSHOW_VALUE="Amháin"
MOD_ARTICLES_OPTION_ONLYCURRENTUSER_VALUE="Amháin ón úsáideoir reatha"
MOD_ARTICLES_OPTION_ONLYFEATURED_VALUE="Amháin"
MOD_ARTICLES_OPTION_ORDERINGFEATURED_VALUE="Ordú Ailt Réadmhaoin"
MOD_ARTICLES_OPTION_ORDERING_VALUE="Ordú Alt"
MOD_ARTICLES_OPTION_RANDOM_VALUE="Randamach"
MOD_ARTICLES_OPTION_RATING_VALUE="Rátáil"
MOD_ARTICLES_OPTION_RELATIVEDAY_VALUE="Dáta Coibhneasta"
MOD_ARTICLES_OPTION_STARTPUBLISHING_VALUE="Dáta Tosaigh Foilsithe"
MOD_ARTICLES_OPTION_VOTE_VALUE="Vóta"
MOD_ARTICLES_OPTION_YEAR_VALUE="Bliain"
MOD_ARTICLES_UNTAGGED="Gan Clib"
MOD_ARTICLES_XML_DESCRIPTION="Taispeánann an modúl seo ailt ar bhealaí éagsúla."
