; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MENU="Roghchlár"
MOD_MENU_FIELD_ACTIVE_LABEL="Mír Bhunúsach"
MOD_MENU_FIELD_ALLCHILDREN_LABEL="Fo-mhíreanna Roghchláir"
MOD_MENU_FIELD_CLASS_LABEL="Aicme Roghchláir"
MOD_MENU_FIELD_ENDLEVEL_LABEL="Leibhéal Deiridh"
MOD_MENU_FIELD_MENUTYPE_LABEL="Roghnaigh Roghchlár"
MOD_MENU_FIELD_STARTLEVEL_LABEL="Leibhéal Tosaigh"
MOD_MENU_FIELD_TAG_ID_LABEL="ID Clib Roghchláir"
MOD_MENU_FIELD_TARGET_DESC="Luachanna JavaScript chun fuinneog aníos a shuíomh, m.sh. barr=50, clé=50, leithead=200, airde=300."
MOD_MENU_FIELD_TARGET_LABEL="Suíomh Sprioc"
MOD_MENU_TOGGLE="Athraigh Nascleanúint"
MOD_MENU_XML_DESCRIPTION="Taispeánann an modúl seo roghchlár ar an Tosaigh."
