; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

COM_BANNERS_NO_CLIENT="- Gan cliant -"
MOD_BANNERS="Meirgí"
MOD_BANNERS_BANNER="Meirge"
MOD_BANNERS_FIELD_BANNERCLIENT_DESC="Roghnaigh meirgí ó chliant amháin amháin."
MOD_BANNERS_FIELD_BANNERCLIENT_LABEL="Cliant"
MOD_BANNERS_FIELD_COUNT_DESC="An líon meirgí le taispeáint (réamhshocrú 5)."
MOD_BANNERS_FIELD_COUNT_LABEL="Líon"
MOD_BANNERS_FIELD_FOOTER_LABEL="Téacs an Bhróga"
MOD_BANNERS_FIELD_HEADER_LABEL="Téacs an Cheanntásca"
MOD_BANNERS_FIELD_RANDOMISE_LABEL="Randamú"
MOD_BANNERS_FIELD_TAG_DESC="Roghnaítear meirge trí mheaitseáil na heochairfhocail meirge leis na heochairfhocail reatha doiciméid."
MOD_BANNERS_FIELD_TAG_LABEL="Roghnaigh de réir Eochairfhocail"
MOD_BANNERS_FIELD_TARGET_LABEL="Sprioc"
MOD_BANNERS_VALUE_STICKYORDERING="Greamaithe, Ordú"
MOD_BANNERS_VALUE_STICKYRANDOMISE="Greamaithe, Randamú"
MOD_BANNERS_XML_DESCRIPTION="Taispeánann an Modúl Meirgí na Meirgí gníomhacha ón gComhpháirt."
