; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_RANDOM_IMAGE="Íomhá Randamach"
MOD_RANDOM_IMAGE_FIELD_FOLDER_LABEL="Fillteán Íomhánna"
MOD_RANDOM_IMAGE_FIELD_HEIGHT_LABEL="Airde (px)"
MOD_RANDOM_IMAGE_FIELD_LINK_LABEL="Nasc"
MOD_RANDOM_IMAGE_FIELD_TYPE_LABEL="Cineál Íomhá"
MOD_RANDOM_IMAGE_FIELD_WIDTH_LABEL="Leithead (px)"
MOD_RANDOM_IMAGE_NO_IMAGES="Níl Íomhánna"
MOD_RANDOM_IMAGE_XML_DESCRIPTION="Taispeánann an modúl seo íomhá randamach ón bhfillteán a roghnaigh tú."
