; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_WRAPPER="Clúdach"
MOD_WRAPPER_FIELD_ADD_LABEL="Cuir http:// go huathoibríoch"
MOD_WRAPPER_FIELD_AUTOHEIGHT_LABEL="Airde Uathoibríoch"
MOD_WRAPPER_FIELD_HEIGHT_LABEL="Airde"
MOD_WRAPPER_FIELD_LAZYLOADING_LABEL="Lódáil Leisciúil"
MOD_WRAPPER_FIELD_TARGET_LABEL="Ainm an Sprioc"
MOD_WRAPPER_FIELD_URL_LABEL="URL"
MOD_WRAPPER_FIELD_WIDTH_LABEL="Leithead"
MOD_WRAPPER_NO_IFRAMES="Gan iframes"
MOD_WRAPPER_XML_DESCRIPTION="Taispeánann an modúl seo fuinneog iframe chuig suíomh sonraithe."
