; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_LATEST="Ailt - Is Déanaí (Oidhreacht)"
MOD_LATEST_NEWS_FIELD_AUTHOR_LABEL="Cruthaithe ag Údar(aithe)"
MOD_LATEST_NEWS_FIELD_COUNT_LABEL="Ailt le Taispeáint"
MOD_LATEST_NEWS_FIELD_FEATURED_LABEL="Ailt Réadmhaoin"
MOD_LATEST_NEWS_FIELD_ORDERING_LABEL="Ordú"
MOD_LATEST_NEWS_FIELD_USER_LABEL="Údair"
MOD_LATEST_NEWS_VALUE_ADDED_BY_ME="Cuirte nó modhnaithe agam"
MOD_LATEST_NEWS_VALUE_ANYONE="Aon duine"
MOD_LATEST_NEWS_VALUE_CREATED_BY="Cruthaithe ag"
MOD_LATEST_NEWS_VALUE_NOTADDED_BY_ME="Níor cuireadh nó modhnaithe agam"
MOD_LATEST_NEWS_VALUE_ONLY_SHOW_FEATURED="Taispeáin Ailt Réadmhaoin amháin"
MOD_LATEST_NEWS_VALUE_RECENT_ADDED="Cuirte le Déanaí ar dtús"
MOD_LATEST_NEWS_VALUE_RECENT_MODIFIED="Modhnaithe le Déanaí ar dtús"
MOD_LATEST_NEWS_VALUE_RECENT_PUBLISHED="Foilsithe le Déanaí ar dtús"
MOD_LATEST_NEWS_VALUE_RECENT_RAND="Ailt Randamacha"
MOD_LATEST_NEWS_VALUE_RECENT_TOUCHED="Teagmháilte le Déanaí ar dtús"
MOD_LATEST_NEWS_XML_DESCRIPTION="Taispeánann an modúl seo liosta de na hAilt is déanaí a foilsíodh agus atá reatha. Tá an modúl seo in áit an mhodúil \"Ailt\"."
