; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_CATEGORY_FIELD_SHOWONARTICLEPAGE_LABEL="Taispeáin ar Leathanach an Ailt"
MOD_ARTICLES_CATEGORY_FIELD_STARTDATE_LABEL="Raon Dáta Tosaigh"
MOD_ARTICLES_CATEGORY_OPTION_ASCENDING_VALUE="Ardaitheach"
MOD_ARTICLES_CATEGORY_OPTION_CREATED_VALUE="Dáta Cruthaithe"
MOD_ARTICLES_CATEGORY_OPTION_DATERANGE_VALUE="Raon Dáta"
MOD_ARTICLES_CATEGORY_OPTION_DESCENDING_VALUE="Ísliúchán"
MOD_ARTICLES_CATEGORY_OPTION_DYNAMIC_VALUE="Dinimiciúil"
MOD_ARTICLES_CATEGORY_OPTION_EXCLUDE_VALUE="Eisiamh"
MOD_ARTICLES_CATEGORY_OPTION_EXCLUSIVE_VALUE="Eisiach"
MOD_ARTICLES_CATEGORY_OPTION_FINISHPUBLISHING_VALUE="Dáta Críochnaithe Foilsithe"
MOD_ARTICLES_CATEGORY_OPTION_HITS_VALUE="Buailtí"
MOD_ARTICLES_CATEGORY_OPTION_ID_VALUE="ID"
MOD_ARTICLES_CATEGORY_OPTION_INCLUDE_VALUE="Cuir san áireamh"
MOD_ARTICLES_CATEGORY_OPTION_INCLUSIVE_VALUE="Cuimsitheach"
MOD_ARTICLES_CATEGORY_OPTION_MODIFIED_VALUE="Dáta Modhnaithe"
MOD_ARTICLES_CATEGORY_OPTION_MONTHYEAR_VALUE="Mí agus Bliain"
MOD_ARTICLES_CATEGORY_OPTION_NORMAL_VALUE="Gnáth"
MOD_ARTICLES_CATEGORY_OPTION_OFF_VALUE="As"
MOD_ARTICLES_CATEGORY_OPTION_ONLYFEATURED_VALUE="Amháin"
MOD_ARTICLES_CATEGORY_OPTION_ORDERING_VALUE="Ordú Alt"
MOD_ARTICLES_CATEGORY_OPTION_ORDERINGFEATURED_VALUE="Ordú Ailt Réadmhaoin"
MOD_ARTICLES_CATEGORY_OPTION_RANDOM_VALUE="Randamach"
MOD_ARTICLES_CATEGORY_OPTION_RATING_VALUE="Rátáil"
MOD_ARTICLES_CATEGORY_OPTION_RELATIVEDAY_VALUE="Dáta Coibhneasta"
MOD_ARTICLES_CATEGORY_OPTION_STARTPUBLISHING_VALUE="Dáta Tosaigh Foilsithe"
MOD_ARTICLES_CATEGORY_OPTION_VOTE_VALUE="Vóta"
MOD_ARTICLES_CATEGORY_OPTION_YEAR_VALUE="Bliain"
MOD_ARTICLES_CATEGORY_READ_MORE="Léigh níos mó: "
MOD_ARTICLES_CATEGORY_READ_MORE_TITLE="Léigh Níos Mó &hellip;"
MOD_ARTICLES_CATEGORY_REGISTER_TO_READ_MORE="Cláraigh chun níos mó a léamh"
MOD_ARTICLES_CATEGORY_UNTAGGED="Gan Clib"
MOD_ARTICLES_CATEGORY_XML_DESCRIPTION="Taispeánann an modúl seo liosta d'altanna ó chatagóirí amháin nó níos mó. Tá an modúl seo in áit an mhodúil \"Ailt\"."
