; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_NEWS="Ailt - Nuachtán (Oidhreacht)"
MOD_ARTICLES_NEWS_FIELD_EXCLUDE_CURRENT_LABEL="Eisiamh an tAlt Reatha"
MOD_ARTICLES_NEWS_FIELD_FEATURED_LABEL="Ailt Réadmhaoin"
MOD_ARTICLES_NEWS_FIELD_IMAGES_ARTICLE_LABEL="Taispeáin Íomhá Réamhrá/Lán"
MOD_ARTICLES_NEWS_FIELD_IMAGES_DESC="Taispeáin na híomhánna atá laistigh de théacs an ailt."
MOD_ARTICLES_NEWS_FIELD_IMAGES_LABEL="Taispeáin Íomhánna Alt"
MOD_ARTICLES_NEWS_FIELD_ITEMS_LABEL="Líon na nAilt"
MOD_ARTICLES_NEWS_FIELD_LINKTITLE_LABEL="Teidil Nascáilte"
MOD_ARTICLES_NEWS_FIELD_ORDERING_CREATED_DATE="Dáta Cruthaithe"
MOD_ARTICLES_NEWS_FIELD_ORDERING_LABEL="Ordú Torthaí"
MOD_ARTICLES_NEWS_FIELD_ORDERING_MODIFIED_DATE="Dáta Modhnaithe"
MOD_ARTICLES_NEWS_FIELD_ORDERING_ORDERING="Ordú"
MOD_ARTICLES_NEWS_FIELD_ORDERING_PUBLISHED_DATE="Dáta Foilsithe"
MOD_ARTICLES_NEWS_FIELD_ORDERING_RANDOM="Randamach"
MOD_ARTICLES_NEWS_FIELD_READMORE_LABEL="Nasc 'Léigh níos mó &hellip;'"
MOD_ARTICLES_NEWS_FIELD_SEPARATOR_LABEL="Deighilteoir Deireanach"
MOD_ARTICLES_NEWS_FIELD_SHOWINTROTEXT_LABEL="Téacs Réamhrá"
MOD_ARTICLES_NEWS_FIELD_TITLE_LABEL="Teideal an Ailt"
MOD_ARTICLES_NEWS_FIELD_TRIGGEREVENTS_LABEL="Spreag Imeachtaí Breiseán"
MOD_ARTICLES_NEWS_OPTION_FULLIMAGE="Íomhá Lán"
MOD_ARTICLES_NEWS_OPTION_INTROIMAGE="Íomhá Réamhrá"
MOD_ARTICLES_NEWS_READMORE="Léigh níos mó &hellip;"
MOD_ARTICLES_NEWS_READMORE_REGISTER="Cláraigh chun Léamh Níos Mó"
MOD_ARTICLES_NEWS_TITLE_HEADING="Leibhéal Ceanntásc"
MOD_ARTICLES_NEWS_VALUE_ONLY_SHOW_FEATURED="Taispeáin Ailt Réadmhaoin Amháin"
MOD_ARTICLES_NEWS_XML_DESCRIPTION="Taispeánfaidh an Modúl Nuachtán Alt líon seasta Ailt ó Chatagóir ar leith nó sraith Catagóirí. Tá an modúl seo in áit an mhodúil \"Ailt\"."
