; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_ARCHIVE="Ailt - Cartlannaithe"
MOD_ARTICLES_ARCHIVE_DATE="%1$s, %2$s"
MOD_ARTICLES_ARCHIVE_FIELD_COUNT_LABEL="# de Mhíonna"
MOD_ARTICLES_ARCHIVE_XML_DESCRIPTION="Taispeánann an modúl seo liosta de na míonna féilire ina bhfuil ailt chartlannaithe. Tar éis duit stádas alt a athrú go cartlannaithe, ginfear an liosta seo go huathoibríoch."
