; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_TAGS_POPULAR="Clibeanna - Coitianta"
MOD_TAGS_POPULAR_FIELD_ALL_TIME="Gach am"
MOD_TAGS_POPULAR_FIELD_DISPLAY_COUNT_LABEL="Taispeáin Líon na Míreanna"
MOD_TAGS_POPULAR_FIELD_LAST_DAY="An lá deireanach"
MOD_TAGS_POPULAR_FIELD_LAST_HOUR="An uair dheireanach"
MOD_TAGS_POPULAR_FIELD_LAST_MONTH="An mhí seo caite"
MOD_TAGS_POPULAR_FIELD_LAST_WEEK="An tseachtain seo caite"
MOD_TAGS_POPULAR_FIELD_LAST_YEAR="An bhliain seo caite"
MOD_TAGS_POPULAR_FIELD_MAXSIZE_DESC="An méid cló uasta a úsáidtear do na clibeanna, i gcomhréir le méid cló réamhshocraithe an tsuímh (m.sh. ciallaíonn &quot;2&quot; 200% den mhéid réamhshocraithe)."
MOD_TAGS_POPULAR_FIELD_MAXSIZE_LABEL="Méid Cló Uasta"
MOD_TAGS_POPULAR_FIELD_MINSIZE_DESC="An méid cló is lú a úsáidtear do na clibeanna, i gcomhréir le méid cló réamhshocraithe an tsuímh (m.sh. ciallaíonn &quot;2&quot; 200% den mhéid réamhshocraithe)."
MOD_TAGS_POPULAR_FIELD_MINSIZE_LABEL="Méid Cló Íosta"
MOD_TAGS_POPULAR_FIELD_NO_RESULTS_LABEL="Taispeáin téacs &quot;Gan torthaí&quot;"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_COUNT="Líon na Míreanna"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_LABEL="Ordú"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_RANDOM="Randamach"
MOD_TAGS_POPULAR_FIELD_ORDER_VALUE_TITLE="Teideal"
MOD_TAGS_POPULAR_FIELD_TIMEFRAME_LABEL="Tréimhse Ama"
MOD_TAGS_POPULAR_FIELDSET_CLOUD_LABEL="Leagan Amach Scamaill"
MOD_TAGS_POPULAR_MAX_LABEL="Uasmhéid Clibeanna"
MOD_TAGS_POPULAR_NO_ITEMS_FOUND="Níor aimsíodh Clibeanna."
MOD_TAGS_POPULAR_PARENT_TAG_DESC="Teorannaigh clibeanna a thaispeántar do leanaí an Chlibe Tuismitheora seo."
MOD_TAGS_POPULAR_PARENT_TAG_LABEL="Clib Tuismitheora"
MOD_TAGS_POPULAR_XML_DESCRIPTION="Taispeánann an modúl seo clibeanna a úsáidtear ar an suíomh i liosta nó i leagan amach scamaill. Is féidir clibeanna a ordú de réir teidil nó de réir líon na míreanna clibeáilte agus iad a theorannú do thréimhse ama ar leith."
