; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_RELATED_ITEMS="Ailt - Gaolta"
MOD_RELATED_ITEMS_LAYOUT_DEFAULT="Réamhshocrú"
MOD_RELATED_XML_DESCRIPTION="Taispeánann an modúl seo Ailt eile atá gaolta leis an gceann atá á fheiceáil. Bunaítear na gaolta seo leis na Eochairfhocail. <br>Déantar cuardach ar gach eochairfhocal den Airteagal reatha i gcoinne gach eochairfhocal de gach Airteagal foilsithe eile. Mar shampla, b'fhéidir go bhfuil Airteagal agat ar &quot;Péacadh Éin&quot; agus ceann eile ar &quot;Éin Dhubha a Thógáil de Láimh&quot;. Má chuireann tú an eochairfhocal &quot;éan&quot; isteach sna hAilt araon, ansin liostálfaidh an Modúl Míreanna Gaolmhara an tAirteagal &quot;Péacadh Éin&quot; nuair a bheidh tú ag féachaint ar &quot;Éin Dhubha a Thógáil de Láimh&quot; agus a mhalairt."
