; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_MENU="Biachlár"
MOD_MENU_LAYOUT_COLLAPSE-DEFAULT="Biachlár Réamhshocraithe Inaistrithe"
MOD_MENU_LAYOUT_DEFAULT="Réamhshocrú"
MOD_MENU_XML_DESCRIPTION="Taispeánann an modúl seo biachlár ar an Tosaigh."
