; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_CATEGORY="Ailt - Catagóir (Oidhreacht)"
MOD_ARTICLES_CATEGORY_LAYOUT_DEFAULT="Réamhshocrú"
MOD_ARTICLES_CATEGORY_XML_DESCRIPTION="Taispeánann an modúl seo liosta d'altanna ó chatagóir amháin nó níos mó. Tá an modúl seo in ionad an mhodúil \"Ailt\"."
