; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_RELATED_FIELD_MAX_DESC="An líon uasta alt gaolmhar le taispeáint (is é 5 an réamhshocrú)."
MOD_RELATED_FIELD_MAX_LABEL="Uasmhéid Alt"
MOD_RELATED_FIELD_SHOWDATE_LABEL="Dáta"
MOD_RELATED_ITEMS="Ailt - Gaolmhara"
MOD_RELATED_XML_DESCRIPTION="Taispeánann an modúl seo Ailt eile atá gaolmhar leis an gceann atá á fheiceáil. Bunaítear na gaolta seo leis na Eochairfhocail. <br>Déantar cuardach ar gach eochairfhocal den Airteagal reatha i gcoinne gach eochairfhocal de gach Airteagal foilsithe eile. Mar shampla, b'fhéidir go bhfuil Airteagal agat ar &quot;Péacadh Éanlaith&quot; agus ceann eile ar &quot;Tógáil Lámh Cockatoos Dubh&quot;. Má chuireann tú an eochairfhocal &quot;éan&quot; isteach sna hAilt araon, ansin liostálfaidh an Modúl Míreanna Gaolmhara an tAirteagal &quot;Péacadh Éanlaith&quot; agus tú ag féachaint ar &quot;Tógáil Lámh Cockatoos Dubh&quot; agus a mhalairt."
