; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_WHOSONLINE="Cé atá Ar Líne"
MOD_WHOSONLINE_LAYOUT_DEFAULT="Réamhshocrú"
MOD_WHOSONLINE_LAYOUT_DISABLED="Faoi Mhíchumas"
MOD_WHOSONLINE_XML_DESCRIPTION="Taispeánann an Módúl Cé atá Ar Líne líon na nÚsáideoirí Gan Ainm (Aíonna) agus na nÚsáideoirí Cláraithe (úsáideoirí logáilte isteach) atá ag rochtain an láithreáin ghréasáin faoi láthair."
