; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_LOGIN="Logáil Isteach"
MOD_LOGIN_LAYOUT_DEFAULT="Réamhshocrú"
MOD_LOGIN_XML_DESCRIPTION="Taispeánann an modúl seo foirm logála isteach le hainm úsáideora agus pasfhocal. Taispeánann sé nasc freisin chun pasfhocal dearmadta a aisghabháil. Má tá clárú úsáideora cumasaithe (i nÚsáideoirí &rarr; Bainistiú &rarr; Roghanna), taispeánfar nasc eile chun féinchlárú a chumasú d'úsáideoirí."
