; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

MOD_ARTICLES_CATEGORY="Ailt - Catagóir (Oidhreacht)"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEGROUPING_LABEL="Grúpáil Alt"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEGROUPINGDIR_LABEL="Treoir Grúpála"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEORDERING_LABEL="Réimse Alt le hOrdú De réir"
MOD_ARTICLES_CATEGORY_FIELD_ARTICLEORDERINGDIR_LABEL="Treoir Ordaithe"
MOD_ARTICLES_CATEGORY_FIELD_AUTHOR_LABEL="Údair"
MOD_ARTICLES_CATEGORY_FIELD_AUTHORALIAS_LABEL="Ainmneacha Bréige Údair"
MOD_ARTICLES_CATEGORY_FIELD_AUTHORALIASFILTERING_LABEL="Cineál Scagtha Ainm Bréige Údair"
MOD_ARTICLES_CATEGORY_FIELD_AUTHORFILTERING_LABEL="Cineál Scagtha Údair"
MOD_ARTICLES_CATEGORY_FIELD_CATDEPTH_LABEL="Doimhneacht Catagóire"
MOD_ARTICLES_CATEGORY_FIELD_CATFILTERINGTYPE_LABEL="Cineál Scagtha Catagóire"
MOD_ARTICLES_CATEGORY_FIELD_COUNT_DESC="An líon míreanna le taispeáint. Taispeánfaidh an luach réamhshocraithe de 0 gach alt."
MOD_ARTICLES_CATEGORY_FIELD_COUNT_LABEL="Líon"
MOD_ARTICLES_CATEGORY_FIELD_DATEFIELD_LABEL="Réimse Dáta"
MOD_ARTICLES_CATEGORY_FIELD_DATEFIELDFORMAT_DESC="Cuir isteach i bhformáid dáta bailí. Féach: https://php.net/date le haghaidh faisnéise formáidithe."
MOD_ARTICLES_CATEGORY_FIELD_DATEFIELDFORMAT_LABEL="Formáid Dáta"
MOD_ARTICLES_CATEGORY_FIELD_DATEFILTERING_LABEL="Scagadh Dáta"
MOD_ARTICLES_CATEGORY_FIELD_DATEGROUPINGFIELD_DESC="Roghnaigh cén réimse dáta ar mhaith leat an grúpáil dáta a chur i bhfeidhm air."
MOD_ARTICLES_CATEGORY_FIELD_DATEGROUPINGFIELD_LABEL="Réimse Grúpála Dáta"
MOD_ARTICLES_CATEGORY_FIELD_DATERANGEFIELD_LABEL="Réimse Raon Dáta"
MOD_ARTICLES_CATEGORY_FIELD_ENDDATE_LABEL="Go Dáta"
MOD_ARTICLES_CATEGORY_FIELD_EXCLUDEDARTICLES_LABEL="IDanna Alt le Eisiamh"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_DISPLAY_LABEL="Roghanna Taispeána"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_FILTERING_LABEL="Roghanna Scagtha"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_GROUPING_LABEL="Roghanna Grúpála"
MOD_ARTICLES_CATEGORY_FIELD_GROUP_ORDERING_LABEL="Roghanna Ordaithe"
MOD_ARTICLES_CATEGORY_FIELD_INTROTEXTLIMIT_LABEL="Teorainn Téacs Réamhrá (carachtair)"
MOD_ARTICLES_CATEGORY_FIELD_LINKTITLES_LABEL="Teidil Nascáilte"
MOD_ARTICLES_CATEGORY_FIELD_MODE_DESC="Roghnaigh an modh ar mhaith leat a úsáid. Má roghnaítear Gnáthmhodh, ansin cumraigh an modúl agus taispeánfaidh sé liosta statach d'Ailt ar na míreanna roghchláir a shanntar an modúl dóibh. Má roghnaítear Modh Dinimiciúil, is féidir leat an modúl a chumrú go hiondúil fós, ach anois ní úsáidfear an rogha Catagóire a thuilleadh. Ina áit sin, braithfidh an modúl go dinimiciúil má tá tú ar radharc Catagóire agus taispeánfaidh sé an liosta alt laistigh den Chatagóir sin. Nuair a roghnaítear Modh Dinimiciúil, is fearr an modúl a fhágáil socraithe chun taispeáint ar gach leathanach, mar go gcinnfidh sé aon rud a thaispeáint go dinimiciúil."
MOD_ARTICLES_CATEGORY_FIELD_MODE_LABEL="Mód"
MOD_ARTICLES_CATEGORY_FIELD_MONTHYEARFORMAT_DESC="Cuir isteach i bhformáid dáta bailí. Féach: https://php.net/date le haghaidh faisnéise formáidithe."
MOD_ARTICLES_CATEGORY_FIELD_MONTHYEARFORMAT_LABEL="Formáid Taispeána Mí agus Bliain"
MOD_ARTICLES_CATEGORY_FIELD_RELATIVEDATE_LABEL="Dáta Coibhneasta"
MOD_ARTICLES_CATEGORY_FIELD_SHOWCHILDCATEGORYARTICLES_LABEL="Ailt Catagóire Leanaí"
MOD_ARTICLES_CATEGORY_FIELD_SHOWFEATURED_LABEL="Ailt Réadmhaoin"
MOD_ARTICLES_CATEGORY_FIELD_SHOWHITS_LABEL="Buailtí"
MOD_ARTICLES_CATEGORY_FIELD_SHOWINTROTEXT_LABEL="Réamhrá"
MOD_ARTICLES_CATEGORY_FIELD_SHOWONARTICLEPAGE_DESC="Roghnaigh Taispeáint nó ceil Liosta Alt ó Leathanaigh Alt. Ciallaíonn sé seo nach dtaispeánfaidh an modúl é féin go dinimiciúil ach ar Leathanaigh Catagóire."
MOD_ARTICLES_CATEGORY_FIELD_SHOWONARTICLEPAGE_LABEL="Taispeáin ar Leathanach an Ailt"
MOD_ARTICLES_CATEGORY_FIELD_STARTDATE_LABEL="Raon Dáta Tosaigh"
MOD_ARTICLES_CATEGORY_OPTION_ASCENDING_VALUE="Ag Dul i Méad"
MOD_ARTICLES_CATEGORY_OPTION_CREATED_VALUE="Dáta Cruthaithe"
MOD_ARTICLES_CATEGORY_OPTION_DATERANGE_VALUE="Raon Dáta"
MOD_ARTICLES_CATEGORY_OPTION_DESCENDING_VALUE="Ag Dul i Lú"
MOD_ARTICLES_CATEGORY_OPTION_DYNAMIC_VALUE="Dinimiciúil"
MOD_ARTICLES_CATEGORY_OPTION_EXCLUDE_VALUE="Eisiamh"
MOD_ARTICLES_CATEGORY_OPTION_EXCLUSIVE_VALUE="Eisiach"
MOD_ARTICLES_CATEGORY_OPTION_FINISHPUBLISHING_VALUE="Dáta Críochnaithe Foilsithe"
MOD_ARTICLES_CATEGORY_OPTION_HITS_VALUE="Buailtí"
MOD_ARTICLES_CATEGORY_OPTION_ID_VALUE="ID"
MOD_ARTICLES_CATEGORY_OPTION_INCLUDE_VALUE="Cuir san áireamh"
MOD_ARTICLES_CATEGORY_OPTION_INCLUSIVE_VALUE="Cuimsitheach"
MOD_ARTICLES_CATEGORY_OPTION_MODIFIED_VALUE="Dáta Modhnaithe"
MOD_ARTICLES_CATEGORY_OPTION_MONTHYEAR_VALUE="Mí agus Bliain"
MOD_ARTICLES_CATEGORY_OPTION_NORMAL_VALUE="Gnáth"
MOD_ARTICLES_CATEGORY_OPTION_OFF_VALUE="As"
MOD_ARTICLES_CATEGORY_OPTION_ONLYFEATURED_VALUE="Amháin"
MOD_ARTICLES_CATEGORY_OPTION_ORDERING_VALUE="Ordú Alt"
MOD_ARTICLES_CATEGORY_OPTION_ORDERINGFEATURED_VALUE="Ordú Ailt Réadmhaoin"
MOD_ARTICLES_CATEGORY_OPTION_RANDOM_VALUE="Randamach"
MOD_ARTICLES_CATEGORY_OPTION_RATING_VALUE="Rátáil"
MOD_ARTICLES_CATEGORY_OPTION_RELATIVEDAY_VALUE="Dáta Coibhneasta"
MOD_ARTICLES_CATEGORY_OPTION_STARTPUBLISHING_VALUE="Dáta Tosaigh Foilsithe"
MOD_ARTICLES_CATEGORY_OPTION_VOTE_VALUE="Vóta"
MOD_ARTICLES_CATEGORY_OPTION_YEAR_VALUE="Bliain"
MOD_ARTICLES_CATEGORY_READ_MORE="Léigh níos mó: "
MOD_ARTICLES_CATEGORY_READ_MORE_TITLE="Léigh Níos Mó &hellip;"
MOD_ARTICLES_CATEGORY_REGISTER_TO_READ_MORE="Cláraigh chun níos mó a léamh"
MOD_ARTICLES_CATEGORY_UNTAGGED="Gan Clib"
MOD_ARTICLES_CATEGORY_XML_DESCRIPTION="Taispeánann an modúl seo liosta alt ó chatagóirí amháin nó níos mó. Tá an modúl seo in áit an mhodúil \"Ailt\"."
