; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

CASSIOPEIA="Teimpléad Suíomh Cassiopeia"
TPL_CASSIOPEIA_BACKTOTOP="Ar Ais go Barr"
TPL_CASSIOPEIA_BACKTOTOP_LABEL="Nasc Ar Ais go Barr"
TPL_CASSIOPEIA_BRAND_LABEL="Branda"
TPL_CASSIOPEIA_COLOR_NAME_ALTERNATIVE="Malartach"
TPL_CASSIOPEIA_COLOR_NAME_LABEL="Téama Dathanna"
TPL_CASSIOPEIA_COLOR_NAME_STANDARD="Caighdeánach"
TPL_CASSIOPEIA_FLUID="Leachtach"
TPL_CASSIOPEIA_FLUID_LABEL="Leagan Amach"
TPL_CASSIOPEIA_FONT_GROUP_LOCAL="Clónna ón bhFillteán"
TPL_CASSIOPEIA_FONT_GROUP_WEB="Clónna ón nGréasán"
TPL_CASSIOPEIA_FONT_LABEL="Scéim Clónna"
TPL_CASSIOPEIA_FONT_NOTE_TEXT="Is iad clónna córais na cinn is éifeachtaí cé go bhféadfadh difríochtaí beaga a bheith idir córais oibriúcháin.<br>D’fhéadfadh sé a bheith in aghaidh rialacháin príobháideachais i roinnt tíortha clónna a luchtú ó fhoinsí seachtracha.<br>D’fhéadfadh tionchar a bheith ag luchtú clónna ó fhillteán áitiúil ar fheidhmíocht do shuíomh."
TPL_CASSIOPEIA_FONT_SYSTEM="Clónna Córais"
TPL_CASSIOPEIA_FONT_SYSTEM_BODY="Cruach Clónna Comhlachta"
TPL_CASSIOPEIA_FONT_SYSTEM_HEADING="Cruach Clónna Ceanntásca"
TPL_CASSIOPEIA_FONT_SYSTEM_SELECT="Roghnaigh Clónna Córais"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_ANTIQUE="Seanré"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_CLASSICAL="Clasaiceach Daonnúil"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_CODE="Cód Monospásach"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_DIDONE="Didone"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_GEOMETRIC="Daonnúil Geoiméadrach"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_GROTESQUE="Nua-Grotesque"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_HANDWRITTEN="Lámhscríofa"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_HUMANIST="Daonnúil"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_INDUSTRIAL="Tionsclaíoch"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_MONOSPACE="Monospásach Slab Serif"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_OLDSTYLE="Sean-Stíl"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_ROUNDED="Sans Cruinn"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_SLAB="Slab Serif"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_TRANSITIONAL="Idirthréimhseach"
TPL_CASSIOPEIA_LOGO_LABEL="Lógó"
TPL_CASSIOPEIA_STATIC="Statach"
TPL_CASSIOPEIA_STICKY_LABEL="Ceanntásc Greamaitheach"
TPL_CASSIOPEIA_TAGLINE_DESC="Téacs roghnach le taispeáint mar fho-cheannteideal"
TPL_CASSIOPEIA_TAGLINE_LABEL="Líne Téama"
TPL_CASSIOPEIA_TITLE="Teideal (malartach ar lógó)"
TPL_CASSIOPEIA_XML_DESCRIPTION="Ag leanúint an téama spáis (Solarflare ó 1.0, Milkyway ó 1.5 agus Protostar ó 3.0), is é Cassiopeia an teimpléad suíomh Joomla 4 agus Joomla 5 bunaithe ar Bootstrap 5."
