; Joomla! Project. Translation by Clifford E Ford using openai.com.
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

CASSIOPEIA="Teimpléad Suíomh Cassiopeia"
TPL_CASSIOPEIA_MOD_CUSTOM_LAYOUT_BANNER="Meirge"
TPL_CASSIOPEIA_MOD_MENU_LAYOUT_COLLAPSE-METISMENU="Roghnachlár Inaistrithe"
TPL_CASSIOPEIA_MOD_MENU_LAYOUT_DROPDOWN-METISMENU="Roghnachlár"
TPL_CASSIOPEIA_POSITION_BANNER="Meirge"
TPL_CASSIOPEIA_POSITION_BELOW-TOP="Faoi Bharr"
TPL_CASSIOPEIA_POSITION_BOTTOM-A="Bun-a"
TPL_CASSIOPEIA_POSITION_BOTTOM-B="Bun-b"
TPL_CASSIOPEIA_POSITION_BREADCRUMBS="Rian aráin"
TPL_CASSIOPEIA_POSITION_DEBUG="Dífhabhtú"
TPL_CASSIOPEIA_POSITION_ERROR-403="Earráid 403"
TPL_CASSIOPEIA_POSITION_ERROR-404="Earráid 404"
TPL_CASSIOPEIA_POSITION_FOOTER="Buntásc"
TPL_CASSIOPEIA_POSITION_MAIN-BOTTOM="Príomh-bun"
TPL_CASSIOPEIA_POSITION_MAIN-TOP="Príomh-barr"
TPL_CASSIOPEIA_POSITION_MENU="Roghchlár"
TPL_CASSIOPEIA_POSITION_SEARCH="Cuardach"
TPL_CASSIOPEIA_POSITION_SIDEBAR-LEFT="Barra Taoibh Clé"
TPL_CASSIOPEIA_POSITION_SIDEBAR-RIGHT="Barra Taoibh Deas"
TPL_CASSIOPEIA_POSITION_TOP-A="Barr-a"
TPL_CASSIOPEIA_POSITION_TOP-B="Barr-b"
TPL_CASSIOPEIA_POSITION_TOPBAR="Barra Barr"
TPL_CASSIOPEIA_XML_DESCRIPTION="Ag leanúint leis an téama spáis (Solarflare ó 1.0, Milkyway ó 1.5 agus Protostar ó 3.0), is é Cassiopeia an teimpléad suíomh Joomla 4 agus Joomla 5 bunaithe ar Bootstrap 5."
